// Original dramatic characterization and dialogue, not authenticated historical quotations.
// Events are stable identifiers shared by tactical and strategic presentation.
export const ATTRIBUTE_LABELS={maxHp:'Salud',agility:'Agilidad',dexterity:'Destreza',strength:'Fuerza',leadership:'Liderazgo',wisdom:'Sabiduría',marksmanship:'Puntería',mechanical:'Mecánica',explosives:'Pólvora y artillería',medical:'Medicina'};
const rows=[
[0,'Protector de su gente, firme en la autonomía del norte. Habla con franqueza y conoce el terreno antes de comprometer a sus gauchos.',['Caballería irregular','Movilidad en barro','Mando provincial'],['Aquí estoy. Primero, la tierra y su gente.','Por la quebrada vienen. Dejémoslos acercarse.','El paso queda en nuestras manos.','No es nada. Mi gente sigue conmigo.','Hasta el mejor caballo precisa un respiro.','Que no abandonen la frontera…','El norte resistió. Ahora cuidemos la libertad.']],
[1,'Resuelta y solidaria con las partidas. Su autoridad nace de compartir los riesgos y sostener a quienes combaten lejos de sus hogares.',['Combate cercano','Moral de las milicias','Guerra de partidas'],['Marcharé con ustedes. Nadie queda atrás.','Atención, compañeros. Ya los tenemos delante.','Hoy este pueblo duerme sin su guardia.','Sigo en pie. Cubran a los heridos.','Un momento. Reunamos fuerzas.','Sigan por los que todavía esperan…','La victoria pertenece también a quienes no volvieron.']],
[2,'Metódico, paciente y práctico. Ve en una herramienta bien cuidada una oportunidad de salvar vidas y en cada problema una tarea que resolver.',['Asistencia de recarga','Servicio de artillería','Maestranza'],['Mostradme las herramientas y empezamos.','Preparad las piezas. Sin precipitación.','Guardemos el material; aún puede servir.','Ajustaremos también esta avería.','Hasta la fragua necesita bajar el fuego.','Que las herramientas sigan trabajando…','Lo que fundimos aquí abrirá otros caminos.']],
[3,'Leal, directo y atento a sus compañeros. Prefiere proteger con hechos antes que discutir y conserva la calma cuando el combate se acerca.',['Escolta de comandantes','Sable y bayoneta','Resistencia'],['A sus órdenes. Estaré cerca.','Ahí están. No se aparte de mí.','El campo es nuestro, mi comandante.','Puedo sostenerme. Mire al frente.','Me falta el aire… cubra mi lugar.','Mi puesto… que alguien lo cubra…','Cumplimos con los nuestros. Eso vale la pena.']],
[4,'Vivaz, audaz y poco amigo de órdenes rígidas. Busca oportunidades rápidas y discute cuando cree que una maniobra desperdicia hombres.',['Escaramuza rápida','Pistolas y tercerolas','Iniciativa'],['Bien. Espero que nos dejen maniobrar.','¡Los vi! Hay un hueco por ese lado.','No les dimos tiempo de entenderlo.','Me rozaron. Todavía puedo moverme.','Una pausa, y vuelvo por el flanco.','No desperdicien la oportunidad…','Ganamos terreno. Ahora toca ganarnos a la gente.']],
[5,'Marino sobrio y perseverante. Valora las cuentas claras, la preparación de las dotaciones y la confianza que se gana en una travesía difícil.',['Artillería naval','Mando de dotaciones','Operaciones del Plata'],['Mi servicio está con esta causa. Acordemos los pertrechos.','Enemigo a la vista. Que nadie rompa la formación.','La comunicación vuelve a estar abierta.','Atiendan primero a la dotación.','Sin descanso tampoco se gobierna una nave.','Mantengan el rumbo…','La bandera tiene por fin un horizonte abierto.']],
[6,'Impaciente ante las defensas inmóviles y decidido en el asalto. Disfruta la iniciativa, pero espera que cada compañero cumpla su parte.',['Brechas en adobe','Asalto nocturno','Trabuco'],['Si hay una entrada, la encontraremos.','Allí está su defensa. Vamos a quebrarla.','La puerta está abierta. Que entre el resto.','Todavía tengo un brazo para pelear.','Dénme un respiro antes del siguiente asalto.','Abran paso… no se detengan…','Ya nadie nos cerrará todos los puertos.']],
[7,'Disciplinado y consciente de lo que representa su mando. Exige respeto entre compañeros y precisión en cada operación de la batería.',['Recarga de artillería','Moral de la infantería','Tiro de penetración'],['Serviré con disciplina y con dignidad.','Firmes. Cada hombre conoce su puesto.','Mantengan el orden y cuenten a los nuestros.','Continúen el servicio de la pieza.','Releven mi puesto un instante.','Que se reconozca a mis hombres…','La libertad debe alcanzar también a nuestros hogares.']],
[8,'Observadora, persuasiva y prudente. Escucha antes de hablar y protege a quienes arriesgan su vida llevando noticias entre los pueblos.',['Red de informantes','Contactos del norte','Diplomacia'],['Las noticias también ganan campañas.','Bajen la voz. Hay movimiento delante.','Revisemos los caminos antes de darlo por seguro.','No se preocupen por mí. Protejan al correo.','Necesito sentarme. Después seguimos.','Los nombres… no entreguen los nombres…','Que ahora las noticias lleven esperanza.']],
[9,'Intenso y orgulloso de su ascendiente entre los jinetes. Respeta el valor personal y reacciona con dureza ante el abandono de los pueblos.',['Choque de lanza','Intimidación montada','Mando de montoneras'],['Mis hombres no marchan para ser olvidados.','¡Ahí los tienen! Que sientan la carga.','Ya saben quién sostiene este camino.','No me han tumbado todavía.','El cuerpo pide tregua, aunque no me guste.','Sostengan a los muchachos…','Que nadie cambie una obediencia por otra.']],
[10,'Sereno y analítico. Prioriza a los heridos sin perder de vista los recursos limitados; explica sus decisiones y evita promesas vacías.',['Cirugía de campaña','Atención rápida','Conocimientos químicos'],['Prepararé los vendajes antes de partir.','Busquemos abrigo. Quiero poder atenderlos.','Traigan a los heridos. Aún queda trabajo.','Presión sobre la herida. Puedo indicarles cómo.','Necesito recuperar el pulso antes de continuar.','El instrumental… que otro lo use…','Ojalá el próximo esfuerzo sea reconstruir vidas.']],
[11,'Reservado y calculador. Se siente más cómodo con un plano y una posición bien elegida que con una carga improvisada.',['Puntería de mando','Iniciativa defensiva','Fusil Baker'],['Estudiemos la posición antes de dar la orden.','Distancias y campos de tiro. No se precipiten.','La maniobra dio resultado. Revisemos las bajas.','Una herida no cambia la geometría del campo.','Fatigado no calcularé bien. Necesito una pausa.','Conserven la posición…','La victoria exige ahora la misma previsión que la guerra.']],
[57,'Exigente, austero y atento a la preparación. Inspira confianza mediante objetivos claros y una visión que excede el combate inmediato.',['Gran estratega','Iniciativa de escuadra','Carga de precisión'],['El ejército está preparado. Marchemos juntos.','Mantengan la serenidad. Cada cual a su puesto.','La posición es nuestra. Aseguren las comunicaciones.','No desordenen la línea por mí.','Un ejército agotado no puede cumplir su misión.','La causa debe continuar…','Hemos preparado el camino. La libertad exige sostenerlo.']],
[100,'Trabajador de pocas palabras, aprende con la práctica y se preocupa por conservar las monturas.',['Caballería','Aprendizaje de campaña'],['Me sumo. Sé trabajar y sé montar.','Patrón… digo, comandante: los veo.','No pensé que podríamos hacerlo.','Me dieron, pero todavía aguanto.','Las piernas no me responden.','Avísenle a mi familia…','Volveré con algo más que mi facón.']],
[101,'Curiosa y alerta, se orienta por los detalles del paisaje y comparte lo que sabe con los recién llegados.',['Exploración','Guerrilla'],['Por estos senderos puedo guiarlos.','Ese movimiento no es del viento.','El camino quedó libre.','Una venda y sigo con ustedes.','Necesito agua y descanso.','No pierdan el sendero…','Volveremos a cruzar sin escondernos.']],
[102,'Joven y aplicado, hace preguntas y anota los procedimientos para no repetir sus errores.',['Maestranza','Artillería'],['Puedo ayudar con las armas. Y aprender.','¿Preparo la pieza? Estoy listo.','Voy a revisar lo que quedó en el campo.','La herida no parece buena…','Me tiemblan las manos. Debo parar.','Mis apuntes están en la bolsa…','En Caroya tendrán mucho que escuchar.']],
[103,'Metódico y paciente con las herramientas, impaciente con las órdenes confusas. Lleva cuentas de cada carga y exige que sus compañeros respeten las distancias de seguridad.',['Maestranza','Artillería'],['Mi oficio está a disposición del regimiento.','Hay movimiento. Preparen la pólvora.','Revisaré la pieza antes de celebrar.','No dejen caer la caja de municiones.','Mis manos necesitan un descanso.','Que la pólvora no se moje…','Ahora podré reparar barcos, en vez de destruirlos.']],
[104,'Sociable, terco y leal a quienes comparten el peligro. Cuenta historias de puerto para aliviar la tensión y detesta abandonar a un compañero.',['Guerrilla','Reconocimiento'],['Cuenten conmigo. Y guárdenme una ración.','A cubierto, compañeros. Nos han encontrado.','Hoy tendremos una historia más que contar.','He conocido cubiertas más duras que este suelo.','Un momento. Ya no siento las piernas.','Lleven mis noticias al puerto…','Brindaremos por los que no volvieron.']],

];
export const SPEECH_EVENTS=['hired','contact','cleared','wounded','exhausted','death','ending'];
export const CHARACTER_PROFILES=Object.fromEntries(rows.map(([id,personality,skills,lines])=>[id,{personality,skills,speech:Object.fromEntries(SPEECH_EVENTS.map((event,i)=>[event,lines[i]])),registry:[5,6,10,103,104].includes(id)?'Registro de voluntarios extranjeros':id>=100?'Boletín Revolucionario Cívico':'Logia Lautaro y mandos provinciales'}]));
export function characterProfile(operative){return CHARACTER_PROFILES[operative.id]??{personality:'Oficial formado ante la comisión del Cabildo. Su carrera se define por las decisiones y experiencias de la campaña.',skills:operative.traits||[],registry:'Comisión del Cabildo',speech:{hired:'Acepto la comisión. Serviré con responsabilidad.',contact:'Enemigo a la vista. Prepárense.',cleared:'Sector asegurado. Revisen a los compañeros.',wounded:'Estoy herido. Necesito atención.',exhausted:'No puedo seguir así. Debo descansar.',death:'Continúen sin mí…',ending:'La campaña termina; nuestra responsabilidad continúa.'}};}
export function speechFor(operative,event){return characterProfile(operative).speech[event]??null;}
