// Authored campaign values derived from the supplied historical conversion specification.
export const OPERATIVES = [
  {
    "maxHp": 82,
    "agility": 90,
    "dexterity": 85,
    "strength": 78,
    "leadership": 95,
    "wisdom": 88,
    "marksmanship": 81,
    "mechanical": 35,
    "explosives": 40,
    "medical": 30,
    "id": 0,
    "name": "Martín Miguel de Güemes",
    "nickname": "Güemes",
    "hp": 82,
    "weapon": 1803,
    "blade": 1813,
    "weeklyPay": 0,
    "monthlyPay": 0,
    "role": "Jefe de caballería irregular",
    "biography": "Martín Miguel de Güemes organiza la defensa del norte con sus gauchos. Su conocimiento de las quebradas y su autoridad entre las milicias lo convierten en un jefe de exploración y emboscadas."
  },
  {
    "maxHp": 88,
    "agility": 89,
    "dexterity": 86,
    "strength": 80,
    "leadership": 91,
    "wisdom": 82,
    "marksmanship": 77,
    "mechanical": 20,
    "explosives": 45,
    "medical": 52,
    "id": 1,
    "name": "Juana Azurduy",
    "nickname": "Azurduy",
    "hp": 88,
    "weapon": 1803,
    "blade": 1809,
    "weeklyPay": 0,
    "monthlyPay": 0,
    "role": "Jefa de partidas",
    "biography": "Juana Azurduy conduce fuerzas partisanas en el Alto Perú. Combina liderazgo, resistencia y combate cercano para sostener la lucha en un territorio disputado."
  },
  {
    "maxHp": 76,
    "agility": 65,
    "dexterity": 94,
    "strength": 84,
    "leadership": 72,
    "wisdom": 96,
    "marksmanship": 50,
    "mechanical": 99,
    "explosives": 90,
    "medical": 45,
    "id": 2,
    "name": "Fray Luis Beltrán",
    "nickname": "Beltrán",
    "hp": 76,
    "weapon": 1805,
    "blade": 1813,
    "weeklyPay": 400,
    "monthlyPay": 1714,
    "role": "Maestro armero",
    "biography": "Fray Luis Beltrán pone sus conocimientos de mecánica y metalurgia al servicio del ejército. En las maestranzas prepara armas, repara piezas y organiza la producción de municiones."
  },
  {
    "maxHp": 96,
    "agility": 84,
    "dexterity": 80,
    "strength": 92,
    "leadership": 60,
    "wisdom": 70,
    "marksmanship": 68,
    "mechanical": 40,
    "explosives": 25,
    "medical": 35,
    "id": 3,
    "name": "Juan Bautista Cabral",
    "nickname": "Cabral",
    "hp": 96,
    "weapon": 1809,
    "blade": 1811,
    "weeklyPay": 150,
    "monthlyPay": 643,
    "role": "Granadero y escolta",
    "biography": "Juan Bautista Cabral integra el Regimiento de Granaderos a Caballo. Su fortaleza física y su valor en el combate cercano lo convierten en un soldado decisivo en la defensa de sus compañeros."
  },
  {
    "maxHp": 84,
    "agility": 92,
    "dexterity": 88,
    "strength": 74,
    "leadership": 80,
    "wisdom": 78,
    "marksmanship": 89,
    "mechanical": 30,
    "explosives": 35,
    "medical": 20,
    "id": 4,
    "name": "Manuel Dorrego",
    "nickname": "Dorrego",
    "hp": 84,
    "weapon": 1808,
    "blade": 1813,
    "weeklyPay": 600,
    "monthlyPay": 2571,
    "role": "Jefe de cazadores",
    "biography": "Manuel Dorrego es un oficial de infantería ligera de carácter decidido. Favorece la iniciativa de los cazadores, el reconocimiento adelantado y las acciones rápidas contra posiciones enemigas."
  },
  {
    "maxHp": 85,
    "agility": 72,
    "dexterity": 80,
    "strength": 86,
    "leadership": 92,
    "wisdom": 90,
    "marksmanship": 75,
    "mechanical": 78,
    "explosives": 85,
    "medical": 40,
    "id": 5,
    "name": "Guillermo Brown",
    "nickname": "Brown",
    "hp": 85,
    "weapon": 1805,
    "blade": 1809,
    "weeklyPay": 900,
    "monthlyPay": 3857,
    "role": "Comandante naval",
    "biography": "Guillermo Brown aporta experiencia naval a la causa de las Provincias Unidas. Su mando resulta fundamental para disputar el control de los ríos y combatir a las fuerzas realistas del Plata."
  },
  {
    "maxHp": 86,
    "agility": 85,
    "dexterity": 87,
    "strength": 85,
    "leadership": 76,
    "wisdom": 84,
    "marksmanship": 78,
    "mechanical": 60,
    "explosives": 75,
    "medical": 30,
    "id": 6,
    "name": "Hipólito Bouchard",
    "nickname": "Bouchard",
    "hp": 86,
    "weapon": 1807,
    "blade": 1810,
    "weeklyPay": 800,
    "monthlyPay": 3429,
    "role": "Corsario de asalto",
    "biography": "Hipólito Bouchard sirve a la revolución como marino y combatiente. Su experiencia favorece las incursiones, los ataques nocturnos y el asalto de posiciones defendidas."
  },
  {
    "maxHp": 85,
    "agility": 80,
    "dexterity": 91,
    "strength": 79,
    "leadership": 78,
    "wisdom": 85,
    "marksmanship": 84,
    "mechanical": 72,
    "explosives": 80,
    "medical": 35,
    "id": 7,
    "name": "Lorenzo Barcala",
    "nickname": "Barcala",
    "hp": 85,
    "weapon": 1801,
    "blade": 1811,
    "weeklyPay": 180,
    "monthlyPay": 771,
    "role": "Artillero de línea",
    "biography": "Lorenzo Barcala representa la experiencia militar de los batallones de pardos y morenos. Aporta disciplina, destreza técnica y firmeza bajo el fuego a las fuerzas patriotas."
  },
  {
    "maxHp": 70,
    "agility": 88,
    "dexterity": 86,
    "strength": 55,
    "leadership": 89,
    "wisdom": 94,
    "marksmanship": 65,
    "mechanical": 45,
    "explosives": 20,
    "medical": 65,
    "id": 8,
    "name": "Macacha Güemes",
    "nickname": "Macacha",
    "hp": 70,
    "weapon": 1806,
    "blade": 1813,
    "weeklyPay": 250,
    "monthlyPay": 1071,
    "role": "Agente de información",
    "biography": "Macacha Güemes participa en las redes políticas y de información de Salta. Su capacidad para reunir noticias, establecer contactos y sostener acuerdos fortalece la defensa del norte."
  },
  {
    "maxHp": 92,
    "agility": 87,
    "dexterity": 76,
    "strength": 94,
    "leadership": 86,
    "wisdom": 68,
    "marksmanship": 55,
    "mechanical": 30,
    "explosives": 20,
    "medical": 25,
    "id": 9,
    "name": "Facundo Quiroga",
    "nickname": "Quiroga",
    "hp": 92,
    "weapon": 1812,
    "blade": 1813,
    "weeklyPay": 350,
    "monthlyPay": 1500,
    "role": "Lancero de montoneras",
    "biography": "Facundo Quiroga reúne las capacidades de un jefe de montoneras: fuerza, decisión y ascendiente personal. Su combate se apoya en la lanza y el facón de los hombres de la campaña."
  },
  {
    "maxHp": 72,
    "agility": 70,
    "dexterity": 89,
    "strength": 62,
    "leadership": 65,
    "wisdom": 95,
    "marksmanship": 60,
    "mechanical": 68,
    "explosives": 65,
    "medical": 98,
    "id": 10,
    "name": "James Paroissien",
    "nickname": "Paroissien",
    "hp": 72,
    "weapon": 1806,
    "blade": 1813,
    "weeklyPay": 550,
    "monthlyPay": 2357,
    "role": "Cirujano de campaña",
    "biography": "James Paroissien aporta formación médica y conocimientos científicos al ejército. Su trabajo permite atender heridos, organizar la asistencia de campaña y apoyar las tareas técnicas de los talleres."
  },
  {
    "maxHp": 78,
    "agility": 82,
    "dexterity": 88,
    "strength": 72,
    "leadership": 82,
    "wisdom": 92,
    "marksmanship": 91,
    "mechanical": 65,
    "explosives": 70,
    "medical": 30,
    "id": 11,
    "name": "José María Paz",
    "nickname": "Paz",
    "hp": 78,
    "weapon": 1802,
    "blade": 1810,
    "weeklyPay": 450,
    "monthlyPay": 1929,
    "role": "Oficial de táctica",
    "biography": "José María Paz estudia el terreno y prepara cuidadosamente sus posiciones. Su método combina precisión de tiro, disciplina y coordinación entre los combatientes."
  },
  {
    "maxHp": 88,
    "agility": 88,
    "dexterity": 90,
    "strength": 84,
    "leadership": 99,
    "wisdom": 98,
    "marksmanship": 92,
    "mechanical": 65,
    "explosives": 60,
    "medical": 50,
    "id": 57,
    "name": "José de San Martín",
    "nickname": "San Martín",
    "hp": 88,
    "weapon": 1808,
    "blade": 1809,
    "weeklyPay": 0,
    "monthlyPay": 0,
    "role": "Comandante del ejército",
    "biography": "José de San Martín organiza el Regimiento de Granaderos a Caballo y prepara una estrategia continental de liberación. Su mando une la instrucción militar con una exigente preparación logística."
  }
];
export const WEAPONS = {
  "1800": {
    "id": 1800,
    "name": "Brown Bess modelo India",
    "caliber": "Bala de plomo .75",
    "capacity": 1,
    "damage": 58,
    "readyAP": 12,
    "fireAP": 12,
    "aimAP": 6,
    "reloadAP": 45,
    "range": 18,
    "type": "firearm",
    "rifled": false,
    "spread": false,
    "weight": 4
  },
  "1801": {
    "id": 1801,
    "name": "Charleville Modèle 1777",
    "caliber": "Bala de plomo .69",
    "capacity": 1,
    "damage": 52,
    "readyAP": 11,
    "fireAP": 11,
    "aimAP": 5,
    "reloadAP": 42,
    "range": 22,
    "type": "firearm",
    "rifled": false,
    "spread": false,
    "weight": 4
  },
  "1802": {
    "id": 1802,
    "name": "Fusil Baker 1800",
    "caliber": "Bala con parche .62",
    "capacity": 1,
    "damage": 64,
    "readyAP": 16,
    "fireAP": 16,
    "aimAP": 10,
    "reloadAP": 70,
    "range": 45,
    "type": "firearm",
    "rifled": true,
    "spread": false,
    "weight": 4
  },
  "1803": {
    "id": 1803,
    "name": "Tercerola de Caballería",
    "caliber": "Bala corta .65",
    "capacity": 1,
    "damage": 44,
    "readyAP": 9,
    "fireAP": 9,
    "aimAP": 4,
    "reloadAP": 38,
    "range": 12,
    "type": "firearm",
    "rifled": false,
    "spread": false,
    "weight": 4
  },
  "1804": {
    "id": 1804,
    "name": "Escopeta Criolla",
    "caliber": "Perdigón calibre 16",
    "capacity": 1,
    "damage": 48,
    "readyAP": 10,
    "fireAP": 10,
    "aimAP": 4,
    "reloadAP": 35,
    "range": 10,
    "type": "firearm",
    "rifled": false,
    "spread": true,
    "weight": 4
  },
  "1805": {
    "id": 1805,
    "name": "Pistola de Arzón",
    "caliber": "Bala de plomo .69",
    "capacity": 1,
    "damage": 42,
    "readyAP": 7,
    "fireAP": 7,
    "aimAP": 3,
    "reloadAP": 32,
    "range": 8,
    "type": "firearm",
    "rifled": false,
    "spread": false,
    "weight": 1.3
  },
  "1806": {
    "id": 1806,
    "name": "Pistola de Duelo",
    "caliber": "Bala de precisión .50",
    "capacity": 1,
    "damage": 38,
    "readyAP": 6,
    "fireAP": 6,
    "aimAP": 2,
    "reloadAP": 28,
    "range": 12,
    "type": "firearm",
    "rifled": true,
    "spread": false,
    "weight": 1.3
  },
  "1807": {
    "id": 1807,
    "name": "Trabuco Naranjero",
    "caliber": "Metralla",
    "capacity": 1,
    "damage": 75,
    "readyAP": 12,
    "fireAP": 12,
    "aimAP": 5,
    "reloadAP": 40,
    "range": 6,
    "type": "firearm",
    "rifled": false,
    "spread": true,
    "weight": 1.3
  },
  "1808": {
    "id": 1808,
    "name": "Pistola Doble Cañón",
    "caliber": "Bala de plomo .54",
    "capacity": 2,
    "damage": 40,
    "readyAP": 8,
    "fireAP": 8,
    "aimAP": 3,
    "reloadAP": 55,
    "range": 9,
    "type": "firearm",
    "rifled": false,
    "spread": false,
    "weight": 1.3
  },
  "1809": {
    "id": 1809,
    "name": "Sable Corvo Sanmartiniano",
    "damage": 46,
    "fireAP": 12,
    "attackAP": 12,
    "range": 1,
    "type": "melee",
    "weight": 1.1
  },
  "1810": {
    "id": 1810,
    "name": "Sable de Caroya",
    "damage": 42,
    "fireAP": 14,
    "attackAP": 14,
    "range": 1,
    "type": "melee",
    "weight": 1.3
  },
  "1811": {
    "id": 1811,
    "name": "Bayoneta de Cubo",
    "damage": 50,
    "fireAP": 16,
    "attackAP": 16,
    "range": 2,
    "type": "melee",
    "weight": 0.5
  },
  "1812": {
    "id": 1812,
    "name": "Lanza de Tacuara",
    "damage": 56,
    "fireAP": 18,
    "attackAP": 18,
    "range": 2,
    "type": "melee",
    "weight": 2.2
  },
  "1813": {
    "id": 1813,
    "name": "Facón Gaucho",
    "damage": 32,
    "fireAP": 8,
    "attackAP": 8,
    "range": 1,
    "type": "melee",
    "weight": 0.6
  },
  "1820": {
    "id": 1820,
    "name": "Cañón de bronce de 4 libras",
    "crew": 2,
    "fireAP": 30,
    "reloadAP": 60,
    "range": 80,
    "radius": 4,
    "capacity": 1,
    "damage": 95,
    "type": "artillery"
  },
  "1821": {
    "id": 1821,
    "name": "Cañón de campaña de 8 libras",
    "crew": 3,
    "fireAP": 40,
    "reloadAP": 75,
    "range": 110,
    "radius": 6,
    "capacity": 1,
    "damage": 120,
    "type": "artillery"
  },
  "1822": {
    "id": 1822,
    "name": "Pedrero de regala",
    "crew": 1,
    "fireAP": 20,
    "reloadAP": 35,
    "range": 35,
    "radius": 3,
    "capacity": 1,
    "damage": 65,
    "type": "artillery"
  }
};

export const FACTIONS = [
  {id:'directory',name:'Directorio patriota',description:'Autoridad central, instrucción regular y defensa de las aduanas.'},
  {id:'gauchos',name:'Gauchos de Güemes',description:'Autonomía del norte y defensa de las estancias.'},
  {id:'pardos',name:'Pardos y Morenos',description:'Emancipación, comisiones militares y respeto a los soldados.'},
  {id:'foreign',name:'Voluntarios extranjeros',description:'Paga regular, comercio seguro y premios de corso.'},
  {id:'indigenous',name:'Confederaciones indígenas',description:'Parlamentos, reciprocidad y respeto a su autonomía.'},
  {id:'royalists',name:'Realistas españoles',description:'Restauración del poder colonial y control de las provincias.'},
];
export const THEATERS = [
  {id:'coast',name:'Buenos Aires y Litoral'}, {id:'interior',name:'Encrucijada de Córdoba'},
  {id:'cuyo',name:'Cuyo y frontera andina'}, {id:'north',name:'Frente del Norte'},
];
// Coordinates are campaign grid references from the specification, not latitude/longitude.
export const CAMPAIGN_SECTORS = [
  {id:'buenos_aires',grid:'G8',name:'Buenos Aires · Plaza Mayor',theater:'coast',biome:'urban',x:84,y:79,income:200,asset:'Cabildo y tesorería',neighbors:['retiro','ensenada','san_nicolas','cordoba']},
  {id:'retiro',grid:'G9',name:'Buenos Aires · Fuerte y Retiro',theater:'coast',biome:'urban',x:91,y:73,income:80,asset:'Academia y sala de armas',neighbors:['buenos_aires']},
  {id:'ensenada',grid:'H8',name:'Ensenada de Barragán',theater:'coast',biome:'wetland',x:92,y:87,income:160,asset:'Puerto de contrabando',neighbors:['buenos_aires']},
  {id:'san_nicolas',grid:'F7',name:'San Nicolás de los Arroyos',theater:'coast',biome:'river',x:76,y:66,income:90,asset:'Paso y aduana del Paraná',neighbors:['buenos_aires','santa_fe','cordoba']},
  {id:'santa_fe',grid:'E7',name:'Santa Fe de la Vera Cruz',theater:'coast',biome:'wetland',x:71,y:50,income:110,asset:'Puerto interior y estancias',neighbors:['san_nicolas','cordoba','tucuman']},
  {id:'cordoba',grid:'F5',name:'Córdoba y talleres de Caroya',theater:'interior',biome:'scrub',x:49,y:58,income:130,asset:'Maestranza y cruce del Camino Real',neighbors:['buenos_aires','san_nicolas','santa_fe','tucuman','mendoza']},
  {id:'mendoza',grid:'H1',name:'Mendoza · El Plumerillo',theater:'cuyo',biome:'foothills',x:25,y:79,income:100,asset:'Fundición y campamento del Ejército de los Andes',neighbors:['cordoba','uspallata','los_patos']},
  {id:'uspallata',grid:'H2',name:'Paso de Uspallata',theater:'cuyo',biome:'mountain',x:12,y:74,income:30,asset:'Paso cordillerano y reduto',neighbors:['mendoza','los_patos']},
  {id:'los_patos',grid:'H3',name:'Paso de Los Patos',theater:'cuyo',biome:'mountain',x:15,y:61,income:20,asset:'Sendas cordilleranas',neighbors:['mendoza','uspallata']},
  {id:'tucuman',grid:'D4',name:'San Miguel de Tucumán · La Ciudadela',theater:'north',biome:'forest',x:44,y:36,income:100,asset:'Fortaleza y talleres del Ejército del Norte',neighbors:['cordoba','santa_fe','salta']},
  {id:'salta',grid:'B2',name:'Salta · Cuartel de los Infernales',theater:'north',biome:'foothills',x:38,y:22,income:90,asset:'Cabildo y enlace de los gauchos',neighbors:['tucuman','jujuy']},
  {id:'jujuy',grid:'A2',name:'San Salvador de Jujuy',theater:'north',biome:'mountain',x:34,y:12,income:65,asset:'Depósito y distribución de ganado',neighbors:['salta','humahuaca']},
  {id:'humahuaca',grid:'A1',name:'Quebrada de Humahuaca',theater:'north',biome:'mountain',x:33,y:3,income:40,asset:'Paso fronterizo del Alto Perú',neighbors:['jujuy']},
];
export const PHASES = [
  {id:'retiro',name:'I · Formación en Retiro',objective:'Destina 20 caballos, 40 mosquetes, 60 textiles y 300 pesos a la academia.'},
  {id:'san_lorenzo',name:'II · Bautismo de fuego',objective:'Libera San Nicolás y vence al desembarco realista en San Lorenzo.'},
  {id:'yatasto',name:'III · Encuentro de Yatasto',objective:'Libera Tucumán y Salta, asegura el Camino Real y pacta con Güemes.'},
  {id:'plumerillo',name:'IV · Preparativos de El Plumerillo',objective:'Controla Cuyo, activa la fundición, equipa 3000 infantes y acuerda el paso con los pehuenches.'},
  {id:'liberation',name:'V · Ejército de los Andes',objective:'Incorpora a San Martín y elimina las últimas guarniciones realistas en los trece sectores.'},
];
export const RECIPES = {
 powder:{name:'Pólvora de maestranza',hours:12,cost:{treasury:20,saltpeter:15,charcoal:3,sulfur:2},yield:{powder:20}},
 charcoal:{name:'Carbón de leña',hours:18,cost:{treasury:10,timber:12},yield:{charcoal:8}},
  cartridges:{name:'Cartuchos de papel',hours:12,cost:{treasury:30,powder:5,lead:3},yield:{cartridges:60}},
  muskets:{name:'Reacondicionar mosquetes',hours:24,cost:{treasury:80,copper:2,scrapIron:8,timber:8},yield:{muskets:50}},
  sabres:{name:'Sables de Caroya',hours:18,cost:{treasury:60,copper:3,scrapIron:6,charcoal:3},yield:{sabres:20}},
  cannon:{name:'Cañón de bronce de 4 libras',hours:48,cost:{treasury:180,copper:15,timber:10,charcoal:8},yield:{cannons:1}},
  uniforms:{name:'Uniformes de campaña',hours:12,cost:{treasury:40,textiles:40,leather:10},yield:{uniforms:200}},
  infantry:{name:'Instruir y equipar infantes',hours:24,cost:{treasury:100,muskets:200,uniforms:200,powder:5},yield:{infantry:200}},
};
export const RESOURCE_NAMES = {timber:'Madera',scrapIron:'Hierro recuperado',lead:'Plomo',leather:'Cuero curtido',saltpeter:'Salitre',charcoal:'Carbón vegetal',sulfur:'Azufre',treasury:'Pesos de plata',horses:'Caballos',powder:'Pólvora',copper:'Cobre',textiles:'Textiles',infantry:'Infantes equipados',muskets:'Mosquetes',sabres:'Sables',cartridges:'Cartuchos',uniforms:'Uniformes',cannons:'Cañones',ponchos:'Ponchos de lana'};
