// Original fictional volunteers. Stable IDs are part of the saved-game format.
// Stats: health, agility, dexterity, strength, leadership, wisdom, marksmanship, mechanical, explosives, medical.
const recruits = [
 [107,'Inés Aguirre','Aguirre','Enfermera de campaña','artesano','buenos_aires',420,[72,62,83,58,55,84,38,25,12,88],['field_rescuer'],
  'Atendía a los trabajadores del matadero antes de organizar un puesto de socorro. Cobra para mantener a su hermana y exige llevar vendas suficientes.',
  'Serena y franca. No tolera que se oculte una herida por orgullo.',
  ['Llevo vendas. Ustedes traigan prudencia.','Veo uniformes entre los árboles.','Ahora sí, traigan las camillas.','Yo también necesito una venda.','Sin pulso firme no puedo atender.','Cuiden de mi hermana…','Volveré a abrir mi puesto de socorro.'],
  '38-year-old Afro-Argentine woman, dark brown skin, round face, white linen head wrap, faded indigo shawl, steady thoughtful eyes'],
 [108,'Julián Pereyra','Tiento','Domador de la campaña','gaucho','buenos_aires',270,[82,76,64,86,32,52,46,18,10,24],['expert_rider'],
  'Domó potros para las postas del sur. Perdió su tropilla en una requisa y busca reunir dinero para empezar de nuevo.',
  'Risueño con los compañeros, desconfiado con los oficiales. Nunca apura a una montura agotada.',
  ['Con un buen caballo llego.','Hay gente cerrando el paso.','Hasta los potros están tranquilos.','Un tiento y aguanto.','Preciso bajar de la montura.','Suelten mi caballo…','Con esta paga armaré otra tropilla.'],
  '29-year-old tan Argentine man, broad jaw, unruly black curls, thin mustache, worn brown gaucho hat, red neckerchief'],
 [109,"Edward Harcourt","Harcourt","Ex teniente coronel británico","soldado","ensenada",1170,[84,62,78,72,94,88,83,31,38,25],["teacher","steadfast"],
  "Antiguo teniente coronel de infantería británico. Vendió su comisión para cubrir deudas familiares y llegó al Plata como asesor de un comerciante. Ofrece instrucción y mando por contratos diarios, sin representar a la Corona.",
  "Formal y exigente. Prefiere una reserva bien situada a una carga vistosa y admite sus errores ante la tropa.",
  ["Mi antigua comisión terminó. Acordemos este servicio.","Mantengan la reserva fuera del fuego.","Reorganicen los pelotones antes de avanzar.","El segundo debe asumir mi puesto.","Un mando agotado da malas órdenes.","Conserven la reserva…","He servido según lo pactado. Ahora regresaré a mis asuntos."],
  "54-year-old British former lieutenant colonel, pale weathered skin, long aristocratic face, gray sideburns, clean shaven chin, faded scarlet high-collared infantry officer coat with dark facings and worn gold shoulder epaulette, white neck stock, no hat"],
 [110,'Baltasar Acosta','Acosta','Fusilero de milicias','soldado','retiro',300,[85,61,68,83,58,61,72,25,28,18],['steadfast'],
  'Trabajó como estibador y costeó su instrucción en las milicias. Prefiere un contrato escrito que le permita enviar parte de la paga a casa.',
  'Formal y protector. Repite las órdenes para que los más nuevos no queden perdidos.',
  ['Entendido. Ocuparé mi puesto.','Milicianos, mantengan la línea.','Contemos antes de celebrar.','Sigo sosteniendo el fusil.','Necesito relevo en la línea.','No separen la escuadra…','Mi familia tendrá noticias y mi paga.'],
  '42-year-old Black Argentine man, powerful build, close cropped hair, broad nose, dark blue plain militia coat with red collar'],
 [111,"Armand Delatour","Delatour","Ex mayor de ingenieros francés","artesano","ensenada",840,[77,60,89,71,78,91,62,92,86,24],["gunsmith_artillerist","workshop_training"],
  "Antiguo mayor de ingenieros francés, separado del servicio tras una disputa por suministros desaparecidos. Trabajó en obras portuarias antes de ofrecer al Cabildo sus conocimientos de fortificación, armas y pólvora.",
  "Meticuloso y poco diplomático. Exige cuentas claras porque una firma ajena ya le costó su carrera.",
  ["Necesito planos, herramientas y cuentas claras.","Ese abrigo no resistirá mucho.","Mediré los daños antes de ordenar reparaciones.","Aparten la pólvora mientras me vendan.","No calcularé una carga con este cansancio.","Mis cálculos están en la cartera…","Construiré un taller donde pueda responder por cada cuenta."],
  "43-year-old French former engineer major, olive skin, compact square face, black curly hair graying at temples, short neat mustache, dark blue high-collared engineer officer coat with black velvet facings, restrained brass buttons, worn gold shoulder trim"],
 [112,'Gaspar Villalba','Villalba','Cirujano de posta','artesano','cordoba',750,[64,58,91,49,62,91,42,30,19,94],['field_rescuer','teacher'],
  'Se formó como practicante y atendió a viajeros del Camino Real. Su instrumental es bueno, pero su consultorio no sobrevivió a las deudas.',
  'Minucioso y algo vanidoso. Explica cada cura incluso cuando nadie se lo pide.',
  ['Mi instrumental está preparado.','Busquemos un lugar para atender.','Primero revisaré a los heridos.','La hemorragia debe detenerse.','Mis manos ya no están firmes.','El maletín, por favor…','La próxima consulta será en mi casa.'],
  '51-year-old light olive skinned man, receding gray hair, small round period spectacles, clean shaven, brown waistcoat and white cravat'],
 [113,"Alistair Kerr","Kerr","Ex mayor de infantería ligera británico","baqueano","ensenada",810,[80,86,78,72,81,84,79,25,24,36],["guerrilla_tactician","night_vision"],
  "Escocés que dejó el ejército británico con grado de mayor tras una herida y una larga convalecencia. Recuperado para marchas cortas, llegó al Plata acompañando una expedición comercial y busca trabajo como explorador e instructor.",
  "Observador y seco al hablar. No permite que el orgullo de un oficial exponga a los exploradores.",
  ["Reconoceré el frente antes de comprometer hombres.","Hay movimiento más allá de esa cresta.","Dejen una pareja vigilando el paso.","La vieja herida no era la única.","Debemos acortar esta marcha.","Retírense por el camino reconocido…","Volveré a elegir mis caminos sin recibir órdenes."],
  "46-year-old Scottish British former light infantry major, fair windburned skin, lean face, auburn graying sideburns, hazel eyes, clean shaven, worn dark green high-collared officer coat with black braiding and white neck stock"],
 [114,'Eusebio Ledesma','Ledesma','Sargento instructor','soldado','retiro',660,[81,63,72,77,88,78,78,34,35,28],['teacher','steadfast'],
  'Pasó años instruyendo milicianos que partían antes de completar el ejercicio. Busca una unidad estable donde enseñar sin desperdiciar vidas.',
  'Severo con el descuido y paciente con el error honesto. Aprende los nombres de todos.',
  ['Comencemos por revisar la formación.','Recuerden lo que practicamos.','El ejercicio dio resultado.','Cubran mi lugar en la fila.','Hasta el instructor necesita relevo.','No olviden la instrucción…','Quiero verlos volver a sus oficios.'],
  '56-year-old brown-skinned man, gray horseshoe mustache, stern lined face, faded navy military coat, cropped gray hair'],
 [115,'Nicolás Funes','Funes','Tirador de las sierras','baqueano','cordoba',570,[70,74,82,62,31,75,86,42,21,17],['line_marksman'],
  'Cazaba para abastecer a una posta serrana. Compró un fusil usado a un viajero y paga sus deudas trabajando como tirador de escolta.',
  'Reservado y competitivo. Lleva una cuenta privada de los disparos desperdiciados.',
  ['Necesito una posición con buena vista.','Veo un blanco entre las piedras.','No hizo falta vaciar la cartuchera.','Todavía puedo sostener la mira.','Se me nubla la vista.','Guarden mi fusil…','Volveré a cazar para la posta.'],
  '35-year-old olive-skinned man, lean angular face, dark sideburns, stubble, faded charcoal poncho, narrow focused eyes'],
 [116,'Petrona Lagos','Lagos','Socorrista del Litoral','baqueano','san_nicolas',240,[75,75,71,72,43,68,39,18,9,70],['field_rescuer'],
  'Rescató familias durante las crecientes del Paraná. Quiere ganar lo suficiente para reparar la canoa con la que trabaja su comunidad.',
  'Práctica y generosa. Habla con calma incluso cuando todos gritan.',
  ['Si alguien cae, iré a buscarlo.','Agáchense junto a la ribera.','Voy a buscar a los rezagados.','Ayúdenme a salir de aquí.','Necesito sentarme junto al agua.','No dejen a nadie atrás…','Ya puedo reparar nuestra canoa.'],
  '45-year-old Afro-Argentine woman, strong square face, deep brown skin, cream headscarf tied behind head, weathered blue shawl'],
 [117,'Jacinto Ojeda','Ojeda','Lancero de frontera','gaucho','mendoza',450,[88,72,62,91,50,55,48,14,12,20],['cavalry_commander'],
  'Escoltó arreos por caminos de frontera. Acepta un estipendio para reemplazar el ganado perdido por una sociedad comercial mal llevada.',
  'Orgulloso y directo. Respeta a quien comparte la guardia nocturna.',
  ['La lanza está lista para marchar.','Puedo abrir paso por ese costado.','El camino nos pertenece.','No han logrado derribarme.','Den respiro a la caballada.','Que siga la carga…','Esta vez el arreo será mío.'],
  '40-year-old tan man, heavy black mustache, broad weather-beaten face, dark flat brim gaucho hat, ochre poncho'],
 [118,"Étienne Valcourt","Valcourt","Ex coronel de artillería francés","artesano","ensenada",1260,[82,54,83,76,89,92,67,84,95,23],["gunsmith_artillerist","teacher"],
  "Antiguo coronel de artillería francés. Una disputa política lo apartó del mando; abandonó Europa antes de 1812 y sobrevivió asesorando a armadores. Solo firma contratos diarios y exige revisar las municiones personalmente.",
  "Austero y paciente con los sirvientes de pieza. Se vuelve inflexible cuando un superior pretende ahorrar en seguridad.",
  ["Antes de firmar, quiero ver las municiones.","Batería, esperen mi indicación de tiro.","Aseguren las piezas y registren el consumo.","El servicio de la batería debe continuar.","Solicito relevo junto a la pieza.","No precipiten la siguiente carga…","Prefiero fundir herramientas a dirigir otra batería."],
  "58-year-old French former artillery colonel, pale lined face, bald crown with swept back silver hair, thick gray eyebrows, clean shaven, worn dark navy artillery officer coat with red collar, modest tarnished gold epaulettes, white cravat"],
 [119,'Benjamín Duarte','Duarte','Recluta de saladero','soldado','buenos_aires',150,[76,67,52,81,22,49,40,12,8,15],['steadfast'],
  'Dejó el saladero después de varios meses sin jornal. No tiene experiencia militar, pero sabe cargar peso y cumplir turnos largos.',
  'Tímido y aplicado. Pide instrucciones claras y guarda cada moneda.',
  ['Díganme dónde debo formar.','Creo que vienen hacia nosotros.','Lo logramos, de verdad.','No sé si es grave.','Necesito recuperar el aire.','Manden mi jornal a casa…','Voy a buscar un trabajo con paga cierta.'],
  '20-year-old Black man, round youthful face, very short curly hair, plain patched brown jacket and open white linen collar'],
 [120,'Mercedes Quiroga','Quiroga','Guía de quebradas','baqueano','jujuy',480,[73,85,75,68,57,86,70,20,18,48],['guerrilla_tactician','night_vision'],
  'Guio caravanas entre quebradas y conoce los refugios donde se puede pasar una noche sin fuego. Cobra para recuperar un pequeño almacén familiar.',
  'Cauta y mordaz. Desconfía de los mapas que omiten a los pobladores.',
  ['Conozco un camino con reparo.','Hay una silueta en la quebrada.','Podremos encender el fogón.','La piedra me sirve de abrigo.','Debemos parar antes de perdernos.','Busquen el refugio alto…','Reabriré el almacén junto al camino.'],
  '43-year-old Andean woman, russet brown skin, prominent cheekbones, black hair with silver streak, burgundy woven shawl'],
 [121,'Ramón Cáceres','Cáceres','Carpintero de campaña','artesano','santa_fe',300,[80,58,79,84,39,67,46,78,40,26],['workshop_training','gunsmith_artillerist'],
  'Reparaba carretas y embarcaciones pequeñas. Viaja con sus herramientas para reunir dinero con que comprar madera y establecerse.',
  'Paciente y literal. Prefiere medidas exactas a discursos largos.',
  ['Traje herramientas para la marcha.','Busquen abrigo detrás de la madera.','Eso puede repararse mañana.','No es una astilla pequeña.','Debo soltar las herramientas.','Aprovechen la madera…','Ya tengo para abrir la carpintería.'],
  '46-year-old tan man, thick eyebrows, salt and pepper short beard, brown leather apron, sturdy neck, kindly eyes'],
 [122,'Isabel Molina','Molina','Botánica y practicante','artesano','tucuman',510,[65,69,84,50,48,92,36,29,32,85],['field_rescuer'],
  'Recogía plantas y preparaba remedios para una botica tucumana. Quiere financiar un local propio sin depender del crédito del comerciante.',
  'Curiosa y prudente. Distingue lo que sabe de lo que apenas supone.',
  ['Llevo remedios y vendas limpias.','Necesitamos cubrir a los heridos.','Ahora revisaré sus lesiones.','Me falta fuerza en ese brazo.','No debo tratar a nadie así.','Entreguen mis notas a la botica…','Tendré una botica con cuentas propias.'],
  '31-year-old light brown skinned woman, oval face, dark brown eyes, center parted black hair pinned back, muted green shawl'],
 [123,'Santiago Soria','Soria','Fusilero veterano','soldado','tucuman',720,[83,68,81,76,65,72,88,35,43,31],['line_marksman','steadfast'],
  'Sirvió en escoltas y guarniciones antes de quedar sin destino. Ofrece tiro disciplinado y pide un contrato que termine en una fecha cierta.',
  'Sobrio y escéptico. No promete victorias, pero cumple cada guardia.',
  ['Una fecha y una paga. Entendido.','Esperen a tener un tiro claro.','La guardia continúa hasta el relevo.','Puedo terminar este turno.','Hace falta un relevo ahora.','Mi turno termina aquí…','He cumplido hasta el último día.'],
  '49-year-old olive-skinned man, long thin face, short gray sideburns, neat mustache, weathered dark blue infantry coat'],
 [124,"Thomas Ashford","Ashford","Ex mayor de dragones británico","gaucho","ensenada",780,[85,80,74,83,79,72,73,22,20,26],["cavalry_commander","expert_rider"],
  "Antiguo mayor de dragones británico que vendió su comisión y perdió el dinero en una sociedad de transporte. Llegó al Plata para trabajar con caballos y ofrece instrucción de caballería para recuperar su independencia.",
  "Enérgico y orgulloso de su equitación. Cuida más a las monturas que a su uniforme y rechaza las cargas sin salida.",
  ["Ensillaremos cuando conozcamos la ruta.","Dejen espacio entre las monturas.","Reúnan los caballos antes de perseguir.","Puedo desmontar sin ayuda.","La caballada necesita un descanso.","No cierren la salida…","Trabajaré con caballos sin pedir crédito otra vez."],
  "41-year-old British former dragoon major, fair ruddy skin, broad face, sandy blond hair, heavy sideburns and clean shaven chin, faded red cavalry officer jacket with dark blue collar and worn gold braid, white neck stock"],
 [125,'Diego Barrera','Barrera','Zapador de milicias','artesano','retiro',540,[85,61,75,88,45,71,60,76,83,20],['gunsmith_artillerist'],
  'Abrió zanjas y cimentó depósitos del puerto. Busca un estipendio mejor como zapador, con experiencia práctica en pólvora y herramientas.',
  'Precavido y tenaz. Se niega a improvisar con munición húmeda.',
  ['Primero revisaré las herramientas.','Cuidado con ese parapeto.','Ya podemos trabajar sin fuego.','Aparten las cargas de aquí.','No sostengo otra palada.','No enciendan esa mecha…','Construiré algo que no haya que derribar.'],
  '34-year-old brown-skinned man, stocky neck, broken nose, short black beard, plain russet work jacket'],
 [126,'Teresa Godoy','Godoy','Exploradora serrana','baqueano','cordoba',210,[63,81,65,53,28,71,49,14,10,32],['guerrilla_tactician'],
  'Cuidaba cabras en las sierras y conoce atajos entre puestos aislados. Su primer contrato ayudará a pagar el arrendamiento de su madre.',
  'Callada hasta que conoce a la gente. Aprende deprisa y no presume de ello.',
  ['Puedo mostrarles un atajo.','No son cabras: vi un arma.','Conozco dónde encontrar agua.','Me cuesta apoyar el pie.','Necesito parar en la sombra.','Busquen a mi madre…','Podremos conservar el puesto otro año.'],
  '21-year-old tan woman, youthful narrow face, straight dark hair in single braid, plain undyed wool shawl'],
 [127,'Esteban Peralta','Peralta','Tambor e instructor','soldado','san_nicolas',360,[71,76,80,61,79,74,57,20,23,38],['teacher'],
  'Marcaba el paso de una milicia local y terminó enseñando a los reemplazos. Quiere convertir esa experiencia en un oficio estable.',
  'Sociable y obstinado. Recuerda las órdenes como si fueran compases.',
  ['Cada cual encontrará su paso.','Junten filas, sin correr.','Buen trabajo, mantengan el orden.','Todavía puedo dar la voz.','Debo recuperar el ritmo.','Que otro marque el paso…','Ahora enseñaré a leer a los muchachos.'],
  '30-year-old Afro-Argentine man, medium dark skin, clean shaven, expressive eyes, curly hair, faded blue militia tunic'],
 [128,"William Blackwood","Blackwood","Ex teniente coronel de fusileros británico","soldado","ensenada",1350,[79,74,88,69,87,85,94,38,29,22],["line_marksman","teacher"],
  "Antiguo teniente coronel británico retirado tras desacuerdos con sus superiores sobre el uso de sus tiradores. Vendió sus intereses en Europa y trabaja para comerciantes del Plata. Cobra por jornadas de tiro e instrucción.",
  "Reservado y preciso. Reprende el disparo apresurado con más dureza que una mala puntería honesta.",
  ["Una jornada de servicio. Revisaré los campos de tiro.","Esperen a distinguir bien el blanco.","No abandonen todavía sus posiciones.","Tendré que modificar mi apoyo.","No instruiré ni dispararé con el pulso así.","Mantengan despejado el tiro…","La última jornada está cumplida y anotada."],
  "50-year-old British former rifle lieutenant colonel, pale skin, narrow angular face, dark hair with silver temples, small old scar beside eyebrow, clean shaven, dark green rifle officer coat with worn black braid and high collar"],
 [129,'Francisco Tapia','Tapia','Arriero del oeste','gaucho','mendoza',270,[86,64,60,88,44,65,45,32,10,26],['expert_rider'],
  'Condujo mulas cargadas de vino y herramientas. Una mala temporada lo llevó a ofrecer sus brazos y su experiencia ecuestre al ejército.',
  'Afable y firme. No acepta que se maltrate a los animales de carga.',
  ['Repartan la carga y salimos.','Detengan las mulas. Hay gente.','La carga puede seguir.','Me duele hasta la cincha.','Hay que aliviar el peso.','Lleven las mulas al agua…','Volveré a transportar vino por el paso.'],
  '53-year-old tan man, full graying beard, deeply lined cheeks, soft brown felt hat, striped muted ochre poncho'],
 [130,'Ángela Cejas','Cejas','Auxiliar de hospital','artesano','salta',180,[67,64,68,55,35,73,30,19,8,65],['field_rescuer'],
  'Lavaba vendas y asistía a los practicantes del hospital. Se incorpora con poca experiencia de combate para sostener a su padre enfermo.',
  'Compasiva y ansiosa. La rutina de atender a otros le devuelve la calma.',
  ['Puedo ayudar con los vendajes.','Busquen un muro, por favor.','Déjenme revisar esas vendas.','Esta sangre es mía.','Necesito calmar las manos.','Cuiden de mi padre…','Con la paga podré llevarlo a casa.'],
  '23-year-old brown-skinned woman, round dark eyes, soft cheeks, black hair under simple cream kerchief, faded gray blue shawl'],
 [131,'Vicente Arce','Arce','Carabinero de frontera','gaucho','salta',630,[82,81,76,79,64,68,82,29,23,25],['cavalry_commander','expert_rider'],
  'Patrulló caminos del norte hasta que su compañía quedó sin fondos. Aporta experiencia de carabina y una disciplina poco habitual entre partidas.',
  'Orgulloso de su oficio. Acepta críticas precisas y rechaza las burlas.',
  ['Carabina revisada. Podemos salir.','Jinetes, mantengan distancia.','Aseguremos el camino de vuelta.','Puedo mantenerme en la silla.','Mi montura y yo precisamos parar.','Sostengan el camino…','Buscaré una patrulla con paga regular.'],
  '39-year-old mestizo man, sharp cheekbones, black mustache, short hair, navy cavalry jacket with worn red trim'],
 [132,"Charles Pembroke","Pembroke","Ex coronel de infantería británico","soldado","ensenada",1080,[78,55,71,64,95,91,74,27,30,38],["teacher","steadfast"],
  "Antiguo coronel británico que dejó el servicio para administrar una herencia que resultó estar endeudada. Tras vender lo que quedaba, cruzó el Atlántico como instructor particular. Busca un contrato diario con atribuciones claras.",
  "Cortés y obstinado. Escucha a los sargentos, pero puede tardar demasiado en abandonar una formación conocida.",
  ["Definamos mis responsabilidades antes de comenzar.","Sargentos, mantengan unidas sus secciones.","Pasen lista y preparen el relevo.","Delegaré el mando mientras me atienden.","Necesito una pausa antes de decidir.","Escuchen a sus sargentos…","No dejaré otra cuenta sin pagar."],
  "61-year-old British former infantry colonel, fair skin, full dignified face, thinning silver hair, long white sideburns, clean shaven, worn scarlet officer coat with buff collar, faded gold epaulettes and white stock"],
 [133,'Pedro Albornoz','Albornoz','Herrero de herraduras','artesano','mendoza',330,[89,52,74,94,31,60,43,83,31,20],['gunsmith_artillerist','workshop_training'],
  'Forjó herraduras y reparó útiles de estancia durante veinte años. Se presenta con sus herramientas para pagar una nueva fragua.',
  'Lento al hablar y rápido al trabajar. No tolera el desperdicio de hierro.',
  ['Mi martillo viaja conmigo.','Busquen cubierta resistente.','Recojan el hierro aprovechable.','La herida no es superficial.','Los brazos ya no responden.','No pierdan el martillo…','Levantaré una fragua mejor ventilada.'],
  '48-year-old dark brown skinned man, massive shoulders, shaved head, short gray beard, worn leather blacksmith apron'],
 [134,'Mariano Véliz','Véliz','Vigía nocturno','baqueano','tucuman',390,[68,84,77,58,33,80,68,23,17,29],['night_vision','guerrilla_tactician'],
  'Vigilaba depósitos de tabaco y acompañaba convoyes de noche. Le cuesta trabajar de día, pero distingue movimiento donde otros apenas ven sombras.',
  'Suspicaz y puntual. Revisa dos veces cada puerta antes de descansar.',
  ['Tomaré la guardia después del ocaso.','Esa sombra acaba de moverse.','La noche vuelve a estar quieta.','No dejen que me duerma.','Necesito cerrar los ojos un rato.','Hay alguien detrás…','Por fin dormiré una noche entera.'],
  '33-year-old pale olive skinned man, deep set dark eyes, long nose, black shoulder length hair, charcoal wool scarf'],
 [135,'Josefa Roldán','Roldán','Practicante veterana','artesano','jujuy',900,[76,65,89,60,74,90,49,31,21,93],['field_rescuer','teacher'],
  'Organizó puestos de socorro para varias caravanas atacadas. La solicitan por su experiencia y reserva sus servicios para contratos diarios.',
  'Firme y poco sentimental al trabajar. Después recuerda el nombre de cada paciente.',
  ['Hoy tendrán un puesto de socorro.','Preparen un lugar protegido.','Nadie se va sin revisión.','Necesito que compriman la herida.','Otro debe hacerse cargo un momento.','Anoten los nombres…','Seguiré atendiendo cuando termine la guerra.'],
  '58-year-old Andean woman, weathered copper skin, gray braided hair, deep smile lines, muted blue wool shawl over linen'],
 [136,'Lorenzo Silva','Silva','Guardia de convoy','soldado','santa_fe',420,[90,58,65,89,52,61,69,27,26,31],['steadfast'],
  'Custodió carretas de cuero y yerba durante años. Busca empleo en una escuadra donde el relevo sea tan fiable como la paga.',
  'Tranquilo y resistente. No deja su puesto mientras falte un compañero.',
  ['Me encargaré de la retaguardia.','No dejen descubierto el convoy.','Llegaron todos. Ahora descanso.','Aún puedo cubrir el camino.','Preciso que alguien me releve.','No abandonen las carretas…','Llevaré un convoy sin escolta algún día.'],
  '41-year-old Afro-Argentine man, broad square jaw, short beard, dark skin, brown traveling coat and ochre neckcloth'],
 [137,"Louis Desforges","Desforges","Ex teniente coronel de caballería francés","gaucho","ensenada",960,[85,83,79,82,85,78,81,23,24,28],["cavalry_commander","expert_rider"],
  "Antiguo teniente coronel de caballería francés, apartado del servicio después de negarse a respaldar una denuncia contra sus oficiales. Llegó al Plata por contactos mercantiles y alquila su experiencia sin jurar fidelidad a un nuevo monarca.",
  "Audaz, con orgullo herido. Protege a sus subordinados, aunque le cuesta aceptar el mando de alguien más joven.",
  ["Serviré a la escuadra según nuestro acuerdo.","Reconozcan el flanco antes de cargar.","Detengan la persecución y reúnan la tropa.","Cubran a los jinetes mientras desmonto.","Necesito recuperar fuerzas antes de otra carga.","No abandonen a los desmontados…","Mi nombre volverá a valer por mi palabra."],
  "45-year-old French former cavalry lieutenant colonel, olive skin, handsome weathered face, black wavy hair, thick curled mustache, faded blue hussar officer dolman with restrained worn gold cords and red collar"],
 [138,'Henri Beaumont','Beaumont','Artillero francés','artesano','ensenada',810,[77,55,84,75,64,85,67,84,94,26],['gunsmith_artillerist'],
  'Un artillero francés que llegó como tripulante de un mercante. Ofrece sus conocimientos de piezas y municiones para establecerse en el puerto.',
  'Metódico y orgulloso. Cuenta las cargas en voz baja cuando está nervioso.',
  ['Revisaré el material antes del contrato.','Atención a la distancia del blanco.','La pieza ha cumplido su servicio.','Otro debe tomar el atacador.','Mis manos necesitan reposo.','Cuenten las cargas restantes…','Quiero un oficio en este puerto.'],
  '47-year-old French man, pale weathered face, receding brown hair, bushy sideburns, dark naval artillery coat'],
 [139,'Bridget O’Connell','Bridget','Enfermera irlandesa','artesano','ensenada',570,[73,68,86,62,59,84,44,27,16,89],['field_rescuer'],
  'Una irlandesa que asistió a tripulantes enfermos en travesías mercantes. Busca un contrato de tierra para dejar de depender de cada capitán.',
  'Cálida y resuelta. Usa el humor para distraer a los pacientes del dolor.',
  ['Prefiero atender en tierra firme.','A cubierto, que aquí no hay borda.','Traigan agua limpia para las vendas.','Hoy me toca ser paciente.','Necesito sentarme sin que todo se mueva.','Lleven mi carta al puerto…','Abriré una casa de socorro en tierra.'],
  '34-year-old Irish woman, fair freckled skin, red hair pinned back, green gray eyes, plain blue shawl and white linen blouse'],
 [140,'Matteo Ricci','Ricci','Armero genovés','artesano','ensenada',480,[65,71,92,56,38,81,57,91,64,19],['gunsmith_artillerist'],
  'Un cerrajero genovés que reparó armas de marineros para costear su pasaje. Espera reunir suficiente plata para traer sus herramientas del depósito.',
  'Perfeccionista y hablador. Describe cada pieza como si fuera irreemplazable.',
  ['Una buena llave merece cuidado.','No golpeen el arma al cubrirse.','Voy a revisar esos mecanismos.','No puedo mover bien los dedos.','Necesito soltar las tenazas.','Mi juego de limas…','Ya puedo rescatar todas mis herramientas.'],
  '28-year-old Italian man, olive complexion, slender face, wavy chestnut hair, fine mustache, leather vest over cream shirt'],
 [141,'Joaquim Ferreira','Ferreira','Marinero portugués','soldado','ensenada',360,[84,75,70,85,40,62,62,44,32,30],['steadfast'],
  'Un marinero portugués que quedó varado tras venderse su buque. Busca empleo regular como guardia y conoce bien la reparación de cubierta.',
  'Pragmático y buen compañero. Siempre separa una ración para quien falta.',
  ['Mientras haya paga, hay servicio.','Busquen abrigo como en cubierta.','Hoy nadie falta al reparto.','He recibido golpes peores en el puerto.','Necesito agua y un banco.','Guarden mi ración…','Buscaré una casa cerca del muelle.'],
  '39-year-old Portuguese man, sun darkened olive skin, curly black beard, short hair, navy wool sailor jacket and red scarf'],
 [142,'Samuel Reed','Reed','Fusilero británico','soldado','ensenada',1080,[79,73,88,70,60,79,94,39,33,22],['line_marksman'],
  'Un tirador británico expatriado que trabaja para comerciantes. Cobra caro por su experiencia y solo firma por una jornada a la vez.',
  'Distante y exacto. Considera sagrados los términos de un contrato.',
  ['Firmado. Una jornada de cobertura.','Distancia suficiente. No se crucen.','Mi sector está despejado.','Tendré que cambiar de apoyo.','Necesito descansar antes de otro tiro.','El contrato queda cumplido…','Cobraré lo acordado y seguiré viaje.'],
  '44-year-old British man, fair ruddy skin, sandy graying hair, clean shaven angular face, dark green rifleman coat without insignia'],
 [143,"Philippe Montreuil","Montreuil","Ex coronel de estado mayor francés","soldado","ensenada",1200,[76,58,77,61,93,94,71,43,46,35],["teacher","steadfast"],
  "Antiguo coronel de estado mayor francés. Perdió su destino tras una purga administrativa y emigró con cartas de recomendación de comerciantes. Ofrece organización e instrucción por jornadas; su talento está en preparar una operación, no en encabezarla.",
  "Analítico y desconfiado del entusiasmo. Redacta órdenes breves y pide a cada subordinado que las repita.",
  ["Comenzaremos por los efectivos y los suministros.","Confirmen el contacto antes de cambiar el plan.","Aseguren el enlace con la retaguardia.","Otro debe transmitir las órdenes.","No debo decidir con esta fatiga.","Las instrucciones están en la cartera…","Esta vez prepararé una empresa sin soldados."],
  "55-year-old French former staff colonel, pale olive skin, long thoughtful face, straight graying dark hair brushed back, clean shaven, dark blue high-collared officer coat, red facings, restrained gold shoulder trim, neatly tied white cravat"],
 [144,'Karl Weiss','Weiss','Mecánico de piezas','artesano','cordoba',630,[79,56,87,80,43,86,52,94,80,25],['gunsmith_artillerist','workshop_training'],
  'Un mecánico de habla alemana contratado por comerciantes para mantener herramientas importadas. Viaja a Caroya buscando un taller mejor equipado.',
  'Literal y perseverante. No abandona una reparación porque termine la jornada.',
  ['Revisaré los ejes y las llaves.','Protejan el material de repuesto.','Podremos reparar con tranquilidad.','No aprieten demasiado la venda.','Debo descansar antes de ajustar nada.','Las piezas están numeradas…','Buscaré un banco de trabajo permanente.'],
  '52-year-old German man, pale skin, broad forehead, swept back graying blond hair, square beard, brown artisan waistcoat'],
 [145,'Domingo Farías','Farías','Jinete veterano','gaucho','salta',990,[88,85,78,87,77,74,87,24,20,33],['cavalry_commander','expert_rider'],
  'Condujo escoltas por el norte durante dos décadas. Su experiencia permite organizar una carga, pero solo acepta compromisos diarios bien pagados.',
  'Austero y protector. Nunca pide al más joven que asuma el mayor riesgo.',
  ['Una jornada. Yo guiaré a los jinetes.','Esperen mi señal para avanzar.','Reúnan la caballada y cuenten a todos.','No pierdan el orden por mi herida.','Hay que dar descanso a las monturas.','El más joven debe volver…','Volveré al norte con los que queden.'],
  '55-year-old tan Argentine man, weather-beaten face, thick silver mustache, black gaucho hat, deep red poncho'],
 [146,"Auguste Bellanger","Bellanger","Ex cirujano mayor del ejército francés","artesano","ensenada",690,[72,61,90,55,76,92,41,33,26,91],["field_rescuer","teacher"],
  "Antiguo cirujano mayor de un hospital militar francés. Renunció tras un conflicto por suministros y viajó como médico de un mercante. Quiere reunir dinero para una clínica; aporta mando sanitario y experiencia, pero poca práctica con armas.",
  "Compasivo con los pacientes y áspero con la negligencia. Exige agua limpia antes que una mesa elegante.",
  ["Organizaré el socorro antes de que partamos.","Preparen un lugar para recibir heridos.","Clasifiquen las lesiones; nadie espera por su grado.","Ahora necesito que sigan mis indicaciones.","Mis manos requieren descanso.","El instrumental debe seguir en uso…","Abriré una clínica con suministros suficientes."],
  "49-year-old French former senior army surgeon, light olive skin, tired kind eyes, receding dark hair with gray temples, small round period wire spectacles, clean shaven, plain dark blue medical officer coat with burgundy collar and white cravat"],
 [147,'Andrés Montiel','Montiel','Explorador veterano','baqueano','jujuy',870,[78,94,86,71,67,88,83,28,24,47],['guerrilla_tactician','night_vision'],
  'Guio partidas por pasos de altura y sobrevivió a varias retiradas. Pide paga de veterano y contratos breves para escoger sus próximos destinos.',
  'Calmo y desconfiado de la prisa. Siempre reconoce una segunda salida.',
  ['Primero reconoceré el camino de vuelta.','Hay una patrulla sobre el paso.','Dejaré señales para los rezagados.','Todavía conozco una salida.','No llegaré si sigo sin descanso.','Sigan mis marcas…','Esta vez cruzaré sin mirar atrás.'],
  '46-year-old Andean man, deep copper skin, high cheekbones, black hair streaked gray, dark woven poncho, watchful eyes'],
];
const attributes=['maxHp','agility','dexterity','strength','leadership','wisdom','marksmanship','mechanical','explosives','medical'];
const equipment={gaucho:[1803,1813],soldado:[1800,1811],baqueano:[1804,1813],artesano:[1805,1813]};
export const FORMER_OFFICER_IDS=[109,111,113,118,124,128,132,137,143,146];
const elites=new Set([109,118,128,132,135,138,142,143,145,147]);
export const MERCENARY_ADDITIONS=recruits.map(([id,name,nickname,role,classId,sector,monthlyPay,stats,traits,biography,personality,lines,appearance])=>({
 id,name,nickname,role,classId,sector,monthlyPay,weeklyPay:Math.ceil(monthlyPay/30)*7,
 ...Object.fromEntries(attributes.map((key,i)=>[key,stats[i]])),hp:stats[0],traits,
 weapon:traits.includes('line_marksman')?1802:equipment[classId][0],blade:id===117?1812:equipment[classId][1],
 ridingSkill:classId==='gaucho'?80:20,priming:50,flints:4,rations:2,
 foreign:(id>=138&&id<=144)||FORMER_OFFICER_IDS.includes(id),tier:elites.has(id)?'elite':'regular',
 biography:`Personaje ficticio. ${biography}`,personalityText:personality,lines,appearance,
}));
