// Paid municipal errands, completed once through adjacent NPC dialogue.
// IDs are stable so old quest progress remains valid.
export const NPC_QUESTS=[
 {id:'retiro-uniformes',npcId:'local-retiro',sector:'retiro',title:'Presentarse ante la guardia',reward:120,requiredSectors:['retiro'],offer:'El Cabildo paga 120 pesos por llevar tu presentación a la guardia. Confirmá el encargo conmigo para recibir el pago.',delivery:'La guardia recibió tu presentación. El Cabildo abona 120 pesos.'},
 {id:'posta-polvora',npcId:'local-san_nicolas',sector:'san_nicolas',title:'Asegurar la posta',reward:200,requiredSectors:['san_nicolas'],offer:'Liberá San Nicolás y volvé a dar el parte. El Cabildo pagará 200 pesos por restablecer el servicio de correos.',delivery:'La posta vuelve a funcionar. Recibís 200 pesos por el servicio.'},
 {id:'salta-correos',npcId:'macacha',sector:'salta',title:'Abrir la ruta del norte',reward:400,requiredSectors:['salta','jujuy'],offer:'Asegurá Salta y Jujuy y volvé a informarme. Pagaré 400 pesos cuando los enlaces puedan recorrer ambas localidades.',delivery:'Salta y Jujuy están seguras. Recibís 400 pesos por abrir la ruta.'},
];
export function questForNPC(state,npcId){const q=NPC_QUESTS.find(q=>q.npcId===npcId);return q?{...q,status:state.quests?.[q.id]?.status??'unoffered',conditionMet:q.requiredSectors.every(id=>state.sectors[id]?.owner==='patriot')}:null;}
export function validateQuests(quests,hour){return quests&&typeof quests==='object'&&!Array.isArray(quests)&&Object.entries(quests).every(([id,q])=>NPC_QUESTS.some(n=>n.id===id)&&q&&['offered','completed'].includes(q.status)&&Number.isInteger(q.offeredAt)&&q.offeredAt>=0&&q.offeredAt<=hour&&(q.status==='offered'?q.completedAt===null:Number.isInteger(q.completedAt)&&q.completedAt>=q.offeredAt&&q.completedAt<=hour));}
