// Deterministic, serializable tactical simulation. The browser uses this module directly.
export const WEAPONS = Object.fromEntries([
  [1800,'Brown Bess',58,12,6,45,18,1],[1801,'Charleville',52,11,5,42,22,1],
  [1802,'Fusil Baker',64,16,10,70,45,1],[1803,'Tercerola',44,9,4,38,12,1],
  [1804,'Escopeta Criolla',48,10,4,35,10,1],[1805,'Pistola de Arzón',42,7,3,32,8,1],
  [1806,'Pistola de Duelo de Oficial',38,6,2,28,12,1],[1807,'Trabuco Naranjero',75,12,5,40,6,1],
  [1808,'Pistola Doble Cañón',40,8,3,55,9,2],
].map(([id,name,damage,fireAP,aimAP,reloadAP,range,capacity])=>[id,{id,name,damage,fireAP,aimAP,reloadAP,range,capacity}]));
export const ARTILLERY={bronze4:{name:'Cañón de Bronce de 4 lb',crew:2,fireAP:30,reloadAP:60,radius:4,range:80,damage:85},field8:{name:'Cañón de Campaña de 8 lb',crew:3,fireAP:40,reloadAP:75,radius:6,range:110,damage:110},swivel:{name:'Pedrero de Regala',crew:1,fireAP:20,reloadAP:35,radius:3,range:35,damage:65}};
export const BLADES=Object.fromEntries([[1809,'Sable Corvo Sanmartiniano',12,46,1.5],[1810,'Sable de Caroya',14,42,1.5],[1811,'Bayoneta de Cubo',16,50,2],[1812,'Lanza de Tacuara',18,56,2.5],[1813,'Facón Gaucho con Poncho',8,32,1.5]].map(([id,name,ap,damage,reach])=>[id,{id,name,ap,damage,reach}]));
export function bladeFor(unit){return unit.activeSlot==='blade'?(BLADES[unit.blade]||BLADES[unit.weapon]||BLADES[1811]):(BLADES[unit.weapon]||BLADES[1811]);}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const alive=u=>u.hp>0&&!u.routed;
const clone=s=>{const copy=structuredClone(s);for(const u of copy.units){u.activeSlot??='primary';u.reactionSpent??=0;u.reactionTurn??=0;u.interceptTurn??=0;u.fatigue??=0;}copy.artillery??=[];return copy;};
function random(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function say(s,text){s.log.push(text);s.log=s.log.slice(-80);}
export function hasFirearm(unit){if(unit.activeSlot==='blade')return false;return typeof unit.weapon==='object'?unit.weapon.capacity>0:Boolean(WEAPONS[unit.weapon]);}
export function weaponFor(unit){if(unit.activeSlot==='blade')return {...bladeFor(unit),fireAP:0,aimAP:0,reloadAP:0,capacity:0,range:bladeFor(unit).reach};return typeof unit.weapon==='object'?unit.weapon:WEAPONS[unit.weapon]||{...bladeFor(unit),fireAP:0,aimAP:0,reloadAP:0,capacity:0,range:bladeFor(unit).reach};}
export function misfireChance(condition=100,rain=0,humidity=0){return clamp(Math.round(2+(100-clamp(condition,0,100))*.2+clamp(rain,0,100)*.5+clamp(humidity,0,100)),0,95);}
function nearby(s,u,id,radius=4){return s?.units.some(v=>Number(v.id)===id&&v.side===u.side&&alive(v)&&dist(u,v)<=radius);}
export function maxActionPoints(s,u){const fatigue=clamp(u.fatigue||0,0,100),high=s.altitude>=2500||s.biome==='mountain',cold=high||s.weather.rain>0;return Math.round(clamp(100-fatigue*.4-(high?15:0)-(cold&&!u.poncho?10:0),35,100));}
function holdMorale(s,u){if(nearby(s,u,57,6)||(u.militia&&nearby(s,u,1,4))){u.morale=Math.max(20,u.morale);u.routed=false;return true;}return false;}
export function reloadCost(unit,state){const w=weaponFor(unit),rounds=Math.min(w.capacity-unit.loaded,unit.ammo);return rounds<=0?0:Math.ceil(Math.ceil(w.reloadAP*rounds/w.capacity)*(unit.stance==='prone'?1.5:1)*(state&&nearby(state,unit,2,2)?.8:1));}
function makeUnit(raw,side,index,x,y){const stats=raw.stats||{};const weapon=raw.weapon??raw.primary??1800;const w=typeof weapon==='object'?weapon:WEAPONS[weapon]||WEAPONS[1800];return {...raw,id:String(raw.id??`${side}-${index}`),name:raw.name||raw.nickname||(side==='player'?'Granadero':'Realista'),side,x:raw.x??x,y:raw.y??y,maxHp:raw.maxHp??raw.health??stats.health??100,hp:raw.hp??raw.health??stats.health??100,ap:100,morale:raw.morale??80,marksmanship:raw.marksmanship??stats.marksmanship??70,agility:raw.agility??stats.agility??75,strength:raw.strength??stats.strength??75,medical:raw.medical??stats.medical??30,weapon,loaded:raw.loaded??(WEAPONS[weapon]||typeof weapon==='object'?w.capacity:0),ammo:raw.ammo??12,condition:raw.condition??100,stance:'standing',mounted:Boolean(raw.mounted),horse:Boolean(raw.horse||raw.canMount||raw.mounted),jammed:false,bleeding:0,routed:false,medkits:raw.medkits??2,momentum:0,lastDirection:null,activeSlot:raw.activeSlot||'primary',fatigue:raw.fatigue||0,interceptTurn:0,overwatch:side==='enemy',reactionTurn:0,reactionSpent:0};}
export function createBattle(squad=[],sector={}){const width=sector.width||16,height=sector.height||12;const state={version:1,sectorId:sector.sector||sector.id||'san-lorenzo',sectorName:sector.name||'San Lorenzo',width,height,biome:sector.biome||'grassland',altitude:sector.altitude||0,decor:sector.decor||[],turn:1,phase:'player',status:'active',seed:(sector.seed??18130203)>>>0,weather:{rain:0,humidity:0,...sector.weather},tiles:[],units:[],artillery:(sector.artillery||[]).map((g,i)=>({id:`gun-${i}`,type:'bronze4',side:'player',loaded:true,ammo:6,...g})),smoke:[],log:[],lastError:null};
state.weather.rain=typeof state.weather.rain==='boolean'?(state.weather.rain?40:0):state.weather.rain;state.weather.humidity=state.weather.humidity>0&&state.weather.humidity<=1?state.weather.humidity*10:state.weather.humidity;
for(let y=0;y<height;y++)for(let x=0;x<width;x++){const edge=x===Math.floor(width*.56)&&y>1&&y<height-2&&y!==Math.floor(height/2);state.tiles.push({x,y,type:edge?'wall':sector.biome==='wetland'&&x>3&&x<width-3&&y%3===0?'mud':sector.biome==='mountain'||sector.biome==='foothills'?'stone':'grass',blocked:edge,cover:edge?40:sector.biome==='forest'&&x>3&&x<width-3&&y%3===0?20:0});}
if(Array.isArray(sector.tiles))state.tiles=sector.tiles.map(t=>({blocked:false,cover:0,...t}));
state.units=squad.map((u,i)=>makeUnit(u,'player',i,1+Math.floor(i/(height-2)),1+i%(height-2)));
const enemies=Array.isArray(sector.enemies)?sector.enemies:Array.from({length:sector.enemyCount||Math.max(3,squad.length+(sector.difficulty||1)-1)},(_,i)=>({id:`enemy-${i}`,name:`Realista ${i+1}`,weapon:i%3===0?1801:1800,marksmanship:50+(sector.difficulty||1)*5,morale:60+(sector.difficulty||1)*5}));
state.units.push(...enemies.map((u,i)=>makeUnit(u,'enemy',i,width-2-Math.floor(i/(height-2)),1+i%(height-2))));
if(!state.artillery.length&&sector.cannons>0)state.artillery=Array.from({length:Math.min(sector.cannons,3)},(_,i)=>({id:`gun-${i}`,type:'bronze4',side:'player',x:2,y:2+i*3,loaded:true,ammo:6}));
for(const u of state.units){u.maxAP=maxActionPoints(state,u);u.ap=u.maxAP;}
say(state,`Combate en ${state.sectorName}. Cada soldado dispone de 100 puntos de acción.`);checkEnd(state);return state;}
function tile(s,x,y){return s.tiles.find(t=>t.x===x&&t.y===y);}
function occupied(s,x,y,except){return s.units.some(u=>alive(u)&&u.id!==except&&u.x===x&&u.y===y);}
function stepCost(u,t){return (u.mounted?4:u.stance==='prone'?16:8)*(t?.type==='mud'?(u.mounted?(Number(u.id)===0?1.25:2):1.5):1);}
export function getReachable(s,unitOrId){const u=typeof unitOrId==='object'?unitOrId:s.units.find(u=>u.id===String(unitOrId));if(!u||!alive(u)||s.status!=='active')return [];const costs=new Map([[`${u.x},${u.y}`,0]]),paths=new Map([[`${u.x},${u.y}`,[]]]),queue=[{x:u.x,y:u.y,cost:0}];while(queue.length){queue.sort((a,b)=>a.cost-b.cost);const p=queue.shift();for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,y=p.y+dy,t=tile(s,x,y);if(!t||t.blocked||occupied(s,x,y,u.id))continue;const key=`${x},${y}`,cost=p.cost+stepCost(u,t);if(cost>u.ap||cost>=(costs.get(key)??Infinity))continue;costs.set(key,cost);paths.set(key,[...paths.get(`${p.x},${p.y}`),{x,y}]);queue.push({x,y,cost});}}return [...costs].map(([key,cost])=>{const[x,y]=key.split(',').map(Number);return{x,y,cost,path:paths.get(key)};});}
function line(a,b){const points=[];let x=a.x,y=a.y;const dx=Math.abs(b.x-x),dy=Math.abs(b.y-y),sx=x<b.x?1:-1,sy=y<b.y?1:-1;let err=dx-dy;while(x!==b.x||y!==b.y){const e=2*err;if(e>-dy){err-=dy;x+=sx;}if(e<dx){err+=dx;y+=sy;}points.push({x,y});}return points;}
export function hasLineOfSight(s,a,b){return !line(a,b).slice(0,-1).some(p=>tile(s,p.x,p.y)?.blocked);}
export function shotChance(s,attacker,target,aim=0){if(!hasLineOfSight(s,attacker,target))return 0;const w=weaponFor(attacker),range=dist(attacker,target);let cap=w.id===1802?(range<=45?95:Math.max(1,85-(range-50)*5)):(range<=15?85:range<=25?85-(range-15)*5:range<=35?35-(range-25)*3:Math.max(1,5-(range-35)));const obscured=line(attacker,target).filter(p=>s.smoke.some(v=>dist(p,v)<=v.radius)).length;return Math.round(clamp(Math.min(cap,attacker.marksmanship+(nearby(s,attacker,57,6)?12:0)+(nearby(s,attacker,11,4)?8:0)+clamp(aim,0,4)*8-range*1.1-(attacker.maxHp-attacker.hp)*.3-(target.stance==='prone'?18:0)-(tile(s,target.x,target.y)?.cover||0)-Math.max(0,range-w.range)*4-(attacker.mounted&&![1803,1805,1806,1808].includes(w.id)?15:0)-obscured*12),1,95));}
function checkEnd(s){if(!s.units.some(u=>u.side==='player'&&alive(u))){s.status='defeat';say(s,'La escuadra quedó fuera de combate.');}else if(!s.units.some(u=>u.side==='enemy'&&alive(u))){s.status='victory';say(s,'¡Victoria! El enemigo abandonó el campo.');}}
function damage(s,target,amount,source,projectile=false){if(projectile&&(Number(target.id)===57||(target.leadership||0)>=90)){const guard=s.units.find(v=>Number(v.id)===3&&v.side===target.side&&v.id!==target.id&&alive(v)&&v.hp>25&&v.ap>=8&&v.interceptTurn!==s.turn&&dist(v,target)<=1.5);if(guard){guard.ap-=8;guard.interceptTurn=s.turn;say(s,`${guard.name} se interpone para proteger a ${target.name}.`);target=guard;}}target.hp=Math.max(0,target.hp-Math.round(amount));target.bleeding=target.hp>0?Math.min(10,target.bleeding+Math.ceil(amount/15)):0;target.morale=Math.max(0,target.morale-amount*.45);say(s,`${source.name} hiere a ${target.name}: ${Math.round(amount)} de daño.`);if(target.hp===0){say(s,`${target.name} cayó en combate.`);for(const u of s.units.filter(u=>u.side===target.side&&alive(u)))u.morale=Math.max(0,u.morale-18);}holdMorale(s,target);if(target.hp>0&&target.morale<15){target.routed=true;say(s,`${target.name} pierde la moral y huye.`);}}
function reactionFire(s,mover){
for(const defender of s.units.filter(u=>u.side!==mover.side&&alive(u)&&u.overwatch&&u.reactionTurn!==s.turn&&hasFirearm(u)&&u.loaded>0&&!u.jammed)){
if(!alive(mover)||s.status!=='active')break;
if(dist(defender,mover)>8||!hasLineOfSight(s,defender,mover)||shotChance(s,defender,mover)<25||defender.ap<weaponFor(defender).fireAP)continue;
defender.reactionTurn=s.turn;const before=defender.ap;say(s,`${defender.name} interrumpe el avance con fuego de reacción.`);
apply(s,{type:'fire',unitId:defender.id,targetId:mover.id},defender.side==='enemy');defender.reactionSpent+=before-defender.ap;
}}
function apply(s,a,enemy=false){const fail=text=>{s.lastError=text;say(s,text);return false;};const u=s.units.find(u=>u.id===String(a.unitId));if(s.status!=='active')return fail('El combate ya terminó.');if(!u||!alive(u))return fail('El soldado no puede actuar.');if(u.side!==(enemy?'enemy':'player'))return fail('No puedes dar órdenes a ese soldado.');const target=s.units.find(u=>u.id===String(a.targetId));const pay=n=>{if(u.ap<n)return false;u.ap-=n;return true;};
if(a.type==='move'){const path=getReachable(s,u).find(p=>p.x===a.x&&p.y===a.y);if(!path||path.cost===0)return fail('Destino inaccesible o puntos de acción insuficientes.');pay(path.cost);for(const p of path.path){const dir=`${p.x-u.x},${p.y-u.y}`;u.momentum=dir===u.lastDirection?u.momentum+1:1;u.lastDirection=dir;u.x=p.x;u.y=p.y;reactionFire(s,u);if(!alive(u)||s.status!=='active')break;}say(s,`${u.name} avanza (${path.cost} PA).`);}
else if(a.type==='fire'){if(!target||target.side===u.side||!alive(target))return fail('Selecciona un enemigo activo.');if(!hasFirearm(u))return fail('Este soldado lleva un arma blanca: acércate para atacar.');if(u.jammed)return fail('La cazoleta falló: vuelve a cebar el arma.');if(u.loaded<1)return fail('El arma está descargada.');if(!hasLineOfSight(s,u,target))return fail('No hay línea de tiro.');const aim=clamp(Math.floor(a.aim||0),0,4),w=weaponFor(u),chance=shotChance(s,u,target,aim);if(!pay(w.fireAP+aim*w.aimAP))return fail('Faltan puntos de acción para disparar.');u.momentum=0;const risk=misfireChance(u.condition,s.weather.rain,s.weather.humidity)*(w.id===1801?.9:1)-(w.id===1806?1:0);if(random(s)*100<risk){u.jammed=true;say(s,`${u.name}: fallo de chispa. La carga se conserva; cebar cuesta 15 PA.`);}else{u.loaded--;u.condition=Math.max(0,u.condition-1);s.smoke.push({x:u.x,y:u.y,radius:1,turns:3});if(random(s)*100<chance)damage(s,target,w.damage*(.8+random(s)*.4),u,true);else{target.morale=Math.max(0,target.morale-4);say(s,`${u.name} dispara y falla (${chance}%).`);}}}
else if(a.type==='reload'){if(!hasFirearm(u))return fail('Las armas blancas no necesitan recarga.');if(u.jammed)return fail('Primero debes volver a cebar el arma.');const cost=reloadCost(u,s);if(!cost)return fail('No falta carga o no quedan cartuchos.');if(!pay(cost))return fail('Faltan puntos de acción para recargar.');const n=Math.min(weaponFor(u).capacity-u.loaded,u.ammo);u.loaded+=n;u.ammo-=n;u.momentum=0;say(s,`${u.name} recarga (${cost} PA).`);}
else if(a.type==='reprime'){if(!u.jammed)return fail('El arma no necesita cebado.');if(!pay(15))return fail('Cebar requiere 15 PA.');u.jammed=false;say(s,`${u.name} vuelve a cebar la cazoleta.`);}
else if(a.type==='melee'){const blade=bladeFor(u);if(!target||!alive(target)||target.side===u.side||dist(u,target)>blade.reach||!hasLineOfSight(s,u,target))return fail('Debes acercarte al enemigo para atacar con arma blanca.');if(!pay(blade.ap))return fail(`El ataque requiere ${blade.ap} PA.`);const direction=`${Math.sign(target.x-u.x)},${Math.sign(target.y-u.y)}`;const bonus=1+(direction===u.lastDirection?Math.min(u.momentum,5)*.1:0);damage(s,target,blade.damage*bonus,u);u.momentum=0;}
else if(a.type==='charge'){const blade=bladeFor(u);if(!target||!alive(target)||target.side===u.side)return fail('Selecciona un enemigo para cargar.');const dx=target.x-u.x,dy=target.y-u.y;if(dx!==0&&dy!==0&&Math.abs(dx)!==Math.abs(dy))return fail('La carga exige una línea recta.');let path=line(u,target);const contact=path.findIndex(p=>dist(p,target)<=blade.reach);path=dist(u,target)<=blade.reach?[]:path.slice(0,contact+1);if(!path.length&&dist(u,target)>blade.reach)return fail('No hay espacio para cargar.');let previous=u,cost=blade.ap;for(const p of path){const t=tile(s,p.x,p.y);if(!t||t.blocked||occupied(s,p.x,p.y,u.id))return fail('La carga está bloqueada.');if(p.x!==previous.x&&p.y!==previous.y&&(tile(s,p.x,previous.y)?.blocked||tile(s,previous.x,p.y)?.blocked))return fail('La carga no puede atravesar una esquina.');cost+=stepCost(u,t)*(p.x!==previous.x&&p.y!==previous.y?1.4:1);previous=p;}if(u.ap<Math.ceil(cost))return fail('Faltan puntos de acción para completar la carga.');for(const p of path){u.x=p.x;u.y=p.y;reactionFire(s,u);if(!alive(u)||s.status!=='active')break;}u.ap=0;if(!alive(u)){say(s,`${u.name} no logra completar la carga.`);return true;}damage(s,target,blade.damage*(1+path.length*.1)*(u.mounted?1.25:1),u);target.morale=Math.max(0,target.morale-15);holdMorale(s,target);if(target.hp>0&&target.morale<15){target.routed=true;say(s,`${target.name} huye ante la carga.`);}u.momentum=0;say(s,`${u.name} ejecuta una carga de ${path.length} casillas con ${blade.name}.`);}
else if(a.type==='artillery'||a.type==='artilleryReload'){const gun=s.artillery.find(g=>g.id===a.artilleryId),spec=ARTILLERY[gun?.type];if(!gun||!spec||gun.side!==u.side||dist(u,gun)>1.5)return fail('Debes estar junto a una pieza de artillería propia.');const cost=Math.ceil((a.type==='artillery'?spec.fireAP:spec.reloadAP)*(nearby(s,u,2,2)?.8:1));const crew=s.units.filter(v=>v.side===u.side&&alive(v)&&dist(v,gun)<=1.5&&v.ap>=cost);if(crew.length<spec.crew||u.ap<cost)return fail(`La pieza necesita ${spec.crew} artilleros próximos con ${cost} PA cada uno.`);if(a.type==='artilleryReload'){if(gun.loaded||gun.ammo<1)return fail('La pieza está cargada o no quedan municiones.');gun.loaded=true;gun.ammo--;say(s,`${u.name} dirige la recarga de ${spec.name}.`);}else{if(!gun.loaded)return fail('Primero hay que recargar la pieza.');const point=target||{x:a.x,y:a.y};if(!Number.isInteger(point.x)||!Number.isInteger(point.y)||!tile(s,point.x,point.y)||dist(gun,point)<1||dist(gun,point)>spec.range)return fail('Objetivo de artillería no válido.');gun.loaded=false;s.smoke.push({x:gun.x,y:gun.y,radius:2,turns:3});if(a.mode==='canister'){const len=dist(gun,point),dx=(point.x-gun.x)/len,dy=(point.y-gun.y)/len;for(const v of s.units.filter(alive)){const vx=v.x-gun.x,vy=v.y-gun.y,forward=vx*dx+vy*dy,across=Math.abs(vx*dy-vy*dx);if(forward>1&&forward<=spec.radius*2&&across<=Math.max(1,forward*.5)&&hasLineOfSight(s,gun,v))damage(s,v,spec.damage*Math.max(.35,1-forward/(spec.radius*3)),u);}say(s,`${spec.name} barre el frente con metralla.`);}else{const hit=tile(s,point.x,point.y);if(hit.blocked){hit.blocked=false;hit.type='rubble';hit.cover=20;say(s,'La bala de cañón abre una brecha en la posición.');}for(const v of s.units.filter(v=>alive(v)&&dist(v,point)<=1))damage(s,v,spec.damage,u);say(s,`${spec.name} dispara una bala rasa.`);}}const assigned=[u,...crew.filter(v=>v.id!==u.id)].slice(0,spec.crew);for(const v of assigned)v.ap-=cost;}
else if(a.type==='weapon'){if(!['primary','blade'].includes(a.slot))return fail('Selecciona arma principal o arma blanca.');if(a.slot==='blade'&&!BLADES[u.blade])return fail('No hay un arma blanca secundaria equipada.');if((u.activeSlot||'primary')===a.slot)return fail('Esa arma ya está en la mano.');if(!pay(4))return fail('Cambiar de arma requiere 4 PA.');u.activeSlot=a.slot;u.momentum=0;say(s,`${u.name} prepara ${weaponFor(u).name}.`);}
else if(a.type==='overwatch'){if(!hasFirearm(u)||!u.loaded||u.jammed)return fail('Necesitas un arma cargada y cebada para cubrir el frente.');u.overwatch=true;say(s,`${u.name} queda preparado para fuego de reacción.`);}
else if(a.type==='mount'){if(!u.horse)return fail('Este soldado no tiene una montura asignada.');if(!pay(12))return fail('Montar o desmontar requiere 12 PA.');u.mounted=!u.mounted;u.stance='standing';u.momentum=0;say(s,`${u.name} ${u.mounted?'monta a caballo':'desmonta'}.`);} 
else if(a.type==='heal'){const t=target||u;if(t.side!==u.side||!alive(t)||dist(u,t)>1.5)return fail('El herido debe estar a tu lado.');if(!u.medkits)return fail('No quedan vendas.');if(t.hp===t.maxHp&&!t.bleeding)return fail('El soldado no necesita atención.');if(!pay(25))return fail('Curar requiere 25 PA.');u.medkits--;t.bleeding=0;t.hp=Math.min(t.maxHp,t.hp+10+Math.round(u.medical*.25));say(s,`${u.name} atiende a ${t.name} y detiene la hemorragia.`);}
else if(a.type==='stance'){if(u.mounted)return fail('Debes desmontar antes de cambiar de postura.');if(!['standing','prone'].includes(a.stance)||u.stance===a.stance)return fail('Postura no válida.');if(!pay(6))return fail('Cambiar de postura requiere 6 PA.');u.stance=a.stance;u.momentum=0;say(s,`${u.name} ${a.stance==='prone'?'se tiende cuerpo a tierra':'se pone de pie'}.`);}
else return fail('Orden desconocida.');checkEnd(s);return true;}
export function actBattle(state,action){const s=clone(state);s.lastError=null;apply(s,action);return s;}
export function endTurn(state){const s=clone(state);s.lastError=null;if(s.status!=='active')return s;s.phase='enemy';for(const u of s.units.filter(u=>u.side==='enemy'&&alive(u))){u.maxAP=maxActionPoints(s,u);u.ap=Math.max(0,u.maxAP-u.reactionSpent);u.reactionSpent=0;for(let n=0;n<12&&u.ap>=6&&s.status==='active';n++){const targets=s.units.filter(t=>t.side==='player'&&alive(t)).sort((a,b)=>dist(u,a)-dist(u,b));const t=targets[0];if(!t)break;if(dist(u,t)<=bladeFor(u).reach&&hasLineOfSight(s,u,t)){if(!apply(s,{type:'melee',unitId:u.id,targetId:t.id},true))break;}else if(u.jammed){if(!apply(s,{type:'reprime',unitId:u.id},true))break;}else if(hasFirearm(u)&&!u.loaded&&u.ammo){if(!apply(s,{type:'reload',unitId:u.id},true))break;}else if(hasFirearm(u)&&u.loaded&&hasLineOfSight(s,u,t)&&shotChance(s,u,t)>=20){if(!apply(s,{type:'fire',unitId:u.id,targetId:t.id},true))break;}else{const candidates=getReachable(s,u).filter(p=>p.cost>0).sort((a,b)=>(dist(a,t)*10+a.cost*.1)-(dist(b,t)*10+b.cost*.1));if(!candidates.length)break;const p=candidates[0];if(dist(p,t)>=dist(u,t)||!apply(s,{type:'move',unitId:u.id,x:p.x,y:p.y},true))break;}}}
s.smoke=s.smoke.map(v=>({...v,radius:Math.min((v.radius||1)+.5,3),turns:v.turns-1})).filter(v=>v.turns>0);for(const u of s.units.filter(alive)){if(u.bleeding){u.hp=Math.max(0,u.hp-u.bleeding);say(s,`${u.name} pierde ${u.bleeding} de salud por hemorragia.`);}if(u.side==='player'){u.maxAP=maxActionPoints(s,u);u.ap=Math.max(0,u.maxAP-u.reactionSpent);u.reactionSpent=0;}u.momentum=0;u.lastDirection=null;}s.turn++;s.phase='player';checkEnd(s);if(s.status==='active')say(s,`Turno ${s.turn}: ¡órdenes, comandante!`);s.lastError=null;return s;}
