import {advanceBattleClock,COMBAT_ROUND_SECONDS,REST_SECONDS} from './time.js';
import {practice} from './skill-training.js';
// Deterministic, serializable tactical simulation. The browser uses this module directly.
export const WEAPONS = Object.fromEntries([
  [1800,'Brown Bess',58,12,6,45,18,1],[1801,'Charleville',52,11,5,42,22,1],
  [1802,'Fusil Baker',64,16,10,70,45,1],[1803,'Tercerola',44,9,4,38,12,1],
  [1804,'Escopeta Criolla',48,10,4,35,10,1],[1805,'Pistola de Arzón',42,7,3,32,8,1],
  [1806,'Pistola de Duelo de Oficial',38,6,2,28,12,1],[1807,'Trabuco Naranjero',75,12,5,40,6,1],
  [1808,'Pistola Doble Cañón',40,8,3,55,9,2],
].map(([id,name,damage,fireAP,aimAP,reloadAP,range,capacity])=>[id,{id,name,damage,fireAP,aimAP,reloadAP,range,capacity}]));
export const ARTILLERY={bronze4:{name:'Cañón de Bronce de 4 lb',crew:2,fireAP:30,reloadAP:60,radius:4,range:80,damage:85},field8:{name:'Cañón de Campaña de 8 lb',crew:3,fireAP:40,reloadAP:75,radius:6,range:110,damage:110},swivel:{name:'Pedrero de Regala',crew:1,fireAP:20,reloadAP:35,radius:3,range:35,damage:65}};
export const BLADES=Object.fromEntries([[1809,'Sable Corvo Sanmartiniano',12,46,1.5],[1810,'Sable de Caroya',14,42,1.5],[1811,'Bayoneta de Cubo',16,50,2],[1812,'Lanza de Tacuara',18,56,2.5],[1813,'Facón Gaucho con Poncho',8,32,1.5]].map(([id,name,ap,damage,reach])=>[id,{id,name,ap,damage,reach}]));
export function bladeFor(unit){return unit.activeSlot==='blade'?(BLADES[unit.blade]||BLADES[unit.weapon]||BLADES[1811]):(BLADES[unit.weapon]||BLADES[1811]);}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const present=u=>u.hp>0&&!u.routed;
const alive=u=>present(u)&&!u.unconscious;
const clone=s=>{const copy=structuredClone(s);for(const u of copy.units){u.activeSlot??='primary';u.reactionSpent??=0;u.reactionTurn??=0;u.interceptTurn??=0;u.fatigue??=0;u.priming??=50;u.flints??=4;u.rations??=2;u.parryTurn??=0;u.counterTurn??=0;u.braceTurn??=0;u.knockedDown??=false;u.braced??=false;u.energy??=100;u.unconscious??=u.energy<=0;u.movementMode??='walk';u.inventory??={};u.boleadoras??=1;u.torches??=2;u.strengthTraining??=0;}copy.artillery??=[];copy.mode??='combat';copy.groundItems??=[];copy.lights??=[];copy.buildings??=[];copy.revealedRooms??=[];copy.sectorCleared??=false;copy.droppedWeapons??=[];return copy;};
function random(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function say(s,text){s.log.push(text);s.log=s.log.slice(-80);}
export function hasFirearm(unit){if(unit.weaponDropped)return false;if(unit.activeSlot==='blade')return false;return typeof unit.weapon==='object'?unit.weapon.capacity>0:Boolean(WEAPONS[unit.weapon]);}
export function weaponFor(unit){if(unit.weaponDropped)return {id:0,name:'Arma abandonada',damage:0,fireAP:0,aimAP:0,reloadAP:0,capacity:0,range:0};if(unit.activeSlot==='blade')return {...bladeFor(unit),fireAP:0,aimAP:0,reloadAP:0,capacity:0,range:bladeFor(unit).reach};return typeof unit.weapon==='object'?unit.weapon:WEAPONS[unit.weapon]||{...bladeFor(unit),fireAP:0,aimAP:0,reloadAP:0,capacity:0,range:bladeFor(unit).reach};}
export function misfireChance(condition=100,rain=0,humidity=0){return clamp(Math.round(2+(100-clamp(condition,0,100))*.2+clamp(rain,0,100)*.5+clamp(humidity,0,100)),0,95);}
export function hasTrait(u,id){return Array.isArray(u.traits)&&u.traits.includes(id);}
function nearbyTrait(s,u,id,radius=4){return s.units.some(v=>v.side===u.side&&alive(v)&&hasTrait(v,id)&&dist(u,v)<=radius);}
export function actionCosts(s,u){const w=weaponFor(u),cavalry=u.mounted&&hasTrait(u,'cavalry_commander');return{heal:Number(u.id)===10?18:25,breach:Number(u.id)===6?25:45,mount:hasTrait(u,'cavalry_commander')?8:12,fire:Math.max(1,Math.ceil(w.fireAP*(cavalry?.8:1))-(Number(u.id)===4&&[1803,1805,1806,1808].includes(w.id)?2:0)),aim:Math.max(1,Math.ceil(w.aimAP*(hasTrait(u,'line_marksman')?.65:1))),reprime:hasTrait(u,'gunsmith_artillerist')?10:15,repair:hasTrait(u,'gunsmith_artillerist')?18:25,reload:reloadCost(u,s),melee:Math.ceil(bladeFor(u).ap*(cavalry?.8:1))};}
export function artilleryCosts(s,u,gun){const spec=ARTILLERY[gun.type],assist=(nearby(s,u,2,2)?.8:1)*(hasTrait(u,'gunsmith_artillerist')?.85:1),base={bronze4:{move:20,pivot:10},field8:{move:30,pivot:15},swivel:{move:10,pivot:5}}[gun.type];return{crew:spec.crew,fire:Math.ceil(spec.fireAP*assist*(Number(u.id)===5?.85:1)),reload:Math.ceil(spec.reloadAP*assist*(Number(u.id)===7?.8:1)),move:base.move,pivot:base.pivot};}
export function interruptInitiative(s,u){return (u.agility||0)+(u.wisdom||0)*.25+(nearby(s,u,11,4)?25:0)+(nearby(s,u,57,6)?50:0);}
export function ignitionRisk(s,u){const w=weaponFor(u);return clamp(misfireChance(u.condition,s.weather.rain,s.weather.humidity)*(w.id===1801?.9:1)*(hasTrait(u,'gunsmith_artillerist')?.65:1)-(w.id===1806?1:0)+(u.priming===0?15:0),0,95);}
function nearby(s,u,id,radius=4){return s?.units.some(v=>Number(v.id)===id&&v.side===u.side&&alive(v)&&dist(u,v)<=radius);}
export function maxActionPoints(s,u){const fatigue=clamp(u.fatigue||0,0,100),high=s.altitude>=2500||s.biome==='mountain',cold=high||s.weather.rain>0;return Math.round(clamp(100-fatigue*(hasTrait(u,'guerrilla_tactician')?.25:.4)-(high?15:0)-(cold&&!u.poncho?10:0),35,100));}
function holdMorale(s,u){if(nearby(s,u,57,6)||(u.militia&&nearby(s,u,1,4))||(u.mounted&&nearbyTrait(s,u,'cavalry_commander',4))||(!u.mounted&&nearby(s,u,7,4))){u.morale=Math.max(20,u.morale);u.routed=false;return true;}return false;}
export function reloadCost(unit,state){const w=weaponFor(unit),rounds=Math.min(w.capacity-unit.loaded,unit.ammo);return rounds<=0?0:Math.ceil(Math.ceil(w.reloadAP*rounds/w.capacity)*(unit.stance==='prone'?1.5:1)*(state&&nearby(state,unit,2,2)?.8:1)*(hasTrait(unit,'gunsmith_artillerist')?.85:1));}
function makeUnit(raw,side,index,x,y){const stats=raw.stats||{};const weapon=raw.weapon??raw.primary??1800;const w=typeof weapon==='object'?weapon:WEAPONS[weapon]||WEAPONS[1800];return {...raw,id:String(raw.id??`${side}-${index}`),name:raw.name||raw.nickname||(side==='player'?'Granadero':'Realista'),side,x:raw.x??x,y:raw.y??y,maxHp:raw.maxHp??raw.health??stats.health??100,hp:raw.hp??raw.health??stats.health??100,ap:100,morale:raw.morale??Math.min(100,(raw.personality==='optimistic'?90:raw.personality==='pessimistic'?70:80)+((raw.traits||[]).includes('steadfast')?10:0)),marksmanship:raw.marksmanship??stats.marksmanship??70,agility:raw.agility??stats.agility??75,strength:raw.strength??stats.strength??75,medical:raw.medical??stats.medical??30,mechanical:raw.mechanical??stats.mechanical??0,stealth:raw.stealth??stats.stealth??0,weapon,loaded:raw.loaded??(WEAPONS[weapon]||typeof weapon==='object'?w.capacity:0),ammo:raw.ammo??12,condition:raw.condition??100,stance:'standing',mounted:Boolean(raw.mounted),horse:Boolean(raw.horse||raw.canMount||raw.mounted),jammed:false,bleeding:0,routed:false,medkits:raw.medkits??2,momentum:0,lastDirection:null,activeSlot:raw.activeSlot||'primary',fatigue:raw.fatigue||0,priming:raw.priming??50,flints:raw.flints??4,rations:raw.rations??2,energy:raw.energy??100,unconscious:(raw.energy??100)<=0,movementMode:raw.movementMode||'walk',inventory:{...raw.inventory},boleadoras:raw.boleadoras??1,torches:raw.torches??2,strengthTraining:raw.strengthTraining??0,interceptTurn:0,parryTurn:0,counterTurn:0,braceTurn:0,braced:false,knockedDown:false,overwatch:side==='enemy',reactionTurn:0,reactionSpent:0};}
export function createBattle(squad=[],sector={}){const width=sector.width||16,height=sector.height||12;const state={version:1,battleId:sector.id??null,startSeconds:(sector.hour??(sector.night||sector.weather?.night?0:12))*3600+(sector.secondOfHour??0),elapsedSeconds:0,syncedSeconds:0,roundTimeCharged:false,sectorId:sector.sector||sector.id||'san-lorenzo',sectorName:sector.name||'San Lorenzo',width,height,biome:sector.biome||'grassland',altitude:sector.altitude||0,night:Boolean(sector.night||sector.weather?.night||(sector.hour!==undefined&&(sector.hour%24>=20||sector.hour%24<6))),enemyCommand:sector.enemyCommand||null,objective:sector.objective||null,npcs:sector.npcs||[],props:structuredClone(sector.props??[]),buildings:sector.buildings||[],revealedRooms:[],decor:sector.decor||[],turn:1,phase:'player',mode:sector.exploration?'exploration':'combat',sectorCleared:false,status:'active',seed:(sector.seed??18130203)>>>0,weather:{rain:0,humidity:0,...sector.weather},tiles:[],units:[],droppedWeapons:[],groundItems:[],lights:(sector.lights||[]).map((l,i)=>({id:`light-${i}`,type:'campfire',radius:4,intensity:1,...l})),artillery:(sector.artillery||[]).map((g,i)=>({id:`gun-${i}`,type:'bronze4',side:'player',loaded:true,ammo:6,...g})),smoke:[],log:[],lastError:null};
state.weather.rain=typeof state.weather.rain==='boolean'?(state.weather.rain?40:0):state.weather.rain;state.weather.humidity=state.weather.humidity>0&&state.weather.humidity<=1?state.weather.humidity*10:state.weather.humidity;
for(let y=0;y<height;y++)for(let x=0;x<width;x++){const edge=x===Math.floor(width*.56)&&y>1&&y<height-2&&y!==Math.floor(height/2);state.tiles.push({x,y,type:edge?'wall':sector.biome==='wetland'&&x>3&&x<width-3&&y%3===0?'mud':sector.biome==='mountain'||sector.biome==='foothills'?'stone':'grass',blocked:edge,cover:edge?40:sector.biome==='forest'&&x>3&&x<width-3&&y%3===0?20:0});}
if(Array.isArray(sector.tiles))state.tiles=sector.tiles.map(t=>({blocked:false,cover:0,...t}));
state.units=squad.map((u,i)=>makeUnit(u,'player',i,1+Math.floor(i/(height-2)),1+i%(height-2)));
const enemies=Array.isArray(sector.enemies)?sector.enemies:Array.from({length:sector.exploration?0:sector.enemyCount||Math.max(3,squad.length+(sector.difficulty||1)-1)},(_,i)=>({id:`enemy-${i}`,name:`Realista ${i+1}`,weapon:i%3===0?1801:1800,marksmanship:50+(sector.difficulty||1)*5,morale:60+(sector.difficulty||1)*5}));
state.units.push(...enemies.map((u,i)=>makeUnit(u,'enemy',i,width-2-Math.floor(i/(height-2)),1+i%(height-2))));
if(!state.artillery.length&&sector.cannons>0)state.artillery=Array.from({length:Math.min(sector.cannons,3)},(_,i)=>({id:`gun-${i}`,type:'bronze4',side:'player',x:2,y:2+i*3,loaded:true,ammo:6}));
for(const u of state.units){u.maxAP=maxActionPoints(state,u);u.ap=u.maxAP;}
say(state,`Combate en ${state.sectorName}. Cada soldado dispone de 100 puntos de acción.`);checkEnd(state);detectContact(state);revealRooms(state);return state;}
function tile(s,x,y){return s.tiles.find(t=>t.x===x&&t.y===y);}
function occupied(s,x,y,except){return (s.npcs||[]).some(n=>n.x===x&&n.y===y)||s.units.some(u=>alive(u)&&u.id!==except&&u.x===x&&u.y===y);}
export function carryCapacity(u){return Math.max(10,(u.strength||50)*.5);}
export function carriedWeight(u){const inventory=Object.values(u.inventory||{}).reduce((sum,item)=>sum+(typeof item==='object'?(item.count||0)*(item.weight||0):0),0);return Number(u.weight??u.carryWeight??0)+inventory+((u.loaded||0)+(u.ammo||0))*.04+(u.weaponDropped?0:(hasFirearm(u)?4:1.3));}
function weightPenalty(u){return Math.max(1,carriedWeight(u)/carryCapacity(u));}
export function movementEnergy(u,t){const style=u.movementMode||'walk',base={walk:1,run:3,crouch:2,prone:3}[style]||1;return Math.max(1,Math.ceil(base*weightPenalty(u)*(u.mounted?1-Math.min(100,u.ridingSkill||0)*.005:1)*(t?.type==='mud'?1.5:1)*(hasTrait(u,'guerrilla_tactician')?.75:1)));}
function exhaust(s,u,cost){if(u.mounted&&u.mount){u.mount.stamina=Math.max(0,u.mount.stamina-Math.max(1,Math.ceil(cost*(1-Math.min(100,u.ridingSkill||0)*.005))));if(u.mount.stamina===0){u.mounted=false;say(s,`${u.name} desmonta: su caballo está agotado.`);}}u.energy=Math.max(0,(u.energy??100)-cost);if(u.energy===0){u.unconscious=true;u.ap=0;u.mounted=false;say(s,`${u.name} cae inconsciente por agotamiento.`);}}
export function tileIllumination(s,x,y){if(!s.night)return 1;let light=.08;for(const lamp of s.lights||[]){if(lamp.turns===0||lamp.extinguished)continue;const distance=dist(lamp,{x,y});if(distance>lamp.radius||!hasLineOfSight(s,lamp,{x,y}))continue;light=Math.max(light,(lamp.intensity??1)*(1-distance/(lamp.radius+1)));}return clamp(light,0,1);}
export function canSee(s,u,target){if(!alive(u)||!hasLineOfSight(s,u,target))return false;const bonus=hasTrait(u,'night_vision')||Number(u.id)===6?2:hasTrait(u,'night_vision_basic')?1:0;const concealment=['crouch','prone'].includes(target.movementMode)&&!target.mounted?Math.min(1,(target.trainedStats?.stealth||0)*.1):0;const range=(s.night?6+bonus:12)-concealment;const distance=dist(u,target);if(distance>range&&!(distance<=16&&tileIllumination(s,target.x,target.y)>=.25))return false;const smoke=line(u,target).filter(p=>s.smoke.some(v=>dist(p,v)<=v.radius)).length;return smoke<5;}
export function teamCanSee(s,side,target){return s.units.some(u=>u.side===side&&alive(u)&&canSee(s,u,target));}
export function visibleRooms(s){const ids=new Set();for(const t of s.tiles){if(t.roomId&&s.units.some(u=>u.side==='player'&&alive(u)&&canSee(s,u,t)))ids.add(t.roomId);}return [...ids];}
function revealRooms(s){s.revealedRooms=[...new Set([...(s.revealedRooms||[]),...visibleRooms(s)])];}
export function visibleTiles(s,u){return s.tiles.filter(t=>canSee(s,u,t)).map(t=>({x:t.x,y:t.y,illumination:tileIllumination(s,t.x,t.y)}));}
export function visibleHostiles(s,u){return s.units.filter(v=>v.side!==u.side&&present(v)&&canSee(s,u,v));}
export function visibleEnemies(s){return s.units.filter(v=>v.side==='enemy'&&s.units.some(u=>u.side==='player'&&alive(u)&&visibleHostiles(s,u).some(t=>t.id===v.id)));}
function detectContact(s){if(s.mode!=='exploration')return false;if(s.units.some(u=>u.side==='player'&&alive(u)&&visibleHostiles(s,u).length)){s.mode='combat';s.phase='player';for(const u of s.units.filter(alive)){u.maxAP=maxActionPoints(s,u);u.ap=u.maxAP;}say(s,'¡Contacto visual con el enemigo! Comienza el combate por turnos.');return true;}return false;}
function stepCost(u,t){const rough=['mud','forest','stone','scrub'].includes(t?.type),base=(u.mounted?(hasTrait(u,'cavalry_commander')?3:4):u.stance==='prone'?16:Number(u.id)===4?6:8)*(t?.type==='mud'?(u.mounted?(Number(u.id)===0?1.25:2):1.5):1);return Math.max(2,Math.ceil(base*(u.mounted?1-Math.min(100,u.ridingSkill||0)*.005:1)*(u.movementMode==='run'?.7:u.movementMode==='crouch'?1.25:1)*weightPenalty(u)*(rough&&hasTrait(u,'guerrilla_tactician')?.75:1)));}
export function getReachable(s,unitOrId){const u=typeof unitOrId==='object'?unitOrId:s.units.find(u=>u.id===String(unitOrId));if(!u||!alive(u)||s.status!=='active')return [];const costs=new Map([[`${u.x},${u.y}`,0]]),paths=new Map([[`${u.x},${u.y}`,[]]]),queue=[{x:u.x,y:u.y,cost:0}];while(queue.length){queue.sort((a,b)=>a.cost-b.cost);const p=queue.shift();for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,y=p.y+dy,t=tile(s,x,y);if(!t||t.blocked||occupied(s,x,y,u.id))continue;const key=`${x},${y}`,cost=p.cost+stepCost(u,t);if(cost>(s.mode==='exploration'?Infinity:u.ap)||cost>=(costs.get(key)??Infinity))continue;costs.set(key,cost);paths.set(key,[...paths.get(`${p.x},${p.y}`),{x,y}]);queue.push({x,y,cost});}}return [...costs].map(([key,cost])=>{const[x,y]=key.split(',').map(Number);return{x,y,cost,path:paths.get(key)};});}
function line(a,b){const points=[];let x=a.x,y=a.y;const dx=Math.abs(b.x-x),dy=Math.abs(b.y-y),sx=x<b.x?1:-1,sy=y<b.y?1:-1;let err=dx-dy;while(x!==b.x||y!==b.y){const e=2*err;if(e>-dy){err-=dy;x+=sx;}if(e<dx){err+=dx;y+=sy;}points.push({x,y});}return points;}
export function hasLineOfSight(s,a,b){return !line(a,b).slice(0,-1).some(p=>(tile(s,p.x,p.y)?.blocksSight??(tile(s,p.x,p.y)?.type==='window'?false:tile(s,p.x,p.y)?.blocked)));}
export function shotChance(s,attacker,target,aim=0){if(!hasLineOfSight(s,attacker,target))return 0;const w=weaponFor(attacker),range=dist(attacker,target);let cap=w.id===1802?(range<=45?95:Math.max(1,85-(range-50)*5)):(range<=15?85:range<=25?85-(range-15)*5:range<=35?35-(range-25)*3:Math.max(1,5-(range-35)));const obscured=line(attacker,target).filter(p=>s.smoke.some(v=>dist(p,v)<=v.radius)).length;return Math.round(clamp(Math.min(cap,attacker.marksmanship+(nearby(s,attacker,57,6)?12:0)+(nearby(s,attacker,11,4)?8:0)+clamp(aim,0,4)*8-range*1.1-(attacker.maxHp-attacker.hp)*.3-(target.stance==='prone'?18:0)-(tile(s,target.x,target.y)?.cover||0)*(Number(attacker.id)===6&&w.id===1807?.5:1)-(s.night?(Number(attacker.id)===6?5:20)*(1-tileIllumination(s,target.x,target.y)):0)-Math.max(0,range-w.range)*4-(attacker.mounted&&![1803,1805,1806,1808].includes(w.id)?15:0)-obscured*(hasTrait(attacker,'line_marksman')?6:12)+(hasTrait(attacker,'guerrilla_tactician')&&!attacker.momentum&&((tile(s,attacker.x,attacker.y)?.cover||0)>=20||['forest','scrub'].includes(tile(s,attacker.x,attacker.y)?.type))?10:0)-(hasTrait(target,'guerrilla_tactician')&&!target.mounted&&((tile(s,target.x,target.y)?.cover||0)>=20||['forest','scrub'].includes(tile(s,target.x,target.y)?.type))?12:0)),1,95));}
function checkEnd(s){if(!s.units.some(u=>u.side==='player'&&present(u))){s.status='defeat';say(s,'La escuadra quedó fuera de combate.');}else if(!s.units.some(u=>u.side==='enemy'&&present(u))){s.sectorCleared=true;if(s.mode==='exploration')return;s.status='victory';say(s,'¡Victoria! El enemigo abandonó el campo.');}}
function rout(s,u){if(u.routed||u.hp<=0||holdMorale(s,u))return;u.routed=true;u.weaponDropped=true;u.droppedWeapon=typeof u.weapon==='object'?u.weapon.id:u.weapon;s.droppedWeapons??=[];s.droppedWeapons.push({unitId:u.id,x:u.x,y:u.y,weapon:u.droppedWeapon,loaded:u.loaded,condition:u.condition});u.loaded=0;u.ap=0;u.braced=false;const goal=u.side==='player'?0:s.width-1,queue=[{x:u.x,y:u.y,path:[]}],seen=new Set([`${u.x},${u.y}`]);let escape=null;while(queue.length){const p=queue.shift();if(p.x===goal){escape=p;break;}for(const[dx,dy]of[[Math.sign(goal-u.x)||1,0],[0,1],[0,-1],[-(Math.sign(goal-u.x)||1),0]]){const x=p.x+dx,y=p.y+dy,key=`${x},${y}`,t=tile(s,x,y);if(!t||t.blocked||seen.has(key)||occupied(s,x,y,u.id))continue;seen.add(key);queue.push({x,y,path:[...p.path,{x,y}]});}}u.fleePath=escape?.path||[];u.fled=Boolean(escape);if(escape){u.x=escape.x;u.y=escape.y;}say(s,`${u.name} abandona el arma y ${escape?'huye hacia la retaguardia':'se rinde sin encontrar una salida'}.`);}
function meleeStrike(s,attacker,target,amount,{counter=true}={}){const blade=bladeFor(attacker),defense=bladeFor(target);if([1809,1810].includes(defense.id)&&target.ap>=6&&target.parryTurn!==s.turn){target.parryTurn=s.turn;target.ap-=6;amount*=.75;say(s,`${target.name} desvía parte del golpe con su sable.`);}if(defense.id===1813||target.poncho)amount*=.8;damage(s,target,amount,attacker);if(alive(target)){if([1809,1810].includes(blade.id))target.bleeding=Math.min(10,target.bleeding+3);if(blade.id===1812){target.knockedDown=true;target.stance='prone';target.mounted=false;target.ap=Math.max(0,target.ap-20);say(s,`${target.name} cae derribado por la lanza.`);}if(counter&&(defense.id===1813||Number(target.id)===3)&&target.counterTurn!==s.turn&&target.ap>=defense.ap&&dist(target,attacker)<=defense.reach&&alive(attacker)){target.counterTurn=s.turn;target.ap-=defense.ap;say(s,`${target.name} responde con un contragolpe.`);damage(s,attacker,defense.damage*.5,target);}}}
function interceptCharge(s,mover,target){if(!alive(target)||!target.braced||target.braceTurn===s.turn||bladeFor(target).id!==1811||target.ap<16||dist(mover,target)>2||!hasLineOfSight(s,target,mover))return;target.braceTurn=s.turn;target.ap-=16;say(s,`${target.name} recibe la carga con la bayoneta calada.`);damage(s,mover,50,target);}
function damage(s,target,amount,source,projectile=false){if(projectile&&(Number(target.id)===57||(target.leadership||0)>=90)){const guard=s.units.find(v=>Number(v.id)===3&&v.side===target.side&&v.id!==target.id&&alive(v)&&v.hp>25&&v.ap>=8&&v.interceptTurn!==s.turn&&dist(v,target)<=1.5);if(guard){guard.ap-=8;guard.interceptTurn=s.turn;say(s,`${guard.name} se interpone para proteger a ${target.name}.`);target=guard;}}target.hp=Math.max(0,target.hp-Math.round(amount));target.bleeding=target.hp>0?Math.min(10,target.bleeding+Math.ceil(amount/15)):0;target.morale=Math.max(0,target.morale-amount*.45);say(s,`${source.name} hiere a ${target.name}: ${Math.round(amount)} de daño.`);if(target.hp===0){say(s,`${target.name} cayó en combate.`);for(const u of s.units.filter(u=>u.side===target.side&&alive(u)))u.morale=Math.max(0,u.morale-18);}holdMorale(s,target);if(target.hp>0&&target.morale<15){rout(s,target);}}
function reactionFire(s,mover){
for(const defender of s.units.filter(u=>u.side!==mover.side&&alive(u)&&u.overwatch&&u.reactionTurn!==s.turn&&hasFirearm(u)&&u.loaded>0&&!u.jammed).sort((a,b)=>interruptInitiative(s,b)-interruptInitiative(s,a))){
if(!alive(mover)||s.status!=='active')break;
if(!canSee(s,defender,mover)||dist(defender,mover)>(nearby(s,defender,57,6)?12:nearby(s,defender,11,4)?10:8)||!hasLineOfSight(s,defender,mover)||shotChance(s,defender,mover)<25||defender.ap<actionCosts(s,defender).fire)continue;
defender.reactionTurn=s.turn;const before=defender.ap;say(s,`${defender.name} interrumpe el avance con fuego de reacción.`);
apply(s,{type:'fire',unitId:defender.id,targetId:mover.id},defender.side==='enemy');defender.reactionSpent+=before-defender.ap;
}}
function apply(s,a,enemy=false){const fail=text=>{s.lastError=text;say(s,text);return false;};const u=s.units.find(u=>u.id===String(a.unitId));if(s.status!=='active')return fail('El combate ya terminó.');if(!u||!alive(u))return fail('El soldado no puede actuar.');if(u.side!==(enemy?'enemy':'player'))return fail('No puedes dar órdenes a ese soldado.');if(u.knockedDown&&!['stance','heal','ration'].includes(a.type))return fail('El soldado está derribado: debe ponerse de pie.');const target=s.units.find(u=>u.id===String(a.targetId));const pay=n=>{if(s.mode==='exploration'){s.actionDurationSeconds=Math.max(1,Math.ceil(n*.06));return true;}if(u.ap<n)return false;u.ap-=n;return true;};
if(a.type==='move'){if(a.movement&&['walk','run','crouch','prone'].includes(a.movement)){u.movementMode=a.movement;u.stance=a.movement==='prone'?'prone':'standing';}if(u.entangled)return fail('Las boleadoras inmovilizan al soldado: debe liberarse.');const path=getReachable(s,u).find(p=>p.x===a.x&&p.y===a.y);if(!path||path.cost===0)return fail('Destino inaccesible o puntos de acción insuficientes.');pay(path.cost);u.braced=false;u.fatigue=clamp((u.fatigue||0)+Math.ceil(path.cost/25*(hasTrait(u,'guerrilla_tactician')?.5:1)),0,100);s.actionDurationSeconds=0;for(const p of path.path){s.actionDurationSeconds+=u.movementMode==='run'?1:u.movementMode==='prone'?5:3;const dir=`${p.x-u.x},${p.y-u.y}`;u.momentum=dir===u.lastDirection?u.momentum+1:1;u.lastDirection=dir;u.x=p.x;u.y=p.y;if(u.mounted&&u.mount&&u.mount.stamina>0){u.ridingPracticeTiles??=[];const key=`${u.x},${u.y}`;if(!u.ridingPracticeTiles.includes(key)){u.ridingPracticeTiles.push(key);practice(u,'ridingSkill');}}exhaust(s,u,movementEnergy(u,tile(s,p.x,p.y)));if(['crouch','prone'].includes(u.movementMode)&&!u.mounted&&s.units.some(v=>v.side!==u.side&&alive(v)&&dist(v,u)<=12)&&!s.units.some(v=>v.side!==u.side&&alive(v)&&canSee(s,v,u))){u.practiceTiles??=[];const key=`${u.x},${u.y}`;if(!u.practiceTiles.includes(key)){u.practiceTiles.push(key);practice(u,'agility');practice(u,'stealth');}}if(carriedWeight(u)>carryCapacity(u)){u.strengthTraining++;if(u.strengthTraining>=30){u.strength=Math.min(100,u.strength+1);u.strengthTraining=0;}}if(!alive(u)||detectContact(s))break;if(s.mode==='combat')reactionFire(s,u);if(!alive(u)||s.status!=='active')break;}say(s,`${u.name} avanza (${path.cost} PA).`);}
else if(a.type==='fire'){if(!target||target.side===u.side||!alive(target))return fail('Selecciona un enemigo activo.');if(!hasFirearm(u))return fail('Este soldado lleva un arma blanca: acércate para atacar.');if(!teamCanSee(s,u.side,target))return fail('Ningún compañero puede ver ese objetivo.');if(u.jammed)return fail('La cazoleta falló: vuelve a cebar el arma.');if(u.loaded<1)return fail('El arma está descargada.');if(!hasLineOfSight(s,u,target))return fail('No hay línea de tiro.');const aim=clamp(Math.floor(a.aim||0),0,4),w=weaponFor(u),chance=shotChance(s,u,target,aim);if(!pay(actionCosts(s,u).fire+aim*actionCosts(s,u).aim))return fail('Faltan puntos de acción para disparar.');u.momentum=0;const risk=ignitionRisk(s,u);if(random(s)*100<risk){u.jammed=true;say(s,`${u.name}: fallo de chispa. La carga se conserva; cebar cuesta ${actionCosts(s,u).reprime} PA.`);}else{u.loaded--;practice(u,'marksmanship',2);u.condition=Math.max(0,u.condition-1);s.smoke.push({x:u.x,y:u.y,radius:1,turns:3});if(w.id===1807){const length=dist(u,target),dx=(target.x-u.x)/length,dy=(target.y-u.y)/length;for(const victim of s.units.filter(v=>alive(v)&&v.id!==u.id)){const vx=victim.x-u.x,vy=victim.y-u.y,forward=vx*dx+vy*dy,across=Math.abs(vx*dy-vy*dx);if(forward<=0||forward>6||across>Math.max(.5,forward*.25)||!hasLineOfSight(s,u,victim))continue;victim.morale=Math.max(0,victim.morale-18);if(random(s)*100<Math.min(95,shotChance(s,u,victim,aim)+20))damage(s,victim,w.damage*(1-forward/12),u,true);else if(victim.morale<15)rout(s,victim);}say(s,`${u.name} descarga el trabuco: una nube de metralla barre tres casillas de ancho.`);}else if(random(s)*100<chance)damage(s,target,w.damage*(.8+random(s)*.4),u,true);else{target.morale=Math.max(0,target.morale-4);say(s,`${u.name} dispara y falla (${chance}%).`);} }}
else if(a.type==='reload'){if(!hasFirearm(u))return fail('Las armas blancas no necesitan recarga.');if(u.jammed)return fail('Primero debes volver a cebar el arma.');const cost=reloadCost(u,s);if(!cost)return fail('No falta carga o no quedan cartuchos.');if(!pay(cost))return fail('Faltan puntos de acción para recargar.');const n=Math.min(weaponFor(u).capacity-u.loaded,u.ammo);u.loaded+=n;u.ammo-=n;u.priming=Math.max(0,u.priming-n);u.momentum=0;say(s,`${u.name} recarga (${cost} PA).`);}
else if(a.type==='reprime'){if(!u.jammed)return fail('El arma no necesita cebado.');if(u.priming<1)return fail('El frasco de pólvora de cebar está vacío.');const cost=actionCosts(s,u).reprime;if(!pay(cost))return fail(`Cebar requiere ${cost} PA.`);u.priming--;practice(u,'mechanical');u.jammed=false;say(s,`${u.name} vuelve a cebar la cazoleta.`);}
else if(a.type==='melee'){const blade=bladeFor(u);if(!target||!alive(target)||target.side===u.side||dist(u,target)>blade.reach||!hasLineOfSight(s,u,target))return fail('Debes acercarte al enemigo para atacar con arma blanca.');const meleeCost=actionCosts(s,u).melee;if(!pay(meleeCost))return fail(`El ataque requiere ${meleeCost} PA.`);const direction=`${Math.sign(target.x-u.x)},${Math.sign(target.y-u.y)}`;const bonus=1+(direction===u.lastDirection?Math.min(u.momentum,5)*.1:0);meleeStrike(s,u,target,blade.damage*bonus);u.momentum=0;}
else if(a.type==='charge'){const blade=bladeFor(u);if(!target||!alive(target)||target.side===u.side)return fail('Selecciona un enemigo para cargar.');const dx=target.x-u.x,dy=target.y-u.y;if(dx!==0&&dy!==0&&Math.abs(dx)!==Math.abs(dy))return fail('La carga exige una línea recta.');let path=line(u,target);const contact=path.findIndex(p=>dist(p,target)<=blade.reach);path=dist(u,target)<=blade.reach?[]:path.slice(0,contact+1);if(!path.length&&dist(u,target)>blade.reach)return fail('No hay espacio para cargar.');let previous=u,cost=actionCosts(s,u).melee;for(const p of path){const t=tile(s,p.x,p.y);if(!t||t.blocked||occupied(s,p.x,p.y,u.id))return fail('La carga está bloqueada.');if(p.x!==previous.x&&p.y!==previous.y&&(tile(s,p.x,previous.y)?.blocked||tile(s,previous.x,p.y)?.blocked))return fail('La carga no puede atravesar una esquina.');cost+=stepCost(u,t)*(p.x!==previous.x&&p.y!==previous.y?1.4:1);previous=p;}if(u.ap<Math.ceil(cost))return fail('Faltan puntos de acción para completar la carga.');for(const p of path){u.x=p.x;u.y=p.y;exhaust(s,u,movementEnergy({...u,movementMode:'run'},tile(s,p.x,p.y)));if(!alive(u))break;reactionFire(s,u);interceptCharge(s,u,target);if(!alive(u)||s.status!=='active')break;}u.fatigue=clamp((u.fatigue||0)+Math.ceil(cost/20*(hasTrait(u,'guerrilla_tactician')?.5:1)),0,100);u.ap=0;if(!alive(u)){say(s,`${u.name} no logra completar la carga.`);checkEnd(s);return true;}meleeStrike(s,u,target,blade.damage*(1+path.length*.1)*(u.mounted?1.25:1)*(Number(u.id)===57&&u.mounted?1.2:1));if(Number(u.id)===9&&u.mounted){for(const levy of s.units.filter(v=>v.side!==u.side&&alive(v)&&dist(v,u)<=4&&(v.militia||v.levy||v.marksmanship<60))){levy.morale=Math.max(0,levy.morale-25);if(levy.morale<15)rout(s,levy);}say(s,`${u.name} aterroriza a las levas con su carga montada.`);}target.morale=Math.max(0,target.morale-15);holdMorale(s,target);if(target.hp>0&&target.morale<15){rout(s,target);}u.momentum=0;say(s,`${u.name} ejecuta una carga de ${path.length} casillas con ${blade.name}.`);}
else if(['artillery','artilleryReload','artilleryMove','artilleryPivot'].includes(a.type)){
const gun=s.artillery.find(g=>g.id===a.artilleryId),spec=ARTILLERY[gun?.type];
if(!gun||!spec||gun.side!==u.side||dist(u,gun)>1.5)return fail('Debes estar junto a una pieza de artillería propia.');
const costs=artilleryCosts(s,u,gun),cost=costs[{artillery:'fire',artilleryReload:'reload',artilleryMove:'move',artilleryPivot:'pivot'}[a.type]];
const crew=s.units.filter(v=>v.side===u.side&&alive(v)&&!v.knockedDown&&!v.mounted&&dist(v,gun)<=1.5&&v.ap>=cost);
if(crew.length<spec.crew||!crew.includes(u))return fail(`La pieza necesita ${spec.crew} artilleros a pie, próximos y con ${cost} PA cada uno.`);
const assigned=[u,...crew.filter(v=>v.id!==u.id)].slice(0,spec.crew);
if(a.type==='artilleryMove'){
const dx=a.x-gun.x,dy=a.y-gun.y;if(!Number.isInteger(a.x)||!Number.isInteger(a.y)||Math.abs(dx)+Math.abs(dy)!==1)return fail('La pieza se arrastra una casilla horizontal o vertical por orden.');
const positions=[{x:a.x,y:a.y},...assigned.map(v=>({x:v.x+dx,y:v.y+dy}))],ids=new Set(assigned.map(v=>v.id));
if(positions.some(p=>!tile(s,p.x,p.y)||tile(s,p.x,p.y).blocked||tile(s,p.x,p.y).type==='water'||s.units.some(v=>alive(v)&&!ids.has(v.id)&&v.x===p.x&&v.y===p.y)||s.artillery.some(g=>g!==gun&&g.x===p.x&&g.y===p.y)))return fail('La pieza y su dotación no caben en ese terreno.');
gun.x=a.x;gun.y=a.y;for(const v of assigned){v.x+=dx;v.y+=dy;}say(s,`${u.name} dirige el arrastre de ${spec.name}.`);
}else if(a.type==='artilleryPivot'){
if(!Number.isInteger(a.x)||!Number.isInteger(a.y)||!tile(s,a.x,a.y)||dist(gun,a)<1)return fail('Indica una casilla hacia la cual orientar la pieza.');gun.facing=Math.atan2(a.y-gun.y,a.x-gun.x);say(s,`${spec.name} gira hacia la nueva línea de tiro.`);
}else if(a.type==='artilleryReload'){
if(gun.loaded||gun.ammo<1)return fail('La pieza está cargada o no quedan municiones.');gun.loaded=true;gun.ammo--;say(s,`${u.name} dirige la recarga de ${spec.name}.`);
}else{
if(!gun.loaded)return fail('Primero hay que recargar la pieza.');const point=target||{x:a.x,y:a.y};
if(!Number.isInteger(point.x)||!Number.isInteger(point.y)||!tile(s,point.x,point.y)||dist(gun,point)<1||dist(gun,point)>spec.range)return fail(`Objetivo fuera del alcance de ${spec.range} casillas o no válido.`);
const facing=Math.atan2(point.y-gun.y,point.x-gun.x);if(Number.isFinite(gun.facing)&&Math.abs(Math.atan2(Math.sin(facing-gun.facing),Math.cos(facing-gun.facing)))>Math.PI/4)return fail('Gira la pieza antes de disparar fuera de su arco frontal.');
gun.facing=facing;gun.loaded=false;s.smoke.push({x:gun.x,y:gun.y,radius:2,turns:3});
if(a.mode==='canister'){
const len=dist(gun,point),dx=(point.x-gun.x)/len,dy=(point.y-gun.y)/len;
for(const v of s.units.filter(alive)){const vx=v.x-gun.x,vy=v.y-gun.y,forward=vx*dx+vy*dy,across=Math.abs(vx*dy-vy*dx);if(forward>1&&forward<=spec.radius*2&&across<=Math.max(1,forward*.5)&&hasLineOfSight(s,gun,v)){damage(s,v,spec.damage*Math.max(.35,1-forward/(spec.radius*3))*(Number(u.id)===5?1.15:1),u);if(alive(v)){v.morale=Math.max(0,v.morale-12);if(v.morale<15)rout(s,v);}}}
say(s,`${spec.name} barre el frente con metralla.`);
}else{
let energy=spec.damage,penetration=({bronze4:3,field8:5,swivel:1}[gun.type])+(Number(u.id)===7?1:0);
for(const p of line(gun,point)){
const ground=tile(s,p.x,p.y);if(ground?.blocked){if(ground.type==='water'||ground.type==='cliff'){break;}const stone=ground.material==='stone'||ground.type==='stone';const resistance=stone?3:1;if(penetration<resistance){say(s,'La bala se detiene contra la fortificación.');break;}penetration-=resistance;ground.blocked=false;ground.blocksSight=false;ground.type='rubble';ground.cover=20;say(s,`La bala abre una brecha en ${stone?'la piedra':'el adobe'}.`);}
for(const victim of s.units.filter(v=>alive(v)&&v.x===p.x&&v.y===p.y)){damage(s,victim,energy,u);energy*=.75;penetration--;}
if(penetration<0||energy<20)break;
}
say(s,`${spec.name} dispara una bala rasa que atraviesa su línea de tiro.`);
}}
for(const v of assigned)v.ap-=cost;
}
else if(a.type==='door'){const door=a.doorId?s.tiles.find(t=>t.doorId===a.doorId):tile(s,a.x,a.y);if(!door||door.type!=='door'||dist(u,door)>1.5)return fail('Acércate a la hoja de puerta que quieres accionar.');if(door.locked)return fail('La puerta está cerrada con llave.');if(!pay(4))return fail('Accionar la puerta requiere 4 PA.');door.open=typeof a.open==='boolean'?a.open:!door.open;door.blocked=!door.open;door.blocksSight=!door.open;say(s,`${u.name} ${door.open?'abre':'cierra'} la puerta.`);}
else if(a.type==='throwTorch'){const point={x:a.x,y:a.y};if(!Number.isInteger(a.x)||!Number.isInteger(a.y)||!tile(s,a.x,a.y)||tile(s,a.x,a.y).blocked||dist(u,point)>8||!hasLineOfSight(s,u,point))return fail('La antorcha debe caer en terreno accesible a ocho casillas o menos.');if(!u.torches)return fail('No quedan antorchas.');if(!pay(10))return fail('Lanzar la antorcha requiere 10 PA.');u.torches--;s.lights.push({id:`torch-${u.id}-${s.turn}-${s.lights.length}`,type:'torch',x:a.x,y:a.y,radius:4,intensity:1,turns:s.weather.rain>50?4:8,age:0});say(s,`${u.name} lanza una antorcha encendida.`);}
else if(a.type==='movement'){if(!['walk','run','crouch','prone'].includes(a.movement))return fail('Elige caminar, correr, agacharte o arrastrarte.');u.movementMode=a.movement;u.stance=a.movement==='prone'?'prone':'standing';say(s,`${u.name} cambia su forma de desplazarse.`);}
else if(a.type==='equipLoot'){const key=a.inventoryKey,record=u.inventory?.[key],slot=a.slot||'primary';if(!record||typeof record!=='object'||record.count<1||!['primary','blade'].includes(slot))return fail('Selecciona un arma recuperada disponible.');if(!(WEAPONS[record.weapon]||BLADES[record.weapon])||(slot==='blade'&&!BLADES[record.weapon]))return fail('Ese objeto no puede equiparse en esa mano.');const capacity=WEAPONS[record.weapon]?.capacity||0;if(!Number.isInteger(record.loaded??0)||(record.loaded??0)>capacity)return fail('La carga del arma recuperada no es válida.');if(!pay(6))return fail('Equipar el arma recuperada requiere 6 PA.');const previous=slot==='primary'?u.weapon:u.blade;const occupiedSlot=previous&&!(slot==='primary'&&u.weaponDropped);if(occupiedSlot){let serial=Object.keys(u.inventory).length,stored=`swap:${previous}:${serial}`;while(u.inventory[stored])stored=`swap:${previous}:${++serial}`;u.inventory[stored]={count:1,weight:WEAPONS[previous]?4:1.3,weapon:previous,loaded:slot==='primary'?u.loaded:0,condition:slot==='primary'?u.condition:100,jammed:slot==='primary'?u.jammed:false};}record.count--;if(slot==='primary'){u.weapon=record.weapon;u.loaded=record.loaded??0;u.condition=record.condition??100;u.jammed=Boolean(record.jammed);u.weaponDropped=false;}else u.blade=record.weapon;u.activeSlot=slot;u.braced=false;u.momentum=0;say(s,`${u.name} equipa ${weaponFor(u).name} y guarda el arma desplazada.`);}
else if(a.type==='loot'){const source=target;const drop=a.dropIndex!==undefined?s.droppedWeapons[a.dropIndex]:null;const ground=a.groundId?s.groundItems.find(g=>g.id===a.groundId):null;let pos=source||drop||ground;if(!pos||dist(u,pos)>1.5)return fail('Acércate al cuerpo o equipo que quieres registrar.');if(source&&source.hp>0&&!source.unconscious&&!source.routed)return fail('Solo puedes registrar un cuerpo o una persona inconsciente.');if(drop?.taken||ground?.count===0||ground?.heldBy)return fail('Ese objeto ya fue recogido o sigue enredado.');const keys=['ammo','priming','flints','rations','boleadoras','medkits','torches'],item=a.item||'all';if(source&&item!=='all'&&item!=='weapon'&&!keys.includes(item))return fail('Ese objeto no se puede saquear.');const weaponAvailable=source?!source.weaponDropped:drop&&!drop.taken;const available=source?(item==='all'?(keys.some(k=>(source[k]||0)>0)||weaponAvailable||Object.values(source.inventory||{}).some(v=>(v.count||0)>0)):item==='weapon'?weaponAvailable:(source[item]||0)>0):Boolean(drop||ground);if(!available)return fail('No queda equipo que recoger.');if(!pay(8))return fail('Registrar el equipo requiere 8 PA.');if(source){for(const key of keys){if(item!=='all'&&item!==key)continue;const count=Math.min(source[key]||0,a.count??Infinity);if(count>0){u[key]=(u[key]||0)+count;source[key]-=count;}}if(item==='all'){for(const[key,record]of Object.entries(source.inventory||{})){if(record.count>0){const unique=`${key}:from${source.id}`;u.inventory[unique]??={...record,count:0};u.inventory[unique].count+=record.count;record.count=0;}}}if((item==='all'||item==='weapon')&&weaponAvailable){const key=`weapon:${typeof source.weapon==='object'?source.weapon.id:source.weapon}:${source.id}`;u.inventory[key]??={count:0,weight:4,weapon:typeof source.weapon==='object'?source.weapon.id:source.weapon,loaded:source.loaded,condition:source.condition};u.inventory[key].count++;source.weaponDropped=true;source.loaded=0;}}else if(drop){const key=`weapon:${drop.weapon}:drop${a.dropIndex}`;u.inventory[key]??={count:0,weight:4,weapon:drop.weapon,loaded:drop.loaded,condition:drop.condition};u.inventory[key].count++;drop.taken=true;}else{u.boleadoras=(u.boleadoras||0)+ground.count;ground.count=0;}say(s,`${u.name} recoge el equipo disponible.`);}
else if(a.type==='boleadoras'){if(!target||target.side===u.side||!alive(target)||dist(u,target)>8||!hasLineOfSight(s,u,target))return fail('El blanco de las boleadoras debe estar visible y a ocho casillas o menos.');if(!u.boleadoras)return fail('No quedan boleadoras.');if(!pay(12))return fail('Lanzar boleadoras requiere 12 PA.');u.boleadoras--;target.entangled=true;target.mounted=false;exhaust(s,target,20);s.groundItems.push({id:`bola-${u.id}-${s.turn}-${s.groundItems.length}`,type:'boleadoras',x:target.x,y:target.y,count:1,heldBy:target.id});say(s,`${u.name} enreda a ${target.name} con las boleadoras.`);}
else if(a.type==='free'){if(!u.entangled)return fail('El soldado no está enredado.');if(!pay(15))return fail('Soltarse requiere 15 PA.');u.entangled=false;for(const g of s.groundItems)if(g.heldBy===u.id)g.heldBy=null;say(s,`${u.name} se libera de las boleadoras.`);}
else if(a.type==='breach'){const wall=tile(s,a.x,a.y);if(!wall?.blocked||dist(u,{x:a.x,y:a.y})>1.5)return fail('Acércate a una barricada o pared de adobe.');if(wall.material==='stone'||['stone','cliff','water'].includes(wall.type))return fail('La piedra requiere artillería; no puede abrirse a mano.');const cost=Number(u.id)===6?25:45;if(!pay(cost))return fail(`Abrir la brecha requiere ${cost} PA.`);wall.blocked=false;wall.blocksSight=false;wall.type='rubble';wall.cover=15;say(s,`${u.name} abre una brecha para el asalto.`);}
else if(a.type==='repair'){if(!hasFirearm(u))return fail('Prepara primero el arma de fuego que quieres mantener.');if(u.condition>=100)return fail('El mecanismo ya está en buen estado.');if(u.flints<1)return fail('No quedan piedras de sílex.');const cost=actionCosts(s,u).repair;if(!pay(cost))return fail(`Cambiar el sílex requiere ${cost} PA.`);u.flints--;practice(u,'mechanical',3);u.condition=Math.min(100,u.condition+(hasTrait(u,'gunsmith_artillerist')?45:hasTrait(u,'workshop_training')?40:30));say(s,`${u.name} cambia el sílex y ajusta el mecanismo.`);}
else if(a.type==='ration'){if(!u.fatigue&&!u.bleeding&&u.ap>=maxActionPoints(s,u))return fail('El soldado ya está descansado y no necesita vendas.');if(u.rations<1)return fail('No quedan raciones de tasajo y lino.');if(!pay(10))return fail('Usar las provisiones requiere 10 PA.');u.rations--;u.fatigue=Math.max(0,(u.fatigue||0)-25);u.bleeding=0;u.maxAP=maxActionPoints(s,u);u.ap=Math.min(u.maxAP,u.ap+20);say(s,`${u.name} toma tasajo y se venda: recupera fuerzas y detiene la hemorragia.`);}
else if(a.type==='brace'){if(bladeFor(u).id!==1811)return fail('Se necesita una bayoneta preparada para recibir la carga.');if(u.ap<16)return fail('Reserva al menos 16 PA para detener una carga.');u.braced=true;say(s,`${u.name} cala la bayoneta y espera la carga.`);}
else if(a.type==='weapon'){if(!['primary','blade'].includes(a.slot))return fail('Selecciona arma principal o arma blanca.');if(a.slot==='blade'&&!BLADES[u.blade])return fail('No hay un arma blanca secundaria equipada.');if((u.activeSlot||'primary')===a.slot)return fail('Esa arma ya está en la mano.');if(!pay(4))return fail('Cambiar de arma requiere 4 PA.');u.activeSlot=a.slot;u.momentum=0;say(s,`${u.name} prepara ${weaponFor(u).name}.`);}
else if(a.type==='overwatch'){if(!hasFirearm(u)||!u.loaded||u.jammed)return fail('Necesitas un arma cargada y cebada para cubrir el frente.');u.overwatch=true;say(s,`${u.name} queda preparado para fuego de reacción.`);}
else if(a.type==='mount'){if(!u.horse)return fail('Este soldado no tiene una montura asignada.');if(!u.mounted&&u.mount&&(u.mount.stamina<20||u.mount.condition<30))return fail('El caballo necesita descanso y cuidados antes de la monta.');const cost=actionCosts(s,u).mount;if(!pay(cost))return fail(`Montar o desmontar requiere ${cost} PA.`);u.mounted=!u.mounted;u.stance='standing';u.momentum=0;say(s,`${u.name} ${u.mounted?'monta a caballo':'desmonta'}.`);} 
else if(a.type==='heal'){const t=target||u;if(t.side!==u.side||!alive(t)||dist(u,t)>1.5)return fail('El herido debe estar a tu lado.');if(!u.medkits)return fail('No quedan vendas.');if(t.hp===t.maxHp&&!t.bleeding)return fail('El soldado no necesita atención.');const medicalCost=Number(u.id)===10?18:hasTrait(u,'field_rescuer')?20:25;if(!pay(medicalCost))return fail(`Curar requiere ${medicalCost} PA.`);u.medkits--;practice(u,'medical',3);t.bleeding=0;t.hp=Math.min(t.maxHp,t.hp+10+Math.round(u.medical*.25));say(s,`${u.name} atiende a ${t.name} y detiene la hemorragia.`);}
else if(a.type==='stance'){if(u.mounted)return fail('Debes desmontar antes de cambiar de postura.');if(!['standing','prone'].includes(a.stance)||u.stance===a.stance)return fail('Postura no válida.');const cost=u.knockedDown?12:6;if(!pay(cost))return fail(`Cambiar de postura requiere ${cost} PA.`);u.stance=a.stance;if(a.stance==='standing')u.knockedDown=false;u.momentum=0;say(s,`${u.name} ${a.stance==='prone'?'se tiende cuerpo a tierra':'se pone de pie'}.`);}
else return fail('Orden desconocida.');checkEnd(s);return true;}
export function actBattle(state,action){if(action.type==='rest')return endTurn(state);const s=clone(state);s.lastError=null;if(action.type==='explore'&&(s.status==='victory'||s.sectorCleared)){s.mode='exploration';s.status='active';say(s,'El sector está despejado. Puedes explorar y recoger equipo.');return s;}const oldMode=s.mode;delete s.actionDurationSeconds;const success=apply(s,action);if(success!==false&&!s.lastError){if(oldMode==='exploration'){advanceBattleClock(s,s.actionDurationSeconds??6);}else if(!s.roundTimeCharged){advanceBattleClock(s,COMBAT_ROUND_SECONDS);s.roundTimeCharged=true;}}delete s.actionDurationSeconds;detectContact(s);revealRooms(s);return s;}
export function endTurn(state){const s=clone(state);s.lastError=null;if(s.status!=='active')return s;if(s.mode==='exploration'){for(const u of s.units.filter(present)){u.energy=Math.min(100,(u.energy??100)+15);u.unconscious=u.energy===0;}advanceBattleClock(s,REST_SECONDS);s.turn++;detectContact(s);return s;}if(!s.roundTimeCharged)advanceBattleClock(s,COMBAT_ROUND_SECONDS);s.roundTimeCharged=false;s.phase='enemy';for(const u of s.units.filter(u=>u.side==='enemy'&&alive(u))){u.maxAP=maxActionPoints(s,u);u.ap=Math.max(0,u.maxAP-u.reactionSpent);u.reactionSpent=0;for(let n=0;n<12&&u.ap>=6&&s.status==='active';n++){const targets=s.units.filter(t=>t.side==='player'&&alive(t)&&canSee(s,u,t)).sort((a,b)=>dist(u,a)-dist(u,b));const t=targets[0];if(!t)break;if(u.entangled){if(!apply(s,{type:'free',unitId:u.id},true))break;}else if(u.knockedDown){if(!apply(s,{type:'stance',unitId:u.id,stance:'standing'},true))break;}else if(dist(u,t)<=bladeFor(u).reach&&hasLineOfSight(s,u,t)){if(!apply(s,{type:'melee',unitId:u.id,targetId:t.id},true))break;}else if(!u.loaded&&dist(u,t)<=6&&(u.x===t.x||u.y===t.y||Math.abs(u.x-t.x)===Math.abs(u.y-t.y))&&hasLineOfSight(s,u,t)&&u.ap>=Math.ceil(dist(u,t)*stepCost(u,t))+actionCosts(s,u).melee){if(!apply(s,{type:'charge',unitId:u.id,targetId:t.id},true))break;}else if(u.jammed){if(!apply(s,{type:'reprime',unitId:u.id},true))break;}else if(hasFirearm(u)&&!u.loaded&&u.ammo){if(!apply(s,{type:'reload',unitId:u.id},true))break;}else if(hasFirearm(u)&&u.loaded&&hasLineOfSight(s,u,t)&&shotChance(s,u,t)>=20){if(!apply(s,{type:'fire',unitId:u.id,targetId:t.id},true))break;}else{const candidates=getReachable(s,u).filter(p=>p.cost>0).sort((a,b)=>(dist(a,t)*10+a.cost*.1)-(dist(b,t)*10+b.cost*.1));if(!candidates.length)break;const p=candidates[0];if(dist(p,t)>=dist(u,t)||!apply(s,{type:'move',unitId:u.id,x:p.x,y:p.y},true))break;}}if(alive(u)&&u.ap>=16&&bladeFor(u).id===1811)u.braced=true;}
s.smoke=s.smoke.map(v=>({...v,radius:Math.min((v.radius||1)+.5,3),turns:v.turns-1})).filter(v=>v.turns>0);for(const u of s.units.filter(present)){u.energy=Math.min(100,(u.energy??100)+10);u.unconscious=u.energy===0;if(u.bleeding){u.hp=Math.max(0,u.hp-u.bleeding);say(s,`${u.name} pierde ${u.bleeding} de salud por hemorragia.`);}if(u.side==='player'){u.maxAP=maxActionPoints(s,u);u.ap=Math.max(0,u.maxAP-u.reactionSpent);u.reactionSpent=0;}u.momentum=0;u.lastDirection=null;}s.turn++;s.phase='player';checkEnd(s);if(s.status==='active')say(s,`Turno ${s.turn}: ¡órdenes, comandante!`);s.lastError=null;return s;}
