import test from 'node:test';import assert from 'node:assert/strict';
import {act} from '../web/node_modules/react/index.js';
import {mountCampaign} from './mounted-campaign-fixture.mjs';
import {supplyCareField} from './supply-transfer-fixture.mjs';
const change=async(m,e,value)=>{const proto=e.tagName==='SELECT'?m.dom.window.HTMLSelectElement.prototype:m.dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,String(value));await act(async()=>e.dispatchEvent(new m.dom.window.Event(e.tagName==='SELECT'?'change':'input',{bubbles:true})));};

test('the production inventory selects a real supply, exact quantity and nearby recipient and persists both remaining amounts',async t=>{
 const p=supplyCareField(),m=await mountCampaign(t,p);await m.click('Equipo y órdenes');const stock=m.document.querySelector('[aria-label="Suministro personal"]'),count=m.document.querySelector('[aria-label="Cantidad de suministros"]'),receiver=m.document.querySelector('[aria-label="Entregar suministros a"]'),button=[...m.document.querySelectorAll('button')].find(b=>b.textContent.startsWith('Entregar suministros'));assert.equal(button.disabled,true);assert.match(m.document.querySelector('.pertrechos').textContent,/4 Vendas/);
 await change(m,stock,'medkits');await change(m,count,3);await change(m,receiver,'111');assert.equal(button.disabled,false);await act(async()=>button.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));let s=m.read();assert.equal(s.battle.units.find(u=>u.id==='110').medkits,1);assert.equal(s.battle.units.find(u=>u.id==='111').medkits,3);assert.equal(button.disabled,true);assert.match(m.document.querySelector('.pertrechos').textContent,/No quedan suficientes/);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});
 await change(m,stock,'rations');await change(m,count,1);assert.equal(button.disabled,false);await act(async()=>button.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));s=m.read();assert.equal(s.battle.units.find(u=>u.id==='110').rations,1);assert.equal(s.battle.units.find(u=>u.id==='111').rations,3);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});
});
test('the supply controls show unavailable amounts and the registered order rechecks an attempted excess without committing it',async t=>{
 const p=supplyCareField(),m=await mountCampaign(t,p);await m.click('Equipo y órdenes');const count=m.document.querySelector('[aria-label="Cantidad de suministros"]'),receiver=m.document.querySelector('[aria-label="Entregar suministros a"]');await change(m,count,5);await change(m,receiver,'111');const button=[...m.document.querySelectorAll('button')].find(b=>b.textContent.startsWith('Entregar suministros'));assert.equal(button.disabled,true);assert.match(m.document.querySelector('.pertrechos').textContent,/No quedan suficientes/);const schema=m.registrations.find(x=>x.name==='issue_granaderos_tactical_order').inputSchema;assert.ok(schema.properties.type.enum.includes('transferSupply'));assert.equal(schema.properties.count.minimum,1);const before=m.read();await act(async()=>assert.throws(()=>m.issue({type:'transferSupply',unitId:'110',targetId:'111',item:'medkits',count:5}),/No quedan suficientes/));assert.deepEqual(m.read().battle.units,before.battle.units);
});
