import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,actBattle,ARTILLERY,artilleryCosts} from '../game/tactical.js';
function setup(type='bronze4',leader=20,width=20){const tiles=Array.from({length:width*7},(_,i)=>({x:i%width,y:Math.floor(i/width),type:'grass',blocked:false,cover:0}));return createBattle([{id:leader,x:1,y:2},{id:21,x:2,y:2},{id:22,x:1,y:3}],{width,height:7,tiles,enemies:[{id:'enemy',x:width-2,y:5}],artillery:[{id:'gun',type,x:2,y:3,side:'player',loaded:true,ammo:5}]});}
test('all three pieces fire with their actual crew requirement',()=>{for(const type of Object.keys(ARTILLERY)){const b=setup(type);const crew=ARTILLERY[type].crew;b.units=b.units.filter(u=>u.side==='enemy'||['20','21','22'].slice(0,crew).includes(u.id));const n=actBattle(b,{type:'artillery',unitId:20,artilleryId:'gun',x:10,y:3,mode:'solid'});assert.equal(n.lastError,null,type);assert.equal(n.artillery[0].loaded,false);assert.equal(n.units[0].ap,100-ARTILLERY[type].fireAP);if(crew>1){const short=structuredClone(b);short.units=short.units.filter(u=>u.id!=='21');assert.ok(actBattle(short,{type:'artillery',unitId:20,artilleryId:'gun',x:10,y:3}).lastError);}}});
test('maximum range is enforced independently of normal battlefield dimensions',()=>{for(const[type,spec]of Object.entries(ARTILLERY)){const b=setup(type,20,spec.range+6);const far=actBattle(b,{type:'artillery',unitId:20,artilleryId:'gun',x:2+spec.range+1,y:3});assert.ok(far.lastError,type);assert.equal(far.artillery[0].loaded,true);assert.equal(far.units[0].ap,100);const exact=actBattle(b,{type:'artillery',unitId:20,artilleryId:'gun',x:2+spec.range,y:3});assert.equal(exact.lastError,null,type);assert.equal(exact.artillery[0].loaded,false);}});
test('crew drags a loaded cannon together and cannot pass through blocked terrain',()=>{let b=setup();const cost=artilleryCosts(b,b.units[0],b.artillery[0]).move;const n=actBattle(b,{type:'artilleryMove',unitId:20,artilleryId:'gun',x:3,y:3});assert.equal(n.lastError,null);assert.equal(n.artillery[0].x,3);assert.equal(n.artillery[0].loaded,true);assert.equal(n.units[0].x,2);assert.equal(n.units[1].x,3);assert.equal(n.units[0].ap,100-cost);assert.equal(n.units[2].x,1,'unassigned third person stays in place');b.tiles.find(t=>t.x===3&&t.y===3).blocked=true;const rejected=actBattle(b,{type:'artilleryMove',unitId:20,artilleryId:'gun',x:3,y:3});assert.ok(rejected.lastError);assert.equal(rejected.artillery[0].x,2);});
test('pivoting consumes crew AP and makes a previously forbidden firing arc usable',()=>{let b=setup();b.artillery[0].facing=Math.PI;assert.ok(actBattle(b,{type:'artillery',unitId:20,artilleryId:'gun',x:10,y:3}).lastError);b=actBattle(b,{type:'artilleryPivot',unitId:20,artilleryId:'gun',x:10,y:3});assert.equal(b.lastError,null);assert.equal(b.artillery[0].facing,0);assert.equal(b.units[0].ap,90);const shot=actBattle(b,{type:'artillery',unitId:20,artilleryId:'gun',x:10,y:3});assert.equal(shot.lastError,null);assert.equal(shot.units[0].ap,60);});
test('solid shot breaches adobe and stone and penetrates consecutive troops',()=>{const b=setup('field8');for(const[x,material]of[[4,'adobe'],[5,'stone']])Object.assign(b.tiles.find(t=>t.x===x&&t.y===3),{type:'wall',material,blocked:true});b.units.push({...b.units.at(-1),id:'rank-one',x:7,y:3,hp:100,morale:100},{...b.units.at(-1),id:'rank-two',x:8,y:3,hp:100,morale:100});const n=actBattle(b,{type:'artillery',unitId:20,artilleryId:'gun',x:12,y:3,mode:'solid'});assert.equal(n.lastError,null);for(const x of [4,5])assert.equal(n.tiles.find(t=>t.x===x&&t.y===3).blocked,false);assert.equal(n.units.find(u=>u.id==='rank-one').hp,0);assert.ok(n.units.find(u=>u.id==='rank-two').hp<100);});
test('light swivel does not magically demolish stone fortifications',()=>{const b=setup('swivel');Object.assign(b.tiles.find(t=>t.x===5&&t.y===3),{type:'wall',material:'stone',blocked:true});const n=actBattle(b,{type:'artillery',unitId:20,artilleryId:'gun',x:10,y:3});assert.equal(n.lastError,null);assert.equal(n.tiles.find(t=>t.x===5&&t.y===3).blocked,true);});
test('Brown fires efficiently and Barcala completes a difficult crew reload',()=>{const brown=setup('swivel',5);brown.units[0].ap=17;const fired=actBattle(brown,{type:'artillery',unitId:5,artilleryId:'gun',x:10,y:3});assert.equal(fired.lastError,null);assert.equal(fired.units[0].ap,0);let barcala=setup('field8',7);barcala.artillery[0].loaded=false;for(const u of barcala.units.filter(u=>u.side==='player'))u.ap=60;const loaded=actBattle(barcala,{type:'artilleryReload',unitId:7,artilleryId:'gun'});assert.equal(loaded.lastError,null);assert.equal(loaded.artillery[0].loaded,true);assert.equal(loaded.units[0].ap,0);});
