import test from 'node:test';import assert from 'node:assert/strict';
import {buildBuilding,placeBuilding} from '../game/buildings.js';
import {createBattle,actBattle,getReachable,hasLineOfSight,visibleRooms} from '../game/tactical.js';
const ground=()=>Array.from({length:240},(_,i)=>({x:i%20,y:Math.floor(i/20),type:'grass',blocked:false,cover:0}));
function house(extra={}){const built=placeBuilding(ground(),{id:'house',x:4,y:2,width:6,height:6,doors:[{id:'left',x:6,y:2},{id:'right',x:7,y:2}],...extra});return createBattle([{id:20,x:6,y:1}],{width:20,height:12,tiles:built.tiles,buildings:[built.building],exploration:true,enemies:[]});}
test('authored building has a real walkable interior rather than a filled rectangle',()=>{const b=buildBuilding({id:'b',x:1,y:1,width:5,height:4,doors:[{x:3,y:1}]});const floors=b.tiles.filter(t=>t.type==='floor');assert.equal(floors.length,6);assert.ok(floors.every(t=>!t.blocked&&!t.blocksSight));assert.equal(b.building.rooms[0].cells.length,6);});
test('double door leaves open independently and permit entry into the room',()=>{let s=house();assert.equal(visibleRooms(s).length,0);s=actBattle(s,{type:'door',unitId:20,doorId:'left'});assert.equal(s.lastError,null);assert.equal(s.tiles.find(t=>t.doorId==='left').blocked,false);assert.equal(s.tiles.find(t=>t.doorId==='right').blocked,true);assert.ok(getReachable(s,'20').some(t=>t.x===6&&t.y===3));s=actBattle(s,{type:'move',unitId:20,x:6,y:3});assert.equal(s.lastError,null);assert.ok(s.revealedRooms.includes('house:interior'));});
test('windows admit sight but remain impassable to walking',()=>{const s=house({windows:[{x:4,y:4}]});s.units[0].x=3;s.units[0].y=4;assert.equal(hasLineOfSight(s,s.units[0],{x:5,y:4}),true);assert.ok(!getReachable(s,'20').some(t=>t.x===4&&t.y===4));assert.ok(visibleRooms(s).includes('house:interior'));});
test('distant interiors remain roof-hidden at night until their floor is illuminated',()=>{const built=placeBuilding(ground(),{id:'night-house',x:10,y:2,width:6,height:6,windows:[{x:10,y:4}]});const s=createBattle([{id:20,x:1,y:4}],{width:20,height:12,tiles:built.tiles,buildings:[built.building],exploration:true,night:true,enemies:[]});assert.equal(visibleRooms(s).length,0);assert.equal(s.revealedRooms.length,0);s.lights.push({x:11,y:4,radius:4,intensity:1});assert.ok(visibleRooms(s).includes('night-house:interior'));});
