import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {Vector3} from '../web/node_modules/three/build/three.module.js';
import {asset,visual,sample,snapshot} from './helpers/climb-native-fixture.mjs';
import {palmBefore} from './helpers/climb-palm-before.mjs';
import {ladderGeometry} from '../game/climb-geometry.js';
const {ActorRuntime}=await import('../web/lib/three/actor-runtime.ts');
const {TILE_METRES}=await import('../web/lib/three/projection.ts');
const records=[],fingers=/^(index|middle|ring|pinky)_\d\d_[lr]$/;
function list(actor){const result=[];actor.model.traverse(mesh=>{if(!mesh.isSkinnedMesh||!mesh.name.startsWith('Exposed_Human_Skin'))return;const p=mesh.geometry.attributes.position,si=mesh.geometry.attributes.skinIndex,sw=mesh.geometry.attributes.skinWeight;for(let index=0;index<p.count;index++){const weights={l:0,r:0},armWeights={l:0,r:0};for(let j=0;j<4;j++){const name=mesh.skeleton.bones[si.getComponent(index,j)].name,w=sw.getComponent(index,j),side=name.slice(-1);if(side==='l'||side==='r'){if(/^(upperarm|lowerarm|hand|index|middle|ring|pinky|thumb)_/.test(name))armWeights[side]+=w;if(/^(hand|index|middle|ring|pinky|thumb)_/.test(name))weights[side]+=w;}}if(armWeights.l>.001||armWeights.r>.001)result.push({mesh,index,handL:weights.l>.001,handR:weights.r>.001});}});return result;}
const v=new Vector3();function scan(actor,skin,g,p,out){let min={l:Infinity,r:Infinity};for(const mesh of new Set(skin.map(x=>x.mesh)))mesh.skeleton.update();for(let i=0;i<skin.length;i++){const {mesh,index,handL,handR}=skin[i];actor.root.worldToLocal(mesh.getVertexPosition(index,v).applyMatrix4(mesh.matrixWorld));out[i*3]=v.x;out[i*3+1]=v.y;out[i*3+2]=v.z;const forward=v.z+p.root.forward,inside=g.span?forward>=g.edgeSpan:!(v.x>=g.hatch.minAcross&&v.x<=g.hatch.maxAcross&&forward>=g.hatch.minForward&&forward<=g.hatch.maxForward);if(inside){const y=v.y+p.root.height-g.height;if(handL)min.l=Math.min(min.l,y);if(handR)min.r=Math.min(min.r,y);}}return min;}
function shift(a,b){let max=0;for(let i=0;i<a.length;i+=3)max=Math.max(max,Math.hypot(a[i]-b[i],a[i+1]-b[i+1],a[i+2]-b[i+2]));return max;}
function unchangedParents(a,b){const native=snapshot(b);for(const[name,value]of Object.entries(snapshot(a))){const old=native[name];assert.deepEqual(value.p,old.p,name+' native joint offsets');assert.deepEqual(value.s,old.s,name+' native scales');if(!fingers.test(name))assert.deepEqual(value.q,old.q,name+' retained Root/parent/arm/wrist/foot channel');}}
for(const id of ['granadero','woman-scout'])for(const lod of [0,1,2])test(`${id} LOD${lod}: complete roof hand skin clears planted fingertips with preserved motion`,async()=>{
 const source=await asset(id,lod),old={...source,animation:await palmBefore(source)};
 for(const action of ['climbUp','climbDown'])for(const height of [2,3,4.2,5.6])for(const direction of ['same','cardinal','diagonal']){
  const upper=direction==='same'?[0,1.2+height,0]:direction==='diagonal'?[TILE_METRES,1.2+height,TILE_METRES]:[0,1.2+height,TILE_METRES],g=ladderGeometry([0,1.2,0],upper,TILE_METRES),spec=source.clips.find(c=>c.name==='life.'+action),duration=Math.max(spec.duration,height/.65),a=new ActorRuntime(source,visual(id,action,{cue:undefined})),b=new ActorRuntime(old,visual(id,action,{cue:undefined})),skin=list(a),oldSkin=list(b),aa=new Float64Array(skin.length*3),ab=new Float64Array(aa.length),ba=new Float64Array(aa.length),bb=new Float64Array(aa.length);assert.equal(skin.length,oldSkin.length);let nowA=aa,prevA=ab,nowB=ba,prevB=bb,last,maxBeforeSpeed=0,maxCurrentSpeed=0,minimumCurrent=Infinity,minimumBefore=Infinity,plantedMinimum=Infinity,checks=0;
  const phases=new Set([0,.5,.76,.82,.84,.85,.86,.91,.98,1]);for(let t=.80;t<1;t+=1/(duration*240))phases.add(t);
  for(const up of [...phases].sort((x,y)=>x-y)){const p=sample(a,id,action,g,spec,up);sample(b,id,action,g,spec,up);assert.deepEqual(a.root.position.toArray(),b.root.position.toArray());assert.deepEqual(a.root.quaternion.toArray(),b.root.quaternion.toArray());assert.equal(a.action.time,b.action.time);assert.equal(a.action.timeScale,b.action.timeScale);assert.equal(a.mixer.time,b.mixer.time);unchangedParents(a,b);const current=scan(a,skin,g,p,nowA),before=scan(b,oldSkin,g,p,nowB);for(const side of ['l','r']){if(up>=.80){minimumCurrent=Math.min(minimumCurrent,current[side]);minimumBefore=Math.min(minimumBefore,before[side]);}if(current[side]<0)assert.ok(current[side]>=before[side]-.000001,'No new whole-approach/release hand floor penetration');const hand=p.hands[side];if(hand.planted&&hand.roofWeight>.999&&hand.weight>.999){plantedMinimum=Math.min(plantedMinimum,current[side]);assert.ok(current[side]>.0001,'Independent complete planted hand has at least .1mm floor clearance');checks++;}}
   if(last!==undefined&&last>=.80){const elapsed=(up-last)*duration;maxBeforeSpeed=Math.max(maxBeforeSpeed,shift(nowB,prevB)/elapsed);maxCurrentSpeed=Math.max(maxCurrentSpeed,shift(nowA,prevA)/elapsed);}
   [nowA,prevA]=[prevA,nowA];[nowB,prevB]=[prevB,nowB];last=up;
  }
  assert.ok(checks>30);assert.ok(maxCurrentSpeed<=maxBeforeSpeed+.001,'No new complete arm/hand continuous peak');
  // New source curves use the same retained native key clocks. Shrinking
  // intervals cover the normal-based source knots and actual native keys.
  const clip=a.action.getClip(),times=[...new Set(clip.tracks.filter(t=>fingers.test(t.name.split('.')[0])).flatMap(t=>Array.from(t.times)))];for(const time of times.filter(t=>t/clip.duration>.82&&t/clip.duration<.98)){const up=action==='climbDown'?1-time/clip.duration:time/clip.duration;if(up<.82||up>.98)continue;let coarse,fine;for(const eps of [1e-4,1e-6]){const p=sample(a,id,action,g,spec,up-eps);scan(a,skin,g,p,aa);const q=sample(a,id,action,g,spec,up+eps);scan(a,skin,g,q,ab);if(eps===1e-4)coarse=shift(aa,ab);else fine=shift(aa,ab);}assert.ok(fine<coarse*.0103+.00001,'Complete hand/arm motion has no fixed native key jump');}
  sample(a,id,action,g,spec,.90);const held=snapshot(a),clock=a.action.time;for(let i=0;i<20;i++)a.tick(1/60,1000);assert.deepEqual(snapshot(a),held,'Held paid phase keeps source pose exact');assert.equal(a.action.time,clock);
  records.push({id,lod,action,height,direction,steps:g.steps,poses:phases.size,minimumBeforeMm:minimumBefore*1000,minimumCurrentMm:minimumCurrent*1000,plantedMinimumMm:plantedMinimum*1000,maxBeforeSpeed,maxCurrentSpeed});a.dispose();b.dispose();
 }
});
test.after(()=>{mkdirSync('artifacts',{recursive:true});writeFileSync('artifacts/climb-roof-finger-surfaces.json',JSON.stringify({records,scope:'Bounded planted fingertip floor repair. Retained native transfer penetration and main-palm support gap stay open; no triangle, natural pace or full palm acceptance claim.'},null,2)+'\n');});
