import{register}from'node:module';register('./tactical-render-loader.mjs',import.meta.url);import test from'node:test';import assert from'node:assert/strict';import{Vector3,LoopOnce}from'../web/node_modules/three/build/three.module.js';import{publishedActor}from'./published-actor-fixture.mjs';const{ActorRuntime}=await import('../web/lib/three/actor-runtime.ts');
test('three native prone pistol guards retain full supported free palms and sleeves at every LOD',async t=>{const rows=[];
for(const appearance of['granadero','woman-scout'])for(const lod of[0,1,2]){
const asset=await publishedActor(appearance,lod),wanted=asset.animation.animations.filter(c=>['prone.idle.short-gun','prone.aim.short-gun','prone.fire.short-gun'].includes(c.name));
for(const clip of wanted)for(const paired of [false,true]){const spec=asset.clips.find(c=>c.name===clip.name),equipment=clip.name.includes('short-gun')?'short-gun':'long-gun',id=spec.item??clip.name.match(/\.(180\d)$/)?.[1]??(equipment==='short-gun'?'1805':'1800'),visual={key:'unit:audit',id:'audit',kind:'unit',appearance,skin:'light',side:'player',position:[0,0,0],yaw:0,tacticalLevel:0,posture:'prone',mounted:false,action:({offer:'drop',grab:'steal',tool:'environment',fitting:'fitBayonet',signal:'prisonerEscort',throw:'throwTorch',bolas:'boleadoras'}[spec.gesture]??spec.gesture),idleAction:'idle',equipment,items:[{id,reference:'primary',socket:'handRight'},...(paired?[{id:'1806',reference:'offhand',socket:'handLeft'}]:[])],garments:{},selected:false,bodyHeights:{}},actor=new ActorRuntime(asset,visual),meshes=[];actor.model.traverse(n=>{if(n.isSkinnedMesh)meshes.push(n);});const surface={boot:[],hand_l:[],hand_r:[],forearm_l:[],forearm_r:[],arm_l:[],arm_r:[],upperBody:[]};
for(const mesh of meshes){const indices=mesh.geometry.attributes.skinIndex,weights=mesh.geometry.attributes.skinWeight;for(let i=0;i<mesh.geometry.attributes.position.count;i++){
if(mesh.name===asset.appearance.parts.footwear.replace('{lod}',String(lod)))surface.boot.push({mesh,index:i});let torso=0;
for(const side of['l','r']){let hand=0,fore=0,arm=0;for(let j=0;j<4;j++){const name=mesh.skeleton.bones[indices.getComponent(i,j)].name,w=weights.getComponent(i,j);if(side==='l'&&/^(pelvis|spine_)/.test(name))torso+=w;if(!name.endsWith('_'+side))continue;if(name.startsWith('lowerarm_'))fore+=w;if(/^(upperarm_|lowerarm_|hand_|thumb_|index_|middle_|ring_|pinky_)/.test(name))arm+=w;if(/^(hand_|thumb_|index_|middle_|ring_|pinky_)/.test(name))hand+=w;}if(fore>.7)surface['forearm_'+side].push({mesh,index:i});if(hand>.7)surface['hand_'+side].push({mesh,index:i});if(arm>.7)surface['arm_'+side].push({mesh,index:i});}if(torso>.7)surface.upperBody.push({mesh,index:i});}}
actor.mixer.stopAllAction();const action=actor.mixer.clipAction(clip).setLoop(LoopOnce,1).play();action.clampWhenFinished=true;actor.clipSpec=spec;actor.action=action;const minima=Object.fromEntries(Object.keys(surface).map(k=>[k,Infinity])),samples=[],itemMinimum={};let nearestMaximum=-Infinity,heldFloor=Infinity,stowedFloor=Infinity;
for(let frame=0;frame<=120;frame++){action.time=clip.duration*frame/120;actor.mixer.update(0);actor.placeEquipment(action.time);actor.timedProps(action.time);actor.root.updateMatrixWorld(true);for(const mesh of meshes)mesh.skeleton.update();const lows={};for(const[name,list]of Object.entries(surface)){let low=Infinity;for(const{mesh,index}of list)low=Math.min(low,mesh.getVertexPosition(index,new Vector3()).applyMatrix4(mesh.matrixWorld).y);lows[name]=low;minima[name]=Math.min(minima[name],low);}nearestMaximum=Math.max(nearestMaximum,Math.min(lows.forearm_l,lows.forearm_r));const items=[];for(const object of[...(actor.equipment.userData.attached??[]),...actor.temporaryProps.values()]){let low=Infinity;if(!object.visible)continue;object.traverse(mesh=>{if(!mesh.isMesh||!mesh.geometry.attributes.position)return;for(let i=0;i<mesh.geometry.attributes.position.count;i++)low=Math.min(low,mesh.getVertexPosition(i,new Vector3()).applyMatrix4(mesh.matrixWorld).y);});if(!Number.isFinite(low))continue;const key=(object.userData.itemId??object.name)+(object.userData.presentationStowed?':stowed':':held');itemMinimum[key]=Math.min(itemMinimum[key]??Infinity,low);if(object.userData.presentationStowed)stowedFloor=Math.min(stowedFloor,low);else heldFloor=Math.min(heldFloor,low);items.push({key,minimum:low});}samples.push({fraction:frame/120,...lows,items});}
rows.push({appearance,lod,paired,clip:clip.name,id,actualDuration:clip.duration,minimum:minima,maximumNearestForearm:nearestMaximum,heldFloor:Number.isFinite(heldFloor)?heldFloor:null,stowedFloor:Number.isFinite(stowedFloor)?stowedFloor:null,itemMinimum,samples});actor.dispose();
}}
assert.equal(rows.length,36);for(const r of rows){assert.ok(r.minimum.hand_l>=.0015&&r.minimum.hand_r>=.0015,'Complete native hands clear ground');assert.ok(r.minimum.forearm_l>=.0015&&r.minimum.forearm_r>=.0015,'Complete native forearms clear ground');assert.ok(r.minimum.arm_l>=.0015&&r.minimum.arm_r>=.0015,'Complete weighted upper/forearm sleeve seams clear ground');assert.ok(r.maximumNearestForearm<.005,'Free forearm supports the guard throughout its breathing cycle');assert.ok(r.heldFloor>.015,'Owned held pistols clear ground');}t.diagnostic(JSON.stringify({cases:rows.length,minimumHand:Math.min(...rows.flatMap(r=>[r.minimum.hand_l,r.minimum.hand_r])),minimumForearm:Math.min(...rows.flatMap(r=>[r.minimum.forearm_l,r.minimum.forearm_r]))}));});
