import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,actBattle,endTurn} from '../game/tactical.js';
const tiles=()=>Array.from({length:80},(_,i)=>({x:i%10,y:Math.floor(i/10),type:'grass',blocked:false,cover:0}));
function battle(weapon=1809,defense=1800){return createBattle([{id:'attacker',weapon,x:1,y:1}],{width:10,height:8,tiles:tiles(),enemies:[{id:'defender',weapon:defense,x:2,y:1,morale:100}],seed:45});}
test('sabre leaves stronger bleeding and a defending sable parries using AP',()=>{const naked=actBattle(battle(1809),{type:'melee',unitId:'attacker',targetId:'defender'});const guarded=actBattle(battle(1809,1810),{type:'melee',unitId:'attacker',targetId:'defender'});assert.ok(guarded.units[1].hp>naked.units[1].hp);assert.equal(guarded.units[1].ap,94);assert.ok(naked.units[1].bleeding>=6);assert.ok(guarded.log.some(t=>t.includes('desvía')));});
test('facón and wrapped poncho absorb force and deliver one bounded counterstrike',()=>{const normal=actBattle(battle(1809),{type:'melee',unitId:'attacker',targetId:'defender'}),counter=actBattle(battle(1809,1813),{type:'melee',unitId:'attacker',targetId:'defender'});assert.ok(counter.units[1].hp>normal.units[1].hp);assert.ok(counter.units[0].hp<100);assert.equal(counter.units[1].ap,92);const again=actBattle(counter,{type:'melee',unitId:'attacker',targetId:'defender'});assert.equal(again.units[0].hp,counter.units[0].hp);});
test('enemy avoids charging a readied bayonet',()=>{let b=createBattle([{id:'defender',weapon:1800,blade:1811,bladeInstanceId:'guard-bayonet',bladeFittingPattern:'india_socket',loaded:0,x:1,y:1}],{width:10,height:8,tiles:tiles(),enemies:[{id:'attacker',weapon:1809,hp:40,x:6,y:1}],seed:45});b=actBattle(b,{type:'fitBayonet',unitId:'defender',item:'blade'});assert.equal(b.lastError,null);b=actBattle(b,{type:'brace',unitId:'defender'});assert.equal(b.lastError,null);let n=endTurn(b);while(n.phase==='interrupt')n=endTurn(n);assert.equal(n.units[1].hp,40);assert.ok(n.units[0].hp<100);assert.ok(!n.log.some(t=>t.includes('ejecuta una carga')));});
test('lance knockdown unhorses and requires standing before fighting again',()=>{const b=battle(1812);b.units[1].mounted=true;let n=actBattle(b,{type:'melee',unitId:'attacker',targetId:'defender'});assert.equal(n.units[1].knockedDown,true);assert.equal(n.units[1].stance,'prone');assert.equal(n.units[1].mounted,false);n=endTurn(n);assert.equal(n.units[1].knockedDown,false);assert.ok(n.log.some(t=>t.includes('se pone de pie')));});
test('routing drops its weapon in place and escapes only on its paid turn',()=>{
 const b=battle();b.units[1].morale=16;
 let n=actBattle(b,{type:'melee',unitId:'attacker',targetId:'defender'});
 const routed=n.units[1];assert.equal(routed.routed,true);assert.equal(routed.weaponDropped,true);assert.equal(routed.weapon,1800);assert.equal(routed.loaded,0);
 assert.deepEqual([routed.x,routed.y],[2,1]);assert.equal(routed.fled,false);assert.equal(routed.departure,undefined);assert.deepEqual(routed.fleePath,[]);assert.equal(n.status,'active');
 assert.deepEqual(n.droppedWeapons[0],{unitId:'defender',x:2,y:1,weapon:1800,weight:4,loaded:1,condition:100});
 n=endTurn(n);while(n.phase==='interrupt')n=endTurn(n);
 const escaped=n.units[1];assert.equal(escaped.departure.edge,'N');assert.equal(escaped.y,0);assert.equal(escaped.fled,true);assert.equal(n.droppedWeapons.length,1);assert.ok(escaped.ap<routed.ap);assert.equal(n.status,'victory');
});
test('blunderbuss cone can injure an ally and suppress several targets with one charge',()=>{const b=battle(1807);b.units[1].x=5;b.units.push({...b.units[0],id:'ally',x:4,y:1});const n=actBattle(b,{type:'fire',unitId:'attacker',targetId:'defender'});assert.equal(n.units[0].loaded,0);assert.ok(n.units[2].hp<100||n.units[2].morale<b.units[2].morale);assert.ok(n.units[1].morale<100);assert.ok(n.log.some(t=>t.includes('tres casillas')));});
