import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,actBattle,endTurn} from '../game/tactical.js';
const tiles=()=>Array.from({length:80},(_,i)=>({x:i%10,y:Math.floor(i/10),type:'grass',blocked:false,cover:0}));
function battle(weapon=1809,defense=1800){return createBattle([{id:'attacker',weapon,x:1,y:1}],{width:10,height:8,tiles:tiles(),enemies:[{id:'defender',weapon:defense,x:2,y:1,morale:100}],seed:45});}
test('sabre leaves stronger bleeding and a defending sable parries using AP',()=>{const naked=actBattle(battle(1809),{type:'melee',unitId:'attacker',targetId:'defender'});const guarded=actBattle(battle(1809,1810),{type:'melee',unitId:'attacker',targetId:'defender'});assert.ok(guarded.units[1].hp>naked.units[1].hp);assert.equal(guarded.units[1].ap,94);assert.ok(naked.units[1].bleeding>=6);assert.ok(guarded.log.some(t=>t.includes('desvía')));});
test('facón and wrapped poncho absorb force and deliver one bounded counterstrike',()=>{const normal=actBattle(battle(1809),{type:'melee',unitId:'attacker',targetId:'defender'}),counter=actBattle(battle(1809,1813),{type:'melee',unitId:'attacker',targetId:'defender'});assert.ok(counter.units[1].hp>normal.units[1].hp);assert.ok(counter.units[0].hp<100);assert.equal(counter.units[1].ap,92);const again=actBattle(counter,{type:'melee',unitId:'attacker',targetId:'defender'});assert.equal(again.units[0].hp,counter.units[0].hp);});
test('a readied bayonet receives a real AI charge before the charging attack lands',()=>{let b=createBattle([{id:'defender',weapon:1800,loaded:0,x:1,y:1}],{width:10,height:8,tiles:tiles(),enemies:[{id:'attacker',weapon:1809,hp:40,x:6,y:1}],seed:45});b=actBattle(b,{type:'brace',unitId:'defender'});assert.equal(b.lastError,null);const n=endTurn(b);assert.equal(n.units[1].hp,0);assert.equal(n.units[0].hp,100);assert.equal(n.status,'victory');assert.ok(n.log.some(t=>t.includes('bayoneta calada')));});
test('lance knockdown unhorses and requires standing before fighting again',()=>{const b=battle(1812);b.units[1].mounted=true;let n=actBattle(b,{type:'melee',unitId:'attacker',targetId:'defender'});assert.equal(n.units[1].knockedDown,true);assert.equal(n.units[1].stance,'prone');assert.equal(n.units[1].mounted,false);n=endTurn(n);assert.equal(n.units[1].knockedDown,false);assert.ok(n.log.some(t=>t.includes('se pone de pie')));});
test('routing drops a loaded weapon at the contact point and follows a clear escape path',()=>{const b=battle();b.units[1].morale=16;const n=actBattle(b,{type:'melee',unitId:'attacker',targetId:'defender'});const routed=n.units[1];assert.equal(routed.routed,true);assert.equal(routed.weaponDropped,true);assert.equal(routed.weapon,1800,'canonical inventory ID remains valid for old save readers');assert.equal(routed.loaded,0);assert.equal(routed.x,n.width-1);assert.ok(routed.fleePath.length>0);for(const p of routed.fleePath)assert.equal(n.tiles.find(t=>t.x===p.x&&t.y===p.y).blocked,false);assert.deepEqual(n.droppedWeapons[0],{unitId:'defender',x:2,y:1,weapon:1800,loaded:1,condition:100});});
test('blunderbuss cone can injure an ally and suppress several targets with one charge',()=>{const b=battle(1807);b.units[1].x=5;b.units.push({...b.units[0],id:'ally',x:4,y:1});const n=actBattle(b,{type:'fire',unitId:'attacker',targetId:'defender'});assert.equal(n.units[0].loaded,0);assert.ok(n.units[2].hp<100||n.units[2].morale<b.units[2].morale);assert.ok(n.units[1].morale<100);assert.ok(n.log.some(t=>t.includes('tres casillas')));});
