import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,actBattle,getReachable,actionCosts,ignitionRisk,shotChance} from '../game/tactical.js';
const tiles=()=>Array.from({length:80},(_,i)=>({x:i%10,y:Math.floor(i/10),type:'grass',blocked:false,cover:0}));
function battlefield(traits=[],extra={}){return createBattle([{id:1000,name:'Oficial del Cabildo',weapon:1800,x:1,y:1,horse:true,traits,...extra}],{width:10,height:8,tiles:tiles(),enemies:[{id:'enemy',x:7,y:1}],seed:45});}
test('cavalry doctrine saves enough AP to mount, advance and fight beyond ordinary budget',()=>{const normal=actBattle(battlefield(),{type:'mount',unitId:1000}),trained=actBattle(battlefield(['cavalry_commander']),{type:'mount',unitId:1000});assert.ok(trained.units[0].ap>normal.units[0].ap);const travel=b=>getReachable(b,'1000').find(t=>t.x===4&&t.y===1).cost;assert.ok(travel(trained)<travel(normal));assert.ok(actionCosts(trained,trained.units[0]).fire<actionCosts(normal,normal.units[0]).fire);assert.ok(actionCosts(trained,trained.units[0]).melee<actionCosts(normal,normal.units[0]).melee);});
test('guerrilla doctrine improves broken-ground endurance, concealment and ambush',()=>{const b=battlefield(['guerrilla_tactician'],{fatigue:60});b.tiles.find(t=>t.x===1&&t.y===1).type='forest';b.tiles.find(t=>t.x===2&&t.y===1).type='stone';const ordinary=structuredClone(b);ordinary.units[0].traits=[];assert.ok(getReachable(b,'1000').find(t=>t.x===2&&t.y===1).cost<getReachable(ordinary,'1000').find(t=>t.x===2&&t.y===1).cost);assert.ok(shotChance(b,b.units[0],b.units[1])>shotChance(ordinary,ordinary.units[0],ordinary.units[1]));assert.ok(shotChance(b,b.units[1],b.units[0])<shotChance(ordinary,ordinary.units[1],ordinary.units[0]));assert.ok(b.units[0].ap>battlefield([],{fatigue:60}).units[0].ap);});
test('gunsmith reloads within a tight budget, primes faster and reduces real rain failure risk',()=>{let b=battlefield(['gunsmith_artillerist'],{loaded:0});b.weather.rain=70;b.units[0].ap=40;assert.ok(ignitionRisk(b,b.units[0])<ignitionRisk(b,{...b.units[0],traits:[]}));b=actBattle(b,{type:'reload',unitId:1000});assert.equal(b.lastError,null);assert.equal(b.units[0].loaded,1);assert.equal(b.units[0].ammo,11);assert.equal(b.units[0].priming,49);b.units[0].jammed=true;b.units[0].ap=10;b=actBattle(b,{type:'reprime',unitId:1000});assert.equal(b.lastError,null);assert.equal(b.units[0].jammed,false);assert.equal(b.units[0].priming,48);assert.equal(b.units[0].loaded,1);});
test('line marksman can afford an aimed shot and loses less accuracy in powder smoke',()=>{const b=battlefield(['line_marksman']);b.smoke=[{x:4,y:1,radius:1,turns:3}];const u=b.units[0],ordinary={...u,traits:[]};assert.ok(actionCosts(b,u).aim<actionCosts(b,ordinary).aim);assert.ok(shotChance(b,u,b.units[1],2)>shotChance(b,ordinary,b.units[1],2));b.units[0].ap=20;const n=actBattle(b,{type:'fire',unitId:1000,targetId:'enemy',aim:2});assert.equal(n.lastError,null);assert.ok(n.units[0].ap>=0);const plain=structuredClone(b);plain.units[0].traits=[];assert.ok(actBattle(plain,{type:'fire',unitId:1000,targetId:'enemy',aim:2}).lastError);});
test('flint repair consumes limited stock and improves the actual ignition risk',()=>{const b=battlefield(['gunsmith_artillerist'],{condition:40});const before=ignitionRisk(b,b.units[0]);const n=actBattle(b,{type:'repair',unitId:1000});assert.equal(n.lastError,null);assert.equal(n.units[0].flints,3);assert.ok(n.units[0].condition>40);assert.ok(ignitionRisk(n,n.units[0])<before);assert.equal(n.units[0].loaded,b.units[0].loaded);n.units[0].flints=0;assert.ok(actBattle(n,{type:'repair',unitId:1000}).lastError);});
test('priming is finite and rations restore work capacity without granting free healing',()=>{let b=battlefield([],{fatigue:60});b.units[0].jammed=true;b.units[0].priming=0;assert.ok(actBattle(b,{type:'reprime',unitId:1000}).lastError);b.units[0].hp=50;b.units[0].bleeding=4;b.units[0].ap=30;const n=actBattle(b,{type:'ration',unitId:1000});assert.equal(n.lastError,null);assert.equal(n.units[0].rations,1);assert.equal(n.units[0].bleeding,0);assert.equal(n.units[0].hp,50);assert.ok(n.units[0].fatigue<60);assert.ok(n.units[0].ap>30);});
test('cavalry commander keeps an adjacent mounted ally from routing under fire',()=>{const make=traits=>createBattle([{id:'shot',x:1,y:1,marksmanship:100,weapon:1800}],{width:10,height:8,tiles:tiles(),enemies:[{id:'rider',x:4,y:1,mounted:true,morale:16},{id:1000,x:4,y:2,traits}],seed:45});const command=actBattle(make(['cavalry_commander']),{type:'fire',unitId:'shot',targetId:'rider'});assert.equal(command.units[1].routed,false);assert.ok(command.units[1].morale>=20);const ordinary=actBattle(make([]),{type:'fire',unitId:'shot',targetId:'rider'});assert.equal(ordinary.units[1].routed,true);});
