import test from 'node:test';import assert from 'node:assert/strict';
import {act} from '../web/node_modules/react/index.js';
import {mountCampaign} from './mounted-campaign-fixture.mjs';
import {supplyCareField} from './supply-transfer-fixture.mjs';

test('the production supply quantity control leaves a saved bundle and another selected soldier collects it under its previous owner',async t=>{
 const p=supplyCareField(),m=await mountCampaign(t,p);await m.click('Equipo y órdenes');const count=m.document.querySelector('[aria-label="Cantidad de suministros"]');Object.getOwnPropertyDescriptor(m.dom.window.HTMLInputElement.prototype,'value').set.call(count,'3');await act(async()=>count.dispatchEvent(new m.dom.window.Event('input',{bubbles:true})));const button=[...m.document.querySelectorAll('button')].find(b=>b.textContent.startsWith('Dejar suministros en el suelo'));assert.equal(button.disabled,false);await act(async()=>button.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));
 let s=m.read();const bundle=s.battle.groundItems.find(g=>g.id.startsWith('supply-'));assert.equal(bundle.type,'medkits');assert.equal(bundle.count,3);assert.equal(s.battle.units.find(u=>u.id==='110').medkits,1);assert.equal(button.disabled,true);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});
 await m.click('Listo');assert.ok(m.document.querySelector(`[data-ground-item="${bundle.id}"]`));const recipient=p.battle.units.find(u=>u.id==='111'),roster=[...m.document.querySelectorAll('.ja2-roster button')].find(b=>b.getAttribute('aria-label')?.includes(recipient.name));await act(async()=>roster.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));const loot=m.document.querySelector('[aria-label="Recoger equipo"]');await act(async()=>loot.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));const source=m.document.querySelector('[data-unit-id="110"]');await act(async()=>source.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));
 s=m.read();assert.equal(s.battle.groundItems.find(g=>g.id===bundle.id).count,0);assert.equal(s.battle.units.find(u=>u.id==='111').medkits,3);assert.equal(s.battle.units.find(u=>u.id==='110').medkits,1);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});assert.equal(m.document.querySelector(`[data-ground-item="${bundle.id}"]`),null);
});
