import test from 'node:test';import assert from 'node:assert/strict';
import {createBattle,actBattle} from '../game/tactical.js';
const tiles=()=>Array.from({length:80},(_,i)=>({x:i%10,y:Math.floor(i/10),type:'grass',blocked:false,cover:0}));
function battle(){return createBattle([{id:20,x:1,y:1,weapon:1808,marksmanship:100}],{width:10,height:8,tiles:tiles(),enemies:[{id:'victim',x:2,y:1,hp:10,weapon:1800,condition:63},{id:'other',x:5,y:1}],seed:45});}
const weapons=u=>Object.values(u.inventory).reduce((sum,r)=>sum+(typeof r==='object'&&r.weapon?r.count:0),u.weaponDropped?0:1);
const charges=u=>u.loaded+Object.values(u.inventory).reduce((sum,r)=>sum+(typeof r==='object'?r.count*(r.loaded||0):0),0);
test('a real killed opponent can be looted, its loaded musket equipped and fired',()=>{let s=battle();s=actBattle(s,{type:'fire',unitId:20,targetId:'victim'});assert.equal(s.units[1].hp,0);s=actBattle(s,{type:'loot',unitId:20,targetId:'victim',item:'weapon'});assert.equal(s.lastError,null);const key=Object.keys(s.units[0].inventory)[0];s=actBattle(s,{type:'equipLoot',unitId:20,inventoryKey:key});assert.equal(s.lastError,null);assert.equal(s.units[0].weapon,1800);assert.equal(s.units[0].condition,63);assert.equal(s.units[0].loaded,1);assert.equal(s.units[0].inventory[key].count,0);const before=s.units[0].loaded;s=actBattle(s,{type:'fire',unitId:20,targetId:'other'});assert.equal(s.lastError,null);assert.ok(s.units[0].loaded<before||s.units[0].jammed);});
test('repeated swaps conserve weapon instances and loaded charges including a jammed mechanism',()=>{let s=battle();s.units[0].inventory.found={count:1,weight:4,weapon:1800,loaded:1,condition:55,jammed:true};const count=weapons(s.units[0]),rounds=charges(s.units[0]);s=actBattle(s,{type:'equipLoot',unitId:20,inventoryKey:'found'});assert.equal(s.units[0].jammed,true);assert.equal(s.units[0].condition,55);assert.equal(weapons(s.units[0]),count);assert.equal(charges(s.units[0]),rounds);const displaced=Object.keys(s.units[0].inventory).find(k=>k.startsWith('swap:'));s=actBattle(s,{type:'equipLoot',unitId:20,inventoryKey:displaced});assert.equal(s.units[0].weapon,1808);assert.equal(weapons(s.units[0]),count);assert.equal(charges(s.units[0]),rounds);assert.ok(actBattle(s,{type:'equipLoot',unitId:20,inventoryKey:'found'}).lastError);});
test('ordinary supplies cannot impersonate equippable weapons and failed orders preserve the inventory',()=>{const s=battle();s.units[0].inventory.bolas={count:2,weight:.7,weapon:1820,loaded:0};const n=actBattle(s,{type:'equipLoot',unitId:20,inventoryKey:'bolas'});assert.ok(n.lastError);assert.deepEqual(n.units[0].inventory,s.units[0].inventory);});
