import test from 'node:test';
import assert from 'node:assert/strict';
import {initialCampaign} from './legacy-campaign-fixture.mjs';
import {dispatchCampaign,restoreCampaign,serializeCampaign,rosterFor} from '../game/campaign.js';
import {armoryInventory,resaleBreakdown,advanceMerchants,medicalSupplyStock,storeEquipment} from '../game/equipment.js';
import {enterSector} from '../game/world.js';
import {actBattle,createBattle,endTurn} from '../game/tactical.js';
import {encodeSave,decodeSave} from '../game/save.js';
import {scriptedBattleReport} from './scripted-battle-report.mjs';
const order=(s,a)=>{const n=dispatchCampaign(s,a);assert.equal(n.lastError,null,n.lastError);return n;};
const act=(b,a)=>{const n=actBattle(b,a);assert.equal(n.lastError,null,n.lastError);return n;};
const buy=(s,item,quantity=1)=>order(s,{type:'purchaseEquipment',item,quantity});
const equip=(s,id,item,slot='weapon',instanceId)=>order(s,{type:'equip',operativeId:id,itemId:item,slot,...(instanceId?{instanceId}:{})});
const report=(s,b)=>({type:s.pendingBattle.exploration?'leaveSector':'battleResult',battleId:s.pendingBattle.id,outcome:b.status,sectorState:b,survivors:b.units.filter(u=>u.side==='player')});
const reject=(s,a)=>{const n=dispatchCampaign(s,a);assert.ok(n.lastError);assert.deepEqual({...n,lastError:null},s);};
function armed(){let s=buy(initialCampaign(),1800);s=order(s,{type:'wait',hours:s.equipmentShipments[0].due-s.hour});s=equip(s,4,1800);s=buy(s,'1811:india_socket');return equip(s,4,'1811:india_socket','blade',s.armoryItems.find(i=>i.fittingPattern==='india_socket').id);}
function fitted(s){s=order(s,{type:'visitSector'});let b=enterSector(s.pendingBattle,s.sectorStates[s.pendingBattle.sector]);b=act(b,{type:'fitBayonet',unitId:'4',item:'blade'});return {s,b};}
// Boundary fixtures isolate campaign custody. Every fitting and departure
// below still uses its paid reducer order and exact snapshot report.
function flat(s,patches={}){const r=s.pendingBattle;return createBattle([...r.squad,...(r.garrison??[])].map((u,i)=>({...u,x:2+i,y:15,...patches[u.id]})),{...r,width:20,height:16,tiles:Array.from({length:320},(_,i)=>({x:i%20,y:Math.floor(i/20),type:'grass',cover:0,blocked:false})),props:[],npcs:r.npcs.map((npc,i)=>({...npc,x:16-i,y:12})),enemies:(r.enemies??[]).map((u,i)=>({...u,x:18,y:i,ap:0}))});}

test('matched purchase has its own finite stock and persistent identity without relabeling generic bayonets',()=>{
 let s=buy(initialCampaign(),1811);assert.equal(s.armoryItems[0].fittingPattern,undefined);s=buy(s,'1811:india_socket',6);assert.equal(s.merchants.retiro.stock['1811:india_socket'],0);assert.equal(s.merchants.retiro.stock[1811],5);assert.equal(s.armory[1811],1);assert.equal(s.armory['1811:india_socket'],6);const items=s.armoryItems.filter(i=>i.fittingPattern);assert.equal(new Set(items.map(i=>i.instanceId)).size,6);assert.deepEqual(items.map(i=>i.instanceId),Array.from({length:6},(_,i)=>`equipment-${i+1}`));assert.ok(items.every(i=>i.id!==i.instanceId));const stock=armoryInventory(s).filter(i=>i.item===1811);assert.deepEqual(stock.map(i=>i.quantity),[1,6]);reject(s,{type:'purchaseEquipment',item:'1811:india_socket'});assert.deepEqual(restoreCampaign(serializeCampaign(s)),s);
 const seed=s.seed;for(let i=0;i<24;i++)advanceMerchants(s,()=>true);assert.equal(s.merchants.retiro.stock['1811:india_socket'],1);assert.equal(s.nextEquipmentInstanceId,7);assert.equal(s.seed,seed);
});
test('strategic swaps and legal fit/remove keep one identified item and independent conditions across reports',()=>{
 let s=armed();const identity=s.operativeState[4].bladeInstanceId;s.operativeState[4].condition=43;s.operativeState[4].bladeCondition=67;s.operativeState[4].jammed=true;let b;({s,b}=fitted(s));const u=b.units.find(u=>u.id==='4');assert.equal(u.blade,undefined);assert.deepEqual(u.weaponFittings.bayonet,{weapon:1811,fittingPattern:'india_socket',instanceId:identity,condition:67});s=order(s,report(s,b));assert.equal(rosterFor(s).find(u=>u.id===4).blade,0);assert.equal(s.operativeState[4].weaponFittings.bayonet.instanceId,identity);
 s=equip(buy(s,1803),4,1803);const assembly=s.armoryItems.find(i=>i.item===1800);assert.equal(assembly.condition,43);assert.equal(assembly.jammed,true);assert.equal(assembly.fittings.bayonet.condition,67);assert.equal(assembly.fittings.bayonet.instanceId,identity);assert.deepEqual(s.operativeState[4].weaponFittings,{});s=equip(s,4,1800,'weapon',assembly.id);assert.equal(s.operativeState[4].weaponFittings.bayonet.instanceId,identity);s=restoreCampaign(serializeCampaign(s));s=order(s,{type:'visitSector'});b=enterSector(s.pendingBattle,s.sectorStates.retiro);b=act(b,{type:'removeBayonet',unitId:'4',destination:'blade'});s=order(s,report(s,b));assert.deepEqual(s.operativeState[4].weaponFittings,{});assert.equal(s.operativeState[4].bladeInstanceId,identity);assert.equal(s.operativeState[4].bladeCondition,67);assert.equal(s.operativeState[4].condition,43);assert.equal(s.operativeState[4].jammed,true);
});
test('assembly resale values both conditions and sells the whole assembly exactly once',()=>{
 let {s,b}=fitted(armed());s=order(s,report(s,b));s.operativeState[4].condition=50;s.operativeState[4].weaponFittings.bayonet.condition=25;s=equip(buy(s,1803),4,1803);const assembly=s.armoryItems.find(i=>i.item===1800),quote=resaleBreakdown(assembly);assert.deepEqual(quote.items.map(i=>i.price),[48,5]);assert.equal(quote.total,53);const cash=s.resources.treasury;s=order(s,{type:'sellEquipment',instanceId:assembly.id});assert.equal(s.resources.treasury,cash+53);assert.ok(!s.armoryItems.some(i=>i.id===assembly.id));assert.ok(!JSON.stringify(s.armoryItems).includes(assembly.fittings.bayonet.instanceId));reject(s,{type:'sellEquipment',instanceId:assembly.id});assert.deepEqual(restoreCampaign(serializeCampaign(s)),s);
});
test('a full report must explicitly include fitting state and ignores stale caller attachment overrides',()=>{
 let {s,b}=fitted(armed());for(const key of ['weaponFittings','weaponFittingPattern','bladeFittingPattern']){const a=report(s,structuredClone(b));delete a.sectorState.units.find(u=>u.id==='4')[key];reject(s,a);}b=act(b,{type:'removeBayonet',unitId:'4',destination:'blade'});const a=report(s,b);a.survivors=a.survivors.map(u=>({...u,weaponFittings:{bayonet:{weapon:1811,fittingPattern:'india_socket',instanceId:'fabricated',condition:100}}}));s=order(s,a);assert.deepEqual(s.operativeState[4].weaponFittings,{});assert.equal(s.operativeState[4].bladeFittingPattern,'india_socket');assert.deepEqual(restoreCampaign(serializeCampaign(s)),s);
});
test('dropping an assembly and taking it with another soldier preserves identity across live saves and re-entry',()=>{
 let s=armed();s=order(s,{type:'visitSector'});let b=flat(s,{3:{x:2,y:2},4:{x:3,y:2},10:{x:5,y:2}});b=act(b,{type:'fitBayonet',unitId:'4',item:'blade'});const identity=b.units.find(u=>u.id==='4').weaponFittings.bayonet.instanceId;b=act(b,{type:'drop',unitId:'4',item:'primary'});const ground=b.groundItems.find(g=>g.fittings?.bayonet);b=act(b,{type:'loot',unitId:'3',groundId:ground.id,count:1});const key=Object.keys(b.units.find(u=>u.id==='3').inventory).find(k=>b.units.find(u=>u.id==='3').inventory[k].fittings);b=act(b,{type:'equipLoot',unitId:'3',inventoryKey:key});s=order(s,{type:'syncTacticalTime',battleId:s.pendingBattle.id,elapsedSeconds:b.elapsedSeconds});b.syncedSeconds=b.elapsedSeconds;assert.equal(decodeSave(encodeSave(s,b)).battle.units.find(u=>u.id==='3').weaponFittings.bayonet.instanceId,identity);s=order(s,report(s,b));s=restoreCampaign(serializeCampaign(s));s=order(s,{type:'visitSector'});b=enterSector(s.pendingBattle,s.sectorStates.retiro);assert.equal(b.units.find(u=>u.id==='3').weaponFittings.bayonet.instanceId,identity);assert.deepEqual(b.units.find(u=>u.id==='4').weaponFittings,{});
});
test('capture keeps the fitted assembly inaccessible and recapture releases the same fitting',()=>{
 let {s,b}=fitted(armed());s=order(s,report(s,b));const fitting=structuredClone(s.operativeState[4].weaponFittings.bayonet);s=order(s,{type:'travel',sector:'buenos_aires'});s=order(s,{type:'attack',sector:'san_nicolas'});b=flat(s,{4:{hp:10,bandaged:74},10:{hp:0,bleeding:0,bandaged:0}});b=act(b,{type:'exit',unitIds:['3'],exitId:b.exits.find(e=>e.destination==='buenos_aires').id});assert.equal(b.status,'retreat');s=order(s,report(s,b));assert.equal(s.operativeState[4].captured,true);assert.deepEqual(s.operativeState[4].weaponFittings.bayonet,fitting);s=restoreCampaign(serializeCampaign(s));s=order(s,{type:'attack',sector:'san_nicolas'});s=order(s,scriptedBattleReport(s));assert.equal(s.operativeState[4].captured,false);assert.deepEqual(s.operativeState[4].weaponFittings.bayonet,fitting);assert.deepEqual(restoreCampaign(serializeCampaign(s)),s);
});
test('a departed soldier who dies leaves one fitted corpse at the destination and later loot changes ownership',()=>{
 let {s,b}=fitted(armed());s=order(s,report(s,b));s=order(s,{type:'travel',sector:'buenos_aires'});s=order(s,{type:'visitSector'});b=flat(s,{4:{x:9,y:0,hp:16,bleeding:3,bandaged:0}});const fitting=structuredClone(b.units.find(u=>u.id==='4').weaponFittings.bayonet);b=act(b,{type:'exit',unitIds:['4'],exitId:b.exits.find(e=>e.destination==='retiro').id});b=endTurn(b);assert.equal(b.units.find(u=>u.id==='4').hp,0);s=order(s,report(s,b));assert.deepEqual(s.sectorRemains.retiro[0].unit.weaponFittings.bayonet,fitting);s=restoreCampaign(serializeCampaign(s));s=order(s,{type:'travel',sector:'retiro'});s=order(s,{type:'visitSector'});b=enterSector(s.pendingBattle,s.sectorStates.retiro);b=act(b,{type:'loot',unitId:'3',targetId:'4',item:'weapon',count:1});const key=Object.keys(b.units.find(u=>u.id==='3').inventory).find(k=>b.units.find(u=>u.id==='3').inventory[k].fittings);b=act(b,{type:'equipLoot',unitId:'3',inventoryKey:key});s=order(s,report(s,b));assert.equal(s.operativeState[4].alive,false);assert.deepEqual(s.operativeState[3].weaponFittings.bayonet,fitting);assert.deepEqual(restoreCampaign(serializeCampaign(s)),s);s=order(s,{type:'visitSector'});b=enterSector(s.pendingBattle,s.sectorStates.retiro);assert.deepEqual(b.units.find(u=>u.id==='4').weaponFittings,{});assert.equal(b.units.find(u=>u.id==='3').weaponFittings.bayonet.instanceId,fitting.instanceId);
});
test('legacy saves retain unmarked bayonets and migrate stock once without granting matched equipment',()=>{
 const s=initialCampaign();delete s.fittingRulesVersion;delete s.nextEquipmentInstanceId;for(const r of Object.values(s.operativeState))for(const key of ['weaponFittings','weaponFittingPattern','bladeFittingPattern'])delete r[key];for(const merchant of Object.values(s.merchants)){delete merchant.supplies;delete merchant.stock['1811:india_socket'];}s.armory={1811:2};delete s.armoryItems;delete s.nextArmoryItemId;delete s.equipmentStorageVersion;delete s.clothingSupplyVersion;let next=restoreCampaign(serializeCampaign(s));assert.equal(next.armoryItems.length,2);assert.ok(next.armoryItems.every(i=>!i.fittingPattern&&!i.instanceId));assert.ok(Object.values(next.operativeState).every(r=>r.bladeFittingPattern===null&&!r.weaponFittings.bayonet));next=buy(next,'1811:india_socket');assert.equal(next.merchants.retiro.stock['1811:india_socket'],5);assert.deepEqual(restoreCampaign(serializeCampaign(next)),next);
});
test('malformed fitting ownership and identity sequence fail without treating deployment mirrors as duplicates',()=>{
 let {s,b}=fitted(armed());s=order(s,report(s,b));assert.deepEqual(restoreCampaign(serializeCampaign(s)),s);for(const edit of [n=>n.operativeState[3].weaponFittings=structuredClone(n.operativeState[4].weaponFittings),n=>n.operativeState[4].weaponFittings.bayonet.weapon=1813,n=>n.operativeState[4].weaponFittings.bayonet.loaded=1,n=>n.operativeState[4].weaponFittings.bayonet.condition=101,n=>n.nextEquipmentInstanceId=1,n=>delete n.operativeState[4].weaponFittings,n=>delete n.operativeState[4].weaponFittingPattern,n=>delete n.operativeState[4].bladeFittingPattern,n=>n.operativeState[4].weaponFittings=null,n=>n.operativeState[4].inventory={duplicate:{count:1,weight:.5,weapon:1811,loaded:0,condition:100,jammed:false,fittingPattern:'india_socket',instanceId:n.operativeState[4].weaponFittings.bayonet.instanceId}}]){const bad=structuredClone(s);edit(bad);assert.throws(()=>restoreCampaign(serializeCampaign(bad)),String(edit));}
});
test('medical purchases consume local finite stock and share the supplied daily merchant clock',()=>{
 let s=initialCampaign();const cash=s.resources.treasury;s=order(s,{type:'purchaseMedicalSupplies',operativeId:3,quantity:20});s=order(s,{type:'purchaseMedicalSupplies',operativeId:4,quantity:20});assert.equal(medicalSupplyStock(s),0);assert.equal(s.resources.treasury,cash-400);reject(s,{type:'purchaseMedicalSupplies',operativeId:10,quantity:1});s=restoreCampaign(serializeCampaign(s));assert.equal(medicalSupplyStock(s),0);s=order(s,{type:'wait',hours:23});assert.equal(medicalSupplyStock(s),0);s=order(s,{type:'wait',hours:1});assert.equal(medicalSupplyStock(s),5);assert.equal(medicalSupplyStock(s,'cordoba'),40);assert.equal(medicalSupplyStock(s,'ensenada'),0);const merchants=structuredClone(s.merchants);for(let i=0;i<24;i++)advanceMerchants(s,()=>false);assert.deepEqual(s.merchants,merchants);s=order(s,{type:'purchaseMedicalSupplies',operativeId:10,quantity:5});assert.equal(medicalSupplyStock(s),0);for(const edit of [n=>n.merchants.retiro.supplies.medkits=-1,n=>delete n.merchants.retiro.supplies,n=>n.merchants.retiro.supplies.medkits=41]){const bad=structuredClone(s);edit(bad);assert.throws(()=>restoreCampaign(serializeCampaign(bad)),String(edit));}
});

test('a timed firearm repair spends actual tools without repairing its attached bayonet',()=>{
 let {s,b}=fitted(armed());s=order(s,report(s,b));s.operativeState[4].condition=50;s.operativeState[4].weaponFittings.bayonet.condition=25;s=order(s,{type:'purchaseToolkits',operativeId:3});s=order(s,{type:'assignWork',operativeId:3,assignment:'repair',targetId:4});const points=s.operativeState[3].toolkitPoints;s=order(s,{type:'wait',hours:1});assert.ok(s.operativeState[4].condition>50);assert.ok(s.operativeState[3].toolkitPoints<points);assert.equal(s.operativeState[4].weaponFittings.bayonet.condition,25);assert.deepEqual(restoreCampaign(serializeCampaign(s)),s);
});
test('existing legacy identities reserve their numbers and a live save rejects a duplicate assembly in storage',()=>{
 let old=initialCampaign();delete old.fittingRulesVersion;delete old.nextEquipmentInstanceId;old.operativeState[3].weaponInstanceId='equipment-99';old=restoreCampaign(serializeCampaign(old));assert.equal(old.operativeState[3].weaponInstanceId,'equipment-99');assert.equal(old.nextEquipmentInstanceId,100);old=buy(old,'1811:india_socket');assert.equal(old.armoryItems[0].instanceId,'equipment-100');
 let {s,b}=fitted(armed());s=order(s,{type:'syncTacticalTime',battleId:s.pendingBattle.id,elapsedSeconds:b.elapsedSeconds});b.syncedSeconds=b.elapsedSeconds;assert.doesNotThrow(()=>decodeSave(encodeSave(s,b)));const bad=structuredClone(s);storeEquipment(bad,1800,{fittings:b.units.find(u=>u.id==='4').weaponFittings});assert.throws(()=>decodeSave(encodeSave(bad,b)));
 const poor=initialCampaign();poor.resources.treasury=49;reject(poor,{type:'purchaseEquipment',item:'1811:india_socket'});assert.equal(poor.nextEquipmentInstanceId,1);
});
test('an old active save gains empty fitting fields without a matched item or inferred fitting',()=>{
 const s=order(initialCampaign(),{type:'visitSector'}),b=enterSector(s.pendingBattle),raw=JSON.parse(encodeSave(s,b));delete raw.campaign.fittingRulesVersion;delete raw.campaign.nextEquipmentInstanceId;delete raw.campaign.pendingBattle.fittingRulesVersion;delete raw.battle.fittingRulesVersion;for(const r of [...Object.values(raw.campaign.operativeState),...raw.campaign.pendingBattle.squad,...raw.battle.units])for(const key of ['weaponFittings','weaponFittingPattern','bladeFittingPattern'])delete r[key];const loaded=decodeSave(JSON.stringify(raw));assert.equal(loaded.campaign.fittingRulesVersion,1);assert.equal(loaded.battle.fittingRulesVersion,1);assert.ok(loaded.battle.units.every(u=>u.bladeFittingPattern===null&&u.weaponFittingPattern===null&&!u.weaponFittings.bayonet));assert.equal(loaded.campaign.nextEquipmentInstanceId,1);assert.equal(loaded.battle.elapsedSeconds,0);assert.deepEqual(loaded.campaign.resources,s.resources);
});
