import {recoverFreshNorthernDoctor} from './fresh-northern-recovery.mjs';
import {tucumanCombatOrder} from './tucuman-driver.mjs';
import {dispatchCampaign} from '../game/campaign.js';
import {sanLorenzoCombatOrder} from './san-lorenzo-driver.mjs';
import {fightNorthernSector,northernCombatOrder,prepareNorthernSquad} from './northern-route.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {beginFreshCampaign,recoverFreshCapital,prepareFreshNorthernAssault,prepareFreshSanLorenzo,prepareFreshMissionSupport,prepareFreshCordobaAssault,recoverFreshCordobaSurvivors,prepareFreshCordobaDefense,prepareFreshTucumanAssault} from './fresh-campaign-route.mjs';

test('a Retiro-only campaign retains paid recovery and real losses through coordinated San Nicolás, San Lorenzo, Córdoba and Tucumán victories',()=>{
 const opening=beginFreshCampaign();
 assert.ok(opening.actions>0);assert.ok(opening.casualties.length>0);
 assert.equal(opening.campaign.officer,null);
 const original=structuredClone(opening.campaign),recovered=recoverFreshCapital(opening.campaign);
 assert.deepEqual(opening.campaign,original);
 assert.ok(recovered.campaign.hour>original.hour);
 assert.equal(recovered.campaign.squad.length,6);
 assert.ok(recovered.patients.length>0);
 for(const id of recovered.patients)assert.equal(recovered.campaign.operativeState[id].hp,recovered.campaign.operativeState[id].maxHp);
 for(const id of opening.casualties)assert.equal(recovered.campaign.operativeState[id].alive,false);
 for(const id of recovered.field){assert.ok(recovered.campaign.operativeState[id].alive);assert.ok(recovered.campaign.contracts[id].expiresAt>recovered.campaign.hour);}
 assert.ok(recovered.campaign.resources.treasury>=0);
 assert.equal(recovered.campaign.flags.academy,true);
 assert.deepEqual(Object.keys(recovered.campaign.sectors).filter(id=>recovered.campaign.sectors[id].owner==='patriot').sort(),['buenos_aires','retiro']);
 assert.equal(recovered.campaign.completed,false);
 const deployed=prepareFreshNorthernAssault(recovered);
 const result=fightNorthernSector(deployed,'san_nicolas',{controller:northernCombatOrder});
 assert.equal(result.campaign.sectors.san_nicolas.owner,'patriot');
 for(const id of opening.casualties)assert.equal(result.campaign.operativeState[id].alive,false);
 assert.equal(result.campaign.completed,false);
 const prior=structuredClone(result.campaign),prepared=prepareFreshSanLorenzo(result.campaign);
 assert.deepEqual(result.campaign,prior);
 assert.deepEqual(prepared.squad,[120,111,125,103,140,112]);
 const paid=prepared.squad.reduce((sum,id)=>sum+prepared.contracts[id].paid,0);
 assert.equal(prepared.resources.treasury,prior.resources.treasury-paid);
 assert.ok(prepared.operativeState[112].medkits>prior.operativeState[112].medkits);
 for(const [id,record]of Object.entries(prior.operativeState))if(!record.alive)assert.equal(prepared.operativeState[id].alive,false);
 assert.equal(prepared.flags.sanLorenzo,false);
 assert.equal(prepared.pendingBattle,null);
 assert.equal(prepared.completed,false);
 const supported=prepareFreshMissionSupport(prepared);
 const mission=dispatchCampaign(supported.campaign,{type:'attack',sector:'san_lorenzo',squadIds:supported.squads});
 assert.equal(mission.lastError,null);assert.equal(mission.pendingBattle.squad.length,12);
 const won=fightNorthernSector(mission,'san_lorenzo',{controller:sanLorenzoCombatOrder});
 assert.equal(won.campaign.flags.sanLorenzo,true);assert.equal(won.campaign.phase,2);
 assert.ok(won.campaign.missionAllies.san_lorenzo.hp>0);assert.equal(won.campaign.defeated,false);
 for(const [id,record]of Object.entries(prior.operativeState))if(!record.alive)assert.equal(won.campaign.operativeState[id].alive,false);
 assert.ok(won.campaign.resources.treasury>=0);assert.equal(won.campaign.completed,false);
 const north=prepareNorthernSquad(won.campaign);
 assert.ok(north.recovery.usedDressings>0);assert.ok(north.campaign.hour>won.campaign.hour);
 assert.equal(north.events.some(({action})=>action.type==='recruitCivic'&&action.id===112),false,'retain the surviving doctor contract');
 for(const id of north.recovery.patients)assert.equal(north.campaign.operativeState[id].hp,north.campaign.operativeState[id].maxHp);
 for(const [id,record]of Object.entries(won.campaign.operativeState))if(!record.alive)assert.equal(north.campaign.operativeState[id].alive,false);
 assert.ok(north.campaign.resources.treasury>=0);
 const cordoba=fightNorthernSector(prepareFreshCordobaAssault(north.campaign),'cordoba',{controller:northernCombatOrder});
 assert.equal(cordoba.campaign.sectors.cordoba.owner,'patriot');
 for(const [id,record]of Object.entries(north.campaign.operativeState))if(!record.alive)assert.equal(cordoba.campaign.operativeState[id].alive,false);
 assert.ok(cordoba.campaign.resources.treasury>=0);
 assert.equal(cordoba.campaign.completed,false);
 const healed=recoverFreshCordobaSurvivors(cordoba.campaign);
 assert.equal(healed.location,'retiro');
 assert.ok(healed.hour>cordoba.campaign.hour);
 for(const id of [111,125]){assert.equal(healed.operativeState[id].hp,healed.operativeState[id].maxHp);assert.equal(healed.operativeState[id].bleeding,0);}
 assert.ok(healed.contracts[139].paid>0);
 assert.ok(healed.resources.treasury>=0);
 const defense=fightNorthernSector(prepareFreshCordobaDefense(healed),'cordoba',{controller:northernCombatOrder});
 assert.equal(defense.campaign.sectors.cordoba.owner,'patriot');
 assert.equal(defense.campaign.pendingEncounter,null);
 const tucuman=fightNorthernSector(prepareFreshTucumanAssault(defense.campaign),'tucuman',{controller:tucumanCombatOrder});
 assert.equal(tucuman.campaign.sectors.tucuman.owner,'patriot');
 assert.ok(tucuman.campaign.resources.treasury>=0);
 assert.equal(tucuman.campaign.completed,false);
 const relief=recoverFreshNorthernDoctor(tucuman.campaign);
 assert.equal(relief.operativeState[122].hp,relief.operativeState[122].maxHp);
 assert.equal(relief.operativeState[122].bleeding,0);
 assert.ok(relief.recruited.includes(10)&&relief.recruited.includes(4)&&relief.recruited.includes(1000));
 assert.equal(relief.contracts[1000].paid,300);
 assert.ok(relief.hour>tucuman.campaign.hour);
 for(const [id,record]of Object.entries(tucuman.campaign.operativeState))if(!record.alive)assert.equal(relief.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(defense.campaign.operativeState))if(!record.alive)assert.equal(tucuman.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(healed.operativeState))if(!record.alive)assert.equal(defense.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(cordoba.campaign.operativeState))if(!record.alive)assert.equal(healed.operativeState[id].alive,false);
});
