import {holdBatteryOrder} from './holding-battery-driver.mjs';
import {prepareFreshTucumanRecapture,prepareFreshSaltaRecapture} from './fresh-northern-return-route.mjs';
import {batteryOrder} from './advancing-battery-driver.mjs';
import {prepareFreshCoastalCommand,prepareFreshEnsenadaAssault,recruitFreshNavalCommand,prepareFreshSantaFeAssault} from './fresh-coastal-route.mjs';
import {prepareFreshUspallataAssault,recoverFreshUspallata,prepareFreshLosPatosAssault,completeFreshAndesPreparation} from './fresh-mountain-route.mjs';
import {prepareFreshCuyoDefense,prepareFreshMendozaAssault,startFreshFoundry,prepareFreshArmyProduction,completeFreshArmyProduction} from './fresh-cuyo-route.mjs';
import {recoverFreshNorthernDoctor,reuniteFreshNorthernSquad,prepareFreshSaltaAssault,finishFreshNorthernCampaign} from './fresh-northern-recovery.mjs';
import {tucumanCombatOrder} from './tucuman-driver.mjs';
import {dispatchCampaign} from '../game/campaign.js';
import {sanLorenzoCombatOrder} from './san-lorenzo-driver.mjs';
import {fightNorthernSector,northernCombatOrder,prepareNorthernSquad} from './northern-route.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {beginFreshCampaign,recoverFreshCapital,prepareFreshNorthernAssault,prepareFreshSanLorenzo,prepareFreshMissionSupport,prepareFreshCordobaAssault,recoverFreshCordobaSurvivors,prepareFreshCordobaDefense,prepareFreshTucumanAssault} from './fresh-campaign-route.mjs';

test('a Retiro-only campaign retains paid recovery and real losses through coordinated San Nicolás, San Lorenzo, Córdoba, Tucumán and Salta victories through Yatasto, Mendoza production and both mountain passes, Ensenada, naval recruitment, Santa Fe, Tucumán and Salta recapture',()=>{
 const opening=beginFreshCampaign();
 assert.ok(opening.actions>0);assert.ok(opening.casualties.length>0);
 assert.equal(opening.campaign.officer,null);
 const original=structuredClone(opening.campaign),recovered=recoverFreshCapital(opening.campaign);
 assert.deepEqual(opening.campaign,original);
 assert.ok(recovered.campaign.hour>original.hour);
 assert.equal(recovered.campaign.squad.length,6);
 assert.ok(recovered.patients.length>0);
 for(const id of recovered.patients)assert.equal(recovered.campaign.operativeState[id].hp,recovered.campaign.operativeState[id].maxHp);
 for(const id of opening.casualties)assert.equal(recovered.campaign.operativeState[id].alive,false);
 for(const id of recovered.field){assert.ok(recovered.campaign.operativeState[id].alive);assert.ok(recovered.campaign.contracts[id].expiresAt>recovered.campaign.hour);}
 assert.ok(recovered.campaign.resources.treasury>=0);
 assert.equal(recovered.campaign.flags.academy,true);
 assert.deepEqual(Object.keys(recovered.campaign.sectors).filter(id=>recovered.campaign.sectors[id].owner==='patriot').sort(),['buenos_aires','retiro']);
 assert.equal(recovered.campaign.completed,false);
 const deployed=prepareFreshNorthernAssault(recovered);
 const result=fightNorthernSector(deployed,'san_nicolas',{controller:northernCombatOrder});
 assert.equal(result.campaign.sectors.san_nicolas.owner,'patriot');
 for(const id of opening.casualties)assert.equal(result.campaign.operativeState[id].alive,false);
 assert.equal(result.campaign.completed,false);
 const prior=structuredClone(result.campaign),prepared=prepareFreshSanLorenzo(result.campaign);
 assert.deepEqual(result.campaign,prior);
 assert.deepEqual(prepared.squad,[120,111,125,103,140,112]);
 const paid=prepared.squad.reduce((sum,id)=>sum+prepared.contracts[id].paid,0);
 assert.equal(prepared.resources.treasury,prior.resources.treasury-paid);
 assert.ok(prepared.operativeState[112].medkits>prior.operativeState[112].medkits);
 for(const [id,record]of Object.entries(prior.operativeState))if(!record.alive)assert.equal(prepared.operativeState[id].alive,false);
 assert.equal(prepared.flags.sanLorenzo,false);
 assert.equal(prepared.pendingBattle,null);
 assert.equal(prepared.completed,false);
 const supported=prepareFreshMissionSupport(prepared);
 const mission=dispatchCampaign(supported.campaign,{type:'attack',sector:'san_lorenzo',squadIds:supported.squads});
 assert.equal(mission.lastError,null);assert.equal(mission.pendingBattle.squad.length,12);
 const won=fightNorthernSector(mission,'san_lorenzo',{controller:sanLorenzoCombatOrder});
 assert.equal(won.campaign.flags.sanLorenzo,true);assert.equal(won.campaign.phase,2);
 assert.ok(won.campaign.missionAllies.san_lorenzo.hp>0);assert.equal(won.campaign.defeated,false);
 for(const [id,record]of Object.entries(prior.operativeState))if(!record.alive)assert.equal(won.campaign.operativeState[id].alive,false);
 assert.ok(won.campaign.resources.treasury>=0);assert.equal(won.campaign.completed,false);
 const north=prepareNorthernSquad(won.campaign);
 assert.ok(north.recovery.usedDressings>0);assert.ok(north.campaign.hour>won.campaign.hour);
 assert.equal(north.events.some(({action})=>action.type==='recruitCivic'&&action.id===112),false,'retain the surviving doctor contract');
 for(const id of north.recovery.patients)assert.equal(north.campaign.operativeState[id].hp,north.campaign.operativeState[id].maxHp);
 for(const [id,record]of Object.entries(won.campaign.operativeState))if(!record.alive)assert.equal(north.campaign.operativeState[id].alive,false);
 assert.ok(north.campaign.resources.treasury>=0);
 const cordoba=fightNorthernSector(prepareFreshCordobaAssault(north.campaign),'cordoba',{controller:northernCombatOrder});
 assert.equal(cordoba.campaign.sectors.cordoba.owner,'patriot');
 for(const [id,record]of Object.entries(north.campaign.operativeState))if(!record.alive)assert.equal(cordoba.campaign.operativeState[id].alive,false);
 assert.ok(cordoba.campaign.resources.treasury>=0);
 assert.equal(cordoba.campaign.completed,false);
 const healed=recoverFreshCordobaSurvivors(cordoba.campaign);
 assert.equal(healed.location,'retiro');
 assert.ok(healed.hour>cordoba.campaign.hour);
 for(const id of [111,125]){assert.equal(healed.operativeState[id].hp,healed.operativeState[id].maxHp);assert.equal(healed.operativeState[id].bleeding,0);}
 assert.ok(healed.contracts[139].paid>0);
 assert.ok(healed.resources.treasury>=0);
 const defense=fightNorthernSector(prepareFreshCordobaDefense(healed),'cordoba',{controller:northernCombatOrder});
 assert.equal(defense.campaign.sectors.cordoba.owner,'patriot');
 assert.equal(defense.campaign.pendingEncounter,null);
 const tucuman=fightNorthernSector(prepareFreshTucumanAssault(defense.campaign),'tucuman',{controller:tucumanCombatOrder});
 assert.equal(tucuman.campaign.sectors.tucuman.owner,'patriot');
 assert.ok(tucuman.campaign.resources.treasury>=0);
 assert.equal(tucuman.campaign.completed,false);
 const relief=recoverFreshNorthernDoctor(tucuman.campaign);
 assert.equal(relief.operativeState[122].hp,relief.operativeState[122].maxHp);
 assert.equal(relief.operativeState[122].bleeding,0);
 assert.ok(relief.recruited.includes(10)&&relief.recruited.includes(4)&&relief.recruited.includes(1000));
 assert.equal(relief.contracts[1000].paid,300);
 assert.ok(relief.hour>tucuman.campaign.hour);
 const reunited=reuniteFreshNorthernSquad(relief);
 assert.equal(reunited.location,'tucuman');
 assert.deepEqual(reunited.squad,[1000,10,4,122,1]);
 assert.deepEqual(reunited.squads.find(q=>q.name==='Apoyo de los oficiales').members,[9,11,126]);
 const salta=fightNorthernSector(prepareFreshSaltaAssault(reunited),'salta',{controller:tucumanCombatOrder});
 assert.equal(salta.campaign.sectors.salta.owner,'patriot');
 assert.equal(salta.campaign.completed,false);
 const yatasto=finishFreshNorthernCampaign(salta.campaign);
 assert.equal(yatasto.phase,3);assert.equal(yatasto.missions.yatasto.completed,true);
 assert.deepEqual(yatasto.squad,[1,0,8]);assert.equal(yatasto.completed,false);
 const defended=fightNorthernSector(prepareFreshCuyoDefense(yatasto),'cordoba',{controller:tucumanCombatOrder});
 assert.equal(defended.campaign.sectors.cordoba.owner,'patriot');
 assert.equal(defended.campaign.sectors.salta.owner,'royalist');
 assert.equal(defended.campaign.operativeState[0].alive,false);
 assert.equal(defended.campaign.operativeState[1].hp,defended.campaign.operativeState[1].maxHp);
 assert.equal(defended.campaign.completed,false);
 const mendoza=fightNorthernSector(prepareFreshMendozaAssault(defended.campaign),'mendoza',{controller:tucumanCombatOrder});
 assert.equal(mendoza.campaign.sectors.mendoza.owner,'patriot');
 const foundry=startFreshFoundry(mendoza.campaign);
 assert.equal(foundry.flags.foundry,true);assert.equal(foundry.flags.emancipation,true);
 assert.ok(foundry.recruited.includes(2)&&foundry.recruited.includes(7));
 assert.equal(foundry.phase,3);assert.equal(foundry.completed,false);
 const initialArmy=prepareFreshArmyProduction(foundry);
 const army=completeFreshArmyProduction(initialArmy);
 assert.equal(army.operativeState[8].hp,army.operativeState[8].maxHp);
 assert.equal(initialArmy.resources.infantry,200);assert.equal(initialArmy.resources.cannons,2);
 assert.equal(army.resources.infantry,3000);assert.equal(army.resources.cannons,3);
 assert.equal(army.phase,3);assert.equal(army.completed,false);
 const pass=fightNorthernSector(prepareFreshUspallataAssault(army),'uspallata',{controller:tucumanCombatOrder});
 assert.equal(pass.campaign.sectors.uspallata.owner,'patriot');
 assert.equal(pass.campaign.operativeState[8].hp,3);assert.equal(pass.campaign.operativeState[105].hp,3);
 const passRecovery=recoverFreshUspallata(pass.campaign);
 assert.equal(passRecovery.phase,3);assert.equal(passRecovery.completed,false);
 for(const id of [128,109,132,145,106])assert.equal(passRecovery.operativeState[id].alive,false);
 const patos=fightNorthernSector(prepareFreshLosPatosAssault(passRecovery),'los_patos',{controller:tucumanCombatOrder});
 assert.equal(patos.campaign.sectors.los_patos.owner,'patriot');
 const andes=completeFreshAndesPreparation(patos.campaign);
 const coastal=prepareFreshCoastalCommand(andes);assert.equal(coastal.location,'retiro');assert.ok(coastal.squad.includes(3));
 const port=fightNorthernSector(prepareFreshEnsenadaAssault(coastal),'ensenada',{controller:tucumanCombatOrder});
 assert.equal(port.campaign.sectors.ensenada.owner,'patriot');
 const navy=recruitFreshNavalCommand(port.campaign);assert.equal(navy.completed,false);
 const santaFe=fightNorthernSector(prepareFreshSantaFeAssault(navy),'santa_fe',{controller:tucumanCombatOrder,report:r=>console.log(JSON.stringify(r))});
 assert.equal(santaFe.campaign.sectors.santa_fe.owner,'patriot');assert.ok(santaFe.campaign.operativeState[57].alive);
 assert.equal(santaFe.campaign.completed,false);
 const recaptured=fightNorthernSector(prepareFreshTucumanRecapture(santaFe.campaign),'tucuman',{controller:batteryOrder,report:r=>console.log(JSON.stringify(r))});
 assert.equal(recaptured.campaign.sectors.tucuman.owner,'patriot');assert.equal(recaptured.campaign.defeated,false);
 for(const id of [57,6])assert.ok(recaptured.campaign.operativeState[id].alive);
 const returnedSalta=fightNorthernSector(prepareFreshSaltaRecapture(recaptured.campaign),'salta',{controller:holdBatteryOrder,report:r=>console.log(JSON.stringify(r))});
 assert.equal(returnedSalta.campaign.sectors.salta.owner,'patriot');
 assert.equal(returnedSalta.campaign.defeated,false);assert.equal(returnedSalta.campaign.completed,false);
 assert.equal(returnedSalta.campaign.operativeState[57].alive,true);
 assert.equal(returnedSalta.campaign.operativeState[6].alive,false);
 assert.equal(Object.values(returnedSalta.campaign.operativeState).filter(u=>!u.alive).length,61);
 for(const [id,record]of Object.entries(recaptured.campaign.operativeState))if(!record.alive)assert.equal(returnedSalta.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(santaFe.campaign.operativeState))if(!record.alive)assert.equal(recaptured.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(navy.operativeState))if(!record.alive)assert.equal(santaFe.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(andes.operativeState))if(!record.alive)assert.equal(navy.operativeState[id].alive,false);
 assert.equal(andes.phase,4);assert.ok(andes.recruited.includes(57));assert.equal(andes.completed,false);
 assert.ok(['mendoza','uspallata','los_patos'].every(id=>andes.sectors[id].owner==='patriot'&&andes.sectors[id].fort>=1));
 for(const id of [7,8,147,143,135])assert.equal(andes.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(passRecovery.operativeState))if(!record.alive)assert.equal(andes.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(army.operativeState))if(!record.alive)assert.equal(passRecovery.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(foundry.operativeState))if(!record.alive)assert.equal(army.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(defended.campaign.operativeState))if(!record.alive)assert.equal(foundry.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(yatasto.operativeState))if(!record.alive)assert.equal(defended.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(salta.campaign.operativeState))if(!record.alive)assert.equal(yatasto.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(reunited.operativeState))if(!record.alive)assert.equal(salta.campaign.operativeState[id].alive,false);
 assert.equal(reunited.flags.partisanSupply,true);
 assert.equal(reunited.resources.muskets,relief.resources.muskets-50);
 for(const id of reunited.squad)assert.equal(reunited.operativeState[id].location,'tucuman');
 for(const [id,record]of Object.entries(relief.operativeState))if(!record.alive)assert.equal(reunited.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(tucuman.campaign.operativeState))if(!record.alive)assert.equal(relief.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(defense.campaign.operativeState))if(!record.alive)assert.equal(tucuman.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(healed.operativeState))if(!record.alive)assert.equal(defense.campaign.operativeState[id].alive,false);
 for(const [id,record]of Object.entries(cordoba.campaign.operativeState))if(!record.alive)assert.equal(healed.operativeState[id].alive,false);
});
