import {selectPocket,usePocket} from './pocket-render-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {act} from '../web/node_modules/react/index.js';
import {mountCampaign} from './mounted-campaign-fixture.mjs';
import {secondaryLootField} from './secondary-loot-fixture.mjs';
import {weaponRecord} from '../game/weapon-definition.js';
import {weaponFor} from '../game/tactical.js';
import {playerKnownBattle,playerKnownCampaign} from '../game/player-known-state.js';
const savedMatchesView=m=>{const s=m.saved(),v=m.read();assert.deepEqual(playerKnownBattle(s.battle),v.battle);assert.deepEqual(playerKnownCampaign(s.campaign),v.campaign);return s;};

test('the normal hand and recipient controls deliver the selected loaded gun and save the empty source and equipped recipient',async t=>{
 const p=secondaryLootField({companion:true}),record=weaponRecord(p.battle.units.find(u=>u.id==='110')),m=await mountCampaign(t,p);await m.click('Equipo');await usePocket(m,record.contentWeapon.name);
 const select=m.document.querySelector('[aria-label="Aliado que recibe el equipo"]'),button=[...m.document.querySelectorAll('button')].find(b=>b.textContent.match(/^(Dar o arrojar|Dar al aliado|Arrojar al aliado|Pasar por aliados)/));assert.equal(button.disabled,true);await act(async()=>{select.value='111';select.dispatchEvent(new m.dom.window.Event('change',{bubbles:true}));});assert.equal(button.disabled,false);await act(async()=>button.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));
 let s=savedMatchesView(m);assert.equal(weaponFor(s.battle.units.find(u=>u.id==='110')).id,0);assert.equal(s.battle.units.find(u=>u.id==='110').loaded,0);assert.deepEqual(Object.values(s.battle.units.find(u=>u.id==='111').inventory).filter(item=>item.weapon),[record]);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});assert.equal(button.disabled,true);
 await m.click('Listo');const recipient=p.battle.units.find(u=>u.id==='111'),roster=[...m.document.querySelectorAll('.ja2-roster button')].find(b=>b.getAttribute('aria-label')?.includes(recipient.name));await act(async()=>roster.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));await m.click('Equipo');const row=await selectPocket(m,record.contentWeapon.name);assert.ok(row);assert.equal([...m.document.querySelectorAll('.ja2-pocket')].find(e=>e.textContent.includes(record.contentWeapon.name)).querySelector('img').getAttribute('src'),record.contentWeapon.art);const equip=[...row.querySelectorAll('button')].find(b=>b.textContent.startsWith('Equipar principal'));await act(async()=>equip.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));s=savedMatchesView(m);assert.deepEqual(weaponRecord(s.battle.units.find(u=>u.id==='111')),record);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});
});
test('the held-weapon handover control shows an unreachable recipient and the registered order cannot bypass it',async t=>{
 const p=secondaryLootField({companion:true});p.battle.units.find(u=>u.id==='111').x=19;const m=await mountCampaign(t,p);await m.click('Equipo');await usePocket(m,weaponRecord(p.battle.units.find(u=>u.id==='110')).contentWeapon.name);const select=m.document.querySelector('[aria-label="Aliado que recibe el equipo"]');await act(async()=>{select.value='111';select.dispatchEvent(new m.dom.window.Event('change',{bubbles:true}));});const button=[...m.document.querySelectorAll('button')].find(b=>b.textContent.match(/^(Dar o arrojar|Dar al aliado|Arrojar al aliado|Pasar por aliados)/));assert.equal(button.disabled,true);assert.match(m.document.querySelector('.ja2-item-feedback').textContent,/al lado|adyacente|acerca|alcance|lejos|distancia/i);const before=m.read();await act(async()=>assert.throws(()=>m.issue({type:'transfer',unitId:'110',targetId:'111',slot:'blade'}),/al lado|adyacente|acerca|alcance|lejos|distancia/i));assert.deepEqual(m.read().battle.units,before.battle.units);
});
