import test from 'node:test';import assert from 'node:assert/strict';
import {actBattle,createBattle,carriedWeight,weaponTransferPreview,weaponFor} from '../game/tactical.js';
import {weaponRecord} from '../game/weapon-definition.js';
import {validateBattleSnapshot} from '../game/validate-battle.js';
import {enterSector} from '../game/world.js';
import {order,saved} from './local-contract-fixture.mjs';
import {secondaryLootField,secondaryOrder} from './secondary-loot-fixture.mjs';
const unit=(p,id='110')=>p.battle.units.find(u=>u.id===id);
const weight=b=>b.units.reduce((sum,u)=>sum+carriedWeight(u),0);
const physical=b=>({units:b.units,drops:b.droppedWeapons,ground:b.groundItems,seed:b.seed,elapsed:b.elapsedSeconds});

test('an actual paid soldier hands over the loaded issued primary once and the recipient equips the same saved gun after return',()=>{
 let p=secondaryLootField({companion:true});p=secondaryOrder(p,{type:'weapon',slot:'primary'});const record=weaponRecord(unit(p)),mass=weight(p.battle),ap=unit(p).ap,receiverAP=unit(p,'111').ap,ammo=unit(p).ammo;
 p=secondaryOrder(p,{type:'transfer',targetId:'111',slot:'primary'});assert.equal(unit(p).weaponDropped,true);assert.equal(unit(p).loaded,0);assert.equal(unit(p).ammo,ammo);assert.equal(unit(p).activeSlot,'unarmed');assert.equal(unit(p).ap,ap-4);assert.equal(unit(p,'111').ap,receiverAP);assert.deepEqual(Object.values(unit(p,'111').inventory),[record]);assert.ok(Math.abs(weight(p.battle)-mass)<1e-9);assert.deepEqual(p.battle.droppedWeapons,[]);
 const repeated=actBattle(p.battle,{type:'transfer',unitId:'110',targetId:'111',slot:'primary'});assert.ok(repeated.lastError);assert.deepEqual(physical(repeated),physical(p.battle));p={...saved(p),target:p.target};
 let c=order(p.campaign,{type:'battleResult',battleId:p.campaign.pendingBattle.id,outcome:'retreat',sectorState:p.battle,survivors:p.battle.units.filter(u=>u.side==='player')});c=order(saved({campaign:c}).campaign,{type:'attack',sector:'buenos_aires'});p={campaign:c,battle:enterSector(c.pendingBattle,c.sectorStates.buenos_aires)};assert.equal(unit(p).weapon,0);assert.deepEqual(Object.values(unit(p,'111').inventory),[record]);const previous=weaponRecord(unit(p,'111')),key=Object.keys(unit(p,'111').inventory)[0];p=secondaryOrder(p,{type:'equipLoot',unitId:'111',inventoryKey:key});assert.deepEqual(weaponRecord(unit(p,'111')),record);assert.ok(Object.values(unit(p,'111').inventory).some(r=>r.count===1&&r.weapon===previous.weapon&&r.loaded===previous.loaded));assert.ok(saved(p));
});
test('the selected authored secondary transfers its own wear and image while the giver keeps the primary',()=>{
 let p=secondaryLootField({companion:true});unit(p).bladeCondition=37;p={...saved(p),target:p.target};const record=weaponRecord(unit(p),'blade'),gun=weaponRecord(unit(p));p=secondaryOrder(p,{type:'transfer',targetId:'111',slot:'blade'});assert.equal(unit(p).blade,0);assert.equal(unit(p).bladeMetadata,undefined);assert.equal(unit(p).bladeCondition,undefined);assert.equal(unit(p).activeSlot,'unarmed');assert.equal(weaponFor(unit(p)).id,0);assert.deepEqual(weaponRecord(unit(p)),gun);p={...saved(p),target:p.target};assert.deepEqual(Object.values(unit(p,'111').inventory),[record]);p=secondaryOrder(p,{type:'equipLoot',unitId:'111',slot:'blade',inventoryKey:Object.keys(unit(p,'111').inventory)[0]});assert.deepEqual(weaponRecord(unit(p,'111'),'blade'),record);assert.ok(saved(p));
});
test('an inactive primary preserves declared partial loading, jam and wear while the other hand stays usable',()=>{
 let p=secondaryLootField({companion:true});Object.assign(unit(p),{loaded:0,reloadProgress:.4,condition:37,jammed:true,braced:true});p={...saved(p),target:p.target};const record=weaponRecord(unit(p)),blade=weaponRecord(unit(p),'blade');p=secondaryOrder(p,{type:'transfer',targetId:'111',slot:'primary'});assert.equal(unit(p).activeSlot,'blade');assert.equal(unit(p).braced,false);assert.equal(unit(p).weaponReady,undefined);assert.equal(unit(p).reloadProgress,undefined);assert.deepEqual(weaponRecord(unit(p),'blade'),blade);p={...saved(p),target:p.target};assert.deepEqual(Object.values(unit(p,'111').inventory),[record]);p=secondaryOrder(p,{type:'equipLoot',unitId:'111',inventoryKey:Object.keys(unit(p,'111').inventory)[0]});assert.deepEqual(weaponRecord(unit(p,'111')),record);assert.ok(saved(p));
});
function prepared(exploration=false){return createBattle([{id:'sender',x:1,y:1,weapon:1800,blade:1809,activeSlot:'blade'},{id:'receiver',x:2,y:1}],{width:8,height:8,exploration,enemies:exploration?[]:[{id:'guard',x:7,y:7,patrol:false}]});}
const send=(b,action={})=>actBattle(b,{type:'transfer',unitId:'sender',targetId:'receiver',slot:'blade',...action});
test('a legacy held blade moves with real weight in one exploration second and cannot overwrite an earlier received piece',()=>{
 let b=prepared(true);b.units[0].ap=0;b.units[1].ap=0;const other={count:1,weight:4,weapon:1800,loaded:1,condition:12,jammed:true};b.units[1].inventory['transfer:sender:held:blade']=other;const seconds=b.elapsedSeconds,mass=weight(b),record=weaponRecord(b.units[0],'blade');b=send(b);assert.equal(b.lastError,null);assert.equal(b.elapsedSeconds,seconds+1);assert.equal(b.units[0].ap,0);assert.equal(b.units[1].ap,0);assert.equal(b.units[0].blade,0);assert.deepEqual(b.units[1].inventory['transfer:sender:held:blade'],other);assert.deepEqual(b.units[1].inventory['transfer:sender:held:blade:1'],record);assert.ok(Math.abs(weight(b)-mass)<1e-9);assert.ok(validateBattleSnapshot(b));
});
test('changed hand, companion, geometry or AP conditions reject held transfers before costs or custody change',()=>{
 for(const [change,action]of [[()=>{},{slot:'unarmed'}],[()=>{},{slot:'unknown'}],[()=>{},{inventoryKey:'spare'}],[b=>b.units[0].blade=0,{}],[b=>{b.units[0].weaponDropped=true;b.units[0].loaded=0;},{slot:'primary'}],[b=>b.units[0].ap=3,{}],[b=>b.units[1].x=5,{}],[b=>b.units[1].entangled=true,{}],[b=>b.tiles.find(t=>t.x===2&&t.y===1).blocked=true,{}],[()=>{},{targetId:'sender'}],[()=>{},{unitId:'guard'}]]){const b=prepared();change(b);const before=structuredClone(b),a={slot:'blade',...action};assert.ok(weaponTransferPreview(b,b.units.find(u=>u.id===(a.unitId||'sender')),b.units.find(u=>u.id===(a.targetId||'receiver')),a.inventoryKey,a.slot).reason);assert.deepEqual(b,before);const n=send(b,action);assert.ok(n.lastError);assert.deepEqual(physical(n),physical(b));}
});
