import {totalReserveAmmunition} from '../game/ammunition-types.js';
import {syncBattleTime} from '../game/time.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {createBattle,actBattle,mainItemPreview,carriedWeight,hasFirearm,weaponFor} from '../game/tactical.js';import {handLayout} from '../game/hand-layout.js';import {inventoryUsage,equipmentFingerprint,transferItemQuantity} from '../game/tactical-inventory.js';import {handSlots,targetingHelp,orderDescriptors} from '../game/ja2-hud.js';import {validateBattleSnapshot} from '../game/validate-battle.js';
import {initialCampaign,dispatchCampaign} from '../game/campaign.js';import {enterSector} from '../game/world.js';import {encodeSave,decodeSave} from '../game/save.js';import {playerKnownBattle,playerKnownCampaign} from '../game/player-known-state.js';
const object={count:1,weight:.3,condition:44,instanceId:'keepsake',name:'Recuerdo'};
const field=(u={},opts={})=>createBattle([{id:'p',name:'Vigía',x:2,y:2,weapon:1805,loaded:1,ammo:8,blade:1813,inventory:{keepsake:object},...u}],{width:10,height:8,seed:127,tiles:Array.from({length:80},(_,i)=>({x:i%10,y:Math.floor(i/10),type:'grass',cover:0,blocked:false})),enemies:[{id:'e',x:3,y:2,patrol:false,overwatch:false}],...opts});
const order=(b,a)=>{const n=actBattle(b,{unitId:'p',...a});assert.equal(n.lastError,null,n.lastError);assert.doesNotThrow(()=>validateBattleSnapshot(n));return n;};
const hold=(b,item='inventory:keepsake')=>order(b,{type:'weapon',slot:'item',item});
const reject=(b,a)=>{const n=actBattle(b,{unitId:'p',...a});assert.ok(n.lastError);assert.deepEqual(n.units,b.units);assert.equal(n.seed,b.seed);assert.equal(n.elapsedSeconds,b.elapsedSeconds);};
const step=(c,a)=>{const n=dispatchCampaign(c,a);assert.equal(n.lastError,null,n.lastError);return n;};
test('an ordinary object uses one real main hand, frees its pocket and preserves the other hand',()=>{
 let b=field(),w=carriedWeight(b.units[0]);b=hold(b);let u=b.units[0];assert.equal(u.ap,96);assert.equal(handLayout(u).right,'inventory:keepsake');assert.equal(handLayout(u).left,'blade');assert.equal(carriedWeight(u),w);assert.equal(u.inventory.keepsake.condition,44);assert.equal(inventoryUsage(u).items.some(i=>i.item==='inventory:keepsake'),false);assert.equal(hasFirearm(u),false);assert.equal(weaponFor(u).damage,0);assert.match(targetingHelp('useItem',u),/Objeto en mano/);assert.equal(orderDescriptors(b,u).find(o=>o.id==='useItem').disabled,true);
 for(const type of ['useItem','melee','charge','fire'])reject(b,{type,targetId:'e'});b=order(b,{type:'weapon',slot:'primary'});assert.equal(b.units[0].activeItem,undefined);assert.equal(b.units[0].loaded,1);
});
test('dragging an ordinary object between hands and back to a pocket preserves identity',()=>{
 let b=field();b=order(b,{type:'equipLoot',slot:'offhandItem',inventoryKey:'inventory:keepsake'});const action=handSlots(b,b.units[0])[1].action;assert.deepEqual(action,{type:'weapon',slot:'item',item:'inventory:keepsake'});b=order(b,action);assert.equal(b.units[0].leftHandItem,null);
 const move=(from,to)=>{b=order(b,{type:'moveEquipment',sourceId:from,destinationId:to,expectedSource:equipmentFingerprint(b.units[0],from),expectedDestination:equipmentFingerprint(b.units[0],to)});};move('hand:right','hand:left');assert.equal(b.units[0].activeItem,undefined);move('hand:left','hand:right');move('hand:right','large-4');assert.equal(b.units[0].activeItem,undefined);assert.equal(inventoryUsage(b.units[0]).slots.find(s=>s.id==='large-4').entry.item,'inventory:keepsake');assert.equal(b.units[0].inventory.keepsake.instanceId,'keepsake');
});
test('dropping or passing the last held object clears its reference without losing the other weapon',()=>{
 let b=hold(field());b=order(b,{type:'drop',item:'inventory:keepsake'});assert.equal(b.units[0].activeItem,undefined);assert.equal(b.units[0].activeSlot,'blade');assert.equal(b.groundItems[0].instanceId,'keepsake');
 b=hold(field({leftHandItem:'medkits',medkits:1}));b=order(b,{type:'drop',item:'inventory:keepsake'});assert.equal(handLayout(b.units[0]).left,'medkits');
 b=hold(field({leftHandItem:'blade'}));const moved=transferItemQuantity(b.units[0],{id:'q',weapon:0,inventory:{}},'inventory:keepsake');assert.equal(moved.source.activeItem,undefined);assert.equal(handLayout(moved.source).right,'blade');assert.equal(moved.source.leftHandItem,null);assert.equal(moved.target.inventory.keepsake.instanceId,'keepsake');
});
test('loose cartridges occupy one main-hand unit and dropping the last clears the hand',()=>{let b=hold(field({ammo:2}),'inventory:ammo:pistol_69');assert.equal(inventoryUsage(b.units[0]).items.find(i=>i.item==='inventory:ammo:pistol_69').count,1);b=order(b,{type:'drop',item:'inventory:ammo:pistol_69',count:1});assert.equal(handLayout(b.units[0]).right,'inventory:ammo:pistol_69');b=order(b,{type:'drop',item:'inventory:ammo:pistol_69',count:1});assert.equal(b.units[0].activeItem,undefined);});
test('unknown, weapon, usable-item and empty references reject; insufficient AP and full pockets are atomic',()=>{
 const b=field({inventory:{keepsake:object,gun:{weapon:1800,count:1,weight:4,condition:100}}});for(const item of ['keepsake','primary','inventory:gun','inventory:missing','medkits','rations']){assert.equal(mainItemPreview(b,b.units[0],item).valid,false);reject(b,{type:'weapon',slot:'item',item});}
 const full=field({weapon:1800,blade:0,ammo:140,priming:0,flints:0,rations:0,medkits:0,boleadoras:0,torches:0,inventory:{keepsake:object,coats:{kind:'outfit',outfit:'poncho',count:4,weight:2,condition:100}}});assert.equal(inventoryUsage(full.units[0]).overloaded,false);reject(full,{type:'weapon',slot:'item',item:'inventory:keepsake'});
 const low=field();low.units[0].ap=3;reject(low,{type:'weapon',slot:'item',item:'inventory:keepsake'});
 const invalid=field();invalid.units[0].activeItem='inventory:keepsake';assert.throws(()=>validateBattleSnapshot(invalid));invalid.units[0].activeSlot='item';invalid.units[0].activeItem='inventory:missing';assert.throws(()=>validateBattleSnapshot(invalid));
});
test('ordinary held items survive a real campaign return, synchronized save and reentry',()=>{
 let c=step(initialCampaign(8),{type:'createOfficer',name:'Testigo',answers:{origin:'cabildo',doctrine:'line_marksman',crisis:'rally'}});c=step(c,{type:'visitSector'});let b=enterSector(c.pendingBattle);b=actBattle(b,{type:'weapon',unitId:'1000',slot:'item',item:'flints'});assert.equal(b.lastError,null);assert.equal(playerKnownBattle(b).units.find(u=>u.id==='1000').activeItem,'flints');({campaign:c,battle:b}=syncBattleTime(c,b));({campaign:c,battle:b}=decodeSave(encodeSave(c,b)));assert.equal(b.units.find(u=>u.id==='1000').activeItem,'flints');
 c=step(c,{type:'leaveSector',battleId:c.pendingBattle.id,sectorState:b,survivors:b.units.filter(u=>u.side==='player')});assert.equal(c.operativeState[1000].activeItem,'flints');assert.equal(playerKnownCampaign(c).operatives.find(u=>u.id===1000).activeItem,'flints');c=decodeSave(encodeSave(c)).campaign;c=step(c,{type:'visitSector'});b=enterSector(c.pendingBattle,c.sectorStates.retiro);assert.equal(handLayout(b.units.find(u=>u.id==='1000')).right,'flints');assert.deepEqual(decodeSave(encodeSave(c,b)).battle,b);
});

test('stowing the main object preserves an explicit blade in the other hand through campaign save',()=>{let c=step(initialCampaign(8),{type:'createOfficer',name:'Testigo',answers:{origin:'cabildo',doctrine:'line_marksman',crisis:'rally'}});c=step(c,{type:'visitSector'});let b=enterSector(c.pendingBattle);b=actBattle(b,{type:'weapon',unitId:'1000',slot:'item',item:'flints'});assert.equal(b.lastError,null);const u=b.units.find(u=>u.id==='1000');assert.equal(handLayout(u).left,'blade');b=actBattle(b,{type:'moveEquipment',unitId:'1000',sourceId:'hand:right',destinationId:'large-4',expectedSource:equipmentFingerprint(u,'hand:right'),expectedDestination:equipmentFingerprint(u,'large-4')});assert.equal(b.lastError,null);assert.equal(b.units.find(u=>u.id==='1000').leftHandItem,'blade');c=step(c,{type:'leaveSector',battleId:c.pendingBattle.id,sectorState:b,survivors:b.units.filter(u=>u.side==='player')});c=decodeSave(encodeSave(c)).campaign;assert.equal(c.operativeState[1000].leftHandItem,'blade');});

test('a held cartridge and its reserve remain personal through return and reentry without a duplicate stock credit',()=>{
 let c=step(initialCampaign(8),{type:'createOfficer',name:'Testigo',answers:{origin:'cabildo',doctrine:'line_marksman',crisis:'rally'}});c=step(c,{type:'visitSector'});let b=enterSector(c.pendingBattle);
 const stock=structuredClone(c.resources),u=b.units.find(u=>u.id==='1000'),item='inventory:'+Object.keys(u.inventory).find(key=>u.inventory[key].kind==='ammunition'),loose=totalReserveAmmunition(u);assert.ok(loose>0);
 b=actBattle(b,{type:'weapon',unitId:'1000',slot:'item',item});assert.equal(b.lastError,null);
 c=step(c,{type:'leaveSector',battleId:c.pendingBattle.id,sectorState:b,survivors:b.units.filter(u=>u.side==='player')});assert.deepEqual(c.resources,stock);assert.equal(totalReserveAmmunition(c.operativeState[1000]),loose);assert.equal(c.operativeState[1000].carriedAmmo-c.operativeState[1000].carriedLoaded,loose);
 c=decodeSave(encodeSave(c)).campaign;c=step(c,{type:'visitSector'});b=enterSector(c.pendingBattle,c.sectorStates.retiro);assert.equal(handLayout(b.units.find(u=>u.id==='1000')).right,item);assert.deepEqual(decodeSave(encodeSave(c,b)).battle,b);
});
