import test from 'node:test';import assert from 'node:assert/strict';
import {initialCampaign,dispatchCampaign as reduce,restoreCampaign,serializeCampaign} from '../game/campaign.js';
import {enterSector} from '../game/world.js';import {createBattle,actBattle,endTurn} from '../game/tactical.js';import {attendYatasto} from './mission-helpers.mjs';
const step=(s,a)=>{const n=reduce(s,a);assert.equal(n.lastError,null,n.lastError);return n;};
const officer=()=>step(initialCampaign(),{type:'createOfficer',name:'Isabel del Norte',answers:{origin:'cabildo',doctrine:'line_marksman',crisis:'rally'}});
function northernCampaign(){const s=officer();s.phase=2;s.flags.sanLorenzo=true;s.flags.northPact=true;for(const id of ['cordoba','tucuman','salta'])s.sectors[id].owner='patriot';return s;}
test('Yatasto requires physical reports and decision and persists separately from Tucumán',()=>{
 let s=northernCampaign();assert.ok(reduce(s,{type:'visitMission',mission:'yatasto'}).lastError);s=step(s,{type:'travel',sector:'tucuman'});s=step(s,{type:'visitSector'});let b=enterSector(s.pendingBattle);s=step(s,{type:'leaveSector',battleId:s.pendingBattle.id,sectorState:b,survivors:b.units.map(u=>({...u,id:Number(u.id)}))});const town=JSON.stringify(s.sectorStates.tucuman);s=attendYatasto(s);assert.equal(s.phase,3);assert.equal(s.missions.yatasto.completed,true);assert.ok(!s.recruited.includes(57));assert.equal(JSON.stringify(s.sectorStates.tucuman),town);assert.equal(s.sceneStates.yatasto.sceneId,'yatasto');assert.equal(restoreCampaign(serializeCampaign(s)).missions.yatasto.completed,true);
});
test('unfinished conference cannot finish remotely or skip Belgrano, and can resume',()=>{
 let s=northernCampaign();s=step(s,{type:'travel',sector:'tucuman'});s=step(s,{type:'visitMission',mission:'yatasto'});let b=enterSector(s.pendingBattle);assert.ok(reduce(s,{type:'finishMission',battleId:s.pendingBattle.id,sectorState:b,survivors:[]}).lastError);assert.ok(reduce(s,{type:'talkNPC',npcId:'yatasto-belgrano',approach:'mission',unitId:1000,sectorState:b}).lastError);s=step(s,{type:'leaveSector',battleId:s.pendingBattle.id,sectorState:b,survivors:b.units.map(u=>({...u,id:Number(u.id)}))});s=restoreCampaign(serializeCampaign(s));assert.equal(s.phase,2);s=attendYatasto(s);assert.equal(s.phase,3);
});
test('San Martín is a temporary combat ally and only verified surviving victory completes mission',()=>{
 let s=officer();s.phase=1;s.flags.academy=true;s.sectors.san_nicolas.owner='patriot';s=step(s,{type:'travel',sector:'buenos_aires'});s=step(s,{type:'travel',sector:'san_nicolas'});s=step(s,{type:'attack',sector:'san_lorenzo'});assert.ok(!s.recruited.includes(57));assert.equal(s.pendingBattle.missionAllies[0].id,57);
 let b=createBattle([...s.pendingBattle.squad.map(u=>({...u,x:1,y:1})),...s.pendingBattle.missionAllies.map(u=>({...u,x:3,y:3}))],{id:'san_lorenzo',width:12,height:10,enemies:[{id:'last-royalist',name:'Último realista',x:4,y:3,hp:10,maxHp:60,weapon:1800}],tiles:Array.from({length:120},(_,i)=>({x:i%12,y:Math.floor(i/12),type:'grass',blocked:false,cover:0}))});assert.ok(reduce(s,{type:'battleResult',battleId:s.pendingBattle.id,outcome:'victory',sectorState:b,survivors:b.units.filter(u=>u.side==='player').map(u=>({...u,id:Number(u.id)}))}).lastError);
 b=actBattle(b,{type:'melee',unitId:'57',targetId:'last-royalist'});assert.equal(b.status,'victory');s=step(s,{type:'battleResult',battleId:s.pendingBattle.id,outcome:'victory',sectorState:b,survivors:b.units.filter(u=>u.side==='player').map(u=>({...u,id:Number(u.id)}))});assert.equal(s.flags.sanLorenzo,true);assert.equal(s.missions.san_lorenzo.completed,true);assert.ok(!s.recruited.includes(57));assert.equal(s.contracts[57],undefined);assert.equal(restoreCampaign(serializeCampaign(s)).missionAllies.san_lorenzo.id,'57');
});
test('fallen allied commander makes San Lorenzo an explicit terminal mission defeat',()=>{
 let s=officer();s.phase=1;s.flags.academy=true;s.sectors.san_nicolas.owner='patriot';s=step(s,{type:'travel',sector:'san_nicolas'});s=step(s,{type:'attack',sector:'san_lorenzo'});
 let b=createBattle([...s.pendingBattle.squad.map(u=>({...u,x:1,y:1})),...s.pendingBattle.missionAllies.map(u=>({...u,x:8,y:3,hp:10}))],{id:'san_lorenzo',width:12,height:10,enemies:[{id:'royalist',name:'Lancero realista',x:9,y:3,weapon:1812}],tiles:Array.from({length:120},(_,i)=>({x:i%12,y:Math.floor(i/12),type:'grass',blocked:false,cover:0}))});b=endTurn(b);assert.equal(b.units.find(u=>u.id==='57').hp,0);s=step(s,{type:'battleResult',battleId:s.pendingBattle.id,outcome:'defeat',sectorState:b,survivors:b.units.filter(u=>u.side==='player').map(u=>({...u,id:Number(u.id)}))});assert.equal(s.defeated,true);assert.equal(s.missions.san_lorenzo.stage,'failed');assert.equal(s.flags.sanLorenzo,false);assert.ok(!s.recruited.includes(57));
});
