import test from 'node:test';import assert from 'node:assert/strict';
import {initialCampaign,dispatchCampaign as reduce,rosterFor,contractQuote,operativeLocation} from '../game/campaign.js';
import {defaultProfile} from '../game/character-profile.js';import {enterSector} from '../game/world.js';import {encodeSave,decodeSave} from '../game/save.js';
const step=(s,a)=>{const n=reduce(s,a);assert.equal(n.lastError,null,`${a.type}: ${n.lastError}`);return n;};
const start=()=>step(initialCampaign(),{type:'createOfficer',name:'Elena Valdés',profile:defaultProfile(),answers:{origin:'cabildo',doctrine:'guerrilla_tactician',crisis:'rally',specialty:'teacher',temperament:'steady'}});
const waitTo=(s,h)=>{while(s.hour<h)s=step(s,{type:'wait',hours:Math.min(240,h-s.hour)});return s;};
const roundTrip=(s)=>{s=step(s,{type:'visitSector'});const b=enterSector(s.pendingBattle,s.sectorStates[s.location]);const restored=decodeSave(encodeSave(s,b));return step(restored.campaign,{type:'leaveSector',battleId:s.pendingBattle.id,sectorState:restored.battle,survivors:restored.battle.units.filter(u=>u.side==='player').map(u=>({...u,id:Number(u.id)}))});};
test('fresh campaign mixed terms survive field visit, expires, save, and depleted-kit rehire',()=>{
 let s=start();const terms=[[100,'day'],[101,'week'],[102,'month']];for(const[id,term]of terms)s=step(s,{type:'recruitCivic',id,term});s=step(s,{type:'purchaseEquipment',item:1803,quantity:1});s=step(s,{type:'equip',operativeId:100,slot:'weapon',itemId:1803});const storedOld=s.armory[1804];
 s=step(s,{type:'travel',sector:'buenos_aires'});assert.equal(s.hour,12);s=roundTrip(s);assert.deepEqual(s.recruited,[1000,100,101,102]);const cartridges=s.resources.cartridges;s=waitTo(s,24);assert.ok(!s.recruited.includes(100));assert.equal(operativeLocation(s,100),'buenos_aires');assert.equal(s.contracts[101].expiresAt,168);s=decodeSave(encodeSave(s)).campaign;s=step(s,{type:'recruitCivic',id:100,term:'week'});assert.equal(rosterFor(s).find(o=>o.id===100).weapon,1803);assert.equal(s.armory[1804],storedOld);assert.equal(s.resources.cartridges,cartridges);s=step(s,{type:'dismiss',id:100});s=waitTo(s,168);assert.deepEqual(s.recruited,[1000,102]);s=waitTo(s,720);assert.deepEqual(s.recruited,[1000]);assert.equal(s.defeated,false);assert.deepEqual(decodeSave(encodeSave(s)).campaign.recruited,[1000]);
});
test('prepaid month never triggers a second monthly payroll debit',()=>{
 const baseline=start();let paid=step(baseline,{type:'recruitCivic',id:102,term:'month'});const cost=baseline.resources.treasury-paid.resources.treasury;const control=waitTo(baseline,720);paid=waitTo(paid,720);assert.equal(paid.resources.treasury,control.resources.treasury-cost);assert.ok(!paid.recruited.includes(102));assert.ok(!paid.log.some(e=>e.text.includes('Se abonaron 0 pesos')));
});
test('trainer contract expiry releases reserved promotions and mount without duplicating militia',()=>{
 let s=start();s=step(s,{type:'militia',trainerId:1000,rank:0});s=waitTo(s,s.militiaTraining[0].remaining);assert.equal(s.sectors.retiro.militia[0],3);s=step(s,{type:'recruitCivic',id:100,term:'day'});s=step(s,{type:'horseAction',order:{type:'acquire',name:'Moro'}});const hid=s.horseState.horses[0].id;s=step(s,{type:'horseAction',order:{type:'assign',horseId:hid,operativeId:100}});s=step(s,{type:'militia',trainerId:100,rank:1});assert.equal(s.sectors.retiro.militia[0],0);s=waitTo(s,s.contracts[100].expiresAt);assert.equal(s.militiaTraining.length,0);assert.deepEqual(s.sectors.retiro.militia,[3,0,0]);assert.equal(s.horseState.horses[0].assignedTo,null);assert.ok(!s.recruited.includes(100));assert.deepEqual(decodeSave(encodeSave(s)).campaign.sectors.retiro.militia,[3,0,0]);
});
test('elite renewals cannot bank additional days even after save reload',()=>{
 let s=start();const elite=rosterFor(s).find(o=>o.tier==='elite');s=step(s,{type:'recruitCivic',id:elite.id,term:'day'});const cash=s.resources.treasury;assert.ok(reduce(s,{type:'renewContract',id:elite.id,term:'day'}).lastError);assert.equal(s.resources.treasury,cash);s=waitTo(s,12);s=decodeSave(encodeSave(s)).campaign;const quote=contractQuote(s,elite,'day');s=step(s,{type:'renewContract',id:elite.id,term:'day'});assert.equal(s.contracts[elite.id].expiresAt,36);assert.equal(s.resources.treasury,cash-quote.price);assert.ok(reduce(s,{type:'renewContract',id:elite.id,term:'week'}).lastError);s=waitTo(s,36);assert.ok(!s.recruited.includes(elite.id));
});
