import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,actBattle,getReachable,shotChance,firearmRangeProfile} from '../game/tactical.js';
const tiles=()=>Array.from({length:140},(_,i)=>({x:i%14,y:Math.floor(i/14),type:'grass',blocked:false,cover:0}));
const sector=enemies=>({width:14,height:10,tiles:tiles(),enemies,seed:45});
function soldier(id,extra={}){return{id,name:`Soldado ${id}`,x:1,y:1,weapon:1808,marksmanship:70,...extra};}
test('Dorrego can fire and skirmish with an AP budget unavailable to an ordinary pistolero',()=>{const make=id=>createBattle([soldier(id)],sector([{id:'enemy',x:6,y:1}]));const d=make(4),ordinary=make(20);d.units[0].ap=6;ordinary.units[0].ap=6;assert.equal(actBattle(d,{type:'fire',unitId:4,targetId:'enemy'}).lastError,null);assert.ok(actBattle(ordinary,{type:'fire',unitId:20,targetId:'enemy'}).lastError);assert.equal(getReachable(d,'4').find(t=>t.x===2&&t.y===1).cost,6);assert.ok(!getReachable(ordinary,'20').some(t=>t.x===2&&t.y===1));});
test('Bouchard opens a real adobe assault route and suffers less night blindness',()=>{const make=id=>createBattle([soldier(id,{weapon:1807})],{...sector([{id:'enemy',x:5,y:1}]),night:true});let b=make(6),plain=make(20);const aided=firearmRangeProfile(b,b.units[0],b.units[1]),ordinary=firearmRangeProfile(plain,plain.units[0],plain.units[1]);assert.ok(aided.visibleRange>ordinary.visibleRange);assert.ok(aided.sightAdjustment>ordinary.sightAdjustment);assert.equal(shotChance(b,b.units[0],b.units[1]),100);assert.equal(shotChance(plain,plain.units[0],plain.units[1]),100,'nearby pellet contact can saturate despite a different center aiming profile');for(const s of[b,plain]){Object.assign(s.tiles.find(t=>t.x===2&&t.y===1),{type:'wall',material:'adobe',blocked:true});Object.assign(s.units[0],{activeSlot:'tool',activeTool:'inventory:bar',inventory:{...s.units[0].inventory,bar:{count:1,weight:2.5,itemType:'tool',toolKey:'crowbar',condition:100}}});s.units[0].ap=30;}const breached=actBattle(b,{type:'breach',unitId:6,x:2,y:1});assert.equal(breached.lastError,null);assert.equal(breached.tiles.find(t=>t.x===2&&t.y===1).blocked,false);assert.equal(breached.units[0].inventory.bar.condition,97);assert.equal(breached.units[0].ap,5);assert.ok(actBattle(plain,{type:'breach',unitId:20,x:2,y:1}).lastError);});
test('Barcala keeps nearby line infantry from breaking after a real musket wound',()=>{const make=leader=>createBattle([soldier('shooter',{weapon:1800,marksmanship:100})],sector([{id:'line',x:4,y:1,morale:16},...(leader?[{id:7,x:4,y:2}]:[])]));const steady=actBattle(make(true),{type:'fire',unitId:'shooter',targetId:'line'}),broken=actBattle(make(false),{type:'fire',unitId:'shooter',targetId:'line'});assert.equal(steady.units[1].routed,false);assert.equal(broken.units[1].routed,true);});
test('Quiroga mounted shock breaks neighboring peasant levies, not just his target',()=>{const make=id=>createBattle([soldier(id,{weapon:1812,mounted:true})],sector([{id:'target',x:6,y:1,hp:10,loaded:0,ammo:0,overwatch:false},{id:'levy',x:6,y:2,militia:true,morale:35,loaded:0,ammo:0,overwatch:false}]));const fierce=actBattle(make(9),{type:'charge',unitId:9,targetId:'target'}),plain=actBattle(make(20),{type:'charge',unitId:20,targetId:'target'});assert.equal(fierce.units[1].hp,0);assert.equal(fierce.units[2].routed,true);assert.equal(plain.units[2].routed,false);});
test('Paroissien stabilizes a critical wound within 18 AP with the kit already held',()=>{const make=id=>createBattle([soldier(id,{medical:98,hp:30,bleeding:8,activeSlot:'medical'})],sector([{id:'enemy',x:12,y:8}]));const b=make(10);b.units[0].ap=18;const n=actBattle(b,{type:'heal',unitId:10});assert.equal(n.lastError,null);assert.equal(n.units[0].bleeding,0);assert.equal(n.units[0].hp,30);assert.equal(n.units[0].ap,0);const other=make(20);other.units[0].ap=18;assert.match(actBattle(other,{type:'heal',unitId:20}).lastError,/6,25 PA/);});
test('Paz changes the actual order of defensive interruptions',()=>{const b=createBattle([soldier('mover',{hp:100})],sector([{id:'fast',name:'Rápido',x:5,y:1,agility:90},{id:'trained',name:'Bajo órdenes de Paz',x:9,y:1,agility:80},{id:11,x:9,y:3,loaded:0}]));const n=actBattle(b,{type:'move',unitId:'mover',x:2,y:1});const first=n.log.find(text=>text.includes('interrumpen con sus PA restantes'));assert.ok(first.startsWith('Bajo órdenes de Paz'));});
test('San Martín delivers a more precise mounted charge without changing listed weapon damage',()=>{const make=id=>createBattle([soldier(id,{weapon:1809,mounted:true})],sector([{id:'target',x:4,y:1,morale:100,loaded:0,ammo:0}]));const commander=actBattle(make(57),{type:'charge',unitId:57,targetId:'target'}),ordinary=actBattle(make(20),{type:'charge',unitId:20,targetId:'target'});assert.equal(commander.lastError,null);assert.equal(ordinary.lastError,null);assert.ok(commander.units[1].hp<ordinary.units[1].hp);});
