import {fillSparePockets} from './pocket-capacity-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {act} from '../web/node_modules/react/index.js';
import {mountCampaign} from './mounted-campaign-fixture.mjs';
import {supplyCareField} from './supply-transfer-fixture.mjs';
import {tactical,saved} from './local-contract-fixture.mjs';
const change=async(m,e,value)=>{const proto=e.tagName==='SELECT'?m.dom.window.HTMLSelectElement.prototype:m.dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,String(value));await act(async()=>e.dispatchEvent(new m.dom.window.Event(e.tagName==='SELECT'?'change':'input',{bubbles:true})));};
async function openPicker(m,p,recipient='111'){
 const who=p.battle.units.find(u=>u.id===recipient),button=[...m.document.querySelectorAll('.ja2-roster button')].find(b=>b.getAttribute('aria-label')?.includes(who.name));await act(async()=>button.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));const loot=m.document.querySelector('[aria-label="Recoger equipo"]');await act(async()=>loot.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));const owner=m.document.querySelector('[data-unit-id="110"]');await act(async()=>owner.dispatchEvent(new m.dom.window.MouseEvent('click',{bubbles:true})));assert.ok(m.document.querySelector('[aria-label="Recoger suministros del suelo"]'));
}
function supplies(){let p=supplyCareField();p=tactical(p,{type:'dropSupply',unitId:'110',item:'medkits',count:3});return tactical(p,{type:'dropSupply',unitId:'110',item:'rations',count:2});}

test('the real ground selector chooses among colocated bundles, collects the requested quantity and saves the untouched remainder',async t=>{
 const p=supplies(),m=await mountCampaign(t,p),ration=p.battle.groundItems.find(g=>g.type==='rations'),vendas=p.battle.groundItems.find(g=>g.type==='medkits');await openPicker(m,p);const select=m.document.querySelector('[aria-label="Bulto del suelo"]');assert.equal(select.options.length,2);await change(m,select,ration.id);await change(m,m.document.querySelector('[aria-label="Cantidad de suministros para recoger"]'),1);await m.click('Recoger cantidad');const s=m.read();assert.equal(s.battle.groundItems.find(g=>g.id===ration.id).count,1);assert.equal(s.battle.groundItems.find(g=>g.id===vendas.id).count,3);assert.equal(s.battle.units.find(u=>u.id==='111').rations,3);assert.equal(m.document.querySelector('[aria-label="Recoger suministros del suelo"]'),null);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});
});
test('opening the ground selector pauses the ordinary exploration clock and cancel or Escape spends nothing',async t=>{
 const p=supplies(),m=await mountCampaign(t,p);await m.click('Reanudar exploración');await openPicker(m,p);const before=m.read();await act(async()=>new Promise(resolve=>setTimeout(resolve,6250)));assert.deepEqual(m.read().battle,before.battle);const first=m.document.querySelector('[aria-label="Bulto del suelo"]');assert.equal(m.document.activeElement,first);await act(async()=>first.dispatchEvent(new m.dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));assert.equal(m.document.querySelector('[aria-label="Recoger suministros del suelo"]'),null);assert.deepEqual(m.read().battle,before.battle);await m.click('Pausar exploración');await openPicker(m,p);await m.click('Cancelar');assert.deepEqual(m.read().battle,before.battle);
});
test('the ground selector explains an overflowing whole bundle and accepts only the reduced exact quantity',async t=>{
 let p=supplyCareField();const recipient=p.battle.units.find(u=>u.id==='111');recipient.medkits=4;fillSparePockets(recipient);p=saved(p);p=tactical(p,{type:'dropSupply',unitId:'110',item:'medkits',count:3});const m=await mountCampaign(t,p);await openPicker(m,p);const dialog=m.document.querySelector('[aria-label="Recoger suministros del suelo"]'),button=[...dialog.querySelectorAll('button')].find(b=>b.textContent==='Recoger cantidad');assert.equal(button.disabled,true);assert.match(dialog.textContent,/bolsillo/);await change(m,m.document.querySelector('[aria-label="Cantidad de suministros para recoger"]'),1);assert.equal(button.disabled,false);await m.click('Recoger cantidad');const s=m.read();assert.equal(s.battle.units.find(u=>u.id==='111').medkits,5);assert.equal(s.battle.groundItems.find(g=>g.type==='medkits').count,2);assert.deepEqual(m.saved(),{campaign:s.campaign,battle:s.battle});
});
