import test from 'node:test';import assert from 'node:assert/strict';
import {initialCampaign,dispatchCampaign,restoreCampaign,serializeCampaign,questForNPC} from '../game/campaign.js';
import {enterSector} from '../game/world.js';import {actBattle} from '../game/tactical.js';
const order=(s,a)=>{const n=dispatchCampaign(s,a);assert.equal(n.lastError,null,n.lastError);return n;};
function meeting(){let s=order(initialCampaign(),{type:'createOfficer',name:'Juana del Sur',answers:{origin:'cabildo',doctrine:'line_marksman',crisis:'rally'}});s=order(s,{type:'visitSector'});let b=enterSector(s.pendingBattle);const npc=b.npcs.find(n=>n.id==='local-retiro');const neighbors=b.tiles.filter(t=>!t.blocked&&Math.abs(t.x-npc.x)+Math.abs(t.y-npc.y)===1);let next;for(const p of neighbors){next=actBattle(b,{type:'move',unitId:'1000',x:p.x,y:p.y});if(!next.lastError){b=next;break;}}assert.equal(b.lastError,null);return{s,b};}
const talk=(s,b)=>order(s,{type:'talkNPC',npcId:'local-retiro',approach:'quest',unitId:1000,sectorState:b});
test('physical NPC errand offers then pays exactly once and raises regional loyalty',()=>{
 let{s,b}=meeting();const treasury=s.resources.treasury,loyalty=s.sectors.buenos_aires.loyalty;s=talk(s,b);assert.equal(s.resources.treasury,treasury);assert.equal(s.quests['retiro-uniformes'].status,'offered');assert.ok(s.lastConversation.options.includes('quest'));s=talk(s,b);assert.equal(s.resources.treasury,treasury+120);assert.equal(s.sectors.buenos_aires.loyalty,loyalty+8);assert.equal(s.sectors.retiro.loyalty,loyalty+8);assert.equal(s.quests['retiro-uniformes'].status,'completed');assert.ok(!s.lastConversation.options.includes('quest'));const again=dispatchCampaign(s,{type:'talkNPC',npcId:'local-retiro',approach:'quest',unitId:1000,sectorState:b});assert.ok(again.lastError);assert.equal(again.resources.treasury,s.resources.treasury);assert.equal(again.cityLoyaltyEvents.length,s.cityLoyaltyEvents.length);assert.equal(restoreCampaign(serializeCampaign(s)).quests['retiro-uniformes'].status,'completed');
});
test('quest requests require adjacency and unsecured locations preserve the offered stage',()=>{
 let{s,b}=meeting();const far=structuredClone(b);far.units[0].x=0;far.units[0].y=0;assert.ok(dispatchCampaign(s,{type:'talkNPC',npcId:'local-retiro',approach:'quest',unitId:1000,sectorState:far}).lastError);s=talk(s,b);s.sectors.retiro.owner='royalist';const denied=dispatchCampaign(s,{type:'talkNPC',npcId:'local-retiro',approach:'quest',unitId:1000,sectorState:b});assert.ok(denied.lastError);assert.equal(denied.quests['retiro-uniformes'].status,'offered');assert.equal(denied.cityLoyaltyEvents.length,0);s.quests['retiro-uniformes'].completedAt=999;assert.throws(()=>restoreCampaign(serializeCampaign(s)));const old=initialCampaign();delete old.quests;assert.deepEqual(restoreCampaign(serializeCampaign(old)).quests,{});
});
test('each local errand has cash rewards and northern route conditions',()=>{const s=initialCampaign();assert.equal(questForNPC(s,'local-san_nicolas').reward,200);assert.equal(questForNPC(s,'macacha').conditionMet,false);s.sectors.salta.owner='patriot';s.sectors.jujuy.owner='patriot';assert.equal(questForNPC(s,'macacha').conditionMet,true);});
