import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Box3,Mesh,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {buildingArtInset,buildingFloorRectangles}=await import('../web/lib/three/world-building-placement.ts');
const {entranceFrame,getBuildingProfile}=await import('../game/building-profile.js');
const {buildingDetails}=await import('../web/app/TacticalBuildingDetails.tsx');
const {ArchitectureVolume}=await import('../web/app/TacticalBuildingVolumes.tsx');
const {createArchitectureReviewBattle}=await import('../web/app/renderer-sandbox/architecture-fixtures.js');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270];
function fixture(rotation,view='exterior',roof='original'){
 const battle=createArchitectureReviewBattle('barraca',rotation,view,roof),b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},frame=entranceFrame({...b,walls:battle.tiles}),geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});
 const point=(u,v,y)=>{const p=frame.at(u,v);return new Vector3(p.x*T,y,p.y*T);};
 return {b,input,frame,point,feature(building){const node=building.getObjectByName(`building-detail:${b.id}:barracks-gate`);return node?.children.length?node:undefined;},build(){const before=JSON.stringify(input),building=buildBuilding(b,input,T,geometry,materials);building.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before);return building;},dispose(building){disposeWorldNode(building);geometry.dispose();materials.dispose();}};
}
function sourceGate(f){const parts=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){for(const child of node)visit(child);return;}if(node.type===ArchitectureVolume&&(/^(gate-pilaster-|barracks-gate-entablature$)/).test(String(node.props.label)))parts.push(node.props);visit(node.props?.children);};for(const object of buildingDetails({...f.b,walls:f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id)},new Set(),(x,y)=>({x:(x-y)*26,y:(x+y)*14})))visit(object.node);assert.equal(parts.length,7);return parts;}
function bounds(f,mesh,keep=()=>true){const p=mesh.geometry.getAttribute('position'),origin=f.frame.at(0,0),result={u0:Infinity,u1:-Infinity,v0:Infinity,v1:-Infinity};for(let n=0;n<p.count;n++){if(!keep(p.getY(n)))continue;const x=p.getX(n)/T-origin.x,y=p.getZ(n)/T-origin.y,u=x*f.frame.u.x+y*f.frame.u.y,v=x*f.frame.v.x+y*f.frame.v.y;result.u0=Math.min(result.u0,u);result.u1=Math.max(result.u1,u);result.v0=Math.min(result.v0,v);result.v1=Math.max(result.v1,v);}return result;}
function sourceBounds(f,parts){const origin=f.frame.at(0,0),points=parts.flatMap(part=>part.points),u=points.map(p=>(p.x-origin.x)*f.frame.u.x+(p.y-origin.y)*f.frame.u.y),v=points.map(p=>(p.x-origin.x)*f.frame.v.x+(p.y-origin.y)*f.frame.v.y);return {u0:Math.min(...u),u1:Math.max(...u),v0:Math.min(...v),v1:Math.max(...v)};}
function sameBounds(a,b){for(const key of ['u0','u1','v0','v1'])assert.ok(Math.abs(a[key]-b[key])<1e-5,`${key}: native ${a[key]} source ${b[key]}`);}
function supported(f,node){node.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++)if(p.getY(n)<1.8)assert.equal(f.input.terrain.tiles.find(tile=>tile.x===Math.round(p.getX(n)/T)&&tile.y===Math.round(p.getZ(n)/T))?.type,'wall','standing parts must remain within actual intact support cells');}});}

test('the actual barracks gate has the source shaft, foot, capital and entablature planes at four rotations',()=>{
 const sourceFixture=fixture(0),source=sourceGate(sourceFixture);for(const rotation of rotations){const f=fixture(rotation),building=f.build(),node=f.feature(building),height=building.userData.height,body=node.children.find(mesh=>mesh.material.name===`world:${f.b.wallFinish}`),foot=node.children.find(mesh=>mesh.material.name==='world:stone'),cap=node.children.find(mesh=>mesh.material.name==='world:barracks-pier-coping');assert.equal(buildingArtInset(f.b,f.input),0);assert.ok(body&&foot&&cap);supported(f,node);
  sameBounds(bounds(f,body,y=>y<height-7/V),sourceBounds(sourceFixture,source.filter(part=>part.label.endsWith('-shaft'))));sameBounds(bounds(f,foot),sourceBounds(sourceFixture,source.filter(part=>part.label.endsWith('-base'))));sameBounds(bounds(f,cap),sourceBounds(sourceFixture,source.filter(part=>part.label.endsWith('-capital'))));sameBounds(bounds(f,body,y=>Math.abs(y-(height-4/V))<1e-5),sourceBounds(sourceFixture,source.filter(part=>part.label==='barracks-gate-entablature')));
  assert.ok(Math.abs(new Box3().setFromObject(foot).max.y-source.find(part=>part.label.endsWith('-base')).top/V)<1e-5);assert.ok(Math.abs(new Box3().setFromObject(cap).max.y-(height+4.5/V))<1e-5);
  const out=new Vector3(-f.frame.v.x,0,-f.frame.v.y);for(const u of [Math.round(f.frame.doorU-1),Math.round(f.frame.doorU+1)]){const ray=new Raycaster(f.point(u,-1,1.3),out.clone().negate(),0,2*T),shaft=ray.intersectObject(node,true)[0],wall=ray.intersectObject(building.getObjectByName(`building-fabric:${f.b.id}`),true)[0];assert.ok(shaft&&wall);assert.ok(Math.abs(wall.distance-shaft.distance-(.34*T-.09))<1e-5,'source shaft exposure remains 33 cm through every rotation');}
  const plaque=node.children.find(mesh=>mesh.material.name==='world:barracks-plaque'),shape=new Box3().setFromObject(plaque);assert.ok(Math.abs(shape.min.y-(height-13/V))<1e-5&&Math.abs(shape.max.y-(height+5/V))<1e-5,'the current plaque spans the actual source height rather than the previous small brass shield');f.dispose(building);
 }sourceFixture.dispose(sourceFixture.build());
});

test('centred barracks roof and both gables join the real walls while the standing door and every window remain clear',()=>{
 for(const rotation of rotations){const f=fixture(rotation);f.frame.door.open=true;const building=f.build(),node=f.feature(building),fabric=building.getObjectByName(`building-fabric:${f.b.id}`),profile=getBuildingProfile(f.b),roof=fabric.children.find(mesh=>mesh.material.name===`world:${f.b.roofFinish}`),positions=roof.geometry.getAttribute('position'),xs=[],zs=[];for(let n=0;n<positions.count;n++){xs.push(positions.getX(n));zs.push(positions.getZ(n));}for(const [actual,expected]of [[Math.min(...xs),(f.b.x-profile.eave)*T],[Math.max(...xs),(f.b.x+f.b.width-1+profile.eave)*T],[Math.min(...zs),(f.b.y-profile.eave)*T],[Math.max(...zs),(f.b.y+f.b.height-1+profile.eave)*T]])assert.ok(Math.abs(actual-expected)<1e-5);
  const rise=Math.min(profile.roofRise/V,Math.max(.4,f.frame.width*.28)),p=fabric.children.find(mesh=>mesh.material.name===`world:${f.b.wallFinish}`).geometry.getAttribute('position');for(const v of [0,f.frame.depth])for(const u of [0,f.frame.width*.5,f.frame.width]){const point=f.point(u,v,building.userData.height+(u===f.frame.width*.5?rise:0));assert.ok(Array.from({length:p.count},(_,n)=>n).some(n=>Math.abs(p.getX(n)-point.x)<1e-5&&Math.abs(p.getY(n)-point.y)<1e-5&&Math.abs(p.getZ(n)-point.z)<1e-5),'both masonry gables stay joined to the actual ridge and wall corners');}
  const out=new Vector3(-f.frame.v.x,0,-f.frame.v.y);for(const offset of [-.20,0,.20])for(const y of [1.3,1.8]){const start=f.point(f.frame.doorU,-1,y).add(new Vector3(offset*f.frame.u.x,0,offset*f.frame.u.y));assert.equal(new Raycaster(start,out.clone().negate(),0,2*T).intersectObject(building,true).length,0);}assert.equal(building.userData.openings.find(opening=>opening.id===f.frame.door.doorId).width,.60*T);
  for(const tile of f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id&&tile.type==='window')){const onX=tile.x===f.b.x||tile.x===f.b.x+f.b.width-1,sign=onX?(tile.x===f.b.x?-1:1):(tile.y===f.b.y?-1:1),start=onX?new Vector3((tile.x+sign)*T,1.3,tile.y*T):new Vector3(tile.x*T,1.3,(tile.y+sign)*T),direction=onX?new Vector3(-sign,0,0):new Vector3(0,0,-sign);assert.equal(new Raycaster(start,direction,0,T*1.6).intersectObject(node,true).length,0);}f.dispose(building);
 }
});

test('edited gate bearings omit their unsupported pier and the bridge while corner edits and legacy keep the released fallback',()=>{
 for(const rotation of rotations){for(const type of ['door','window','rubble']){const f=fixture(rotation),p=f.frame.at(Math.round(f.frame.doorU-1),0),tile=f.input.terrain.tiles.find(tile=>tile.x===p.x&&tile.y===p.y);tile.type=type;f.input.terrain.tiles=[f.frame.door,...f.input.terrain.tiles.filter(tile=>tile!==f.frame.door)];const building=f.build(),node=f.feature(building);assert.ok(node);supported(f,node);assert.equal(node.children.some(mesh=>mesh.material.name==='world:barracks-plaque'),false);const out=new Vector3(-f.frame.v.x,0,-f.frame.v.y);assert.equal(new Raycaster(new Vector3(p.x*T,type==='window'?1.3:1.8,p.y*T).addScaledVector(out,T),out.clone().negate(),0,2*T).intersectObject(node,true).length,0);f.dispose(building);}
  for(const uEnd of [0,1])for(const type of ['rubble','grass','door','window']){const f=fixture(rotation),p=f.frame.at(uEnd?f.frame.width:0,0);f.input.terrain.tiles.find(tile=>tile.x===p.x&&tile.y===p.y).type=type;f.input.terrain.tiles=[f.frame.door,...f.input.terrain.tiles.filter(tile=>tile!==f.frame.door)];assert.equal(buildingArtInset(f.b,f.input),.4);const building=f.build(),node=f.feature(building);assert.equal(Boolean(building.getObjectByName(`building-barracks-gate:${f.b.id}`)),false);assert.ok(node.children.some(mesh=>mesh.material.name==='world:brass'),'the original fallback gate and crossing path stay selected');f.dispose(building);}
  const legacy=fixture(rotation);legacy.b.architecture='barracks';legacy.b.kind=undefined;legacy.b.wallFinish=undefined;assert.equal(buildingArtInset(legacy.b,legacy.input),.4);const building=legacy.build();assert.ok(legacy.feature(building).children.some(mesh=>mesh.material.name==='world:brass'));assert.equal(Boolean(building.getObjectByName(`building-barracks-gate:${legacy.b.id}`)),false);legacy.dispose(building);
 }
});

test('barracks source gate materials preserve authored pigments, local plaster, warm feet and the actual geometric plaque',()=>{
 for(const finish of ['adobe','limewash','ochre','stone','brick']){const sourceFixture=fixture(0);sourceFixture.b.wallFinish=finish;const source=sourceGate(sourceFixture),shaft=source.find(part=>part.label.endsWith('-shaft')),foot=source.find(part=>part.label.endsWith('-base')),capital=source.find(part=>part.label.endsWith('-capital'));for(const rotation of rotations){const f=fixture(rotation);f.b.wallFinish=finish;const building=f.build(),node=f.feature(building),body=node.children.find(mesh=>mesh.material.name===`world:${finish}`&&mesh.material.color.getHexString()===shaft.palette.base.slice(1)),base=node.children.find(mesh=>mesh.material.name==='world:stone'&&mesh.material.color.getHexString()===foot.palette.base.slice(1));assert.ok(body&&base);assert.equal(body.material.userData.architectureFinish.textureOpacity,.36);assert.equal(body.material.userData.architectureFinish.texture,'/art/architecture-plaster-v2.png');assert.equal(body.material.userData.architectureFinish.multiplyOpacity,0);assert.equal(base.material.userData.architectureFinish.textureOpacity,.60);assert.equal(node.children.find(mesh=>mesh.material.name==='world:barracks-pier-coping').material.color.getHexString(),capital.palette.trim.slice(1));assert.equal(node.children.find(mesh=>mesh.material.name==='world:barracks-plaque').material.color.getHexString(),'c9bc93');assert.equal(node.children.find(mesh=>mesh.material.name==='world:barracks-plaque-mark').material.color.getHexString(),'7b6945');f.dispose(building);}sourceFixture.dispose(sourceFixture.build());}
});

test('barracks source gate follows real flat heights and omits decoration that would occupy usable upper routes or short doors',()=>{
 for(const rotation of rotations){for(const roof of ['slab','terrace','roof-route']){const f=fixture(rotation,'exterior',roof),building=f.build(),node=f.feature(building);if(roof==='roof-route')assert.equal(Boolean(node),false);else{assert.ok(node);assert.ok(Math.abs(new Box3().setFromObject(node.children.find(mesh=>mesh.material.name==='world:barracks-pier-coping')).max.y-(building.userData.height+4.5/V))<1e-5);}f.dispose(building);}
  const short=fixture(rotation,'exterior','slab');short.input.terrain.upperSurfaces=short.input.terrain.upperSurfaces.map(surface=>({...surface,elevation:1.8}));const shortBuilding=short.build();assert.equal(Boolean(short.feature(shortBuilding)),false);short.dispose(shortBuilding);
  for(const blocked of [false,true])for(const elevation of [2.2,4]){const f=fixture(rotation),p=f.frame.at(Math.round(f.frame.doorU-1),0);f.input.terrain.upperSurfaces=[{...p,tacticalLevel:1,elevation,blocked,kind:'platform',buildingId:f.b.id,type:'floor'}];const building=f.build();assert.equal(Boolean(f.feature(building)),blocked||elevation===4,'only a usable surface at or below the actual gate top excludes the source gate');f.dispose(building);}
  for(const view of ['partial','interior']){const f=fixture(rotation,view),building=f.build();assert.equal(Boolean(f.feature(building)),false);f.dispose(building);}
 }
});

test('centred barracks disclosed floors meet the wall and retain actual hatch, upper and door-threshold footprints',()=>{
 for(const rotation of rotations){const f=fixture(rotation,'interior'),cell=f.b.rooms.flatMap(room=>room.cells).find(cell=>cell.x===f.b.x+1&&cell.y===f.b.y+1);assert.ok(cell);const normal=buildingFloorRectangles(f.b,f.input,{...cell,elevation:0},T,[],0);assert.equal(normal[0].minX,f.b.x*T+.09);assert.equal(normal[0].minZ,f.b.y*T+.09);const hatch={linkId:'barracks-return-hatch',level:0,height:0,minX:f.b.x*T+.10,maxX:f.b.x*T+.30,minZ:f.b.y*T+.10,maxZ:f.b.y*T+.30},clipped=buildingFloorRectangles(f.b,f.input,{...cell,elevation:0},T,[hatch],0);assert.ok(clipped.length>1);for(const part of clipped)assert.ok(part.maxX<=hatch.minX||part.minX>=hatch.maxX||part.maxZ<=hatch.minZ||part.minZ>=hatch.maxZ);for(const point of [{...cell,tacticalLevel:1,elevation:3},{x:f.frame.door.x,y:f.frame.door.y,elevation:0}])assert.deepEqual(buildingFloorRectangles(f.b,f.input,point,T,[],0),[{minX:(point.x-.5)*T,maxX:(point.x+.5)*T,minZ:(point.y-.5)*T,maxZ:(point.y+.5)*T}]);f.dispose(f.build());}
});

test('barracks gate source finishes retain metre texture density and ordinary day and night light',()=>{
 for(const rotation of rotations)for(const night of [false,true]){const f=fixture(rotation);f.input.terrain.night=night;f.input.illumination={[`0:${f.b.x},${f.b.y}`]:.5};const building=f.build(),node=f.feature(building),expected=night?.27+.73*.5:1;for(const mesh of node.children){const p=mesh.geometry.getAttribute('position'),colour=mesh.geometry.getAttribute('color');for(let n=0;n<p.count;n++)for(const channel of ['getX','getY','getZ'])assert.ok(Math.abs(colour[channel](n)-expected)<1e-6);if(mesh.material.userData.architectureFinish){const uv=mesh.geometry.getAttribute('uv'),normal=mesh.geometry.getAttribute('normal');let courses=0;for(let n=0;n<p.count;n++)if(n%3===0&&Math.abs(normal.getY(n))<.5)for(const next of [n+1,n+2])if(Math.abs(p.getY(n)-p.getY(next))>.20){assert.ok(Math.abs(Math.abs(uv.getY(n)-uv.getY(next))-Math.abs(p.getY(n)-p.getY(next)))<1e-5);courses++;}assert.ok(courses>0);}}f.dispose(building);}
});
