import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Mesh,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {buildingArtInset}=await import('../web/lib/three/world-building-placement.ts');
const {ISO_PITCH}=await import('../web/lib/three/projection.ts');
const {entranceFrame}=await import('../game/building-profile.js');
const {buildingDetails}=await import('../web/app/TacticalBuildingDetails.tsx');
const {ArchitectureVolume}=await import('../web/app/TacticalBuildingVolumes.tsx');
const {createArchitectureReviewBattle}=await import('../web/app/renderer-sandbox/architecture-fixtures.js');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270];
function fixture(rotation,view='exterior',roof='original'){
 const battle=createArchitectureReviewBattle('iglesia',rotation,view,roof),b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},frame=entranceFrame({...b,walls:battle.tiles}),geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});
 return {b,input,frame,feature:building=>building.getObjectByName(`building-detail:${b.id}:church-nave-buttresses`),point(u,v,y){const p=frame.at(u,v);return new Vector3(p.x*T,y,p.y*T);},build(){const before=JSON.stringify(input),object=buildBuilding(b,input,T,geometry,materials);object.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before);return object;},dispose(object){disposeWorldNode(object);geometry.dispose();materials.dispose();}};
}
const near=(actual,expected,message)=>assert.ok(Math.abs(actual-expected)<2e-5,`${message}: ${actual} versus ${expected}`);
function support(f,node){node.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++){assert.ok(p.getY(n)>=-1e-6,'ground edge strokes cannot extend below the authored floor');assert.equal(f.input.terrain.tiles.find(tile=>tile.x===Math.round(p.getX(n)/T)&&tile.y===Math.round(p.getZ(n)/T))?.type,'wall','every stroke remains within its intact actual support cell');}}});}
function sourceWedges(f){const parts=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(String(node.props?.['data-architectural-volume']).includes('nave-buttress'))parts.push(node.props.children.filter(child=>child.type===ArchitectureVolume).map(child=>child.props));visit(node.props?.children);};for(const object of buildingDetails({...f.b,walls:f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id)},new Set(),(x,y)=>({x:(x-y)*26,y:(x+y)*14})))visit(object.node);assert.ok(parts.length>=2);return parts;}
function sourceStrokes(part){const result=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(node.type==='polygon'&&node.props.strokeWidth)result.push(node.props);visit(node.props?.children);};visit(ArchitectureVolume(part));return result;}
function distance(point,a,b){const d=b.clone().sub(a),t=Math.max(0,Math.min(1,point.clone().sub(a).dot(d)/d.lengthSq()));return point.distanceTo(a.clone().addScaledVector(d,t));}

test('nave border pigments and physical stroke widths follow the actual direct volume recipe in every rotation',()=>{
 for(const rotation of rotations)for(const finish of ['adobe','limewash','ochre','stone','brick']){const f=fixture(rotation);f.b.wallFinish=finish;const direct=sourceWedges(f),building=f.build(),node=f.feature(building),body=node.children.find(mesh=>mesh.material.name==='world:church-nave-outline'),foot=node.children.find(mesh=>mesh.material.name==='world:church-nave-foot-outline');assert.equal(body.material.color.getHexString(),direct[0][0].palette.shadow.slice(1));assert.equal(foot.material.color.getHexString(),direct[0][1].palette.shadow.slice(1));assert.equal(body.material.map,null);assert.equal(foot.material.map,null);
  const strokes=sourceStrokes(direct[0][0]),side=strokes.find(part=>part.fill==='none'),cap=strokes.find(part=>part.fill===direct[0][0].palette.trim);assert.equal(Number(side.strokeWidth),.45);assert.equal(Number(cap.strokeWidth),.5);assert.equal(Number(sourceStrokes(direct[0][1])[0].strokeWidth),.45);
  // Source screen-facing rhythm can differ after rotation. This border-only
  // cut compares its exact shape at the existing native support anchors.
  const bodyEdges=[],footEdges=[],cells=new Set(),used=new Set();for(const [shaft,base]of direct){const centre=shaft.points.reduce((a,p)=>({x:a.x+p.x/4,y:a.y+p.y/4}),{x:0,y:0}),u=Math.round((centre.x-f.frame.origin.x)*f.frame.u.x+(centre.y-f.frame.origin.y)*f.frame.u.y),candidates=[];for(let v=f.frame.depth-2;v>0;v-=3){const point=f.frame.at(u,v);if(f.input.terrain.tiles.find(tile=>tile.x===point.x&&tile.y===point.y)?.type==='wall'&&!used.has(`${point.x},${point.y}`))candidates.push(point);}const anchor=candidates.sort((a,b)=>Math.hypot(a.x-centre.x,a.y-centre.y)-Math.hypot(b.x-centre.x,b.y-centre.y))[0];assert.ok(anchor);used.add(`${anchor.x},${anchor.y}`);cells.add(`${anchor.x},${anchor.y}`);const shifted=p=>({x:p.x+anchor.x-centre.x,y:p.y+anchor.y-centre.y}),bottom=shaft.points.map(p=>{const q=shifted(p);return new Vector3(q.x*T,0,q.y*T);}),feet=shaft.points.map(p=>{const q=shifted(p);return new Vector3(q.x*T,base.top/V,q.y*T);}),tops=shaft.points.map((p,n)=>{const q=shifted(p);return new Vector3(q.x*T,shaft.top[n]/V,q.y*T);});for(let n=0;n<4;n++){const next=(n+1)%4;bodyEdges.push({a:feet[n],b:tops[n],radius:Number(side.strokeWidth)/V*.5},{a:tops[n],b:tops[next],radius:Number(cap.strokeWidth)/V*.5});footEdges.push({a:bottom[n],b:feet[n],radius:.45/V*.5},{a:feet[n],b:feet[next],radius:.45/V*.5},{a:bottom[n],b:bottom[next],radius:.45/V*.5});}}
  for(const [mesh,edges]of [[body,bodyEdges],[foot,footEdges]]){const p=mesh.geometry.getAttribute('position');let checked=0,max=0;for(let n=0;n<p.count;n++){if(!cells.has(`${Math.round(p.getX(n)/T)},${Math.round(p.getZ(n)/T)}`))continue;const point=new Vector3(p.getX(n),p.getY(n),p.getZ(n)),nearest=edges.map(edge=>({...edge,distance:distance(point,edge.a,edge.b)})).sort((a,b)=>a.distance/a.radius-b.distance/b.radius)[0];assert.ok(nearest.distance<=nearest.radius+2e-5,`the stroke must follow the source edge and keep its measured width: ${nearest.distance} versus ${nearest.radius}`);max=Math.max(max,nearest.distance/nearest.radius);checked++;}assert.ok(checked>100&&max>.98,`the check must measure real stroke geometry: ${rotation}/${finish}/${mesh.material.name}: ${checked} vertices, radius ratio ${max}`);}support(f,node);f.dispose(building);
 }
});

test('closed nave body and foot faces point outward and remain visible before the wall at the actual camera angle',()=>{
 const cameraDirection=new Vector3(Math.cos(ISO_PITCH)/Math.SQRT2,Math.sin(ISO_PITCH),Math.cos(ISO_PITCH)/Math.SQRT2);
 for(const rotation of rotations){const f=fixture(rotation),building=f.build(),node=f.feature(building),fabric=building.getObjectByName(`building-fabric:${f.b.id}`);for(const mesh of node.children.filter(mesh=>['world:limewash','world:stone'].includes(mesh.material.name))){const p=mesh.geometry.getAttribute('position'),normal=mesh.geometry.getAttribute('normal');for(let n=0;n<p.count;n+=3){if(Math.abs(normal.getY(n))>.5)continue;const cx=(p.getX(n)+p.getX(n+1)+p.getX(n+2))/3,cz=(p.getZ(n)+p.getZ(n+1)+p.getZ(n+2))/3,dx=cx-Math.round(cx/T)*T,dz=cz-Math.round(cz/T)*T;assert.ok(normal.getX(n)*dx+normal.getZ(n)*dz>.10,'the physical vertical face normal must point outside its closed prism');}}
  for(const u of [0,f.frame.width])for(let v=f.frame.depth-2;v>0;v-=3){const tile=f.frame.at(u,v);if(f.input.terrain.tiles.find(p=>p.x===tile.x&&p.y===tile.y)?.type!=='wall')continue;const out=new Vector3((u===0?-1:1)*f.frame.u.x,0,(u===0?-1:1)*f.frame.u.y);for(const y of [.35,1,1.3]){const start=f.point(u,v,y).addScaledVector(out,T),ray=new Raycaster(start,out.clone().negate(),0,T*2),detail=ray.intersectObject(node,true)[0],wall=ray.intersectObject(fabric,true)[0];assert.ok(detail&&wall);near(wall.distance-detail.distance,.39*T-.09,'retained body and foot exposure');assert.equal(ray.intersectObject(building,true)[0].object,detail.object,'the body is physically before the wall');}
   if(out.x+out.z>0){const target=f.point(u,v,1).addScaledVector(out,.39*T+.001),ray=new Raycaster(target.clone().addScaledVector(cameraDirection,20),cameraDirection.clone().negate(),0,20.1),hit=ray.intersectObject(building,true)[0];assert.ok(hit.object.name.includes('church-nave-buttresses:world:limewash'),'the actual camera ray must meet the exposed body before another shell face');}
  }f.dispose(building);
 }
});

test('nave border work preserves body and foot source palettes, opacity, UV phase and ordinary illumination',()=>{
 for(const rotation of rotations)for(const night of [false,true]){const f=fixture(rotation);f.input.terrain.night=night;f.input.illumination={[`0:${f.b.x},${f.b.y}`]:.5};const direct=sourceWedges(f),building=f.build(),node=f.feature(building);for(const [name,part,opacity]of [['world:limewash',direct[0][0],.36],['world:stone',direct[0][1],.60]]){const mesh=node.children.find(mesh=>mesh.material.name===name),recipe=mesh.material.userData.architectureFinish;assert.equal(mesh.material.color.getHexString(),part.palette.base.slice(1));assert.equal(recipe.textureOpacity,opacity);assert.equal(recipe.multiplyOpacity,0);const p=mesh.geometry.getAttribute('position'),normal=mesh.geometry.getAttribute('normal'),uv=mesh.geometry.getAttribute('uv');for(let n=0;n<p.count;n+=6){const horizontal=Math.abs(normal.getY(n))>.5,oldX=horizontal?normal.getX(n):-normal.getX(n),oldZ=horizontal?normal.getZ(n):-normal.getZ(n),raw=i=>horizontal?p.getX(i):Math.abs(oldX)>Math.abs(oldZ)?p.getZ(i)*(oldX>0?-1:1):p.getX(i)*(oldZ>0?1:-1);for(let i=n;i<n+6;i++){near(uv.getX(i),raw(i)-raw(n),'retained wall-local U phase and direction');near(uv.getY(i),horizontal?p.getZ(i):p.getY(i),'retained metre V coordinates');}}}
  const expected=night?.27+.73*.5:1;for(const mesh of node.children){const colour=mesh.geometry.getAttribute('color');for(let n=0;n<colour.count;n++)for(const channel of ['getX','getY','getZ'])near(colour[channel](n),expected,'normal vertex illumination');}f.dispose(building);
 }
});

test('thin source nave borders preserve apertures, edited support fallbacks and ordinary room disclosure',()=>{
 for(const rotation of rotations){const f=fixture(rotation);f.frame.door.open=true;const building=f.build(),node=f.feature(building);for(const offset of [-.20,0,.20])for(const y of [1.3,1.8]){const start=f.point(f.frame.doorU,-1,y).add(new Vector3(offset*f.frame.u.x,0,offset*f.frame.u.y));assert.equal(new Raycaster(start,new Vector3(f.frame.v.x,0,f.frame.v.y),0,T*1.6).intersectObject(building,true).length,0);}for(const tile of f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id&&tile.type==='window')){const onX=tile.x===f.b.x||tile.x===f.b.x+f.b.width-1,sign=onX?(tile.x===f.b.x?-1:1):(tile.y===f.b.y?-1:1),start=onX?new Vector3((tile.x+sign)*T,1.3,tile.y*T):new Vector3(tile.x*T,1.3,(tile.y+sign)*T),direction=onX?new Vector3(-sign,0,0):new Vector3(0,0,-sign);assert.equal(new Raycaster(start,direction,0,T*1.6).intersectObject(node,true).length,0);}f.dispose(building);
  for(const type of ['rubble','window','door']){const edited=fixture(rotation),point=edited.frame.at(0,0);edited.input.terrain.tiles.find(tile=>tile.x===point.x&&tile.y===point.y).type=type;edited.input.terrain.tiles=[edited.frame.door,...edited.input.terrain.tiles.filter(tile=>tile!==edited.frame.door)];const object=edited.build();assert.equal(buildingArtInset(edited.b,edited.input),.4);support(edited,edited.feature(object));edited.dispose(object);}
  for(const view of ['partial','interior']){const f=fixture(rotation,view),building=f.build();assert.equal(f.feature(building),undefined);f.dispose(building);}
 }
});

test('nave source borders remain below actual roofs and omit the same occupied lower upper cells',()=>{
 for(const rotation of rotations){for(const roof of ['slab','terrace','roof-route']){const f=fixture(rotation,'exterior',roof),building=f.build(),node=f.feature(building);support(f,node);node.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++)assert.ok(p.getY(n)<building.userData.height-.04,'the original low support and its source border remain below a legal roof surface');}});f.dispose(building);}
  for(const blocked of [false,true]){const f=fixture(rotation),point=f.frame.at(0,f.frame.depth-2);f.input.terrain.upperSurfaces=[{...point,tacticalLevel:1,elevation:1.2,blocked,kind:'platform',type:'floor',buildingId:f.b.id}];const building=f.build(),node=f.feature(building);let occupied=0;node.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++)if(Math.round(p.getX(n)/T)===point.x&&Math.round(p.getZ(n)/T)===point.y)occupied++;}});assert.equal(occupied>0,blocked);f.dispose(building);}
 }
});
