import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Box3,Mesh,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {entranceFrame,getBuildingProfile}=await import('../game/building-profile.js');
const {buildingDetails}=await import('../web/app/TacticalBuildingDetails.tsx');
const {ArchitectureVolume}=await import('../web/app/TacticalBuildingVolumes.tsx');
const {createArchitectureReviewBattle}=await import('./legacy-building-fixtures.mjs');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270];
function fixture(rotation,view='exterior',roof='original'){
 const battle=createArchitectureReviewBattle('herreria',rotation,view,roof),b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},frame=entranceFrame({...b,walls:battle.tiles}),geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});
 return {b,input,frame,materials,point(u,v,y){const p=frame.at(u,v);return new Vector3(p.x*T,y,p.y*T);},feature:building=>building.getObjectByName(`building-detail:${b.id}:forge-chimney`),build(){const before=JSON.stringify(input),building=buildBuilding(b,input,T,geometry,materials);building.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before);return building;},dispose(building){disposeWorldNode(building);geometry.dispose();materials.dispose();}};
}
const near=(actual,expected,message)=>assert.ok(Math.abs(actual-expected)<2e-5,`${message}: ${actual} versus ${expected}`);
function local(f,x,z){const origin=f.frame.at(0,0);return {u:(x/T-origin.x)*f.frame.u.x+(z/T-origin.y)*f.frame.u.y,v:(x/T-origin.x)*f.frame.v.x+(z/T-origin.y)*f.frame.v.y};}
function boxBounds(f,mesh,start=0,count=mesh.geometry.getAttribute('position').count){const p=mesh.geometry.getAttribute('position'),out={u0:Infinity,u1:-Infinity,v0:Infinity,v1:-Infinity,y0:Infinity,y1:-Infinity};for(let n=start;n<start+count;n++){const point=local(f,p.getX(n),p.getZ(n));out.u0=Math.min(out.u0,point.u);out.u1=Math.max(out.u1,point.u);out.v0=Math.min(out.v0,point.v);out.v1=Math.max(out.v1,point.v);out.y0=Math.min(out.y0,p.getY(n));out.y1=Math.max(out.y1,p.getY(n));}return out;}
function supported(f,node){node.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++)assert.equal(f.input.terrain.tiles.find(tile=>tile.x===Math.round(p.getX(n)/T)&&tile.y===Math.round(p.getZ(n)/T))?.type,'wall','the full source cap and flue stay in an intact actual wall cell');}});}
function source(f){const result={};const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(node.type===ArchitectureVolume&&['forge-chimney','chimney-cap'].includes(node.props.label))result[node.props.label]=node.props;if(node.type==='polygon'&&node.key==='chimney-flue')result.flue=node.props;visit(node.props?.children);};for(const object of buildingDetails({...f.b,walls:f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id)},new Set(),(x,y)=>({x:(x-y)*26,y:(x+y)*14})))visit(object.node);assert.ok(result['forge-chimney']&&result['chimney-cap']&&result.flue);return result;}
function sourceBounds(f,part){const points=part.points.map(p=>local(f,p.x*T,p.y*T));return {u0:Math.min(...points.map(p=>p.u)),u1:Math.max(...points.map(p=>p.u)),v0:Math.min(...points.map(p=>p.v)),v1:Math.max(...points.map(p=>p.v))};}
function actualRise(f){return f.b.roof==='terrace'||(f.input.terrain.upperSurfaces??[]).some(surface=>surface.kind==='roof'&&surface.buildingId===f.b.id)?0:Math.min(getBuildingProfile({...f.b,kind:f.b.kind??f.b.architecture}).roofRise/V,Math.max(.4,f.frame.width*.28));}

test('the authored forge shaft and cap match the actual current source footprint and height in all rotations',()=>{
 for(const rotation of rotations){const f=fixture(rotation),direct=source(f),building=f.build(),node=f.feature(building),brick=node.children.find(mesh=>mesh.material.name==='world:brick'),height=building.userData.height,rise=actualRise(f),parts=[boxBounds(f,brick,0,36),boxBounds(f,brick,36,36)];assert.equal(brick.geometry.getAttribute('position').count,72);supported(f,node);
  for(const [n,label]of [[0,'forge-chimney'],[1,'chimney-cap']]){const bounds=sourceBounds(f,direct[label]);for(const key of ['u0','u1','v0','v1'])near(parts[n][key],bounds[key],`${rotation}/${label}/${key}`);}
  const sourceHeight=getBuildingProfile(f.b).wallHeight,sourceRise=getBuildingProfile(f.b).roofRise;near(parts[0].y0,height+(direct['forge-chimney'].bottom-sourceHeight)/V,'source shaft bottom');near(parts[0].y1,height+rise+(direct['chimney-cap'].bottom-sourceHeight-sourceRise)/V,'body joins the cap');near(parts[1].y1,height+rise+(direct['chimney-cap'].top-sourceHeight-sourceRise)/V,'source cap top');assert.ok(parts[1].y1-height-rise>1.59,'the broad brick cap must clear the actual roof by the source height');f.dispose(building);
 }
});

test('the forge retains the source inset dark flue plane above the broad brick cap',()=>{
 for(const rotation of rotations){const f=fixture(rotation),direct=source(f),building=f.build(),node=f.feature(building),mesh=node.children.find(mesh=>mesh.material.name==='world:forge-flue'),native=boxBounds(f,mesh),sourceZ=direct['chimney-cap'].top+.3,projected=direct.flue.points.split(' ').map(pair=>pair.split(',').map(Number)),points=projected.map(([sx,sy])=>local(f,((sx/26+(sy+sourceZ)/14)*.5)*T,(((sy+sourceZ)/14-sx/26)*.5)*T));assert.equal(mesh.material.color.getHexString(),direct.flue.fill.slice(1));near(native.u0,Math.min(...points.map(p=>p.u)),'source flue left');near(native.u1,Math.max(...points.map(p=>p.u)),'source flue right');near(native.v0,Math.min(...points.map(p=>p.v)),'source flue front');near(native.v1,Math.max(...points.map(p=>p.v)),'source flue back');near(native.y0,native.y1,'flue is the retained flat aperture plane');near(native.y1,building.userData.height+actualRise(f)+40.3/V,'flue follows the source cap height');assert.equal(mesh.geometry.getAttribute('position').count,6);f.dispose(building);}
});

test('forge source masonry preserves standing openings and uses intact edited side supports through four rotations',()=>{
 for(const rotation of rotations){const f=fixture(rotation);f.frame.door.open=true;const building=f.build(),node=f.feature(building);for(const offset of [-.20,0,.20])for(const y of [1.3,1.8]){const start=f.point(f.frame.doorU,-1,y).add(new Vector3(offset*f.frame.u.x,0,offset*f.frame.u.y));assert.equal(new Raycaster(start,new Vector3(f.frame.v.x,0,f.frame.v.y),0,T*1.6).intersectObject(building,true).length,0);}for(const tile of f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id&&tile.type==='window')){const onX=tile.x===f.b.x||tile.x===f.b.x+f.b.width-1,sign=onX?(tile.x===f.b.x?-1:1):(tile.y===f.b.y?-1:1),start=onX?new Vector3((tile.x+sign)*T,1.3,tile.y*T):new Vector3(tile.x*T,1.3,(tile.y+sign)*T),direction=onX?new Vector3(-sign,0,0):new Vector3(0,0,-sign);assert.equal(new Raycaster(start,direction,0,T*1.6).intersectObject(node,true).length,0);}const old=new Box3().setFromObject(node).getCenter(new Vector3()),oldCell={x:Math.round(old.x/T),y:Math.round(old.z/T)};f.dispose(building);
  for(const type of ['door','window','rubble']){const edited=fixture(rotation),target=edited.input.terrain.tiles.find(tile=>tile.x===oldCell.x&&tile.y===oldCell.y);target.type=type;edited.input.terrain.tiles=[edited.frame.door,...edited.input.terrain.tiles.filter(tile=>tile!==edited.frame.door)];const object=edited.build(),chimney=edited.feature(object),centre=new Box3().setFromObject(chimney).getCenter(new Vector3());assert.ok(chimney);supported(edited,chimney);assert.notEqual(`${Math.round(centre.x/T)},${Math.round(centre.z/T)}`,`${oldCell.x},${oldCell.y}`,'an edited opening cannot bear the chimney');edited.dispose(object);}
  const fallback=fixture(rotation);for(let v=1;v<fallback.frame.depth;v++){const p=fallback.frame.at(fallback.frame.width,v);fallback.input.terrain.tiles.find(tile=>tile.x===p.x&&tile.y===p.y).type='window';}const object=fallback.build(),chimney=fallback.feature(object),centre=new Box3().setFromObject(chimney).getCenter(new Vector3()),position=local(fallback,centre.x,centre.z);near(position.u,0,'the released alternate side support remains available after an edited source side');supported(fallback,chimney);fallback.dispose(object);
  for(const type of ['door','window','rubble']){const corner=fixture(rotation),p=corner.frame.at(0,0);corner.input.terrain.tiles.find(tile=>tile.x===p.x&&tile.y===p.y).type=type;corner.input.terrain.tiles=[corner.frame.door,...corner.input.terrain.tiles.filter(tile=>tile!==corner.frame.door)];const object=corner.build();supported(corner,corner.feature(object));corner.dispose(object);}
 }
});

test('forge brick is the retained local source volume on every saved wall paint and roof finish',()=>{
 for(const finish of ['adobe','limewash','ochre','stone','brick'])for(const rotation of rotations){const f=fixture(rotation);f.b.wallFinish=finish;f.b.roofFinish=['clay','aged','thatch'][rotation/90%3];const direct=source(f),building=f.build(),node=f.feature(building),brick=node.children.find(mesh=>mesh.material.name==='world:brick').material;assert.equal(direct['forge-chimney'].texture,'brick');assert.equal(direct['chimney-cap'].texture,'brick');assert.equal(brick.color.getHexString(),direct['forge-chimney'].palette.base.slice(1));assert.equal(brick.userData.architectureFinish.texture,'/art/architecture-brick-v2.png');assert.equal(brick.userData.architectureFinish.textureOpacity,.60);assert.equal(brick.userData.architectureFinish.multiplyOpacity,0);assert.ok(building.getObjectByName(`building-fabric:${f.b.id}`).children.some(mesh=>mesh.material.name===`world:${finish}`&&mesh.material.userData.architectureFinish.role==='wall'));assert.ok(building.getObjectByName(`building-fabric:${f.b.id}`).children.some(mesh=>mesh.material?.name===`world:${f.b.roofFinish}`),'the main roof keeps its saved finish');assert.ok(building.getObjectByName(`building-detail:${f.b.id}:forge-canopy`).children.some(mesh=>mesh.material?.name===`world:${f.b.roofFinish==='thatch'?'clay':f.b.roofFinish}`),'the porch keeps its retained thatch-to-clay source exception');f.dispose(building);}
});

test('forge height follows real slabs and terrace roofs and preserves all usable upper routes',()=>{
 for(const rotation of rotations){for(const roof of ['slab','terrace']){const f=fixture(rotation,'exterior',roof),building=f.build(),node=f.feature(building);assert.ok(node);near(new Box3().setFromObject(node).max.y,building.userData.height+40.3/V,'a real flat roof must not retain template pitch');supported(f,node);f.dispose(building);}
  const short=fixture(rotation,'exterior','slab');short.input.terrain.upperSurfaces=short.input.terrain.upperSurfaces.map(surface=>({...surface,elevation:1.8}));const object=short.build();near(new Box3().setFromObject(short.feature(object)).min.y,1.8-1/V,'short slab chimney bottom');near(new Box3().setFromObject(short.feature(object)).max.y,1.8+40.3/V,'short slab chimney top');supported(short,short.feature(object));short.dispose(object);
  const route=fixture(rotation,'exterior','roof-route'),walkable=route.build();assert.equal(route.feature(walkable),undefined,'a real roof route cannot contain a decorative chimney');route.dispose(walkable);
  for(const blocked of [false,true])for(const elevation of [2.2,6]){const f=fixture(rotation);f.input.terrain.upperSurfaces=f.input.terrain.tiles.filter(tile=>tile.type==='wall').map(tile=>({...tile,type:'floor',kind:'platform',tacticalLevel:1,elevation,blocked}));const building=f.build();assert.equal(Boolean(f.feature(building)),blocked||elevation===6,'blocked cells and platforms above the cap retain the chimney; occupied lower routes omit it');f.dispose(building);}
  const unsupported=fixture(rotation);for(const tile of unsupported.input.terrain.tiles.filter(tile=>tile.type==='wall'))tile.type='window';const empty=unsupported.build();assert.equal(unsupported.feature(empty),undefined);unsupported.dispose(empty);
 }
});

test('forge disclosure and unpainted legacy chimney geometry retain their released behavior',()=>{
 for(const rotation of rotations){for(const view of ['partial','interior']){const f=fixture(rotation,view),building=f.build();assert.equal(f.feature(building),undefined);f.dispose(building);}
  const f=fixture(rotation);f.b.architecture='smithy';f.b.kind=undefined;f.b.wallFinish=undefined;const building=f.build(),node=f.feature(building),brick=node.children.find(mesh=>mesh.material.name==='world:brick'),trim=node.children.find(mesh=>mesh.material.name==='world:trim'),body=boxBounds(f,brick);near(body.u1-body.u0,.42,'released legacy shaft width');near(body.v1-body.v0,.42,'released legacy shaft depth');near(body.y0,building.userData.height-.12,'released legacy bottom');near(body.y1,building.userData.height+actualRise(f)+1.08,'released legacy top');const cap=boxBounds(f,trim);near(cap.u1-cap.u0,.56,'released legacy cap width');near(cap.v1-cap.v0,.56,'released legacy cap depth');assert.equal(brick.material,f.materials.get('brick'));assert.equal(brick.material.userData.architectureFinish,undefined);assert.equal(node.children.some(mesh=>mesh.material.name==='world:forge-flue'),false);supported(f,node);f.dispose(building);
  const painted=fixture(rotation);painted.b.architecture='smithy';painted.b.kind=undefined;painted.b.wallFinish='limewash';const authored=painted.build(),face=painted.feature(authored),localBrick=face.children.find(mesh=>mesh.material.name==='world:brick');near(boxBounds(painted,localBrick,0,36).u1-boxBounds(painted,localBrick,0,36).u0,.58,'an explicit saved finish enables the authored source shaft');assert.equal(localBrick.material.userData.architectureFinish.textureOpacity,.60);assert.equal(localBrick.material.color.getHexString(),'9b6849');supported(painted,face);painted.dispose(authored);
 }
});

test('local forge brick retains metre UV courses and ordinary day and night vertex lighting',()=>{
 for(const rotation of rotations)for(const night of [false,true]){const f=fixture(rotation);f.input.terrain.night=night;f.input.illumination={[`0:${f.b.x},${f.b.y}`]:.5};const building=f.build(),node=f.feature(building),expected=night?.27+.73*.5:1;for(const mesh of node.children){const p=mesh.geometry.getAttribute('position'),uv=mesh.geometry.getAttribute('uv'),normal=mesh.geometry.getAttribute('normal'),colour=mesh.geometry.getAttribute('color');let courses=0;for(let n=0;n<p.count;n++){for(const key of ['getX','getY','getZ'])near(colour[key](n),expected,'ordinary source light');if(n%3===0&&Math.abs(normal.getY(n))<.5)for(const next of [n+1,n+2])if(Math.abs(p.getY(n)-p.getY(next))>.1){near(Math.abs(uv.getY(n)-uv.getY(next)),Math.abs(p.getY(n)-p.getY(next)),'metric brick texture');courses++;}}if(mesh.material.name==='world:brick')assert.ok(courses>0);}f.dispose(building);}
});
