import{register}from'node:module';register('./tactical-render-loader.mjs',import.meta.url);
import assert from'node:assert/strict';import test from'node:test';import{Vector3}from'../web/node_modules/three/build/three.module.js';import{publishedActor}from'./published-actor-fixture.mjs';
const{ActorRuntime}=await import('../web/lib/three/actor-runtime.ts');const{presentActors}=await import('../web/lib/three/presentation.ts');const{createBattle,presentedActBattle,actBattle,actionCosts,reloadPlan,reprimePlan,firearmMaintenancePreview,equipmentUnloadPreview}=await import('../game/tactical.js');const{presentedFrameDuration}=await import('../web/lib/useEnemyPlayback.ts');const{equipmentFingerprint}=await import('../game/tactical-inventory.js');const{admittedReloadWork}=await import('../web/lib/three/action-timing.ts');
test('all114 ordinary prone firearm routes retain full boots, native placement and paid owned rounds',async t=>{
const tasks=[...['1800','1801','1802','1803','1804','1807'].map(weapon=>({type:'unloadAmmunition',weapon:Number(weapon)})),{type:'reprime',weapon:1800},{type:'repair',weapon:1800},...[1805,1806,1808].map(weapon=>({type:'reload',weapon})),...['aim','firePoint','reprime','repair','unloadAmmunition'].map(type=>({type,weapon:1805})),{type:'reload',weapon:1805,paired:true},{type:'reload',weapon:1808,paired:true,exploration:true},{type:'reprime',weapon:1805,paired:true}],results=[];
for(const appearance of['granadero','woman-scout'])for(const lod of[0,1,2]){
 const asset=await publishedActor(appearance,lod);
 for(const task of tasks){
 const loading=task.type==='reload',weapon=task.weapon,state=createBattle([{id:'worker',name:'Prone firearm worker',x:2,y:2,facing:2,weapon,activeSlot:'primary',weaponInstanceId:'owned-right',loaded:loading?0:weapon===1808?2:1,ammo:8,condition:task.type==='repair'?61:91,jammed:task.type==='reprime',toolkitPoints:50,energy:100,stance:'prone',movementMode:'prone',spriteAppearance:appearance,agility:90,dexterity:90,wisdom:90,strength:90,experienceLevel:7,...(task.paired?{leftHandItem:'offhand',offHand:{weapon:task.type==='reload'&&weapon===1808?1808:1806,loaded:loading?0:1,condition:73,jammed:task.type==='reprime',count:1,weight:1.2,instanceId:'owned-left'}}:{})}],{width:24,height:8,seed:45,tiles:Array.from({length:192},(_,i)=>({x:i%24,y:Math.floor(i/24),type:'grass',blocked:false,cover:0})),exploration:Boolean(task.exploration),enemies:task.exploration?[]:[{id:'far',x:22,y:6,weapon:0,patrol:false,overwatch:false}]});state.deploymentComplete=true;state.units[0].ap=100;
 const before=JSON.stringify(state),unit=s=>s.units.find(u=>u.id==='worker'),show=(s,mode,frame,now)=>presentActors(s,[{key:'unit:worker',kind:'unit',actor:unit(s)}],{},new Set(),{selected:'worker',mode,frame,now})[0],actor=new ActorRuntime(asset,show(state,'move',undefined,0)),mesh=actor.model.getObjectByName(asset.appearance.parts.footwear.replace('{lod}',String(lod))),native=new Map();actor.model.traverse(n=>{if(n.isBone)native.set(n.name,{position:n.position.clone(),scale:n.scale.clone()});});
 let minimum=Infinity,maximumContact=0,maximumSpeed=0,prior,priorNow,baselineMinimum;const seen=new Set(),admittedWork=new Set(),playedWork=new Set();
 const sample=(shown,time)=>{const dt=priorNow===undefined?0:(time-priorNow)/1000;actor.update(shown,time);actor.tick(Math.min(.1,Math.max(0,dt)),time);actor.root.updateMatrixWorld(true);mesh.skeleton.update();const points=[],feet={l:Infinity,r:Infinity};for(let i=0;i<mesh.geometry.attributes.position.count;i++){const p=mesh.getVertexPosition(i,new Vector3()).applyMatrix4(mesh.matrixWorld);p.y-=shown.position[1];points.push(p);const side=mesh.geometry.attributes.position.getX(i)>0?'l':'r';feet[side]=Math.min(feet[side],p.y);if(prior&&dt>1e-6)maximumSpeed=Math.max(maximumSpeed,p.distanceTo(prior[i])/dt);}minimum=Math.min(minimum,feet.l,feet.r);maximumContact=Math.max(maximumContact,feet.l,feet.r);prior=points;priorNow=time;assert.deepEqual(actor.root.position.toArray(),shown.position);assert.equal(actor.root.rotation.y,shown.yaw);for(const[n,shape]of native){const bone=actor.model.getObjectByName(n);if(n!=='Root')assert.ok(bone.position.distanceTo(shape.position)<1e-6,n+' native offset');assert.ok(bone.scale.distanceTo(shape.scale)<1e-6,n+' native scale');}seen.add(actor.action.getClip().name);if(shown.action==='reload'&&actor.action.getClip().name.includes('.reload.'))playedWork.add((actor.actionHand==='handLeft'?'offhand':'primary')+':'+actor.actionBarrel);for(const w of shown.cue?.work??[])admittedWork.add(w.hand+':'+(w.barrel??0));return Math.min(feet.l,feet.r);};
 try{
 for(let i=0;i<=30;i++)sample(show(state,'move',undefined,i*1000/60),i*1000/60);baselineMinimum=minimum;let totalDuration=0,apCost=0,paidState=state;
 if(task.type==='aim'){
  for(let i=1;i<=30;i++){const now=500+i*1000/60;sample(show(state,'fire',undefined,now),now);}
  for(let i=1;i<=30;i++){const now=1000+i*1000/60;sample(show(state,'move',undefined,now),now);}
 }else{
  const order={type:task.type,unitId:'worker',...(task.type==='firePoint'?{x:9,y:2,part:'torso',aim:0}:{})},outcome=presentedActBattle(state,order);assert.equal(outcome.state.lastError,null,outcome.state.lastError);assert.deepEqual(outcome.state,actBattle(state,order));assert.equal(JSON.stringify(state),before);paidState=outcome.state;apCost=unit(state).ap-unit(outcome.state).ap;assert.ok(task.exploration?apCost===0:apCost>0,'The actual accepted work follows combat/exploration payment');const expectedAP=task.exploration?0:task.type==='reload'?reloadPlan(unit(state),state).pa:task.type==='reprime'?reprimePlan(unit(state),state).pa:task.type==='repair'?firearmMaintenancePreview(state,unit(state)).pa:task.type==='unloadAmmunition'?equipmentUnloadPreview(state,unit(state),{hostId:'hand:right',expectedHost:equipmentFingerprint(unit(state),'hand:right')}).pa:actionCosts(state,unit(state)).fire;assert.equal(apCost,expectedAP,'One exact paid AP charge');
  const frames=task.type==='reload'?admittedReloadWork(outcome.frames):outcome.frames,durations=frames.map(f=>presentedFrameDuration(f,state));totalDuration=durations.reduce((a,b)=>a+b,0);let start=500;
  for(const[index,f]of frames.entries()){
   const duration=durations[index],frame={...f,index,sequenceId:'prone-work-review',actionId:1,startedAt:start,durationMs:duration,actionStartedAt:500,actionDurationMs:totalDuration},stop=start+duration;
   for(let t=start;t<stop-1e-5;t+=1000/60)sample(show(f.state,'move',frame,t),t);
   if(!duration)sample(show(f.state,'move',frame,start),start);start=stop;
  }
  for(let i=1;i<=40;i++){const now=start+i*1000/60;sample(show(outcome.state,'move',undefined,now),now);}
  assert.equal(unit(paidState).weaponInstanceId,'owned-right');if(task.paired)assert.equal(unit(paidState).offHand.instanceId,'owned-left');
  const rounds=u=>u.ammo+u.loaded+(u.offHand?.loaded??0);assert.equal(rounds(unit(paidState)),rounds(unit(state))-(task.type==='firePoint'?1:0),'No owned rounds appear or vanish outside the paid shot');
 }
 if(task.type==='reload'&&task.paired){assert.deepEqual([...admittedWork].sort(),task.exploration?['offhand:0','offhand:1','primary:0','primary:1']:['offhand:0','primary:0']);assert.deepEqual([...playedWork].sort(),[...admittedWork].sort(),'Each admitted hand/barrel interval must actually play');if(!task.exploration)assert.ok(seen.has('prone.reload.short-gun.1806:left-hand'),'The actual paid second hand uses its owned1806 clip');}
 const equipment=weapon<1805||weapon===1807?'long-gun':'short-gun',gesture={firePoint:'fire',unloadAmmunition:'unload'}[task.type]??task.type,expected=gesture==='reload'?`prone.reload.short-gun.${weapon}`:gesture==='unload'&&equipment==='long-gun'?`prone.unload.long-gun.${weapon}`:`prone.${gesture}.${equipment}`;assert.ok(seen.has(expected),expected+' must be selected by actual admitted presentation');
 const row={appearance,lod,task,baselineMinimum,minimum,maximumContact,maximumSpeed,apCost,totalDuration,seen:[...seen],admittedWork:[...admittedWork],playedWork:[...playedWork],nativeDimensions:'exact',wrapper:'exact'};results.push(row);
 }finally{actor.dispose();}
 }
}
for(const r of results){assert.ok(r.minimum>0,'Complete native boot floor');assert.ok(r.maximumContact<.003,'Both native boot contacts');assert.ok(r.maximumSpeed<.0001,'Static native boot speed');}assert.equal(results.length,114);t.diagnostic(JSON.stringify({checks:results.length,minimum:Math.min(...results.map(r=>r.minimum)),maximumContact:Math.max(...results.map(r=>r.maximumContact)),maximumSpeed:Math.max(...results.map(r=>r.maximumSpeed))}));
});
