import assert from 'node:assert/strict';
import test from 'node:test';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {ActorRuntime}=await import('../web/lib/three/actor-runtime.ts');
const {NativeMeleeContactFit:NativeFit}=await import('../web/lib/three/melee-contact-fit.ts');
const {runFitJob}=await import('../web/lib/three/melee-fit-worker.ts');
const {presentActors}=await import('../web/lib/three/presentation.ts');
const {resolveContactTargetModel}=await import('../web/lib/three/contact-target-model.ts');
const {publishedActor}=await import('./published-actor-fixture.mjs');
const {createBattle,presentedActBattle,actBattle}=await import('../game/tactical.js');
const {Group,InterpolateDiscrete}=await import('../web/node_modules/three/build/three.module.js');
// Keep the current tested consumer, mixer, pose transitions and renderer.
// Only the reference admission method uses the unchanged original helper.
function originalRuntime(...args){const runtime=new ActorRuntime(...args);runtime.meleeFit.apply=NativeFit.prototype.apply;return runtime;}
async function pair(appearance='granadero',diagonal=false,posture='standing',weapon=1800,lod=0,options={}){
 const squad=[{id:'sabre',name:'Culata',x:6,y:10,facing:2,spriteAppearance:appearance,weapon,weaponInstanceId:'rifle-butt-owned',activeSlot:'primary',weaponMode:'melee',loaded:1,ammo:12,blade:0,condition:81,agility:90,dexterity:85,strength:85,wisdom:80,experienceLevel:7,energy:100,stance:'standing',movementMode:'walk',skinTone:'brown',headwear:null,outfit:null,legwear:null}],enemy={id:'target-sabre',name:'Realista',x:7,y:10+(diagonal?1:0),facing:6,weapon:1800,loaded:1,ammo:6,hp:100,morale:100,patrol:false,overwatch:false,marksmanship:55,spriteAppearance:'royalist',skinTone:'light',stance:posture,movementMode:posture==='crouched'?'crouch':'walk'};
 if(options.offhand)squad[0].offHand={weapon:1806,loaded:1,count:1,weight:1.2,condition:57,jammed:false,instanceId:'rifle-butt-owned-left'};
 const state=createBattle(squad,{id:'rifle-butt-contact',width:24,height:20,seed:45,tiles:Array.from({length:480},(_,i)=>({x:i%24,y:Math.floor(i/24),type:'grass',blocked:false,cover:0})),enemies:[enemy,{id:'reserve',x:22,y:18,patrol:false,overwatch:false}]});
 for(const actor of state.units)actor.ap=actor.id==='sabre'?100:0;const unit=state.units.find(unit=>unit.id==='sabre'),target=state.units.find(unit=>unit.id==='target-sabre');
 if(options.bayonet)unit.weaponFittings={bayonet:{weapon:1811,fittingPattern:'india_socket',condition:80,instanceId:'owned-fixed-bayonet'}};
 const before=JSON.stringify(state),result=presentedActBattle(state,{type:'melee',unitId:unit.id,targetId:target.id}),contact=result.frames.find(frame=>frame.type==='contact');
 assert.ok(contact,`The real rules admit one paid strike: ${result.state.lastError}`);assert.equal(JSON.stringify(state),before);assert.deepEqual(result.state,actBattle(state,{type:'melee',unitId:unit.id,targetId:target.id}));
 assert.equal(result.frames.filter(frame=>frame.type==='contact'&&frame.unitId===unit.id).length,1);assert.equal(result.state.units.find(actor=>actor.id===unit.id).loaded,unit.loaded);assert.equal(result.state.units.find(actor=>actor.id===unit.id).ammo,unit.ammo);
 const frame={...contact,sequenceId:'rifle-butt-contact-review',actionId:1,index:1,startedAt:420,durationMs:650,actionStartedAt:0,actionDurationMs:1970};
 const admitted=frame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:`unit:${actor.id}`,kind:'unit',actor})),actors=presentActors(frame.state,admitted,{},new Set(),{frame,now:420}),attacker=actors.find(actor=>actor.id==='sabre'),defender=actors.find(actor=>actor.id==='target-sabre');
 assert.ok(attacker.cue.contactTarget);assert.ok(attacker.cue.contactSupport.floors.length);
 const [asset,other]=await Promise.all([publishedActor(appearance,lod),publishedActor(defender.appearance,lod)]),body=new ActorRuntime(other,defender);body.tick(.1,1070);body.root.updateMatrixWorld(true);
 return {attacker,defender,asset,body,frame,result,state,weapon};
}

async function fixtureFor(appearance,diagonal,posture,weapon,lod=0){
 const f=await pair(appearance,diagonal,posture,weapon,lod),raw=f.result.frames.find(frame=>frame.type==='prepare'),frame={...raw,sequenceId:'ready-review',actionId:1,index:0,startedAt:0,durationMs:420,actionStartedAt:0,actionDurationMs:1970},entries=frame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:'unit:'+actor.id,kind:'unit',actor})),actors=presentActors(frame.state,entries,{},new Set(),{frame,now:0,selected:'sabre'}),prepared=actors.find(actor=>actor.id==='sabre'),defender=actors.find(actor=>actor.id==='target-sabre');f.body.update(defender,0);f.body.tick(.1,0);f.body.root.updateMatrixWorld(true);
 const resolve=target=>resolveContactTargetModel(target,actors,{visual:defender,runtime:f.body,pending:false,error:false}),idle={...prepared,action:'idle',cue:undefined,contactWarm:{targets:[prepared.cue.contactTarget],support:prepared.cue.contactSupport}};return {...f,prepared,idle,resolve};
}
function workerHarness(){
 const original=Object.getOwnPropertyDescriptor(globalThis,'Worker'),workers=[],settings={constructorFail:false,postFail:false};
 globalThis.Worker=class{jobs=[];terminated=false;constructor(){if(settings.constructorFail)throw Error('controlled constructor failure');workers.push(this);}postMessage(job){if(settings.postFail)throw Error('controlled post failure');this.jobs.push(structuredClone(job));}terminate(){this.terminated=true;}};
 return {workers,settings,restore(){if(original)Object.defineProperty(globalThis,'Worker',original);else delete globalThis.Worker;}};
}
function copyInput(from,to){
 const a=[],b=[];from.root.traverse(node=>a.push(node));to.root.traverse(node=>b.push(node));assert.equal(a.length,b.length);
 for(let i=0;i<a.length;i++){const src=a[i],dst=b[i];assert.equal(src.name,dst.name);dst.position.copy(src.position);dst.quaternion.copy(src.quaternion);dst.scale.copy(src.scale);dst.matrix.copy(src.matrix);dst.matrixAutoUpdate=src.matrixAutoUpdate;dst.visible=src.visible;
  if(src.geometry){dst.geometry=src.geometry;if(src.morphTargetInfluences)dst.morphTargetInfluences=[...src.morphTargetInfluences];}
  if(src.isSkinnedMesh){dst.bindMode=src.bindMode;dst.bindMatrix.copy(src.bindMatrix);dst.bindMatrixInverse.copy(src.bindMatrixInverse);}
 }
 to.root.parent.visible=from.root.parent.visible;to.root.updateMatrixWorld(true);
 for(const [name,limb]of from.meleeFit.limbs){const target=to.meleeFit.limbs.get(name);target.first=limb.first;target.second=limb.second;}
 to.meleeFit.nativeGait.speed=from.meleeFit.nativeGait.speed;
}
let template;
async function context(harness){
 const f=await fixtureFor('granadero',false,'standing',1800),parent=new Group(),ownParent=new Group();parent.add(f.body.root);let model=f.body.model,targetRoot=f.body.root,trap=false,reads=0,modelReads=0;
 const resolve=()=>{reads++;return {root:targetRoot,get model(){modelReads++;assert.equal(trap,false,'An ancestor-hidden target model getter must stay unread');return model;}};};
 const runtime=new ActorRuntime(f.asset,f.idle,undefined,resolve),original=originalRuntime(f.asset,f.idle,undefined,resolve),originalParent=new Group();ownParent.add(runtime.root);originalParent.add(original.root);runtime.tick(.1,0);original.tick(.1,0);const fit=runtime.meleeFit,clip=f.asset.animation.animations.find(clip=>clip.name==='stand.butt.long-gun'),spec=f.asset.clips.find(spec=>spec.name==='stand.butt.long-gun'),gun=runtime.equipment.userData.attached.find(item=>item.userData.hand==='handRight'),cue=structuredClone(f.prepared.cue),warm={targets:[cue.contactTarget],support:cue.contactSupport};assert.ok(gun);
 const ctx={f,runtime,original,fit,clip,spec,gun,cue,warm,resolve,parent,ownParent,get reads(){return reads;},get modelReads(){return modelReads;},set model(value){model=value;},set targetRoot(value){targetRoot=value;},set trap(value){trap=value;},resetReads(){reads=0;modelReads=0;},dispose(){runtime.dispose();original.dispose();f.body.dispose();}};
 ctx.warmNow=()=>{const count=harness.workers.reduce((sum,worker)=>sum+worker.jobs.length,0);fit.prewarm(warm,clip,spec,gun,resolve);const worker=harness.workers.at(-1),job=worker?.jobs.at(-1);return {worker,job,added:harness.workers.reduce((sum,worker)=>sum+worker.jobs.length,0)-count};};
 ctx.packet=job=>{if(!template)template=runFitJob(job);return {...structuredClone(template),id:job.id};};ctx.apply=(next=cue,time=0)=>{
  if(ctx.delegationOnly){
   // Deliberately altered clips/gait may trigger an expensive original no-plan
   // search. This boundary case checks exact delegation; native physical
   // gates are tested with supported paid fixtures below.
   const originalApply=NativeFit.prototype.apply;let calls=0;
   NativeFit.prototype.apply=function(...args){calls++;assert.equal(this,fit);assert.deepEqual(args,[next,clip,spec,ctx.gun,time,resolve]);assert.equal(this.sample,undefined);assert.equal(this.previewFit,undefined);};
   try{fit.apply(next,clip,spec,ctx.gun,time,resolve);}finally{NativeFit.prototype.apply=originalApply;}
   assert.equal(calls,1);ctx.originalCompared=true;ctx.delegationCompared=true;return;
  }
  copyInput(runtime,original);const originalGun=ctx.gun===gun?original.equipment.userData.attached.find(item=>item.userData.hand==='handRight'):ctx.gun.clone(true);
  NativeFit.prototype.apply.call(original.meleeFit,next,clip,spec,originalGun,time,resolve);
  fit.apply(next,clip,spec,ctx.gun,time,resolve);
  assert.deepEqual(planState(fit),planState(original.meleeFit),'Fallback keeps the exact original first physical recipe');assert.deepEqual(shape(runtime),shape(original),'Fallback keeps every original rendered bone coordinate');ctx.originalCompared=true;
 };return ctx;
}
function noPlan(ctx){assert.equal(ctx.originalCompared,true,'Supported stale input is compared with the current original physical fitter');assert.equal(ctx.fit.fallbackCue,ctx.cue.id,'Invalid readiness latches the original physical path for this entire paid cue');}
function shape(runtime){runtime.root.updateMatrixWorld(true);const values=[...runtime.root.matrixWorld.elements];runtime.model.traverse(node=>{if(node.isBone)values.push(...node.position.toArray(),...node.quaternion.toArray(),...node.scale.toArray(),...node.matrixWorld.elements);});return values;}
const mutations={
 'hidden target ancestor':ctx=>{ctx.parent.visible=false;ctx.trap=true;return()=>{ctx.parent.visible=true;ctx.trap=false;};},
 'replaced target model':ctx=>{ctx.model=ctx.f.body.model.clone(true);return()=>{ctx.model=ctx.f.body.model;};},
 'replaced target root':ctx=>{ctx.targetRoot=new Group();return()=>{ctx.targetRoot=ctx.f.body.root;};},
 'hidden own ancestor':ctx=>{ctx.ownParent.visible=false;return()=>{ctx.ownParent.visible=true;};},
 'changed own model transform':ctx=>{ctx.runtime.model.position.x+=.01;return()=>{ctx.runtime.model.position.x-=.01;};},
 'changed own root pitch':ctx=>{ctx.runtime.root.rotation.x=.1;return()=>{ctx.runtime.root.rotation.x=0;};},
 'changed own visible skin':ctx=>{let mesh;ctx.runtime.model.traverse(node=>{if(!mesh&&node.isSkinnedMesh&&node.visible)mesh=node;});mesh.visible=false;return()=>{mesh.visible=true;};},
 'changed own skin geometry':ctx=>{const mesh=ctx.fit.completeBoot.mesh,old=mesh.geometry;mesh.geometry=old.clone();mesh.geometry.attributes.position.setX(0,mesh.geometry.attributes.position.getX(0)+.001);return()=>{const modified=mesh.geometry;mesh.geometry=old;modified.dispose();};},
 'changed own inverse bind':ctx=>{const mesh=ctx.fit.completeBoot.mesh,value=mesh.skeleton.boneInverses[0].elements[12];mesh.skeleton.boneInverses[0].elements[12]+=.001;return()=>{mesh.skeleton.boneInverses[0].elements[12]=value;};},
 'changed clip sample':ctx=>{const track=ctx.clip.tracks[0],value=track.values[0];track.values[0]+=.001;return()=>{track.values[0]=value;};},
 'changed clip interpolation':ctx=>{const track=ctx.clip.tracks[0],value=track.getInterpolation();track.setInterpolation(InterpolateDiscrete);return()=>{track.setInterpolation(value);};},
 'changed gait sample':ctx=>{const track=ctx.fit.nativeGait.clip.tracks[0],value=track.values[0];track.values[0]+=.001;return()=>{track.values[0]=value;};},
 'changed numeric gait speed':ctx=>{const value=ctx.fit.nativeGait.speed;ctx.fit.nativeGait.speed=value/100;return()=>{ctx.fit.nativeGait.speed=value;};},
 'changed disclosed floor':ctx=>{const value=ctx.warm.support.floors[0].maxX;ctx.warm.support.floors[0].maxX+=.01;return()=>{ctx.warm.support.floors[0].maxX=value;};},
 'changed target posture':ctx=>{const value=ctx.warm.targets[0].posture;ctx.warm.targets[0].posture='crouched';return()=>{ctx.warm.targets[0].posture=value;};},
 'changed current source calibration':ctx=>{const limb=ctx.fit.limbs.get('hand_r'),value=limb.first;limb.first+=.01;return()=>{limb.first=value;};},
};
test('current composed ready-worker guards preserve original physical fallback, identity and paid clocks',async t=>{
 const harness=workerHarness(),receipt={checks:[]};
 async function check(name,call){await t.test(name,call);receipt.checks.push(name);}
 try{
  await check('unsupported native input reads no target or packet',async()=>{const c=await context(harness);try{const before=harness.workers.length;c.resetReads();for(const change of [{mounted:true,posture:'mounted'},{mounted:false,posture:'prone'}])c.fit.prewarm({...c.warm,targets:[{...c.cue.contactTarget,...change}]},c.clip,c.spec,c.gun,c.resolve);c.fit.prewarm(c.warm,c.clip,{...c.spec,name:'stand.thrust.long-gun'},c.gun,c.resolve);assert.equal(c.reads,0);assert.equal(harness.workers.length,before);}finally{c.dispose();}});
  await check('ancestor-hidden capture never reads target model',async()=>{const c=await context(harness);try{c.parent.visible=false;c.trap=true;c.resetReads();const result=c.warmNow();assert.equal(result.added,0);assert.equal(c.modelReads,0);}finally{c.parent.visible=true;c.trap=false;c.dispose();}});
  for(const [name,mutate]of Object.entries(mutations))for(const phase of ['delivery','paid apply']){
   // Constructor calibration is rechecked at paid application. It is not a
   // gate on delivery of pose-independent data; no plan is installed there.
   if(name==='changed current source calibration'&&phase==='delivery')continue;
   await check(name+' at '+phase,async()=>{const c=await context(harness);let restore;try{const {worker,job}=c.warmNow();assert.ok(job);const packet=c.packet(job);if(phase==='paid apply'){worker.onmessage({data:packet});assert.ok(c.fit.ready);}const visibleModelReads=c.modelReads;restore=mutate(c);if(phase==='paid apply'&&/^(changed clip|changed gait|changed numeric gait)/.test(name))c.delegationOnly=true;if(phase==='delivery'){worker.onmessage({data:packet});assert.equal(c.fit.ready,undefined,'Changed lease cannot accept a stale delivery');}else{c.apply();noPlan(c);}if(name==='hidden target ancestor')assert.equal(c.modelReads,visibleModelReads,'No hidden model getter is read at stale delivery or paid apply');}finally{restore?.();c.dispose();}});
  }
  await check('replaced owned weapon rejects paid apply',async()=>{const c=await context(harness);try{const {worker,job}=c.warmNow();worker.onmessage({data:c.packet(job)});c.gun=new Group();c.gun.userData.itemId='rifle1800';c.apply();noPlan(c);}finally{c.dispose();}});
  await check('same public key rewarms changed visible own geometry',async()=>{const c=await context(harness);let restore;try{const {worker,job}=c.warmNow();worker.onmessage({data:c.packet(job)});restore=mutations['changed own visible skin'](c);const before=worker.jobs.length,result=c.warmNow();assert.equal(result.added,1);assert.equal(worker.jobs.length,before+1);assert.equal(c.fit.ready,undefined);}finally{restore?.();c.dispose();}});
  await check('same public key rewarms replaced visible target',async()=>{const c=await context(harness);try{const {worker,job}=c.warmNow();worker.onmessage({data:c.packet(job)});c.model=c.f.body.model.clone(true);assert.equal(c.warmNow().added,1);assert.equal(c.fit.ready,undefined);}finally{c.dispose();}});
  await check('one shared worker has one outstanding packet across two owners',async()=>{const a=await context(harness),b=await context(harness);try{const before=harness.workers.length,{worker,job}=a.warmNow();for(let i=0;i<4;i++){assert.equal(a.warmNow().added,0);assert.equal(b.warmNow().added,0);}assert.equal(harness.workers.length,before+1);assert.equal(worker.jobs.length,1);const reads=b.reads;assert.equal(reads,0);worker.onmessage({data:{id:job.id+99}});assert.equal(b.warmNow().added,0,'A wrong ID cannot release another live owner');worker.onmessage({data:a.packet(job)});assert.equal(b.warmNow().added,1);a.dispose();assert.equal(worker.terminated,false,'Inactive disposal cannot terminate the live other owner');b.dispose();assert.equal(worker.terminated,true,'Active owner disposal terminates its packet and worker');worker.onmessage({data:{id:worker.jobs.at(-1).id,...structuredClone(template)}});assert.equal(b.fit.plan,undefined);}finally{a.dispose();b.dispose();}});
  for(const name of ['constructor failure','postMessage failure','worker error','watchdog expiry'])await check(name+' retains original physical cue playback',async()=>{const c=await context(harness);let undo;try{if(name==='constructor failure')harness.settings.constructorFail=true;if(name==='postMessage failure')harness.settings.postFail=true;if(name==='watchdog expiry'){const set=globalThis.setTimeout,clear=globalThis.clearTimeout;let callback;const marker={};globalThis.setTimeout=(call,ms,...args)=>{if(ms===5000){callback=call;return marker;}return set(call,ms,...args);};globalThis.clearTimeout=value=>{if(value!==marker)return clear(value);};undo=()=>{globalThis.setTimeout=set;globalThis.clearTimeout=clear;};c.warmNow();assert.ok(callback);callback();}else{const {worker}=c.warmNow();if(name==='worker error')worker.onerror({message:'controlled error'});}assert.equal(c.fit.stopped,true);c.apply();noPlan(c);assert.equal(c.warmNow().added,0);}finally{harness.settings.constructorFail=false;harness.settings.postFail=false;undo?.();c.dispose();}});
  await check('late delivery never joins a paid cue or delays its paid clock',async()=>{const c=await context(harness),complete=[],originalComplete=[],native=originalRuntime(c.f.asset,c.f.idle,(key,id)=>originalComplete.push([key,id]),c.resolve);try{c.runtime.onCueComplete=(key,id)=>complete.push([key,id]);native.tick(.1,0);const {worker,job}=c.warmNow();c.runtime.update(c.f.prepared,0);native.update(c.f.prepared,0);c.runtime.tick(1/60,0);native.tick(1/60,0);assert.equal(c.fit.fallbackCue,c.cue.id);assert.deepEqual(planState(c.fit),planState(native.meleeFit));assert.deepEqual(shape(c.runtime),shape(native));worker.onmessage({data:c.packet(job)});assert.ok(c.fit.ready,'Late native data may be stored for a later cue');for(const now of [20,100,240,400]){c.runtime.update(c.f.prepared,now);native.update(c.f.prepared,now);c.runtime.tick(.016,now);native.tick(.016,now);assert.equal(c.fit.usingCue,'','A late packet never installs temporary worker hooks into an original-only cue');assert.deepEqual(planState(c.fit),planState(native.meleeFit));assert.deepEqual(shape(c.runtime),shape(native));assert.equal(c.runtime.action.time,native.action.time);assert.equal(c.runtime.mixer.time,native.mixer.time);assert.equal(c.runtime.visual.cue.phase,native.visual.cue.phase);}
   const raw=c.f.result.frames.find(frame=>frame.type==='contact'),frame={...raw,sequenceId:'ready-review',actionId:1,index:1,startedAt:420,durationMs:650,actionStartedAt:0,actionDurationMs:1970},entries=frame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:'unit:'+actor.id,kind:'unit',actor})),contact=presentActors(frame.state,entries,{},new Set(),{frame,now:420,selected:'sabre'}).find(actor=>actor.id==='sabre');for(const now of [420,600,1000]){c.runtime.update(contact,now);native.update(contact,now);c.runtime.tick(.016,now);native.tick(.016,now);assert.equal(c.fit.usingCue,'','A late packet never installs temporary worker hooks into an original-only cue');assert.deepEqual(planState(c.fit),planState(native.meleeFit));assert.deepEqual(shape(c.runtime),shape(native));assert.equal(c.runtime.action.time,native.action.time);}const impactRaw=c.f.result.frames.find(frame=>frame.type==='impact');assert.ok(impactRaw,'The real paid recorder supplies its finite impact/recovery phase');const impactFrame={...impactRaw,sequenceId:'ready-review',actionId:1,index:2,startedAt:1070,durationMs:900,actionStartedAt:0,actionDurationMs:1970},impactEntries=impactFrame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:'unit:'+actor.id,kind:'unit',actor})),impact=presentActors(impactFrame.state,impactEntries,{},new Set(),{frame:impactFrame,now:1070,selected:'sabre'}).find(actor=>actor.id==='sabre');assert.ok(impact.cue);for(const now of [1070,1400,1969,1970,2000]){c.runtime.update(impact,now);native.update(impact,now);c.runtime.tick(.016,now);native.tick(.016,now);assert.equal(c.fit.usingCue,'','A late packet never installs temporary worker hooks into an original-only cue');assert.deepEqual(planState(c.fit),planState(native.meleeFit));assert.deepEqual(shape(c.runtime),shape(native));assert.equal(c.runtime.action.time,native.action.time);}assert.deepEqual(complete,originalComplete);assert.equal(complete.length,1,'The original physical cue still completes once at the original paid phase time');receipt.lateFrames=13;receipt.completions=1;
  }finally{c.dispose();native.dispose();}});
  await check('caught error reply latches once and sends no unchanged lease retries',async()=>{const c=await context(harness);try{const {worker}=c.warmNow();for(let i=0;i<4;i++){const job=worker.jobs.at(-1);worker.onmessage({data:{id:job.id,error:'controlled source fit error'}});assert.equal(c.fit.ready,undefined);assert.equal(c.warmNow().added,0);}assert.equal(worker.jobs.length,1);assert.equal(c.fit.stopped,true);receipt.sameKeyErrorRetries=0;receipt.errorRetryBackoff=true;}finally{c.dispose();}});
  await check('failed owner leaves the shared worker available and stale error cannot stop another owner',async()=>{const a=await context(harness),b=await context(harness);try{const {worker,job}=a.warmNow();worker.onmessage({data:{id:job.id,error:'controlled source fit error'}});assert.equal(a.fit.stopped,true);assert.equal(worker.terminated,false);const next=b.warmNow();assert.equal(next.worker,worker);assert.equal(next.added,1);worker.onmessage({data:{id:job.id,error:'stale prior owner error'}});assert.equal(b.fit.stopped,false);assert.equal(b.fit.ready,undefined);worker.onmessage({data:b.packet(next.job)});assert.ok(b.fit.ready);assert.equal(b.fit.stopped,false);assert.equal(worker.terminated,false);}finally{a.dispose();b.dispose();}});
  await check('contact-only first observation never uses a ready plan',async()=>{const c=await context(harness);try{const {worker,job}=c.warmNow();worker.onmessage({data:c.packet(job)});c.cue.phase='contact';c.apply();noPlan(c);}finally{c.dispose();}});
  await check('missing first target latches exact fallback even after it returns',async()=>{const c=await context(harness);try{const {worker,job}=c.warmNow();worker.onmessage({data:c.packet(job)});c.apply({...c.cue,contactTarget:undefined},0);noPlan(c);c.apply(c.cue,.1);noPlan(c);}finally{c.dispose();}});
 }finally{harness.restore();}
 t.diagnostic(JSON.stringify({checks:receipt.checks.length,lateFrames:receipt.lateFrames,completions:receipt.completions}));
});
function planState(fit){const p=fit.plan;return p?{body:p.body.toArray(),hand:p.hand.toArray(),step:p.step.toArray(),rearStep:p.rearStep.toArray(),contact:p.contact,duration:p.duration,twoHands:p.twoHands,pistol:p.pistol,turn:p.turn,handRecovery:p.handRecovery,yaw:p.yaw,key:p.key}:null;}
function traceAcceptedPath(fit){
 const prepare=fit.prepare,accepted=[];
 fit.prepare=function(...args){const path=this.pathAllowed;this.pathAllowed=function(plan,...pathArgs){const pf=this.previewFit,pose=pf.pose,times=[];pf.pose=function(p,time){times.push(time);return pose.call(this,p,time);};try{const result=path.call(this,plan,...pathArgs);if(result){assert.deepEqual(times.slice(-241),Array.from({length:241},(_,index)=>index/240),'Every accepted rifle candidate retains all 241 chronological source samples');accepted.push(times.slice(-241));}return result;}finally{pf.pose=pose;}};try{return prepare.apply(this,args);}finally{this.pathAllowed=path;}};
 return {accepted,restore(){fit.prepare=prepare;}};
}
test('ready positive paid rifle pairs preserve the original current consumer and full native gate',async t=>{
 const harness=workerHarness(),rows=[];try{for(const appearance of ['granadero','woman-scout'])for(const diagonal of [false,true]){
  const f=await fixtureFor(appearance,diagonal,'standing',1800),runtime=new ActorRuntime(f.asset,f.idle,undefined,f.resolve),source=originalRuntime(f.asset,f.idle,undefined,f.resolve),trace=traceAcceptedPath(runtime.meleeFit);
  try{runtime.tick(.1,0);source.tick(.1,0);runtime.prewarmContact();const worker=harness.workers.at(-1);assert.ok(worker?.jobs.length);worker.onmessage({data:runFitJob(worker.jobs.at(-1))});assert.ok(runtime.meleeFit.ready,'Only a completed pre-cue proof is ready');runtime.update(f.prepared,0);source.update(f.prepared,0);runtime.tick(1/60,0);source.tick(1/60,0);assert.ok(runtime.meleeFit.plan);assert.deepEqual(planState(runtime.meleeFit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));
   for(const now of [100,240,400]){runtime.update(f.prepared,now);source.update(f.prepared,now);runtime.tick(.06,now);source.tick(.06,now);assert.deepEqual(shape(runtime),shape(source));}
   const raw=f.result.frames.find(frame=>frame.type==='contact'),frame={...raw,sequenceId:'ready-review',actionId:1,index:1,startedAt:420,durationMs:650,actionStartedAt:0,actionDurationMs:1970},entries=frame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:'unit:'+actor.id,kind:'unit',actor})),contact=presentActors(frame.state,entries,{},new Set(),{frame,now:420,selected:'sabre'}).find(actor=>actor.id==='sabre');f.body.tick(.017,420);runtime.update(contact,420);source.update(contact,420);runtime.tick(.02,420);source.tick(.02,420);assert.ok(runtime.meleeFit.plan);assert.deepEqual(planState(runtime.meleeFit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));assert.equal(trace.accepted.length,2,'Preparation and current-target contact are each admitted through the complete path');rows.push({appearance,diagonal,prepare:true,contact:true,chronologicalSamples:482});
  }finally{trace.restore();runtime.dispose();source.dispose();f.body.dispose();}
 }}finally{harness.restore();}t.diagnostic(JSON.stringify({pairs:rows.length,acceptedChronologicalSamples:rows.length*482,actualCoordinateDifference:0}));
});
test('Worker-present free primary pistol stays on the original helper',async t=>{
 const harness=workerHarness(),rows=[];try{for(const appearance of ['granadero','woman-scout'])for(const diagonal of [false,true])for(const posture of ['standing','crouched']){
  const f=await fixtureFor(appearance,diagonal,posture,1806),runtime=new ActorRuntime(f.asset,f.idle,undefined,f.resolve),source=originalRuntime(f.asset,f.idle,undefined,f.resolve);
  try{runtime.tick(.1,0);source.tick(.1,0);const count=harness.workers.length;runtime.prewarmContact();assert.equal(harness.workers.length,count,'A primary pistol cannot submit a rifle prewarm job');runtime.update(f.prepared,0);source.update(f.prepared,0);runtime.tick(1/60,0);source.tick(1/60,0);assert.equal(runtime.clipSpec.name,'stand.butt.short-gun');assert.deepEqual(planState(runtime.meleeFit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));for(const now of [100,240,400]){runtime.update(f.prepared,now);source.update(f.prepared,now);runtime.tick(.06,now);source.tick(.06,now);assert.deepEqual(shape(runtime),shape(source));}
   const raw=f.result.frames.find(frame=>frame.type==='contact'),frame={...raw,sequenceId:'ready-review',actionId:1,index:1,startedAt:420,durationMs:650,actionStartedAt:0,actionDurationMs:1970},entries=frame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:'unit:'+actor.id,kind:'unit',actor})),contact=presentActors(frame.state,entries,{},new Set(),{frame,now:420,selected:'sabre'}).find(actor=>actor.id==='sabre');f.body.tick(.017,420);runtime.update(contact,420);source.update(contact,420);runtime.tick(.02,420);source.tick(.02,420);assert.deepEqual(planState(runtime.meleeFit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));assert.equal(harness.workers.length,count);rows.push({appearance,diagonal,posture,fitted:Boolean(runtime.meleeFit.plan)});
  }finally{runtime.dispose();source.dispose();f.body.dispose();}
 }}finally{harness.restore();}assert.equal(rows.filter(row=>row.fitted).length,8);assert.equal(harness.workers.length,0);t.diagnostic(JSON.stringify({pairs:8,fitted:8,workerPackets:0,actualCoordinateDifference:0}));
});

function phaseVisual(f,type,index,start,duration,now= start,sequence='ready-review'){
 const raw=f.result.frames.find(frame=>frame.type===type);assert.ok(raw);const frame={...raw,sequenceId:sequence,actionId:1,index,startedAt:start,durationMs:duration,actionStartedAt:0,actionDurationMs:1970},entries=frame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:'unit:'+actor.id,kind:'unit',actor}));return presentActors(frame.state,entries,{},new Set(),{frame,now,selected:'sabre'}).find(actor=>actor.id==='sabre');
}
function calibration(fit){return [...fit.previewFit.limbs].map(([name,limb])=>[name,limb.first,limb.second]);}
test('post-pose cache exceptions restore the original actual body and retained paid turn',async t=>{
 const harness=workerHarness();let injections=0;
 try{for(const appearance of ['granadero','woman-scout'])for(const phase of ['prepare','contact']){
  await t.test(appearance+' '+phase,async()=>{
   const f=await fixtureFor(appearance,true,'standing',1800),runtime=new ActorRuntime(f.asset,f.idle,undefined,f.resolve),source=originalRuntime(f.asset,f.idle,undefined,f.resolve),fit=runtime.meleeFit;
   try{runtime.tick(.1,0);source.tick(.1,0);runtime.prewarmContact();const worker=harness.workers.at(-1);worker.onmessage({data:runFitJob(worker.jobs.at(-1))});assert.ok(fit.ready);
    if(phase==='contact')for(const now of [0,100,240,400]){runtime.update(f.prepared,now);source.update(f.prepared,now);runtime.tick(1/60,now);source.tick(1/60,now);assert.deepEqual(planState(fit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));}
    const priorSample=fit.sample,priorCalibration=priorSample?calibration(fit):undefined,pose=fit.pose;let thrown=false,modified=0;
    fit.pose=function(...args){const result=pose.apply(this,args);if(!thrown){thrown=true;modified=this.nativePose.length;assert.ok(modified>0,'The injected exception follows actual body and four-limb mutation');injections++;throw Error('CONTROLLED_CACHE_ERROR_AFTER_ACTUAL_POSE');}return result;};
    try{const now=phase==='prepare'?100:420,visual=phase==='prepare'?f.prepared:phaseVisual(f,'contact',1,420,650);runtime.update(visual,now);source.update(visual,now);runtime.tick(1/60,now);source.tick(1/60,now);assert.ok(thrown);assert.ok(fit.plan);assert.deepEqual(planState(fit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));assert.equal(fit.fallbackCue,visual.cue.id);assert.equal(fit.usingCue,phase==='prepare'?'':visual.cue.id);
     if(priorSample){assert.equal(fit.sample,priorSample,'An established preview is preserved');assert.deepEqual(calibration(fit),priorCalibration,'Its first mixed limb radii are unchanged');}else assert.deepEqual(calibration(fit),calibration(source.meleeFit),'A new transferred preview rebuilds with original current mixed radii');
     assert.equal(fit.sampleMixer.update.name,source.meleeFit.sampleMixer.update.name,'Temporary mixer replay is removed');assert.equal(fit.previewFit.pose.name,source.meleeFit.previewFit.pose.name,'Temporary settled replay is removed');
     for(const later of phase==='prepare'?[240,400]:[600,1000]){runtime.update(visual,later);source.update(visual,later);runtime.tick(.016,later);source.tick(.016,later);assert.deepEqual(planState(fit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));}
    }finally{fit.pose=pose;}
   }finally{runtime.dispose();source.dispose();f.body.dispose();}
  });
 }}finally{harness.restore();}assert.equal(injections,4);t.diagnostic(JSON.stringify({injections,phases:['prepare','contact'],actualCoordinatesExact:true}));
});

test('an original first cue keeps its mixed preview calibration during a later ready cue',async t=>{
 const harness=workerHarness();const rows=[];
 try{for(const appearance of ['granadero','woman-scout']){
  const f=await fixtureFor(appearance,true,'standing',1800),done=[],referenceDone=[],runtime=new ActorRuntime(f.asset,f.idle,(...args)=>done.push(args),f.resolve),source=originalRuntime(f.asset,f.idle,(...args)=>referenceDone.push(args),f.resolve),fit=runtime.meleeFit;
  try{runtime.tick(.1,0);source.tick(.1,0);const start=Date.now();
   for(const [visual,times]of [[f.prepared,[0,20,100,240,400]],[phaseVisual(f,'contact',1,420,650),[420,600,1000]],[phaseVisual(f,'impact',2,1070,900),[1070,1400,1969,1970,2000]]])for(const now of times){runtime.update(visual,now);source.update(visual,now);runtime.tick(.016,now);source.tick(.016,now);assert.deepEqual(planState(fit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));}
   assert.equal(done.length,1);assert.deepEqual(done,referenceDone);const firstPreview=fit.sample,firstCalibration=calibration(fit);assert.equal(fit.finalized,true,'Synchronous admission finalizes the first mixed preview');assert.deepEqual(firstCalibration,calibration(source.meleeFit));
   const result=presentedActBattle(f.result.state,{type:'melee',unitId:'sabre',targetId:'target-sabre'});assert.ok(result.frames.find(frame=>frame.type==='contact'),result.state.lastError);assert.deepEqual(result.state,actBattle(f.result.state,{type:'melee',unitId:'sabre',targetId:'target-sabre'}));
   const raw=result.frames.find(frame=>frame.type==='prepare'),frame={...raw,sequenceId:'second-ready-review',actionId:2,index:0,startedAt:2200,durationMs:420,actionStartedAt:2200,actionDurationMs:1970},entries=frame.state.units.filter(actor=>['sabre','target-sabre'].includes(actor.id)).map(actor=>({key:'unit:'+actor.id,kind:'unit',actor})),actors=presentActors(frame.state,entries,{},new Set(),{frame,now:2200,selected:'sabre'}),prepared=actors.find(actor=>actor.id==='sabre'),defender=actors.find(actor=>actor.id==='target-sabre');f.body.update(defender,2200);f.body.tick(.1,2200);f.body.root.updateMatrixWorld(true);
   const resolve=target=>resolveContactTargetModel(target,actors,{visual:defender,runtime:f.body,pending:false,error:false});runtime.contactActor=resolve;source.contactActor=resolve;const idle={...prepared,action:'idle',cue:undefined,contactWarm:{targets:[prepared.cue.contactTarget],support:prepared.cue.contactSupport}};runtime.update(idle,2200);source.update(idle,2200);runtime.tick(.1,2200);source.tick(.1,2200);runtime.prewarmContact();const worker=harness.workers.at(-1);assert.ok(worker?.jobs.length);worker.onmessage({data:runFitJob(worker.jobs.at(-1))});assert.ok(fit.ready);
   const pose=fit.previewFit,limbValues=calibration(fit);assert.deepEqual(limbValues,firstCalibration);assert.equal(fit.sample,firstPreview);
   for(const now of [2200,2300,2440,2600]){runtime.update(prepared,now);source.update(prepared,now);runtime.tick(.016,now);source.tick(.016,now);assert.ok(fit.plan);assert.equal(fit.usingCue,prepared.cue.id,'The later cue uses ready rows');assert.deepEqual(planState(fit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));assert.equal(fit.sample,firstPreview);assert.equal(fit.previewFit,pose);assert.deepEqual(calibration(fit),firstCalibration);}
   const contactRaw=result.frames.find(frame=>frame.type==='contact'),contactFrame={...contactRaw,sequenceId:'second-ready-review',actionId:2,index:1,startedAt:2620,durationMs:650,actionStartedAt:2200,actionDurationMs:1970},contact=presentActors(contactFrame.state,entries,{},new Set(),{frame:contactFrame,now:2620,selected:'sabre'}).find(actor=>actor.id==='sabre');runtime.update(contact,2620);source.update(contact,2620);runtime.tick(.016,2620);source.tick(.016,2620);assert.deepEqual(planState(fit),planState(source.meleeFit));assert.deepEqual(shape(runtime),shape(source));assert.deepEqual(calibration(fit),firstCalibration);rows.push({appearance,firstCueFrames:13,firstCompletion:1,laterReadyPrepare:true,laterReadyContact:true,calibrationExact:true});
  }finally{runtime.dispose();source.dispose();f.body.dispose();}
 }}finally{harness.restore();}t.diagnostic(JSON.stringify(rows));
});
