import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Mesh,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldBatch,WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {addWindowFace}=await import('../web/lib/three/world-building-windows.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {buildingArtInset}=await import('../web/lib/three/world-building-placement.ts');
const {entranceFrame}=await import('../game/building-profile.js');
const {BUILDING_OPENINGS}=await import('../game/building-scale.js');
const {Opening,WALL_COLOURS}=await import('../web/app/TacticalArchitectureMaterials.tsx');
const {createArchitectureReviewBattle}=await import('./legacy-building-fixtures.mjs');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270];
function sourceBars(){const result=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){for(const child of node)visit(child);return;}if(node.type==='path'&&node.props.stroke==='#767c68')result.push(node.props);visit(node.props?.children);};visit(Opening({type:'window',style:'arched',open:false,trim:'#eee6d1'}));return result;}
function faceFixture(axis='x',sourceParish=true,style='arched'){
 const geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path}),batch=new WorldBatch(geometry),face={axis,mid:4,cross:3,base:.8,sill:BUILDING_OPENINGS.windowSill/V,top:BUILDING_OPENINGS.windowTop/V,width:.60*T,style,light:.43,sourceParish};addWindowFace(batch,materials,face);const node=batch.finish('window');node.updateMatrixWorld(true);return {face,node,point(x,y,d){return axis==='x'?new Vector3(face.mid+x,face.base+y,face.cross+d):new Vector3(face.cross+d,face.base+y,face.mid+x);},bars(){return node.children.find(mesh=>mesh.material.color.getHexString()==='767c68');},dispose(){disposeWorldNode(node);geometry.dispose();materials.dispose();}};
}
function fixture(id,rotation,view='exterior',roof='original'){
 const battle=createArchitectureReviewBattle(id,rotation,view,roof),b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},frame=entranceFrame({...b,walls:battle.tiles}),geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});
 return {b,input,frame,bars(building){return building.getObjectByName(`building-fabric:${b.id}`).children.find(mesh=>mesh.material.name==='world:iron'&&mesh.material.color.getHexString()==='767c68');},build(){const before=JSON.stringify(input),building=buildBuilding(b,input,T,geometry,materials);building.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before);return building;},dispose(building){disposeWorldNode(building);geometry.dispose();materials.dispose();}};
}
function segments(f,y,d){const hits=[],steps=720,width=f.face.width,direction=f.face.axis==='x'?new Vector3(0,0,-Math.sign(d)):new Vector3(-Math.sign(d),0,0);let first;for(let n=0;n<=steps;n++){const x=-width*.5+n*width/steps,hit=new Raycaster(f.point(x,y,d),direction,0,Math.abs(d)*2).intersectObject(f.bars(),true).length>0;if(hit&&first===undefined)first=x;if(!hit&&first!==undefined){hits.push([first,x-width/steps]);first=undefined;}}if(first!==undefined)hits.push([first,width*.5]);return hits;}

test('authored parish arched windows use the actual three source bars, pigment, stroke widths and top/bottom insets from either face',()=>{
 const source=sourceBars(),vertical=source.filter(path=>/^M[\d.]+,-[\d.]+V-/.test(path.d));assert.equal(vertical.length,3);const expectedX=vertical.map(path=>(Number(path.d.match(/^M([\d.]+)/)[1])-20)/18),stroke=Number(vertical[0].strokeWidth),top=Number(vertical[0].d.match(/,-([\d.]+)/)[1]),bottom=Number(vertical[0].d.match(/V-([\d.]+)/)[1]);
 for(const axis of ['x','y'])for(const d of [-.5,.5]){const f=faceFixture(axis),height=f.face.top-f.face.sill,bars=f.bars(),sample=f.face.sill+height*.70,runs=segments(f,sample,d);assert.equal(runs.length,3);for(let n=0;n<runs.length;n++){assert.ok(Math.abs((runs[n][0]+runs[n][1])*.5/f.face.width-expectedX[n])<1/720);assert.ok(Math.abs((runs[n][1]-runs[n][0])/f.face.width-stroke/18)<3/720,`${axis}/${d}/${n}: got ${(runs[n][1]-runs[n][0])/f.face.width}, source ${stroke/18}`);}const p=bars.geometry.getAttribute('position'),ys=Array.from({length:p.count},(_,n)=>p.getY(n)-f.face.base);assert.ok(Math.abs(Math.min(...ys)-(f.face.sill+height*(bottom-13)/25))<1e-5);assert.ok(Math.abs(Math.max(...ys)-(f.face.top-height*(38-top)/25))<1e-5);assert.equal(bars.material.color.getHexString(),vertical[0].stroke.slice(1));for(const y of [f.face.sill+height*.015,f.face.top-height*.03])assert.equal(segments(f,y,d).length,0,'the new bars leave the real source top and bottom gaps');f.dispose();}
});

test('the actual source transverse bar keeps its inset width and height while glazing and ordinary metal lighting stay intact',()=>{
 const source=sourceBars().find(path=>/H/.test(path.d)),match=source.d.match(/^M([\d.]+),-([\d.]+)H([\d.]+)/);assert.ok(match);for(const axis of ['x','y']){const f=faceFixture(axis),height=f.face.top-f.face.sill,y=f.face.sill+height*(Number(match[2])-13)/25,runs=segments(f,y,.5);assert.equal(runs.length,1);assert.ok(Math.abs((runs[0][1]-runs[0][0])/f.face.width-(Number(match[3])-Number(match[1]))/18)<2/720);const glass=f.node.children.find(mesh=>mesh.material.name==='world:glass');assert.ok(glass);assert.equal(glass.material.opacity,.38);const colour=f.bars().geometry.getAttribute('color');for(let n=0;n<colour.count;n++)for(const channel of ['getX','getY','getZ'])assert.ok(Math.abs(colour[channel](n)-f.face.light)<1e-6);f.dispose();}
});

test('actual church and explicitly arched chapel panes get local source bars through four rotations while other saved styles and buildings retain their rules',()=>{
 const sample=faceFixture(),perWindow=sample.bars().geometry.getAttribute('position').count;sample.dispose();
 for(const rotation of rotations){for(const id of ['iglesia','capilla']){const f=fixture(id,rotation);if(id==='capilla')f.b.windowStyle='arched';const building=f.build(),windows=building.userData.openings.filter(opening=>opening.type==='window');assert.equal(f.bars(building).geometry.getAttribute('position').count,perWindow*windows.length);for(const opening of windows){assert.equal(opening.width,.60*T);assert.ok(Math.abs(opening.height-(BUILDING_OPENINGS.windowTop-BUILDING_OPENINGS.windowSill)/V)<1e-5);}f.dispose(building);}
  const ordinary=fixture('capilla',rotation),ordinaryBuilding=ordinary.build();assert.ok(ordinary.bars(ordinaryBuilding),'ordinary chapel windows keep the three source rectangular bars');assert.equal(ordinary.bars(ordinaryBuilding).geometry.getAttribute('position').count,ordinaryBuilding.userData.openings.filter(opening=>opening.type==='window').length*108,'ordinary small panes do not inherit the arched transverse bar');ordinary.dispose(ordinaryBuilding);
  const other=fixture('palacio',rotation),otherBuilding=other.build();assert.equal(Boolean(other.bars(otherBuilding)),false,'the cut cannot repaint palace ground or upper bars');other.dispose(otherBuilding);
  for(const style of ['small','barred','lattice','shutters']){const f=fixture('iglesia',rotation),windows=f.input.terrain.tiles.filter(tile=>tile.type==='window'&&tile.buildingId===f.b.id);for(const tile of windows)tile.style=style;const building=f.build();assert.equal(Boolean(f.bars(building)),['small','barred'].includes(style),'explicit saved tile styles must select their rectangular bars or retained timber instead of an arched building default');assert.equal(building.userData.openings.filter(opening=>opening.type==='window').length,windows.length);f.dispose(building);}
  const legacy=fixture('iglesia',rotation);legacy.b.architecture='church';legacy.b.kind=undefined;legacy.b.wallFinish=undefined;const legacyBuilding=legacy.build();assert.equal(Boolean(legacy.bars(legacyBuilding)),false);legacy.dispose(legacyBuilding);
 }
});

test('both curved surrounds and the exact real window gaps remain visible while standing doors and upper routes stay clear',()=>{
 for(const rotation of rotations)for(const roof of ['original','slab','terrace','roof-route']){const f=fixture('iglesia',rotation,'exterior',roof);f.frame.door.open=true;const building=f.build(),bars=f.bars(building),out=new Vector3(-f.frame.v.x,0,-f.frame.v.y);assert.ok(bars);for(const offset of [-.20,0,.20])for(const y of [1.3,1.8]){const p=f.frame.at(f.frame.doorU,0),start=new Vector3(p.x*T+offset*f.frame.u.x,y,p.y*T+offset*f.frame.u.y).addScaledVector(out,T);assert.equal(new Raycaster(start,out.clone().negate(),0,2*T).intersectObject(building,true).length,0);}
  const tile=f.input.terrain.tiles.find(tile=>tile.type==='window'&&tile.buildingId===f.b.id),opening=building.userData.openings.find(opening=>opening.id===`window:${tile.x},${tile.y}`),axis=opening.axis,inset=buildingArtInset(f.b,f.input),cross=((axis==='x'?tile.y:tile.x)+inset)*T,mid=(axis==='x'?tile.x:tile.y)*T,width=opening.width,top=BUILDING_OPENINGS.windowTop/V,sill=BUILDING_OPENINGS.windowSill/V,radius=width*.5,point=(x,y,d)=>axis==='x'?new Vector3(mid+x,y,cross+d):new Vector3(cross+d,y,mid+x);
  for(const side of [-1,1]){const direction=axis==='x'?new Vector3(0,0,-side):new Vector3(-side,0,0),gap=new Raycaster(point(width/9,sill+(top-sill)*.60,side*T),direction,0,2*T).intersectObject(building,true)[0];assert.equal(gap?.object.material.name,'world:glass','the real gap remains open through the grille to its retained glazing');const arc=new Raycaster(point(radius*Math.cos(Math.PI/4),top-radius+radius*Math.sin(Math.PI/4),side*T),direction,0,2*T).intersectObject(building,true)[0];assert.equal(arc?.object.material.name,`world:window-trim-${f.b.wallFinish}`,'the retained curved surround remains present on both actual wall faces');assert.equal(arc.object.material.color.getHexString(),WALL_COLOURS[f.b.wallFinish].trim.slice(1),'the real source trim pigment reaches both curved camera faces');}
  const p=bars.geometry.getAttribute('position');for(let n=0;n<p.count;n++)assert.ok(p.getY(n)<building.userData.height,'the new bars never enter the actual upper roof route');f.dispose(building);
 }
});

test('edited corner apertures, short slabs, open/broken flags and ordinary cutaways retain their actual shell dimensions and disclosure',()=>{
 const sample=faceFixture(),perWindow=sample.bars().geometry.getAttribute('position').count;sample.dispose();
 for(const rotation of rotations){const corner=fixture('iglesia',rotation),p=corner.frame.at(0,0),tile=corner.input.terrain.tiles.find(tile=>tile.x===p.x&&tile.y===p.y);tile.type='window';tile.style='arched';tile.doorId='edited-parish-corner';corner.input.terrain.tiles=[corner.frame.door,...corner.input.terrain.tiles.filter(tile=>tile!==corner.frame.door)];assert.equal(buildingArtInset(corner.b,corner.input),.4);const cornerBuilding=corner.build(),record=cornerBuilding.userData.openings.find(opening=>opening.id==='edited-parish-corner');assert.ok(Math.abs(record.width-.065*T)<1e-5||Math.abs(record.width-.585*T)<1e-5,'the original clipped corner aperture width stays unchanged');assert.ok(corner.bars(cornerBuilding));corner.dispose(cornerBuilding);
  const short=fixture('iglesia',rotation,'exterior','slab');short.input.terrain.upperSurfaces=short.input.terrain.upperSurfaces.map(surface=>({...surface,elevation:1.8}));const shortBuilding=short.build(),positions=short.bars(shortBuilding).geometry.getAttribute('position');for(let n=0;n<positions.count;n++)assert.ok(positions.getY(n)<1.8);short.dispose(shortBuilding);
  for(const open of [false,true])for(const broken of [false,true]){const f=fixture('iglesia',rotation),windows=f.input.terrain.tiles.filter(tile=>tile.type==='window'&&tile.buildingId===f.b.id);for(const tile of windows){tile.open=open;tile.broken=broken;}const building=f.build();assert.equal(f.bars(building).geometry.getAttribute('position').count,perWindow*windows.length);for(const record of building.userData.openings.filter(opening=>opening.type==='window'))assert.equal(record.open,open);f.dispose(building);}
  for(const view of ['partial','interior']){const f=fixture('iglesia',rotation,view),building=f.build(),retained=building.userData.openings.filter(opening=>opening.type==='window'&&opening.height>.28).length;assert.equal(f.bars(building)?.geometry.getAttribute('position').count??0,perWindow*retained,'only retained uncut panes keep their bars');f.dispose(building);}
  const breach=fixture('iglesia',rotation);for(const tile of breach.input.terrain.tiles)if(tile.type==='window')tile.type='rubble';const breachBuilding=breach.build();assert.equal(Boolean(breach.bars(breachBuilding)),false);breach.dispose(breachBuilding);
 }
});
