import{register}from'node:module';register('./tactical-render-loader.mjs',import.meta.url);import test from'node:test';import assert from'node:assert/strict';import{Quaternion,Vector3}from'../web/node_modules/three/build/three.module.js';import{publishedActor}from'./published-actor-fixture.mjs';
const{ActorRuntime}=await import('../web/lib/three/actor-runtime.ts'),{presentActors}=await import('../web/lib/three/presentation.ts'),{createBattle,presentedActBattle}=await import('../game/tactical.js'),{admittedReloadWork}=await import('../web/lib/three/action-timing.ts'),{presentedFrameDuration}=await import('../web/lib/useEnemyPlayback.ts');
test('a held prone reload fade restores native mixer values and keeps exact grips without accumulation',async()=>{
 const appearance='granadero',asset=await publishedActor(appearance,1),state=createBattle([{id:'worker',x:2,y:2,facing:2,weapon:1805,activeSlot:'primary',weaponInstanceId:'owned-right',loaded:0,ammo:8,condition:90,energy:100,stance:'prone',movementMode:'prone',spriteAppearance:appearance,agility:90,dexterity:90,wisdom:90,experienceLevel:7}],{width:24,height:8,seed:45,tiles:Array.from({length:192},(_,i)=>({x:i%24,y:Math.floor(i/24),type:'grass',blocked:false,cover:0})),enemies:[{id:'far',x:22,y:6,weapon:0,patrol:false,overwatch:false}]});state.deploymentComplete=true;state.units[0].ap=100;
 const show=(s,f,now)=>presentActors(s,[{key:'unit:worker',kind:'unit',actor:s.units[0]}],{},new Set(),{selected:'worker',mode:'move',frame:f,now})[0],actor=new ActorRuntime(asset,show(state,undefined,0));let prior=0;
 const step=(s,f,now)=>{actor.update(show(s,f,now),now);actor.tick((now-prior)/1000,now);prior=now;};
 try{
  for(let j=0;j<=80;j++)step(state,undefined,j*1000/60);const out=presentedActBattle(state,{type:'reload',unitId:'worker'}),frames=admittedReloadWork(out.frames),duration=frames.reduce((n,f)=>n+presentedFrameDuration(f,state),0);let start=1400;
  for(const[index,f]of frames.entries()){const d=presentedFrameDuration(f,state),frame={...f,index,sequenceId:'repeat',actionId:1,startedAt:start,durationMs:d,actionStartedAt:1400,actionDurationMs:duration};for(let now=start;now<start+d-1e-5;now+=1000/60)step(f.state,frame,now);start+=d;}
  for(let j=1;j<=7;j++){step(out.state,undefined,start+j*1000/60);if(actor.proneArmSupport.maximumAngle>.025)break;}
  const helper=actor.proneArmSupport;assert.ok(helper.maximumAngle>.025,'Actual admitted return requires a fit');const bones=[];actor.model.traverse(n=>{if(n.isBone)bones.push(n);});const pose=bones.map(n=>n.quaternion.clone()),hands=['l','r'].map(side=>{const n=actor.model.getObjectByName('hand_'+side);return{n,p:n.getWorldPosition(new Vector3()),q:n.getWorldQuaternion(new Quaternion()).normalize()};});
  for(let frame=0;frame<120;frame++){helper.restore();actor.mixer.update(0);helper.apply(actor.mixer.time);actor.root.updateMatrixWorld(true);for(const[n,q]of bones.map((n,i)=>[n,pose[i]]))assert.ok(Math.max(...n.quaternion.toArray().map((v,i)=>Math.abs(v-q.toArray()[i])))<1e-6,'A held native phase does not accumulate a fit');for(const h of hands){assert.ok(h.n.getWorldPosition(new Vector3()).distanceTo(h.p)<1e-6);assert.ok(h.n.getWorldQuaternion(new Quaternion()).normalize().angleTo(h.q)<1e-6);}for(const limb of helper.limbs.values())assert.ok(helper.lowest(limb)>=actor.root.position.y+.0015,'Complete sleeves retain their floor');assert.equal(helper.rejectedFits,0);}
  helper.restore();actor.mixer.update(0);const limb=helper.limbs.get('l'),offset=limb.lower.position.clone(),native=[limb.upper,limb.lower,limb.hand].map(n=>n.quaternion.clone());limb.lower.position.set(0,0,0);actor.root.updateMatrixWorld(true);helper.fit(limb,actor.root.position.y);assert.ok(helper.rejectedFits>0,'An unsupported native length rejects the fit');[limb.upper,limb.lower,limb.hand].forEach((n,i)=>assert.deepEqual(n.quaternion.toArray(),native[i].toArray()));limb.lower.position.copy(offset);actor.root.updateMatrixWorld(true);
  helper.begin(undefined,{name:'stand.idle.unarmed',gesture:'idle',loop:true},actor.mixer.time);const exact=bones.map(n=>n.quaternion.toArray());helper.apply(actor.mixer.time);helper.apply(NaN);helper.begin(undefined,{name:'prone.reload.short-gun',gesture:'reload',loop:false},NaN);helper.apply(actor.mixer.time+.1);assert.deepEqual(bones.map(n=>n.quaternion.toArray()),exact,'Unsupported and non-finite admission keeps native output');
 }finally{actor.dispose();}
});
