import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Box3,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldBatch,WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {addWindowFace}=await import('../web/lib/three/world-building-windows.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {buildingArtInset}=await import('../web/lib/three/world-building-placement.ts');
const {BUILDING_OPENINGS}=await import('../game/building-scale.js');
const {Opening}=await import('../web/app/TacticalArchitectureMaterials.tsx');
const {createArchitectureReviewBattle}=await import('./legacy-building-fixtures.mjs');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270],ids=['barraca','capilla','cabildo','ayuntamiento','almacen','deposito','herreria'];
function sourceBars(style){const result=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(node.type==='path'&&node.props.stroke==='#767c68')result.push(node.props);visit(node.props?.children);};visit(Opening({type:'window',style,open:false,trim:'#eee6d1'}));return result;}
function pane(style,axis='x',sourceRectangular=true){const geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path}),batch=new WorldBatch(geometry),face={axis,mid:4,cross:3,base:.8,sill:BUILDING_OPENINGS.windowSill/V,top:BUILDING_OPENINGS.windowTop/V,width:.6*T,style,light:.43,sourceRectangular};addWindowFace(batch,materials,face);const node=batch.finish('pane');node.updateMatrixWorld(true);return {face,node,bars:node.children.find(mesh=>mesh.material.name==='world:iron'&&mesh.material.color.getHexString()==='767c68'),point(x,y,d){return axis==='x'?new Vector3(face.mid+x,face.base+y,face.cross+d):new Vector3(face.cross+d,face.base+y,face.mid+x);},dispose(){disposeWorldNode(node);geometry.dispose();materials.dispose();}};}
function runs(f,y,side){const result=[],steps=1000,w=f.face.width,dir=f.face.axis==='x'?new Vector3(0,0,-side):new Vector3(-side,0,0);let start;for(let n=0;n<=steps;n++){const x=-w*.5+n*w/steps,hit=new Raycaster(f.point(x,y,side*.5),dir,0,1).intersectObject(f.bars,true).length>0;if(hit&&start===undefined)start=x;if(!hit&&start!==undefined){result.push([start,x-w/steps]);start=undefined;}}if(start!==undefined)result.push([start,w*.5]);return result;}
function fixture(id,rotation,view='exterior',roof='original'){const battle=createArchitectureReviewBattle(id,rotation,view,roof),b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});return {battle,b,input,build(){const before=JSON.stringify(input),node=buildBuilding(b,input,T,geometry,materials);node.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before,'rendering must preserve saved authored collision, inventory and disclosure');return node;},dispose(node){disposeWorldNode(node);geometry.dispose();materials.dispose();}};}
function bars(node,b){return node.getObjectByName(`building-fabric:${b.id}`).children.find(mesh=>mesh.material.name==='world:iron'&&mesh.material.color.getHexString()==='767c68');}
function shellWindow(f,record,height){const tile=f.input.terrain.tiles.find(tile=>(tile.doorId??`window:${tile.x},${tile.y}`)===record.id),axis=record.axis,inset=buildingArtInset(f.b,f.input),along=axis==='x'?tile.x:tile.y,lo=(axis==='x'?f.b.x:f.b.y)+inset,hi=(axis==='x'?f.b.x+f.b.width-1:f.b.y+f.b.height-1)+inset,mid=(Math.max(along-.5,lo)+Math.min(along+.5,hi))*.5*T,cross=((axis==='x'?tile.y:tile.x)+inset)*T,base=tile.elevation??0,top=Math.min(height-.12,BUILDING_OPENINGS.windowTop/V),sill=Math.min(top-.25,BUILDING_OPENINGS.windowSill/V);return {tile,axis,mid,cross,base,sill,top,width:record.width,point(x,y,d){return axis==='x'?new Vector3(mid+x,base+y,cross+d):new Vector3(cross+d,base+y,mid+x);}};}

test('authored rectangular bars use the current three source strokes, pigment and complete end insets on both faces',()=>{for(const style of ['barred','small']){const source=sourceBars(style),vertical=source.filter(p=>/^M[\d.]+,-[\d.]+V-/.test(p.d)),span=style==='small'?10:18,rise=style==='small'?10:19;assert.equal(vertical.length,3);for(const axis of ['x','y'])for(const side of [-1,1]){const f=pane(style,axis),h=f.face.top-f.face.sill;assert.ok(f.bars,'authored rectangular bars must use the actual source pigment');const r=runs(f,f.face.sill+h*.7,side);assert.equal(r.length,3);for(let n=0;n<3;n++){const x=Number(vertical[n].d.match(/^M([\d.]+)/)[1]);assert.ok(Math.abs((r[n][0]+r[n][1])*.5/f.face.width-(x-20)/span)<1/1000);assert.ok(Math.abs((r[n][1]-r[n][0])/f.face.width-Number(vertical[n].strokeWidth)/span)<3/1000);}const bound=new Box3().setFromObject(f.bars);assert.ok(Math.abs(bound.min.y-f.face.base-f.face.sill-h/rise)<1e-5);assert.ok(Math.abs(bound.max.y-f.face.base-f.face.top+h/rise)<1e-5);for(const y of [f.face.sill+h*.025,f.face.top-h*.025])assert.equal(runs(f,y,side).length,0);f.dispose();}}});

test('the regular transverse stroke keeps its real inset span while small windows retain open centre-height gaps',()=>{for(const style of ['barred','small'])for(const axis of ['x','y']){const f=pane(style,axis),h=f.face.top-f.face.sill;assert.ok(f.bars);const source=sourceBars(style).find(p=>/H/.test(p.d)),r=runs(f,f.face.sill+h*9/19,1);if(style==='small'){assert.equal(source,undefined);assert.equal(r.length,3,'a small source pane has no horizontal closure');}else{assert.ok(source);assert.equal(r.length,1);assert.ok(Math.abs((r[0][1]-r[0][0])/f.face.width-16/18)<3/1000);}assert.equal(f.node.children.find(mesh=>mesh.material.name==='world:glass').material.opacity,.38);const c=f.bars.geometry.getAttribute('color');for(let n=0;n<c.count;n++)assert.ok(Math.abs(c.getX(n)-.43)<1e-6);f.dispose();}});

test('seven actual rectangular-window templates get the source grille through four rotations without changing their physical aperture or saved state',()=>{const counts={};for(const style of ['barred','small']){const f=pane(style);counts[style]=f.bars?.geometry.getAttribute('position').count;f.dispose();}assert.ok(counts.small&&counts.barred);for(const id of ids)for(const rotation of rotations){const f=fixture(id,rotation),node=f.build(),windows=node.userData.openings.filter(o=>o.type==='window'),style=['cabildo','ayuntamiento','herreria'].includes(id)?'barred':'small';assert.ok(windows.length);assert.equal(node.getObjectByName(`building-fabric:${f.b.id}`).children.some(mesh=>mesh.material.name==='world:iron'&&mesh.material.color.getHexString()!=='767c68'),false,'no obsolete grille remains behind the source bars');assert.equal(bars(node,f.b).geometry.getAttribute('position').count,windows.length*counts[style],`${id}/${rotation}: real retained window count`);for(const o of windows){assert.equal(o.width,.6*T);assert.ok(Math.abs(o.height-(BUILDING_OPENINGS.windowTop-BUILDING_OPENINGS.windowSill)/V)<1e-6);}f.dispose(node);}});

 test('actual standing doorway crossings and window sight gaps remain clear from both sides across four rotations and all authored roof states',()=>{for(const id of ids)for(const rotation of rotations)for(const roof of ['original','slab','roof-route']){const f=fixture(id,rotation,'exterior',roof);for(const tile of f.input.terrain.tiles)if(tile.type==='door')tile.open=true;const node=f.build();for(const record of node.userData.openings){if(record.type==='window'){const w=shellWindow(f,record,node.userData.height),h=w.top-w.sill,style=['cabildo','ayuntamiento','herreria'].includes(id)?'barred':'small',x=w.width*(style==='small'?.2:.11),dir=side=>w.axis==='x'?new Vector3(0,0,-side):new Vector3(-side,0,0);for(const side of [-1,1]){const hit=new Raycaster(w.point(x,w.sill+h*.7,side*T),dir(side),0,2*T).intersectObject(node,true)[0];assert.equal(hit?.object.material.name,'world:glass',`${id}/${rotation}/${roof}: real standing sight gap retained`);}}else{const tile=f.input.terrain.tiles.find(t=>(t.doorId??`door:${t.x},${t.y}`)===record.id),inset=buildingArtInset(f.b,f.input),axis=record.axis,cross=((axis==='x'?tile.y:tile.x)+inset)*T,mid=(axis==='x'?tile.x:tile.y)*T;for(const side of [-1,1])for(const x of [-.18,0,.18])for(const y of [1.3,1.8]){const start=axis==='x'?new Vector3(mid+x,y,cross+side*T):new Vector3(cross+side*T,y,mid+x),dir=axis==='x'?new Vector3(0,0,-side):new Vector3(-side,0,0);assert.equal(new Raycaster(start,dir,0,2*T).intersectObject(node,true).length,0,`${id}/${rotation}/${roof}: standing door approach remains clear`);}}}const bound=new Box3().setFromObject(bars(node,f.b));assert.ok(bound.max.y<node.userData.height,'bars do not reach a legal roof route');f.dispose(node);}});

 test('edited corner apertures, short slabs, saved tile styles, open/broken flags and ordinary disclosure retain their existing shell rules',()=>{for(const rotation of rotations){const corner=fixture('capilla',rotation);const tile=corner.input.terrain.tiles.find(t=>t.x===corner.b.x&&t.y===corner.b.y);tile.type='window';tile.style='small';tile.doorId='edited-corner';const node=corner.build(),record=node.userData.openings.find(o=>o.id==='edited-corner');assert.ok(record);assert.ok(record.width<.6*T);assert.equal(buildingArtInset(corner.b,corner.input),.4);assert.ok(bars(node,corner.b));corner.dispose(node);
 const short=fixture('capilla',rotation,'exterior','slab');short.input.terrain.upperSurfaces=short.input.terrain.upperSurfaces.map(s=>({...s,elevation:1.8}));const shortNode=short.build();assert.ok(new Box3().setFromObject(bars(shortNode,short.b)).max.y<1.8);short.dispose(shortNode);
 for(const style of ['small','barred','arched','lattice','shutters']){const f=fixture('capilla',rotation);for(const tile of f.input.terrain.tiles)if(tile.type==='window'){tile.style=style;tile.open=true;tile.broken=true;}const n=f.build();assert.equal(Boolean(bars(n,f.b)),['small','barred','arched'].includes(style),'explicit styles must choose only their admitted helper');for(const record of n.userData.openings.filter(o=>o.type==='window'))assert.equal(record.open,true);f.dispose(n);}
 for(const view of ['partial','interior']){const f=fixture('capilla',rotation,view),n=f.build(),retained=n.userData.openings.filter(o=>o.type==='window'&&o.height>.28).length,p=pane('small'),count=p.bars.geometry.getAttribute('position').count;p.dispose();assert.equal(bars(n,f.b)?.geometry.getAttribute('position').count??0,retained*count);f.dispose(n);}
 const breached=fixture('capilla',rotation);for(const tile of breached.input.terrain.tiles)if(tile.type==='window')tile.type='rubble';const breachedNode=breached.build();assert.equal(bars(breachedNode,breached.b),undefined);breached.dispose(breachedNode);
 }});

 test('legacy grilles and accepted arched, lattice and shutter dressings retain their existing behavior',()=>{for(const style of ['barred','small','arched','lattice','shutters']){const f=pane(style,'x',false);assert.equal(f.bars,undefined);assert.ok(f.node.children.some(c=>c.material.name==='world:glass'));f.dispose();}for(const id of ['iglesia','palacio','pulperia','casa']){const f=fixture(id,0),n=f.build(),styles=n.getObjectByName(`building-fabric:${f.b.id}`).children.map(c=>c.material.name);if(id==='iglesia')assert.ok(bars(n,f.b));else assert.equal(bars(n,f.b),undefined);if(id==='pulperia')assert.ok(styles.includes('world:timber-lattice'));if(id==='casa')assert.ok(styles.includes('world:timber-shutter'));f.dispose(n);}const f=fixture('capilla',0);f.b.architecture='chapel';f.b.kind=undefined;f.b.wallFinish=undefined;const n=f.build();assert.equal(bars(n,f.b),undefined);f.dispose(n);const painted=fixture('capilla',0);painted.b.architecture='chapel';painted.b.kind=undefined;painted.b.wallFinish='ochre';const authored=painted.build();assert.ok(bars(authored,painted.b),'explicit saved finish admits the authored bar recipe on a legacy shell');painted.dispose(authored);});
