import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Mesh,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {buildingArtInset}=await import('../web/lib/three/world-building-placement.ts');
const {entranceFrame,getBuildingProfile}=await import('../game/building-profile.js');
const {buildingDetails}=await import('../web/app/TacticalBuildingDetails.tsx');
const {ArchitectureVolume}=await import('../web/app/TacticalBuildingVolumes.tsx');
const {BUILDING_TEMPLATES}=await import('../game/map-templates.js');
const {blankMap}=await import('../game/map-schema.js');
const {applyMapCommands}=await import('../game/map-commands.js');
const {compileMap}=await import('../game/compile-map.js');
const {createArchitectureReviewBattle,legacyCellMap}=await import('./legacy-building-fixtures.mjs');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270];
const near=(a,b,label)=>assert.ok(Math.abs(a-b)<2e-5,`${label}: ${a} versus ${b}`);
function fixture(rotation,view='exterior',roof='original',resized=false){
 let battle=createArchitectureReviewBattle('cabildo',rotation,view,roof);
 if(resized){const edited=applyMapCommands(blankMap({id:'odd-cabildo',width:24,height:24}),[{type:'stampTemplate',id:'resized-cabildo',template:BUILDING_TEMPLATES.cabildo,x:4,y:4},{type:'resizeBuilding',id:'resized-cabildo',width:12,height:7},...Array.from({length:rotation/90},()=>({type:'rotateObject',id:'resized-cabildo'}))]);assert.deepEqual(edited.errors,[]);battle={...battle,...legacyCellMap(compileMap(edited.document)),upperSurfaces:[],revealedRooms:[]};}
 const b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},frame=entranceFrame({...b,walls:battle.tiles}),geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});
 return {b,input,frame,point(u,v,y){const p=frame.at(u,v),inset=buildingArtInset(b,input);return new Vector3((p.x+inset)*T,y,(p.y+inset)*T);},feature(building,name){return building.getObjectByName(`building-detail:${b.id}:${name}`);},build(){const before=JSON.stringify(input),object=buildBuilding(b,input,T,geometry,materials);object.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before);return object;},dispose(object){disposeWorldNode(object);geometry.dispose();materials.dispose();}};
}
function bounds(f,mesh){const p=mesh.geometry.getAttribute('position'),origin=f.frame.origin,inset=buildingArtInset(f.b,f.input),result={u0:Infinity,u1:-Infinity,v0:Infinity,v1:-Infinity,y0:Infinity,y1:-Infinity};for(let n=0;n<p.count;n++){const x=p.getX(n)/T-inset-origin.x,z=p.getZ(n)/T-inset-origin.y,u=x*f.frame.u.x+z*f.frame.u.y,v=x*f.frame.v.x+z*f.frame.v.y;result.u0=Math.min(result.u0,u);result.u1=Math.max(result.u1,u);result.v0=Math.min(result.v0,v);result.v1=Math.max(result.v1,v);result.y0=Math.min(result.y0,p.getY(n));result.y1=Math.max(result.y1,p.getY(n));}return result;}
function boxes(f,node){const result=[];node?.traverse(mesh=>{if(!(mesh instanceof Mesh)||!['world:limewash','world:stone','world:cabildo-pier-coping'].includes(mesh.material.name))return;const p=mesh.geometry.getAttribute('position');assert.equal(p.count%36,0);for(let start=0;start<p.count;start+=36){const part={geometry:{getAttribute:()=>({count:36,getX:n=>p.getX(start+n),getY:n=>p.getY(start+n),getZ:n=>p.getZ(start+n)})}},r=bounds(f,part);result.push({...r,material:mesh.material});}});return result;}
function direct(f){const parts=[],circles=[],roof=[],paths=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(node.type===ArchitectureVolume)parts.push(node.props);if(node.type==='circle')circles.push(node.props);if(node.type==='path')paths.push(node.props);if(node.type?.name==='ProjectedRoofSurface'&&String(node.props.id).includes('civic-cupola'))roof.push(node.props);visit(node.props?.children);};for(const item of buildingDetails({...f.b,walls:f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id)},new Set(),(x,y)=>({x:(x-y)*26,y:(x+y)*14})))visit(item.node);return {parts,circles,roof,paths};}
function sourceBounds(f,part){const us=part.points.map(p=>(p.x-f.frame.origin.x)*f.frame.u.x+(p.y-f.frame.origin.y)*f.frame.u.y),vs=part.points.map(p=>(p.x-f.frame.origin.x)*f.frame.v.x+(p.y-f.frame.origin.y)*f.frame.v.y);return {u0:Math.min(...us),u1:Math.max(...us),v0:Math.min(...vs),v1:Math.max(...vs)};}
function supported(f,node){node?.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++)if(p.getY(n)<1.8){assert.ok(p.getY(n)>=-1e-6);assert.equal(f.input.terrain.tiles.find(tile=>tile.x===Math.round(p.getX(n)/T)&&tile.y===Math.round(p.getZ(n)/T))?.type,'wall','low masonry must remain within an actual solid support');}}});}

test('the actual short Cabildo uses the current six source piers, warm feet and joined capitals through four rotations',()=>{
 const reference=fixture(0),source=direct(reference).parts.filter(p=>String(p.label).startsWith('arcade-pier')),h=getBuildingProfile(reference.b).wallHeight;assert.equal(source.length,18);
 for(const rotation of rotations){const f=fixture(rotation),building=f.build(),node=f.feature(building,'civic-ground-arcade'),parts=boxes(f,node);assert.equal(parts.filter(p=>p.material.name==='world:stone').length,6);assert.equal(f.feature(building,'civic-upper-arcade'),undefined);supported(f,node);
  for(const part of source){const r=sourceBounds(reference,part),kind=part.label.split('-').at(-1),u=(r.u0+r.u1)*.5,match=parts.filter(p=>Math.abs((p.u0+p.u1)*.5-u)<1e-5&&Math.abs(p.u1-p.u0-(r.u1-r.u0))<1e-5),box=kind==='capital'?match.find(p=>p.material.name==='world:limewash'):match[0];assert.ok(box);for(const key of ['u0','u1','v0','v1'])near(box[key],r[key],`${rotation}/${part.label}/${key}`);if(kind==='base'){near(box.y0,0,'source foot ground');near(box.y1,part.top/V,'source foot height');assert.equal(box.material.color.getHexString(),part.palette.base.slice(1));}if(kind==='shaft'){near(box.y0,12/V,'the source stone overlay and plaster join once');near(box.y1,building.userData.height-10.5/V,'shaft joins capital');}if(kind==='capital'){near(box.y0,building.userData.height+(part.bottom-h)/V,'source capital bottom');near(Math.max(...match.map(p=>p.y1)),building.userData.height+(part.top-h)/V,'source capital top');}}
  const ray=new Raycaster(f.point(2,-1,1.3),new Vector3(f.frame.v.x,0,f.frame.v.y),0,T*2),wall=ray.intersectObject(building.getObjectByName(`building-fabric:${f.b.id}`),true)[0],pier=ray.intersectObject(node,true)[0];near(wall.distance-pier.distance,.34*T-.09,'source shaft relief');f.dispose(building);
 }reference.dispose(reference.build());
});

test('a real editor-resized odd facade keeps the source endpoint rhythm on both arcade levels',()=>{
 const reference=fixture(0,'exterior','original',true),source=direct(reference).parts.filter(p=>String(p.label).startsWith('arcade-pier')&&p.label.endsWith('base')),expected=source.map(p=>{const r=sourceBounds(reference,p);return (r.u0+r.u1)*.5;});assert.equal(reference.frame.width,11);assert.ok(expected.includes(0)&&expected.includes(11)&&!expected.includes(10));
 for(const rotation of rotations){const f=fixture(rotation,'exterior','original',true);f.input.terrain.upperSurfaces=[{...f.frame.at(3,2),tacticalLevel:1,elevation:5.1,kind:'roof',type:'floor',buildingId:f.b.id,blocked:true,obstacleHeight:0}];const building=f.build(),feet=boxes(f,f.feature(building,'civic-ground-arcade')).filter(p=>p.material.name==='world:stone');assert.deepEqual(feet.map(p=>Math.round((p.u0+p.u1)*.5)||0),expected);const upper=f.feature(building,'civic-upper-arcade');assert.ok(upper);const p=upper.children.find(mesh=>mesh.material.name==='world:trim').geometry.getAttribute('position');let falseSupport=0;for(let n=0;n<p.count;n++){const x=p.getX(n)/T-f.frame.origin.x,z=p.getZ(n)/T-f.frame.origin.y,u=x*f.frame.u.x+z*f.frame.u.y;if(Math.abs(u-10)<.08&&p.getY(n)>2.7&&p.getY(n)<3.1)falseSupport++;}assert.equal(falseSupport,0,'the upper rhythm must not silently add the excluded penultimate odd-end pier');supported(f,f.feature(building,'civic-ground-arcade'));f.dispose(building);
 }reference.dispose(reference.build());
});

test('the authored Cabildo crown matches the source shallow clock body, cornice and tiled pyramid rather than the old round cap',()=>{
 const reference=fixture(0),source=direct(reference),tower=source.parts.find(p=>p.label==='cabildo-clock-tower'),cornice=source.parts.find(p=>p.label==='cabildo-tower-cornice'),circle=source.circles.find(p=>p.fill==='#ddd0aa');assert.ok(tower&&cornice&&circle&&source.roof.length);
 for(const rotation of rotations){const f=fixture(rotation),building=f.build(),height=building.userData.height,crown=f.feature(building,'civic-clock-tower'),parts=boxes(f,crown),wallParts=parts.filter(p=>p.material.name==='world:limewash'),body=wallParts.find(p=>Math.abs(p.u1-p.u0-1.4)<1e-5),cap=wallParts.find(p=>Math.abs(p.u1-p.u0-1.56)<1e-5),u=f.frame.width*.5,h=getBuildingProfile(f.b).wallHeight;for(const [part,box]of [[tower,body],[cornice,cap]])for(const key of ['u0','u1','v0','v1'])near(box[key],sourceBounds(reference,part)[key],'source crown plan');near(body.y0,height+(tower.bottom-h)/V,'source bearing height');near(body.y1,height+(cornice.bottom-h)/V,'clock body joins its cornice');near(cap.y0,body.y1,'joined cornice');
  const roof=f.feature(building,'civic-cupola-roof'),tiles=roof.children.find(mesh=>mesh.material?.name==='world:clay'),p=tiles.geometry.getAttribute('position');for(const panel of source.roof)for(const point of panel.points){const a=(point.x-reference.frame.origin.x)*reference.frame.u.x+(point.y-reference.frame.origin.y)*reference.frame.u.y,c=(point.x-reference.frame.origin.x)*reference.frame.v.x+(point.y-reference.frame.origin.y)*reference.frame.v.y,target=f.point(a,c,height+(point.z-h)/V);assert.ok(Array.from({length:p.count},(_,n)=>n).some(n=>Math.abs(p.getX(n)-target.x)<2e-5&&Math.abs(p.getZ(n)-target.z)<2e-5&&Math.abs(p.getY(n)-target.y)<2e-5),'source pyramid corners/apex must match');}assert.ok(roof.getObjectByName(`building-roof-edges:${f.b.id}:civic-cupola`));
  const face=crown.children.find(mesh=>mesh.material?.name==='world:linen'),faceBounds=bounds(f,face);assert.equal(face.material.color.getHexString(),circle.fill.slice(1));near(faceBounds.u0,u-circle.r*1.4/40,'source clock horizontal radius');near(faceBounds.u1,u+circle.r*1.4/40,'source clock horizontal radius');near(faceBounds.y0,height+20/V-circle.r/V,'source clock vertical radius');near(faceBounds.y1,height+20/V+circle.r/V,'source clock vertical radius');assert.equal(crown.children.some(mesh=>mesh.material?.name==='world:iron'),false,'the source cupola has no iron cross');f.dispose(building);
 }reference.dispose(reference.build());
});

test('the pale source arcade stroke remains visible over its wider shadow and keeps the exact facade-local widths',()=>{
 const reference=fixture(0),source=direct(reference),outer=source.paths.find(p=>Number(p.strokeWidth)===6),inner=source.paths.find(p=>Number(p.strokeWidth)===4.5);assert.ok(outer&&inner);assert.equal(outer.d,inner.d);
 for(const rotation of rotations){const f=fixture(rotation),building=f.build(),arc=f.feature(building,'civic-ground-arcade'),shadow=arc.children.find(mesh=>mesh.material.name==='world:cabildo-arcade-shadow'),trim=arc.children.find(mesh=>mesh.material.name==='world:cabildo-coping'),dark=bounds(f,shadow),pale=bounds(f,trim);assert.equal(shadow.material.color.getHexString(),outer.stroke.slice(1));assert.equal(trim.material.color.getHexString(),inner.stroke.slice(1));near(dark.u0,.14-Number(outer.strokeWidth)*.5*1.72/40,'source horizontal shadow stroke');near(pale.u0,.14-Number(inner.strokeWidth)*.5*1.72/40,'source horizontal trim stroke');near(dark.v0,-.35,'source facade plane');near(pale.v0,-.35-.001/T,'the narrow front layer cannot be hidden inside an opaque shadow');
  const u=4.14+.86*(1-Math.SQRT1_2),y=building.userData.height-24/V+17/V*Math.SQRT1_2,ray=new Raycaster(f.point(u,-1,y),new Vector3(f.frame.v.x,0,f.frame.v.y),0,T*1.6),visible=ray.intersectObject(building,true)[0];assert.ok(visible);assert.equal(visible.object.material,trim.material,'the visible arch face must show the narrow pale stroke');f.dispose(building);
 }reference.dispose(reference.build());
});

test('Cabildo source masonry and arc strokes retain local paint recipes and saved main wall/roof finishes',()=>{
 for(const rotation of rotations)for(const finish of ['adobe','limewash','ochre','stone','brick']){const f=fixture(rotation);f.b.wallFinish=finish;f.b.roofFinish='thatch';const building=f.build(),arc=f.feature(building,'civic-ground-arcade'),wall=arc.children.find(mesh=>mesh.material.name===`world:${finish}`&&mesh.material.userData.architectureFinish.texture.includes('plaster')).material,foot=arc.children.find(mesh=>mesh.material.name==='world:stone'&&mesh.material.color.getHexString()==='a99a79').material;assert.equal(wall.userData.architectureFinish.textureOpacity,.36);assert.equal(wall.userData.architectureFinish.multiplyOpacity,0);assert.equal(foot.userData.architectureFinish.textureOpacity,.60);assert.ok(building.getObjectByName(`building-fabric:${f.b.id}`).children.some(mesh=>mesh.material.name===`world:${finish}`&&mesh.material.userData.architectureFinish.role==='wall'));assert.ok(building.getObjectByName(`building-fabric:${f.b.id}`).children.some(mesh=>mesh.material.name==='world:thatch'));assert.ok(f.feature(building,'civic-cupola-roof').children.some(mesh=>mesh.material.name==='world:clay'),'source pyramid has its explicit thatch-to-clay exception');f.dispose(building);}
});

test('Cabildo standing doors, window centres and edited corner/support openings retain their real crossings',()=>{
 for(const rotation of rotations){const f=fixture(rotation);f.frame.door.open=true;const building=f.build();for(const offset of [-.20,0,.20])for(const y of [1.3,1.8,building.userData.openings.find(opening=>opening.id===f.frame.door.doorId).height-.065])assert.equal(new Raycaster(f.point(f.frame.doorU,-1,y).addScaledVector(new Vector3(f.frame.u.x,0,f.frame.u.y),offset),new Vector3(f.frame.v.x,0,f.frame.v.y),0,T*1.6).intersectObject(building,true).length,0);supported(f,f.feature(building,'civic-ground-arcade'));f.dispose(building);
  for(const corner of [false,true])for(const type of ['window','door','rubble']){const g=fixture(rotation),u=corner?0:2,p=g.frame.at(u,0);g.input.terrain.tiles.find(tile=>tile.x===p.x&&tile.y===p.y).type=type;g.input.terrain.tiles=[g.frame.door,...g.input.terrain.tiles.filter(tile=>tile!==g.frame.door)];const object=g.build(),inset=buildingArtInset(g.b,g.input);assert.equal(inset,corner?.4:0);supported(g,g.feature(object,'civic-ground-arcade'));assert.equal(new Raycaster(g.point(u-inset*(g.frame.u.x+g.frame.u.y),-1,type==='window'?1.3:1.9),new Vector3(g.frame.v.x,0,g.frame.v.y),0,T*1.6).intersectObject(object.getObjectByName(`building-details:${g.b.id}`),true).length,0);if(corner)assert.equal(g.feature(object,'civic-cupola-roof'),undefined,'edited corners retain the released round crown');g.dispose(object);}
 }
});

test('Cabildo has one ordinary arcade, keeps its edited tall two-level rule and excludes the actual shallow roof footprint',()=>{
 for(const rotation of rotations){for(const roof of ['slab','terrace','roof-route']){const f=fixture(rotation,'exterior',roof),building=f.build();assert.equal(f.feature(building,'civic-upper-arcade'),undefined);assert.equal(Boolean(f.feature(building,'civic-clock-tower')),roof!=='roof-route');supported(f,f.feature(building,'civic-ground-arcade'));f.dispose(building);}
  for(const mode of ['closed','front','side-cap','inner']){const f=fixture(rotation),p=f.frame.at(mode==='side-cap'?f.frame.doorU+1:f.frame.doorU,mode==='inner'?2:0);f.input.terrain.upperSurfaces=[{...p,kind:'roof',type:'floor',buildingId:f.b.id,tacticalLevel:1,elevation:5.1,blocked:mode==='closed',obstacleHeight:0}];const building=f.build();assert.ok(f.feature(building,'civic-upper-arcade'));assert.ok(f.feature(building,'civic-side-windows'));assert.equal(Boolean(f.feature(building,'civic-clock-tower')),['closed','inner'].includes(mode));supported(f,f.feature(building,'civic-ground-arcade'));f.dispose(building);}
  for(const view of ['partial','interior']){const f=fixture(rotation,view),building=f.build();for(const name of ['civic-ground-arcade','civic-upper-arcade','civic-clock-tower','civic-cupola-roof'])assert.equal(f.feature(building,name),undefined);f.dispose(building);}
 }
});

test('local Cabildo source geometry keeps metre UVs, ordinary illumination and the exact unpainted legacy fallback',()=>{
 for(const rotation of rotations){for(const night of [false,true]){const f=fixture(rotation);f.input.terrain.night=night;f.input.illumination={[`0:${f.b.x},${f.b.y}`]:.5};const building=f.build(),node=building.getObjectByName(`building-cabildo-facade:${f.b.id}`),expected=night?.27+.73*.5:1;node.traverse(mesh=>{if(!(mesh instanceof Mesh))return;const p=mesh.geometry.getAttribute('position'),uv=mesh.geometry.getAttribute('uv'),normal=mesh.geometry.getAttribute('normal'),colour=mesh.geometry.getAttribute('color');let vertical=0;for(let n=0;n<p.count;n++){for(const channel of ['getX','getY','getZ'])near(colour[channel](n),expected,'ordinary vertex light');if(n%3===0&&Math.abs(normal.getY(n))<.5&&mesh.material.userData.architectureFinish)for(const next of [n+1,n+2])if(Math.abs(p.getY(n)-p.getY(next))>.10){near(Math.abs(uv.getY(n)-uv.getY(next)),Math.abs(p.getY(n)-p.getY(next)),'retained metre wall course spacing');vertical++;}}if(mesh.material.userData.architectureFinish)assert.ok(vertical);});f.dispose(building);}
  const f=fixture(rotation);f.b.architecture='cabildo';f.b.kind=undefined;f.b.wallFinish=undefined;const building=f.build();assert.equal(buildingArtInset(f.b,f.input),.4);assert.equal(building.getObjectByName(`building-cabildo-facade:${f.b.id}`),undefined);assert.ok(f.feature(building,'civic-clock-tower').children.some(mesh=>mesh.material.name==='world:iron'));f.dispose(building);
 }
});
