import{register}from'node:module';register('./tactical-render-loader.mjs',import.meta.url);import test from'node:test';import assert from'node:assert/strict';import{Vector3,AnimationMixer,LoopOnce}from'../web/node_modules/three/build/three.module.js';import{publishedActor}from'./published-actor-fixture.mjs';import{createReachReviewBattle}from'../web/app/renderer-sandbox/reach-fixture.js';import{actBattle,presentedActBattle}from'../game/tactical.js';
const{ActorRuntime}=await import('../web/lib/three/actor-runtime.ts'),{presentActors}=await import('../web/lib/three/presentation.ts'),{admittedHealingIntervals}=await import('../web/lib/three/action-timing.ts'),{presentedFrameDuration}=await import('../web/lib/useEnemyPlayback.ts');
const appearances=['granadero','royalist','worker','surgeon','gaucho','friar','woman-scout','woman-shawl'];
for(const appearance of appearances)test(`${appearance}: ordinary prone care keeps complete native arms clear through admission/work/return`,async t=>{const rows=[];
 for(const lod of[0,1,2]){
  const anatomy=appearance.startsWith('woman-')?'female':'male',state=createReachReviewBattle('prone'),id='reach-healer-'+anatomy,patient='reach-patient-'+anatomy,doctor=state.units.find(u=>u.id===id);doctor.spriteAppearance=appearance;const saved=JSON.stringify(state),asset=await publishedActor(appearance,lod),entry=s=>[{key:'unit:'+id,kind:'unit',actor:s.units.find(u=>u.id===id)},{key:'unit:'+patient,kind:'unit',actor:s.units.find(u=>u.id===patient)}],shown=(s,frame,now)=>presentActors(s,entry(s),{},new Set(),{selected:id,mode:'heal',frame,now}).find(v=>v.id===id),actor=new ActorRuntime(asset,shown(state,undefined,0)),parts=[],meshes=[];actor.model.traverse(mesh=>{if(!mesh.isSkinnedMesh)return;meshes.push(mesh);const ix=mesh.geometry.attributes.skinIndex,w=mesh.geometry.attributes.skinWeight;for(let i=0;i<mesh.geometry.attributes.position.count;i++){let arm=0,forearm=0;for(let j=0;j<4;j++){const n=mesh.skeleton.bones[ix.getComponent(i,j)].name,v=w.getComponent(i,j);if(/^(upperarm_|lowerarm_|hand_|thumb_|index_|middle_|ring_|pinky_)/.test(n))arm+=v;if(n==='lowerarm_l')forearm+=v;}if(arm>.7)parts.push({mesh,index:i,support:forearm>.7});}});
  let minimum=Infinity,supportGap=0,maximumHandSpeed=0,maximumSupportSpeed=0,priorNow,priorHands,priorSupport;const seen=new Set();
  function sample(s,f,now){const v=shown(s,f,now);actor.update(v,now);actor.tick(priorNow===undefined?0:Math.max(0,(now-priorNow)/1000),now);actor.root.updateMatrixWorld(true);for(const m of meshes)m.skeleton.update();let left=Infinity;const support=[];for(const p of parts){if(!p.mesh.visible)continue;const point=p.mesh.getVertexPosition(p.index,new Vector3()).applyMatrix4(p.mesh.matrixWorld),y=point.y-v.position[1];minimum=Math.min(minimum,y);if(p.support){left=Math.min(left,y);support.push(point);}}const hands=['l','r'].map(side=>actor.model.getObjectByName('hand_'+side).getWorldPosition(new Vector3()));if(priorNow!==undefined&&now>priorNow){const dt=(now-priorNow)/1000;maximumHandSpeed=Math.max(maximumHandSpeed,...hands.map((p,i)=>p.distanceTo(priorHands[i])/dt));if(f&&actor.action.time>.15&&actor.action.time<1.25)maximumSupportSpeed=Math.max(maximumSupportSpeed,...support.map((p,i)=>p.distanceTo(priorSupport[i])/dt));}if(f&&actor.action.time>.15&&actor.action.time<1.25)supportGap=Math.max(supportGap,left);priorNow=now;priorHands=hands;priorSupport=support;seen.add(actor.action.getClip().name);assert.deepEqual(actor.root.position.toArray(),v.position);assert.equal(actor.root.rotation.y,v.yaw);assert.ok([...hands.flatMap(p=>p.toArray()),minimum].every(Number.isFinite));}
  for(let i=0;i<=80;i++)sample(state,undefined,i*1000/120);const order={type:'heal',unitId:id,targetId:patient},result=presentedActBattle(state,order);assert.equal(result.state.lastError,null);assert.deepEqual(result.state,actBattle(state,order));const frames=admittedHealingIntervals(result.frames),duration=frames.reduce((n,f)=>n+presentedFrameDuration(f,state),0);let start=700;
  for(const[index,f]of frames.entries()){const d=presentedFrameDuration(f,state),frame={...f,index,sequenceId:'native-care-floor',actionId:1,startedAt:start,durationMs:d,actionStartedAt:700,actionDurationMs:duration};for(let now=start;now<start+d-1e-5;now+=1000/120)sample(f.state,frame,now);start+=d;}
  for(let i=1;i<=60;i++)sample(result.state,undefined,start+i*1000/120);assert.equal(JSON.stringify(state),saved);assert.ok(seen.has('prone.gesture.heal'));assert.ok(minimum>=.0015,`${appearance} LOD${lod} floor ${minimum}`);assert.ok(supportGap<=.005,`${appearance} LOD${lod} opposite forearm support ${supportGap}`);assert.ok(maximumHandSpeed<1.1,`${appearance} LOD${lod} wrist speed ${maximumHandSpeed}`);assert.ok(maximumSupportSpeed<.12,`${appearance} LOD${lod} planted forearm speed ${maximumSupportSpeed}`);assert.equal(result.state.units.find(u=>u.id===id).medkits,doctor.medkits-1);rows.push({lod,minimum,supportGap,maximumHandSpeed,maximumSupportSpeed,duration});actor.dispose();
 }
 t.diagnostic(JSON.stringify(rows));
});

test('held entry/return blend weights preserve complete native finger and sleeve clearance',async t=>{const rows=[];
for(const appearance of['granadero','woman-scout'])for(const lod of[0,1,2]){const{body,animation}=await publishedActor(appearance,lod),model=body.scene,mixer=new AnimationMixer(model),idle=mixer.clipAction(animation.animations.find(c=>c.name==='prone.idle.unarmed')).setLoop(LoopOnce,1).play(),heal=mixer.clipAction(animation.animations.find(c=>c.name==='prone.gesture.heal')).setLoop(LoopOnce,1).play();idle.clampWhenFinished=heal.clampWhenFinished=true;const parts=[],meshes=[];model.traverse(mesh=>{if(!mesh.isSkinnedMesh)return;meshes.push(mesh);const ix=mesh.geometry.attributes.skinIndex,w=mesh.geometry.attributes.skinWeight;for(let i=0;i<mesh.geometry.attributes.position.count;i++){let arm=0;for(let j=0;j<4;j++){const n=mesh.skeleton.bones[ix.getComponent(i,j)].name;if(/^(upperarm_|lowerarm_|hand_|thumb_|index_|middle_|ring_|pinky_)/.test(n))arm+=w.getComponent(i,j);}if(arm>.7)parts.push({mesh,index:i});}});let minimum=Infinity,minimumAt;for(const idleTime of[0,.7])for(const time of[0,.04,.08,.12,1.28,1.32,1.36,1.399999976158142])for(let j=0;j<=12;j++){idle.enabled=heal.enabled=true;idle.setEffectiveWeight(1-j/12);heal.setEffectiveWeight(j/12);idle.time=idleTime;heal.time=time;mixer.update(0);model.updateMatrixWorld(true);for(const mesh of meshes)mesh.skeleton.update();for(const p of parts){const y=p.mesh.getVertexPosition(p.index,new Vector3()).applyMatrix4(p.mesh.matrixWorld).y;if(y<minimum){minimum=y;minimumAt={idleTime,healTime:time,healWeight:j/12};}}}rows.push({appearance,lod,minimum,minimumAt,cases:208});assert.ok(minimum>=.0015,`${appearance} LOD${lod} held fade ${minimum}`);}
t.diagnostic(JSON.stringify({states:rows.reduce((n,r)=>n+r.cases,0),minimum:Math.min(...rows.map(r=>r.minimum))}));});
