import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Mesh,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {buildingArtInset}=await import('../web/lib/three/world-building-placement.ts');
const {ISO_PITCH}=await import('../web/lib/three/projection.ts');
const {entranceFrame,getBuildingProfile}=await import('../game/building-profile.js');
const {buildingDetails}=await import('../web/app/TacticalBuildingDetails.tsx');
const {ArchitectureVolume}=await import('../web/app/TacticalBuildingVolumes.tsx');
const {createArchitectureReviewBattle}=await import('./legacy-building-fixtures.mjs');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270];
function fixture(rotation,view='exterior',roof='original'){
 const battle=createArchitectureReviewBattle('capilla',rotation,view,roof),b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},frame=entranceFrame({...b,walls:battle.tiles}),geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});
 return {b,input,frame,feature:node=>node.getObjectByName(`building-detail:${b.id}:chapel-corner-piers`),point(u,v,y){const p=frame.at(u,v);return new Vector3(p.x*T,y,p.y*T);},build(){const before=JSON.stringify(input),node=buildBuilding(b,input,T,geometry,materials);node.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before,'decoration may not change collision, openings or room disclosure');return node;},dispose(node){disposeWorldNode(node);geometry.dispose();materials.dispose();}};
}
function source(finish){const f=fixture(0);f.b.wallFinish=finish;const parts=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(node.type===ArchitectureVolume&&String(node.props.label).startsWith('chapel-corner-'))parts.push(node.props);visit(node.props?.children);};for(const object of buildingDetails({...f.b,walls:f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id)},new Set(),(x,y)=>({x:(x-y)*26,y:(x+y)*14})))visit(object.node);assert.equal(parts.length,6);const frame=f.frame,h=getBuildingProfile(f.b).wallHeight;f.dispose(f.build());return {parts,frame,h};}
function strokes(part){const result=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(node.type==='polygon'&&node.props.strokeWidth)result.push(node.props);visit(node.props?.children);};visit(ArchitectureVolume(part));return result;}
function edgesFor(f,direct,height){const result={body:[],foot:[]};for(const part of direct.parts){const kind=part.label.split('-').at(-1),bottom=kind==='base'?0:kind==='shaft'?getBuildingProfile(f.b).plinthHeight/V:height+(part.bottom-direct.h)/V,top=kind==='base'?part.top/V:kind==='shaft'?height+(direct.parts.find(p=>p.label===part.label.replace('-shaft','-capital')).bottom-direct.h)/V:height+(part.top-direct.h)/V;
 const lower=part.points.map(p=>{const u=(p.x-direct.frame.origin.x)*direct.frame.u.x+(p.y-direct.frame.origin.y)*direct.frame.u.y,v=(p.x-direct.frame.origin.x)*direct.frame.v.x+(p.y-direct.frame.origin.y)*direct.frame.v.y;return f.point(u,v,bottom);}),upper=lower.map(p=>new Vector3(p.x,top,p.z)),edges=result[kind==='base'?'foot':'body'];for(let n=0;n<4;n++){const next=(n+1)%4;edges.push({a:lower[n],b:upper[n],radius:.45/V*.5});if(kind!=='shaft'){edges.push({a:lower[n],b:lower[next],radius:.45/V*.5},{a:upper[n],b:upper[next],radius:(kind==='capital'?.5:.45)/V*.5});}}
 }return result;}
function distance(point,a,b){const d=b.clone().sub(a),t=Math.max(0,Math.min(1,point.clone().sub(a).dot(d)/d.lengthSq()));return point.distanceTo(a.clone().addScaledVector(d,t));}
function support(f,node){node.traverse(mesh=>{if(!(mesh instanceof Mesh))return;const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++){assert.ok(p.getY(n)>=-1e-6,'source lower strokes cannot enter the ground');const x=p.getX(n)/T,z=p.getZ(n)/T,tile=f.input.terrain.tiles.find(tile=>tile.x===Math.round(x)&&tile.y===Math.round(z));assert.equal(tile?.type,'wall','the entire stroke belongs to an intact actual wall support');assert.ok(Math.abs(x-tile.x)<=.49001&&Math.abs(z-tile.y)<=.49001,'fallback borders retain the complete solid-cell limit');}});}

 test('chapel border pigments and complete physical strokes follow the actual direct source recipe at all four rotations',()=>{
 for(const finish of ['adobe','limewash','ochre','stone','brick']){const direct=source(finish),shaft=direct.parts.find(p=>p.label.endsWith('-shaft')),foot=direct.parts.find(p=>p.label.endsWith('-base')),capital=direct.parts.find(p=>p.label.endsWith('-capital'));assert.equal(Number(strokes(shaft).find(p=>p.fill==='none').strokeWidth),.45);assert.equal(Number(strokes(foot)[0].strokeWidth),.45);assert.equal(Number(strokes(capital).find(p=>p.fill===capital.palette.trim).strokeWidth),.5);
  for(const rotation of rotations){const f=fixture(rotation);f.b.wallFinish=finish;const node=f.build(),pier=f.feature(node),expected=edgesFor(f,direct,node.userData.height);for(const [name,part,key]of [['world:chapel-pier-outline',shaft,'body'],['world:chapel-foot-outline',foot,'foot']]){const mesh=pier.children.find(mesh=>mesh.material.name===name);assert.ok(mesh,'current source face borders must be present');assert.equal(mesh.material.color.getHexString(),part.palette.shadow.slice(1));assert.equal(mesh.material.map,null);const p=mesh.geometry.getAttribute('position');let max=0;for(let n=0;n<p.count;n++){const point=new Vector3(p.getX(n),p.getY(n),p.getZ(n)),nearest=expected[key].map(edge=>({...edge,d:distance(point,edge.a,edge.b)})).sort((a,b)=>a.d/a.radius-b.d/b.radius)[0];assert.ok(nearest.d<=nearest.radius+2e-5,`${rotation}/${finish}/${name}: source edge radius ${nearest.radius}, got ${nearest.d}`);max=Math.max(max,nearest.d/nearest.radius);}assert.ok(p.count>100&&max>.98,'measure the full visible source stroke, rather than only its axis');}support(f,pier);f.dispose(node);}
 }
});

 test('native body, footing and coping retain their source recipes and metric UVs while local borders keep normal day and night illumination',()=>{
 for(const rotation of rotations)for(const night of [false,true]){const f=fixture(rotation),direct=source(f.b.wallFinish);f.input.terrain.night=night;f.input.illumination={[`0:${f.b.x},${f.b.y}`]:.5};const node=f.build(),pier=f.feature(node),body=pier.children.find(mesh=>mesh.material.name===`world:${f.b.wallFinish}`),foot=pier.children.find(mesh=>mesh.material.name==='world:stone'),coping=pier.children.find(mesh=>mesh.material.name==='world:chapel-pier-coping');assert.equal(body.material.color.getHexString(),direct.parts[0].palette.base.slice(1));assert.equal(body.material.userData.architectureFinish.textureOpacity,.36);assert.equal(body.material.userData.architectureFinish.texture,'/art/architecture-plaster-v2.png');assert.equal(foot.material.userData.architectureFinish.textureOpacity,.60);assert.equal(foot.material.color.getHexString(),'a99a79');assert.equal(coping.material.color.getHexString(),direct.parts[0].palette.trim.slice(1));
  for(const mesh of [body,foot]){const p=mesh.geometry.getAttribute('position'),n=mesh.geometry.getAttribute('normal'),uv=mesh.geometry.getAttribute('uv');for(let i=0;i<p.count;i++){const expected=Math.abs(n.getY(i))>.5?[p.getX(i),p.getZ(i)]:Math.abs(n.getX(i))>Math.abs(n.getZ(i))?[p.getZ(i)*(n.getX(i)>0?-1:1),p.getY(i)]:[p.getX(i)*(n.getZ(i)>0?1:-1),p.getY(i)];assert.ok(Math.abs(uv.getX(i)-expected[0])<2e-5&&Math.abs(uv.getY(i)-expected[1])<2e-5,'the released metric wall UVs remain exact');}}
  const expected=night?.27+.73*.5:1;for(const mesh of pier.children){const c=mesh.geometry.getAttribute('color');for(let i=0;i<c.count;i++)assert.ok(Math.abs(c.getX(i)-expected)<1e-6&&Math.abs(c.getY(i)-expected)<1e-6&&Math.abs(c.getZ(i)-expected)<1e-6);}f.dispose(node);
 }
});

 test('source borders are actually visible before the masonry at the ordinary camera angle without changing shaft exposure',()=>{
 const camera=new Vector3(Math.cos(ISO_PITCH)/Math.SQRT2,Math.sin(ISO_PITCH),Math.cos(ISO_PITCH)/Math.SQRT2);
 for(const rotation of rotations){const f=fixture(rotation),node=f.build(),pier=f.feature(node),out=new Vector3(-f.frame.v.x,0,-f.frame.v.y);for(const u of [0,f.frame.width]){const sample=u===0?.04:u-.04,ray=new Raycaster(f.point(sample,-1,1.3),out.clone().negate(),0,2*T),body=ray.intersectObject(pier,true)[0],wall=ray.intersectObject(node.getObjectByName(`building-fabric:${f.b.id}`),true)[0];assert.ok(Math.abs(wall.distance-body.distance-(.34*T-.09))<1e-5,'the original 33 cm shaft relief remains exact');if(out.x+out.z<=0)continue;
  const points=[f.point(u-.14,-.34,1.3),f.point(u+.14,-.34,1.3)],target=points.sort((a,b)=>b.x+b.z-a.x-a.z)[0],hit=new Raycaster(target.clone().addScaledVector(camera,20),camera.clone().negate(),0,20.1).intersectObject(node,true)[0];assert.equal(hit?.object.material.name,'world:chapel-pier-outline','the actual camera can see the source shaft edge before another wall or roof');}
  f.dispose(node);
 }
});

 test('standing door crossings and complete window approaches remain clear across all rotations, roof edits and clipped corner supports',()=>{
 for(const rotation of rotations)for(const roof of ['original','slab','terrace','roof-route']){const f=fixture(rotation,'exterior',roof);f.frame.door.open=true;const node=f.build(),pier=f.feature(node);for(const offset of [-.20,0,.20])for(const y of [1.3,1.8]){const start=f.point(f.frame.doorU,-1,y).add(new Vector3(offset*f.frame.u.x,0,offset*f.frame.u.y));assert.equal(new Raycaster(start,new Vector3(f.frame.v.x,0,f.frame.v.y),0,T*1.6).intersectObject(node,true).length,0);}
  if(pier){support(f,pier);for(const tile of f.input.terrain.tiles.filter(t=>t.type==='window'&&t.buildingId===f.b.id)){const onX=tile.x===f.b.x||tile.x===f.b.x+f.b.width-1,sign=onX?(tile.x===f.b.x?-1:1):(tile.y===f.b.y?-1:1);for(const x of [-.20,0,.20])for(const y of [1.3,1.8]){const start=onX?new Vector3((tile.x+sign)*T,y,tile.y*T+x):new Vector3(tile.x*T+x,y,(tile.y+sign)*T),dir=onX?new Vector3(-sign,0,0):new Vector3(0,0,-sign);assert.equal(new Raycaster(start,dir,0,T*1.6).intersectObject(pier,true).length,0,'source borders cannot conceal an authored window');}}}f.dispose(node);
 }
 for(const rotation of rotations)for(const type of ['rubble','window','door']){const f=fixture(rotation),point=f.frame.at(0,0);f.input.terrain.tiles.find(tile=>tile.x===point.x&&tile.y===point.y).type=type;f.input.terrain.tiles=[f.frame.door,...f.input.terrain.tiles.filter(t=>t!==f.frame.door)];const node=f.build(),pier=f.feature(node);assert.equal(buildingArtInset(f.b,f.input),.4);support(f,pier);f.dispose(node);}
});

 test('complete source stroke bounds respect short slabs, active roof routes, lower upper cells, ordinary disclosure and unpainted legacy selection',()=>{
 for(const rotation of rotations){const short=fixture(rotation,'exterior','slab');short.input.terrain.upperSurfaces=short.input.terrain.upperSurfaces.map(s=>({...s,elevation:1.8}));const node=short.build(),pier=short.feature(node);support(short,pier);let top=0;pier.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let i=0;i<p.count;i++)top=Math.max(top,p.getY(i));}});assert.ok(Math.abs(top-(1.8+2.5/V+.25/V))<2e-5,'complete bounds include the half-width of the actual source cap stroke');short.dispose(node);
  for(const blocked of [false,true]){const f=fixture(rotation),corners=[f.frame.at(0,0),f.frame.at(f.frame.width,0)];f.input.terrain.upperSurfaces=corners.map(p=>({...p,tacticalLevel:1,elevation:2.2,blocked,kind:'platform',buildingId:f.b.id,type:'floor'}));const n=f.build();assert.equal(Boolean(f.feature(n)),blocked,'the new borders obey the same actual upper cell exclusion');f.dispose(n);}
  for(const view of ['partial','interior']){const f=fixture(rotation,view),n=f.build();assert.equal(f.feature(n),undefined);f.dispose(n);}
  const route=fixture(rotation,'exterior','roof-route'),r=route.build();assert.equal(route.feature(r),undefined);route.dispose(r);
  const legacy=fixture(rotation);legacy.b.architecture='chapel';legacy.b.kind=undefined;legacy.b.wallFinish=undefined;const old=legacy.build();assert.equal(legacy.feature(old),undefined);legacy.dispose(old);
 }
});
