import{register}from'node:module';register('./tactical-render-loader.mjs',import.meta.url);
import assert from'node:assert/strict';import test from'node:test';import{Vector3}from'../web/node_modules/three/build/three.module.js';import{publishedActor}from'./published-actor-fixture.mjs';
const{ActorRuntime}=await import('../web/lib/three/actor-runtime.ts');const{presentActors}=await import('../web/lib/three/presentation.ts');const{createBattle,presentedActBattle,actBattle}=await import('../game/tactical.js');const{presentedFrameDuration}=await import('../web/lib/useEnemyPlayback.ts');
const tasks=[['heal',{activeSlot:'medical',medkits:2,hp:60,bleeding:4,medical:70},{targetId:'worker'}],['free',{activeSlot:'unarmed',entangled:true},{}],['weapon',{activeSlot:'unarmed'},{slot:'primary'}],['drop',{activeSlot:'unarmed',medkits:2},{item:'medkits',count:1}],['loot',{activeSlot:'unarmed',medkits:0},{groundId:'native-bundle'}],['door',{activeSlot:'unarmed'},{doorId:'native-door'}],['environment',{activeSlot:'unarmed'},{kind:'container',id:'native-chest',verb:'inspect'}],['ration',{activeSlot:'supply',activeSupply:'rations',rations:2,energy:60,fatigue:15},{}],['fitBayonet',{activeSlot:'primary',blade:1811,bladeInstanceId:'owned-socket',bladeFittingPattern:'india_socket'},{item:'blade'}]];
test('54 accepted prone interaction routes retain full boots through paid ordinary presentation and return',async t=>{
const rows=[];
for(const appearance of['granadero','woman-scout'])for(const lod of[0,1,2]){const asset=await publishedActor(appearance,lod);
for(const[type,patch,args]of tasks){const tiles=Array.from({length:192},(_,i)=>({x:i%24,y:Math.floor(i/24),type:'grass',blocked:false,cover:0}));if(type==='door')Object.assign(tiles.find(t=>t.x===3&&t.y===2),{type:'door',doorId:'native-door',open:false,locked:false,blocked:true,blocksSight:true});
const state=createBattle([{id:'worker',name:'Prone interaction worker',x:2,y:2,facing:2,weapon:1800,weaponInstanceId:'owned-rifle',loaded:1,ammo:8,condition:90,energy:100,stance:'prone',movementMode:'prone',spriteAppearance:appearance,...patch}],{width:24,height:8,seed:45,tiles,props:[{id:'native-chest',type:'chest',x:3,y:2,open:false,locked:false,contents:[]}],enemies:[{id:'far',x:22,y:6,weapon:0,patrol:false,overwatch:false}]});state.deploymentComplete=true;state.units[0].ap=100;if(type==='loot')state.groundItems=[{id:'native-bundle',type:'medkits',x:2,y:2,count:1}];
const before=JSON.stringify(state),unit=s=>s.units.find(u=>u.id==='worker'),show=(s,frame,now)=>presentActors(s,[{key:'unit:worker',kind:'unit',actor:unit(s)}],{},new Set(),{selected:'worker',mode:'move',frame,now})[0],actor=new ActorRuntime(asset,show(state,undefined,0)),mesh=actor.model.getObjectByName(asset.appearance.parts.footwear.replace('{lod}',String(lod))),native=new Map();actor.model.traverse(n=>{if(n.isBone)native.set(n.name,{position:n.position.clone(),scale:n.scale.clone()});});
let minimum=Infinity,contact=0,speed=0,prior,priorNow;const seen=new Set();const sample=(v,now)=>{const dt=priorNow===undefined?0:(now-priorNow)/1000;actor.update(v,now);actor.tick(Math.min(.1,Math.max(0,dt)),now);actor.root.updateMatrixWorld(true);mesh.skeleton.update();const points=[],feet={l:Infinity,r:Infinity};for(let i=0;i<mesh.geometry.attributes.position.count;i++){const p=mesh.getVertexPosition(i,new Vector3()).applyMatrix4(mesh.matrixWorld);p.y-=v.position[1];points.push(p);const side=mesh.geometry.attributes.position.getX(i)>0?'l':'r';feet[side]=Math.min(feet[side],p.y);if(prior&&dt>1e-6)speed=Math.max(speed,p.distanceTo(prior[i])/dt);}minimum=Math.min(minimum,feet.l,feet.r);contact=Math.max(contact,feet.l,feet.r);prior=points;priorNow=now;assert.deepEqual(actor.root.position.toArray(),v.position);assert.equal(actor.root.rotation.y,v.yaw);for(const[n,s]of native){const b=actor.model.getObjectByName(n);if(n!=='Root')assert.ok(b.position.distanceTo(s.position)<1e-6,n+' offset');assert.ok(b.scale.distanceTo(s.scale)<1e-6,n+' scale');}seen.add(actor.action.getClip().name);};
try{for(let i=0;i<=30;i++)sample(show(state,undefined,i*1000/60),i*1000/60);const order={type,unitId:'worker',...args},outcome=presentedActBattle(state,order);assert.equal(outcome.state.lastError,null,type+': '+outcome.state.lastError);assert.deepEqual(outcome.state,actBattle(state,order));assert.equal(JSON.stringify(state),before);const ap=unit(state).ap-unit(outcome.state).ap;assert.equal(ap,{heal:25,free:15,weapon:4,drop:4,loot:8,door:4,environment:4,ration:10,fitBayonet:12}[type],type+' pays exactly one ordinary action');assert.equal(unit(outcome.state).ammo,unit(state).ammo,'No ammunition changes during interaction');assert.equal(unit(outcome.state).loaded,unit(state).loaded,'The owned rifle load is retained');let start=500,total=outcome.frames.reduce((a,f)=>a+presentedFrameDuration(f,state),0);for(const[index,f]of outcome.frames.entries()){const duration=presentedFrameDuration(f,state),frame={...f,index,sequenceId:'prone-interaction',actionId:1,startedAt:start,durationMs:duration,actionStartedAt:500,actionDurationMs:total};for(let now=start;now<start+duration-1e-5;now+=1000/60)sample(show(f.state,frame,now),now);if(!duration)sample(show(f.state,frame,start),start);start+=duration;}for(let i=1;i<=40;i++)sample(show(outcome.state,undefined,start+i*1000/60),start+i*1000/60);
const gesture={weapon:'equip',drop:'offer',loot:'pickup',environment:'tool',fitBayonet:'fitting'}[type]??type;assert.ok(seen.has('prone.gesture.'+gesture),type+' actual admitted native clip');assert.ok(minimum>0,type+' whole boots clear floor');assert.ok(contact<.003,type+' both contacts below 3mm');assert.ok(speed<.0001,type+' retained static support');rows.push({appearance,lod,type,ap,total,minimum,contact,speed,seen:[...seen]});}finally{actor.dispose();}
}}
assert.equal(rows.length,54);t.diagnostic(JSON.stringify({routes:rows.length,minimum:Math.min(...rows.map(r=>r.minimum)),contact:Math.max(...rows.map(r=>r.contact)),speed:Math.max(...rows.map(r=>r.speed)),paid:rows.filter(r=>r.lod===0&&r.appearance==='granadero').map(({type,ap,total})=>({type,ap,total}))}));
});
