import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./tactical-render-loader.mjs',import.meta.url);
const {Mesh,Raycaster,Vector3}=await import('../web/node_modules/three/build/three.module.js');
const {WorldGeometry,disposeWorldNode}=await import('../web/lib/three/world-geometry.ts');
const {WorldMaterials}=await import('../web/lib/three/world-materials.ts');
const {buildBuilding}=await import('../web/lib/three/world-buildings.ts');
const {buildingArtInset,buildingFloorRectangles}=await import('../web/lib/three/world-building-placement.ts');
const {entranceFrame,getBuildingProfile}=await import('../game/building-profile.js');
const {buildingDetails}=await import('../web/app/TacticalBuildingDetails.tsx');
const {ArchitectureVolume}=await import('../web/app/TacticalBuildingVolumes.tsx');
const {createArchitectureReviewBattle}=await import('../web/app/renderer-sandbox/architecture-fixtures.js');
const T=1.2360585147470482,V=25.066666666666666,rotations=[0,90,180,270];
function fixture(rotation,view='exterior',roof='original'){
 const battle=createArchitectureReviewBattle('ayuntamiento',rotation,view,roof),b=battle.buildings[0],input={terrain:{width:battle.width,height:battle.height,tiles:battle.tiles,buildings:battle.buildings,upperSurfaces:battle.upperSurfaces},revealedRooms:battle.revealedRooms},frame=entranceFrame({...b,walls:battle.tiles}),geometry=new WorldGeometry(),materials=new WorldMaterials({tileMetres:T,assetUrl:path=>path});
 return {b,input,frame,materials,point(u,v,y){const p=frame.at(u,v),inset=buildingArtInset(b,input);return new Vector3((p.x+inset)*T,y,(p.y+inset)*T);},feature(building){return building.getObjectByName(`building-detail:${b.id}:townhall-formal-columns`);},build(){const before=JSON.stringify(input),object=buildBuilding(b,input,T,geometry,materials);object.updateMatrixWorld(true);assert.equal(JSON.stringify(input),before);return object;},dispose(object){disposeWorldNode(object);geometry.dispose();materials.dispose();}};
}
const near=(a,b,message)=>assert.ok(Math.abs(a-b)<2e-5,`${message}: ${a} versus ${b}`);
function boxes(f,node){const result=[],origin=f.frame.at(0,0),inset=buildingArtInset(f.b,f.input);node?.traverse(mesh=>{if(!(mesh instanceof Mesh))return;const p=mesh.geometry.getAttribute('position');assert.equal(p.count%36,0);for(let n=0;n<p.count;n+=36){const box={u0:Infinity,u1:-Infinity,v0:Infinity,v1:-Infinity,y0:Infinity,y1:-Infinity,material:mesh.material};for(let i=n;i<n+36;i++){const x=p.getX(i)/T-inset-origin.x,z=p.getZ(i)/T-inset-origin.y,u=x*f.frame.u.x+z*f.frame.u.y,v=x*f.frame.v.x+z*f.frame.v.y;box.u0=Math.min(box.u0,u);box.u1=Math.max(box.u1,u);box.v0=Math.min(box.v0,v);box.v1=Math.max(box.v1,v);box.y0=Math.min(box.y0,p.getY(i));box.y1=Math.max(box.y1,p.getY(i));}result.push(box);}});return result;}
function supported(f,node){node?.traverse(mesh=>{if(mesh instanceof Mesh){const p=mesh.geometry.getAttribute('position');for(let n=0;n<p.count;n++){assert.ok(p.getY(n)>=-1e-6);assert.equal(f.input.terrain.tiles.find(tile=>tile.x===Math.round(p.getX(n)/T)&&tile.y===Math.round(p.getZ(n)/T))?.type,'wall','all column, foot and capital geometry remains in its actual intact support cell');}}});}
function direct(f){const result=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(node.type===ArchitectureVolume)result.push(node.props);visit(node.props?.children);};for(const item of buildingDetails({...f.b,walls:f.input.terrain.tiles.filter(tile=>tile.buildingId===f.b.id)},new Set(),(x,y)=>({x:(x-y)*26,y:(x+y)*14})))visit(item.node);return result;}
function sourceBounds(f,part){const origin=f.frame.at(0,0),us=part.points.map(p=>(p.x-origin.x)*f.frame.u.x+(p.y-origin.y)*f.frame.u.y),vs=part.points.map(p=>(p.x-origin.x)*f.frame.v.x+(p.y-origin.y)*f.frame.v.y);return {u0:Math.min(...us),u1:Math.max(...us),v0:Math.min(...vs),v1:Math.max(...vs)};}
function footprint(box,r,message){for(const k of ['u0','u1','v0','v1'])near(box[k],r[k],`${message}/${k}`);}
function sourceReference(){const f=fixture(0),parts=direct(f),columns=parts.filter(p=>String(p.label).startsWith('townhall-entrance-column')),corners=parts.filter(p=>String(p.label).startsWith('townhall-corner')),upper=parts.filter(p=>String(p.label).startsWith('townhall-upper-corner'));assert.equal(columns.length,6);assert.equal(corners.length,6);assert.ok(upper.length);return {f,columns,corners,upper};}

test('town hall front columns and corner profiles match the current source dimensions and joined vertical planes',()=>{
 const source=sourceReference(),h=getBuildingProfile(source.f.b).groundFloorHeight;
 for(const rotation of rotations){const f=fixture(rotation),building=f.build(),node=f.feature(building),all=boxes(f,node),storey=building.userData.height*66/118;assert.equal(buildingArtInset(f.b,f.input),0);supported(f,node);
  for(const offset of [-2,2]){const u=f.frame.doorU+offset,parts=all.filter(p=>Math.abs((p.u0+p.u1)*.5-u)<1e-5&&p.v0<0&&p.v1>0),shaft=parts.find(p=>Math.abs(p.u1-p.u0-.28)<1e-5),foot=parts.find(p=>p.y0===0),caps=parts.filter(p=>p.y0>storey-.1);assert.ok(shaft&&foot&&caps.length===2);
   for(const [part,box]of [[source.columns.find(p=>p.label.includes('shaft')),shaft],[source.columns.find(p=>p.label.includes('base')),foot],[source.columns.find(p=>p.label.includes('capital')),caps[0]]]){const r=sourceBounds(source.f,part),centre=(r.u0+r.u1)*.5;footprint(box,{...r,u0:r.u0-centre+u,u1:r.u1-centre+u},`${rotation}/${part.label}`);}near(foot.y1,source.columns.find(p=>p.label.includes('base')).top/V,'source stone foot');near(shaft.y0,foot.y1,'one joined body starts above its foot');near(shaft.y1,storey+(source.columns.find(p=>p.label.includes('capital')).bottom-h)/V,'shaft joins capital');near(Math.max(...caps.map(p=>p.y1)),storey+(source.columns.find(p=>p.label.includes('capital')).top-h)/V,'source capital upper plane');
  }
  for(const u of [0,f.frame.width]){const parts=all.filter(p=>Math.abs((p.u0+p.u1)*.5-u)<1e-5&&p.v0<0&&p.v1>0),shaft=parts.find(p=>Math.abs(p.u1-p.u0-.27)<1e-5),foot=parts.find(p=>p.y0===0),caps=parts.filter(p=>Math.abs(p.u1-p.u0-.37)<1e-5);assert.ok(shaft&&foot&&caps.length===2);for(const [part,box]of [[source.corners.find(p=>p.label.endsWith('shaft')),shaft],[source.corners.find(p=>p.label.endsWith('base')),foot],[source.corners.find(p=>p.label.endsWith('capital')),caps[0]]]){const r=sourceBounds(source.f,part),centre=(r.u0+r.u1)*.5;footprint(box,{...r,u0:r.u0-centre+u,u1:r.u1-centre+u},`${rotation}/${part.label}`);}near(shaft.y0,foot.y1,'plaster pier joins the warm foot');near(shaft.y1,storey-5.5/V,'source corner capital lower plane');near(Math.max(...caps.map(p=>p.y1)),storey-.5/V,'source corner capital upper plane');}
  f.dispose(building);
 }source.f.dispose(source.f.build());
});

test('centred town hall source shafts expose real depth in front of the wall and preserve the standing aperture',()=>{
 for(const rotation of rotations){const f=fixture(rotation);f.frame.door.open=true;const building=f.build(),node=f.feature(building),fabric=building.getObjectByName(`building-fabric:${f.b.id}`),out=new Vector3(-f.frame.v.x,0,-f.frame.v.y);for(const u of [f.frame.doorU-2,f.frame.doorU+2]){const ray=new Raycaster(f.point(u,-1,1.3),out.clone().negate(),0,T*2),column=ray.intersectObject(node,true)[0],wall=ray.intersectObject(fabric,true)[0];assert.ok(column&&wall);near(wall.distance-column.distance,.34*T-.09,'the exposed source column shaft');assert.equal(ray.intersectObject(building,true)[0].object,column.object);}for(const offset of [-.20,0,.20])for(const y of [1.3,1.8])assert.equal(new Raycaster(f.point(f.frame.doorU,-1,y).addScaledVector(new Vector3(f.frame.u.x,0,f.frame.u.y),offset),out.clone().negate(),0,T*1.6).intersectObject(building,true).length,0);supported(f,node);f.dispose(building);}
});

test('town hall source stone and plaster recipes retain every saved wall and roof finish',()=>{
 for(const rotation of rotations)for(const finish of ['adobe','limewash','ochre','stone','brick']){const f=fixture(rotation);f.b.wallFinish=finish;f.b.roofFinish='aged';const source=direct(f).find(p=>String(p.label).includes('entrance-column-shaft')),building=f.build(),node=f.feature(building),stone=node.children.find(mesh=>mesh.material.name==='world:stone').material,wall=node.children.find(mesh=>mesh.material.name===`world:${finish}`&&mesh.material!==stone)?.material;assert.equal(stone.color.getHexString(),(source?.palette.base??'#a99a79').slice(1));assert.equal(stone.userData.architectureFinish.texture,'/art/architecture-stone-v2.png');assert.equal(stone.userData.architectureFinish.textureOpacity,.60);assert.equal(stone.userData.architectureFinish.multiplyOpacity,0);assert.ok(wall);assert.equal(wall.userData.architectureFinish.texture,'/art/architecture-plaster-v2.png');assert.equal(wall.userData.architectureFinish.textureOpacity,.36);assert.equal(wall.userData.architectureFinish.multiplyOpacity,0);assert.ok(building.getObjectByName(`building-fabric:${f.b.id}`).children.some(mesh=>mesh.material.name===`world:${finish}`&&mesh.material.userData.architectureFinish.role==='wall'));assert.ok(building.getObjectByName(`building-fabric:${f.b.id}`).children.some(mesh=>mesh.material.name==='world:aged'));f.dispose(building);}
});

test('town hall source support details keep edited windows, doors and rubble clear with exact corner fallback',()=>{
 for(const rotation of rotations)for(const corner of [false,true])for(const type of ['window','door','rubble']){const f=fixture(rotation),p=f.frame.at(corner?0:f.frame.doorU+2,0),tile=f.input.terrain.tiles.find(tile=>tile.x===p.x&&tile.y===p.y);tile.type=type;f.input.terrain.tiles=[f.frame.door,...f.input.terrain.tiles.filter(tile=>tile!==f.frame.door)];const building=f.build(),node=f.feature(building);assert.equal(buildingArtInset(f.b,f.input),corner?.4:0);supported(f,node);const details=building.getObjectByName(`building-details:${f.b.id}`),inset=buildingArtInset(f.b,f.input),u=(corner?0:f.frame.doorU+2)-inset*(f.frame.u.x+f.frame.u.y);assert.equal(new Raycaster(f.point(u,-1,type==='window'?1.3:1.8),new Vector3(f.frame.v.x,0,f.frame.v.y),0,T*1.6).intersectObject(details,true).length,0);if(corner){const all=boxes(f,node);assert.ok(all.some(box=>Math.abs((box.u1-box.u0)*T-.38)<1e-5&&Math.abs((box.v1-box.v0)*T-.38)<1e-5),'edited corners retain the released square feet and capitals');}f.dispose(building);}
});

test('town hall source columns retain actual short slabs, upper walking cells and ordinary room disclosure',()=>{
 for(const rotation of rotations){for(const roof of ['slab','terrace','roof-route']){const f=fixture(rotation,'exterior',roof),building=f.build(),node=f.feature(building);supported(f,node);if(roof==='terrace')near(building.userData.height,getBuildingProfile(f.b).wallHeight/V,'an explicit terrace keeps its authored tall storeys');else{assert.equal(building.userData.height,3);assert.equal(building.getObjectByName(`building-detail:${f.b.id}:townhall-upper-windows`),undefined);}if(roof==='roof-route')for(const u of [f.frame.doorU-2,f.frame.doorU+2])assert.equal(boxes(f,node).filter(part=>Math.abs((part.u0+part.u1)*.5-u)<1e-5&&part.v0<0).length,0,'a capital cannot overlap the actual roof route');f.dispose(building);}
  for(const blocked of [false,true]){const f=fixture(rotation),p=f.frame.at(f.frame.doorU-2,0);f.input.terrain.upperSurfaces=[{...p,tacticalLevel:1,elevation:1.5,blocked,kind:'platform',type:'floor',buildingId:f.b.id}];const building=f.build(),parts=boxes(f,f.feature(building));assert.equal(parts.some(part=>Math.abs((part.u0+part.u1)*.5-(f.frame.doorU-2))<1e-5&&part.v0<0),blocked);f.dispose(building);}
  for(const view of ['partial','interior']){const f=fixture(rotation,view),building=f.build();assert.equal(f.feature(building),undefined);f.dispose(building);}
 }
});

test('town hall centred floor returns keep the disclosed finish, physical hatches and original upper floors',()=>{
 for(const rotation of rotations){const f=fixture(rotation,'interior'),cell=f.b.rooms.flatMap(room=>room.cells).find(p=>p.x===f.b.x+1&&p.y===f.b.y+1),parts=buildingFloorRectangles(f.b,f.input,{...cell,elevation:0},T,[],buildingArtInset(f.b,f.input));assert.equal(parts[0].minX,f.b.x*T+.09);assert.equal(parts[0].minZ,f.b.y*T+.09);const opening={linkId:'civic-return',level:0,height:0,minX:f.b.x*T+.10,maxX:f.b.x*T+.30,minZ:f.b.y*T+.10,maxZ:f.b.y*T+.30};for(const rect of buildingFloorRectangles(f.b,f.input,{...cell,elevation:0},T,[opening],0))assert.ok(rect.maxX<=opening.minX||rect.minX>=opening.maxX||rect.maxZ<=opening.minZ||rect.minZ>=opening.maxZ);assert.deepEqual(buildingFloorRectangles(f.b,f.input,{...cell,tacticalLevel:1,elevation:3},T,[],0),[{minX:(cell.x-.5)*T,maxX:(cell.x+.5)*T,minZ:(cell.y-.5)*T,maxZ:(cell.y+.5)*T}]);f.dispose(f.build());}
});

test('town hall local source volumes keep metre UVs and normal illumination while legacy geometry stays released',()=>{
 for(const rotation of rotations){for(const night of [false,true]){const f=fixture(rotation);f.input.terrain.night=night;f.input.illumination={[`0:${f.b.x},${f.b.y}`]:.5};const building=f.build(),node=f.feature(building),expected=night?.27+.73*.5:1;for(const mesh of node.children){const p=mesh.geometry.getAttribute('position'),uv=mesh.geometry.getAttribute('uv'),normal=mesh.geometry.getAttribute('normal'),colour=mesh.geometry.getAttribute('color');let vertical=0;for(let n=0;n<p.count;n++){for(const channel of ['getX','getY','getZ'])near(colour[channel](n),expected,'normal vertex lighting');if(n%3===0&&Math.abs(normal.getY(n))<.5)for(const next of [n+1,n+2])if(Math.abs(p.getY(n)-p.getY(next))>.10){near(Math.abs(uv.getY(n)-uv.getY(next)),Math.abs(p.getY(n)-p.getY(next)),'metre course spacing');vertical++;}}if(mesh.material.map)assert.ok(vertical);}f.dispose(building);}
  const legacy=fixture(rotation);legacy.b.architecture='townhall';legacy.b.kind=undefined;legacy.b.wallFinish=undefined;const object=legacy.build(),parts=boxes(legacy,legacy.feature(object));assert.equal(buildingArtInset(legacy.b,legacy.input),.4);assert.ok(parts.some(p=>Math.abs((p.u1-p.u0)*T-.38)<1e-5&&Math.abs((p.v1-p.v0)*T-.38)<1e-5));assert.equal(legacy.feature(object).children.find(mesh=>mesh.material.name==='world:stone').material.userData.architectureFinish,undefined);legacy.dispose(object);const painted=fixture(rotation);painted.b.architecture='townhall';painted.b.kind=undefined;painted.b.wallFinish='limewash';const authored=painted.build();assert.equal(buildingArtInset(painted.b,painted.input),0);assert.equal(painted.feature(authored).children.find(mesh=>mesh.material.name==='world:stone').material.color.getHexString(),'a99a79');supported(painted,painted.feature(authored));painted.dispose(authored);
 }
});
