import {register} from 'node:module';register('./tactical-render-loader.mjs',import.meta.url);
import test from 'node:test';import assert from 'node:assert/strict';import {createElement as h} from '../web/node_modules/react/index.js';import {renderToStaticMarkup as render} from '../web/node_modules/react-dom/server.node.js';import {createBattle} from '../game/tactical.js';
const {default:Roster}=await import('../web/app/JA2Roster.tsx');
const {default:Hands}=await import('../web/app/JA2Hands.tsx');
const html=(unit={})=>{const battle=createBattle([{id:'p',...unit}],{exploration:true,enemies:[]});return render(h(Hands,{battle,unit:battle.units[0],busy:false,onPick(){},onOrder(){}}));};
test('inventory shows exactly two hand slots and locks the second while holding a long gun',()=>{const text=html({weapon:1800,blade:1813});assert.equal((text.match(/<button/g)||[]).length,2);assert.match(text,/Segunda mano: Ocupada por el arma/);assert.match(text,/class="blocked" disabled/);assert.doesNotMatch(text,/weapon-1813/);});
test('each held pistol shows its own load and condition',()=>{const text=html({weapon:1805,condition:81,loaded:1,offHand:{count:1,weapon:1808,weight:1.3,loaded:2,condition:57}});assert.match(text,/weapon-1805/);assert.match(text,/weapon-1808/);assert.match(text,/1 carga\(s\) · 81%/);assert.match(text,/2 carga\(s\) · 57%/);assert.doesNotMatch(text,/disabled/);});
test('a medkit uses a hand and the long gun appears only after putting it back in the hand',()=>{const text=html({weapon:1800,activeSlot:'medical',medkits:1,blade:1813});assert.match(text,/Mano principal: Vendas/);assert.match(text,/weapon-1813/);assert.doesNotMatch(text,/weapon-1800|Ocupada por el arma/);});

test('an ordinary object shows its condition in the main hand with the second hand available',()=>{const text=html({weapon:1805,activeSlot:'item',activeItem:'inventory:keepsake',inventory:{keepsake:{name:'Recuerdo',count:1,weight:.3,condition:44}}});assert.match(text,/Mano principal: Recuerdo/);assert.match(text,/Estado 44%/);assert.doesNotMatch(text,/Ocupada por el arma/);});

test('the squad portrait describes an ordinary held object without labelling it a weapon',()=>{const b=createBattle([{id:'p',name:'Vigía',weapon:1805,activeSlot:'item',activeItem:'inventory:note',inventory:{note:{count:1,weight:.1,name:'Carta'}}}],{exploration:true,enemies:[]});const text=render(h(Roster,{battle:b,players:b.units.filter(u=>u.side==='player'),selected:'p',onSelect(){},onOpenInventory(){}}));assert.match(text,/Mano principal: Carta/);const mainHand=text.match(/<span class="ja2-roster-hand held" data-hand-side="right"[^]*?<\/span>/)?.[0]??'';assert.match(mainHand,/data-hand-item="inventory:note"/);assert.match(mainHand,/lucide-package/);assert.doesNotMatch(mainHand,/<img|data-close-combat="true"/);assert.doesNotMatch(text,/Arma blanca/);});
