'use client';
// Read only the status while sampling: a full DOM/AX snapshot disturbs frame timing.
// Inspect the full page before starting or after the eight-second result.
import {Profiler,useEffect,useRef,useState} from 'react';
import Battlefield from '../Battlefield';
import {useBattleExecutor} from '../../lib/useBattleExecutor';
import {enterSector} from '../../../game/world.js';
import {getReachable,initializeBattlePerception,visibleEnemies} from '../../../game/tactical.js';
export default function Gameplay(){
 const [battle,setBattle]=useState(()=>enterSector({sector:'buenos_aires',squad:[{id:3},{id:4},{id:5}],enemies:[],exploration:true,hour:0,seed:8}));
 const calculation=useBattleExecutor(battle);
 const timings=useRef<{searchMs:number;orderMs:number;renders:{phase:string;duration:number}[]}>({searchMs:0,orderMs:0,renders:[]});
 const prepared=useRef<any>(null),outcome=useRef<any>(null);
 const [running,setRunning]=useState(false),[result,setResult]=useState('Prepare a route');
 useEffect(()=>{if(!running)return;let handle=0,last=performance.now(),start=last;const moving:number[]=[],all:number[]=[],slow:any[]=[],tasks:any[]=[];
 const observer=new PerformanceObserver(list=>{for(const entry of list.getEntries())tasks.push({at:entry.startTime-start,duration:entry.duration,...(entry.entryType==='long-animation-frame'?{frame:entry.toJSON()}:{} )});});
 observer.observe({entryTypes:['longtask','long-animation-frame'].filter(type=>PerformanceObserver.supportedEntryTypes.includes(type))});
 let issued=false;
 const tick=(now:number)=>{const gap=now-last;last=now;all.push(gap);if(gap>16.8)slow.push({at:now-start,gap,moving:Boolean(document.querySelector('[data-moving="true"]'))});if(document.querySelector('[data-moving="true"]'))moving.push(gap);if(!issued&&prepared.current){issued=true;const orderStart=performance.now();const {jobKind='action',...request}=prepared.current;prepared.current=null;void calculation.run(request,jobKind).then((result:any)=>{const next=jobKind==='group'?result?.state:result;timings.current.orderMs=performance.now()-orderStart;if(!next){outcome.current={cancelled:true};return;}outcome.current={...(jobKind==='group'?{group:{status:result.status,actions:result.actions,members:result.members.map((m:any)=>({id:m.unitId,status:m.status,moved:m.moved,to:m.to}))}}:{}),phase:next.phase,lastError:next.lastError,visibleEnemies:visibleEnemies(next).length,position:next.units.filter((u:any)=>u.side==='player').map((u:any)=>({id:u.id,x:u.x,y:u.y}))};setBattle(next);});}if(now-start<8000)handle=requestAnimationFrame(tick);else{const sorted=[...moving].sort((a,b)=>a-b);setRunning(false);setResult(JSON.stringify({orderMetric:'asynchronous elapsed time, not main-thread CPU time',outcome:outcome.current,scenario:{reactionEnabled:battle.units.some((u:any)=>u.side==='enemy'&&u.overwatch!==false),enemies:battle.units.filter((u:any)=>u.side==='enemy'&&u.hp>0).length,players:battle.units.filter((u:any)=>u.side==='player'&&u.hp>0).length,night:battle.night,visibleEnemies:visibleEnemies(battle).length,renderedActors:document.querySelectorAll('[data-unit-id]').length},timings:timings.current,movingFrames:moving.length,mean:moving.reduce((a,b)=>a+b,0)/moving.length,p95:sorted[Math.floor(sorted.length*.95)],p99:sorted[Math.floor(sorted.length*.99)],max:Math.max(...moving),overBudget:moving.filter(v=>v>16.8).length,slow,tasks,wholeMax:Math.max(...all),wholeOverBudget:all.filter(v=>v>16.8).length,wholeMean:all.reduce((a,b)=>a+b,0)/all.length}));}};handle=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(handle);observer.disconnect();};},[running]);
 const prepare=(group=false)=>{timings.current={searchMs:0,orderMs:0,renders:[]};const searchStart=performance.now();const u=battle.units.find((u:any)=>u.side==='player');const path=getReachable(battle,u).filter((p:any)=>p.path?.length>=10&&p.path.length<=18).sort((a:any,b:any)=>b.path.length-a.path.length)[0];timings.current.searchMs=performance.now()-searchStart;prepared.current=path?(group?{jobKind:'group',unitIds:battle.units.filter((u:any)=>u.side==='player').map((u:any)=>u.id),anchorId:u.id,x:path.x,y:path.y,tacticalLevel:path.tacticalLevel??0}:{type:'move',unitId:u.id,x:path.x,y:path.y,tacticalLevel:path.tacticalLevel??0}):null;setResult(path?'Route prepared':'no path');};
 const measure=()=>{if(!prepared.current||running)return;timings.current.renders=[];setRunning(true);setResult('measuring');};
 const scene=(sector:string,enemyCount=0,reactions=true,lineup=true)=>{prepared.current=null;outcome.current=null;let next=enterSector({sector,squad:[{id:3},{id:4},{id:5},{id:1},{id:7},{id:8}],enemies:Array.from({length:enemyCount},()=>({overwatch:reactions})),exploration:true,hour:12,seed:8});if(enemyCount&&lineup){next.units.filter((u:any)=>u.side==='player').forEach((u:any,i:number)=>{u.x=43;u.y=20+i;u.facing=6;});next=structuredClone(next);initializeBattlePerception(next);}setBattle(next);setResult('Prepare a route');};
 return <><button disabled={running} onClick={()=>scene('tucuman')}>Forest scene</button><button disabled={running} onClick={()=>scene('tucuman',4)}>Four enemies</button><button disabled={running} onClick={()=>scene('tucuman',30)}>Thirty enemies</button><button disabled={running} onClick={()=>scene('tucuman',30,false)}>Thirty enemies without reactions</button><button disabled={running} onClick={()=>scene('tucuman',30,true,false)}>Thirty hidden enemies</button><button disabled={running} onClick={()=>{prepared.current=null;timings.current={searchMs:0,orderMs:0,renders:[]};setRunning(true);setResult('measuring');}}>Measure scene</button><button onClick={()=>setBattle({...battle,night:!battle.night,startSeconds:(battle.night?12:24)*3600-battle.elapsedSeconds})}>Change lighting</button><button onClick={()=>setBattle({...battle,revealedRooms:battle.buildings.flatMap((b:any)=>b.rooms.map((r:any)=>r.id))})}>Reveal rooms</button><button disabled={running} onClick={()=>prepare()}>Prepare route</button><button disabled={running} onClick={()=>prepare(true)}>Prepare group route</button><button disabled={running} onClick={measure}>Measure walk</button><output style={{display:"block",height:64,overflow:"auto"}}>{result}</output><Profiler id="battlefield" onRender={(_id,phase,duration)=>{if(duration>1)timings.current.renders.push({phase,duration});}}><Battlefield battle={battle} onChange={setBattle} onFinish={()=>{}}/></Profiler></>;
}
