'use client';
import {AMMO_TYPES,ammoTypeFor,ammunitionLoadsFor,ammunitionChoiceReason} from '../../game/ammo-types.js';
import {projectileEnergyJ} from '../../game/projectile-energy.js';
export default function AmmunitionLoadChoice({unit,disabled=false,onSelect,onUnload,unloadCost=''}:{unit:any;disabled?:boolean;onSelect:(family:string)=>void;onUnload:()=>void;unloadCost?:string}){
 const loads=ammunitionLoadsFor(unit);if((loads.length<2&&!loads[0]?.projectileEnergy)||unit.weaponDropped||unit.activeSlot==='blade'||unit.activeSlot==='unarmed')return null;
 const reason=ammunitionChoiceReason(unit,ammoTypeFor(unit)),selected=loads.find((load:any)=>load.family===ammoTypeFor(unit)),profile=selected?.projectileEnergy,drag=selected?.projectileAirDrag;
 const retained=drag?.retentionAtRange<.0001?'menos del 0,01 %':`cerca del ${(drag?.retentionAtRange*100).toLocaleString('es-AR',{maximumFractionDigits:2})} %`;
 return <div className="ammunition-load-choice"><label>Carga para esta arma<select aria-label="Carga para esta arma" value={ammoTypeFor(unit)} disabled={disabled||!!reason} onChange={e=>onSelect(e.target.value)}>{loads.map((load:any)=><option key={load.family} value={load.family}>{AMMO_TYPES[load.family].name}{load.damage?` · daño ${load.damage} · alcance ${load.range} · ${load.pattern==='cone'?'abanico':'tiro único'}`:' · carga principal'}</option>)}</select></label>{profile&&<small aria-label="Energía de la carga">{profile.massGrams} g de proyectiles · {profile.muzzleVelocityMps} m/s · {projectileEnergyJ(profile).toLocaleString('es-AR',{maximumFractionDigits:2})} J iniciales. La cobertura y los cuerpos gastan energía; el daño conserva su límite. Modelo de juego.</small>}{drag&&<small aria-label="Energía en el aire">{drag.retentionAtRange<1?`Tras una distancia de vuelo libre igual al alcance de esta carga, conserva ${retained} de energía. La distancia puede reducir el daño y la penetración.`:'Esta carga conserva su energía en el aire.'}</small>}{reason&&<small>{reason}</small>}<button disabled={disabled||!(unit.loaded>0)||!!unit.reloadProgress||unit.weaponDropped||unit.activeSlot==='blade'||unit.activeSlot==='unarmed'} onClick={onUnload}>Descargar arma{unloadCost}</button></div>;
}
