'use client';
import {SendArtillery,ArtilleryStorage} from './ArtilleryTransport';
import ArtilleryTrading from './ArtilleryTrading';
import {localArtilleryDepot,depotSelection} from '../../game/artillery-transport.js';
import {artilleryProfile} from '../../game/artillery-definitions.js';
import {artillerySupplyQuote} from '../../game/artillery-supply.js';
import {stationedArtillery} from '../../game/campaign-artillery.js';
import {cartridgePrice} from '../../game/campaign-rules.js';
import {importRulesFor,importPortName,importOrderReason,importDelayReason} from '../../game/campaign-imports.js';
import {usesAuthoredEquipment} from '../../game/armory-items.js';
import {weaponSpecification} from '../../game/weapon-definition.js';
import {tradeQuote} from '../../game/politics.js';
import {useState} from 'react';
import {rosterFor,isSupplied,operativeLocation} from '../../game/campaign.js';
import {workshopServiceQuote} from '../../game/workshop-service.js';
import {campaignPlace} from '../../game/world-cells.js';
import {artilleryDeploymentChoices,artillerySelectionReason,isImportedEquipment,EQUIPMENT_CATALOG,equipmentCatalog,armoryOptions,armoryInventory} from '../../game/equipment.js';
import './armory.css';
type Props={state:any;dispatch:(action:any)=>void};
export default function Armory({state:s,dispatch}:Props){
 const [selected,setSelected]=useState(String(s.recruited[0]??3));const roster=rosterFor(s),op=roster.find(o=>String(o.id)===selected&&s.recruited.includes(o.id)&&s.operativeState[o.id].alive)??roster.find(o=>s.recruited.includes(o.id)&&s.operativeState[o.id].alive);
 const [battery,setBattery]=useState<string[]|null>(null),batteryTypes=battery??artilleryDeploymentChoices(s),batteryReason=artillerySelectionReason(s,batteryTypes.filter(Boolean));const emplacements=stationedArtillery(s),inventory=armoryInventory(s),record=op?s.operativeState[op.id]:null;
 const resupply=workshopServiceQuote(s,op,'resupply',isSupplied(s,s.location)),repair=workshopServiceQuote(s,op,'repairWeapon',isSupplied(s,s.location));
 const authored=usesAuthoredEquipment(s),catalog=equipmentCatalog(s),imports=importRulesFor(s),importBlocked=importOrderReason(s),delayReason=importDelayReason(s);
 const equip=(slot:string,key:string)=>{if(!op||!key)return;const item:any=armoryOptions(s,op,slot).find((w:any)=>w.key===key);if(item)dispatch({type:'equip',operativeId:op.id,slot,itemId:item.item,...(item.instanceId?{instanceId:item.instanceId}:{})});};
 return <section className="armory-section"><div className="section-intro"><p className="eyebrow">SALA DE ARMAS</p><h2>El equipo de cada combatiente</h2><p>Las armas locales se entregan en la armería. {imports.port===null?'Esta campaña no admite pedidos de armas importadas.':`Las armas importadas llegan a ${importPortName(s)} en ${imports.minHours===imports.maxHours?imports.minHours:`${imports.minHours} a ${imports.maxHours}`} horas; los bloqueos y la ocupación del puerto demoran la entrega.`} Al cambiar un equipo, el arma anterior vuelve a la armería. La munición se compra al entrar al sector: {cartridgePrice(s)} {cartridgePrice(s)===1?'peso':'pesos'} por cartucho; al salir se devuelve el valor de los cartuchos restantes. Las monturas están incluidas en el equipo.</p></div>
  <div className="production-queue">{importBlocked&&imports.port!==null&&<p>{importBlocked}</p>}{(s.equipmentShipments??[]).map((q:any,i:number)=><p key={i}>{q.quantity} × {catalog.find(w=>w.item===q.item)?.name} · {Math.max(0,q.due-s.hour)} horas{delayReason?` · ${delayReason}`:''}</p>)}</div><div className="armory-layout"><div className="armory-loadout"><label htmlFor="armory-officer">Hoja de equipo<select id="armory-officer" value={String(op?.id??'')} onChange={e=>setSelected(e.target.value)}>{roster.filter(o=>s.recruited.includes(o.id)&&s.operativeState[o.id].alive).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
  {op&&<><h3>{op.name}</h3><p>Ubicación: {campaignPlace(operativeLocation(s,op.id))?.name}</p>{(['weapon','blade'] as const).map(slot=><label key={slot} htmlFor={`armory-${slot}`}>{slot==='weapon'?'Arma principal':'Arma blanca'}<select id={`armory-${slot}`} value={authored?'equipped':String(op[slot])} onChange={e=>equip(slot,e.target.value)}>
   {authored&&<option value="equipped">{(slot==='weapon'?weaponSpecification(op):weaponSpecification(op,'blade'))?.name??'Sin arma'} · Equipada</option>}
   {armoryOptions(s,op,slot).map((w:any)=><option key={w.key} value={w.key}>{w.name}{w.equipped?' · Equipada':authored?` · Estado ${w.condition}% · ${w.key}`:` · ${s.armory[w.item]} disponibles`}</option>)}
  </select></label>)}

  <div className="armory-condition"><span>Estado del arma <b>{record?.condition??100}%</b></span><span>Cargas de cebo <b>{record?.priming??50}/50</b></span><span>Piedras de sílex <b>{record?.flints??4}/4</b></span><span>Raciones <b>{record?.rations??2}/2</b></span></div>
  <button className="line-button" disabled={!resupply.available} title={resupply.reason||undefined} onClick={()=>dispatch({type:'resupply',operativeId:op.id})}>Reponer provisiones · {resupply.cost} pesos</button>
  <button className="line-button" disabled={!repair.available} title={repair.reason||undefined} onClick={()=>dispatch({type:'repairWeapon',operativeId:op.id})}>Reparar arma · {repair.cost} pesos</button><small>{resupply.reason===repair.reason?resupply.reason||'La reposición y la reparación se realizan para esta persona en el taller actual.':[resupply.reason&&`Provisiones: ${resupply.reason}`,repair.reason&&`Reparación: ${repair.reason}`].filter(Boolean).join(' ')}</small></>}
  {emplacements.length>0&&<section aria-label="Artillería emplazada"><h3>Piezas emplazadas en este sector</h3><p>Conservan su posición y munición al volver. Permanecen aquí cuando la escuadra sale. Para moverlas, organizá un traslado. Al retirarte de un combate pueden quedar en manos realistas.</p>{emplacements.map(({sector,gun}:any)=>{const quote=artillerySupplyQuote(s,sector,gun.id,isSupplied(s,s.location));return <div key={`${sector}:${gun.id}`} data-artillery-id={gun.id}><p>{equipmentCatalog(s).find(item=>item.item===gun.type)?.name} · {gun.loaded?'Cargada':gun.reloadProgress?`Recarga ${Math.floor(gun.reloadProgress*100)}%`:'Descargada'} · {gun.ammo} en reserva · {gun.side==='player'?'Propia':'Realista'}</p><button className="line-button" disabled={!quote.available} title={quote.reason||undefined} onClick={()=>dispatch({type:'resupplyArtillery',sector,artilleryId:gun.id})}>Comprar 1 munición · {quote.cost} pesos</button><small>{quote.reason||`Se entrega en reserva, sin cargar la pieza. Límite de reposición: ${quote.limit}.`}</small><SendArtillery state={s} sector={sector} gun={gun} dispatch={dispatch}/></div>;})}</section>}
  <ArtilleryStorage state={s}/><ArtilleryTrading state={s} dispatch={dispatch} supplied={isSupplied(s,s.location)}/><h3>Batería de campaña</h3><p>Elegí hasta tres piezas de la armería o del depósito local para el próximo ataque. Preparar todos los espacios sin pieza deja los cañones guardados.</p>{[0,1,2].map(i=><label key={i} htmlFor={`battery-${i}`}>Pieza {i+1}<select id={`battery-${i}`} value={batteryTypes[i]??''} onChange={e=>{const next=[...batteryTypes];next[i]=e.target.value;setBattery(next);}}><option value="">Sin pieza</option>{equipmentCatalog(s).filter(w=>w.category==='artillery').map(w=><option key={w.item} value={w.item}>{w.name}</option>)}{localArtilleryDepot(s).map((gun:any)=><option key={gun.id} value={depotSelection(gun)}>Depósito: {artilleryProfile(s,gun).name} · {gun.loaded?'cargada':gun.reloadProgress?`recarga ${Math.floor(gun.reloadProgress*100)}%`:'descargada'} · {gun.ammo} en reserva</option>)}</select></label>)}<button className="gold-button" disabled={Boolean(batteryReason)||Boolean(s.pendingBattle)} onClick={()=>{dispatch({type:'configureArtillery',types:batteryTypes.filter(Boolean)});setBattery(null);}}>Preparar batería</button>{batteryReason&&<p role="status">{batteryReason}</p>}
  </div><div className="armory-catalog">{['firearm','blade','artillery'].map(category=><div key={category}><h3>{category==='firearm'?'Armas de chispa':category==='blade'?'Acero y armas de asta':'Piezas de artillería'}</h3>{inventory.filter(w=>w.category===category).map((w:any)=><article key={w.item}><img className="armory-weapon-art" src={w.art??`/art/weapon-${w.id}.png`} alt={w.name}/><div><strong>{w.name}</strong><small>{w.quantity} en armería{w.category==='artillery'?` · Dotación: ${w.crew} hombres`:''}</small></div><button className="line-button" disabled={Boolean(isImportedEquipment(w)&&importBlocked)||s.resources.treasury<(isImportedEquipment(w)?tradeQuote(s,w.price):w.price)} onClick={()=>dispatch({type:'purchaseEquipment',item:w.item,quantity:1})}>{isImportedEquipment(w)?'Importar':'Comprar'} · {isImportedEquipment(w)?tradeQuote(s,w.price):w.price} pesos</button></article>)}</div>)}</div></div>
 </section>;
}
