'use client';
import TacticalScene from './TacticalScene';
import './tactical-hud.css';
import {TACTICAL_KEYS,tacticalShortcut} from '../../game/hotkeys.js';
import {portraitFor} from '../lib/portraits';
import { useEffect, useMemo, useState, useRef } from 'react';
import { useUnitMotion } from './useUnitMotion';
import RecoveredInventory from './RecoveredInventory';
import TrainingProgress from './TrainingProgress';
import { Crosshair, Footprints, Swords, RotateCcw, Heart, ChevronRight, Flag, Shield, Target, Eye, CircleArrowUp } from 'lucide-react';
import { actBattle, endTurn, getReachable, shotChance, weaponFor, reloadCost, hasFirearm, bladeFor, actionCosts, ignitionRisk, artilleryCosts, ARTILLERY, visibleEnemies, visibleTiles, visibleRooms, canSee, tileIllumination, carriedWeight, carryCapacity } from '../../game/tactical.js';

type Props = {battle:any; onChange:(s:any)=>void; onFinish:()=>void; onRetreat:()=>void; onMap?:()=>void; onMissionFinish?:()=>void; mission?:any; conversation?:any; quests?:any; onTalk?:(npcId:string,approach:string,unitId:string)=>void};
const isAlive=(u:any)=>u.hp>0&&!u.routed&&!u.unconscious;
const short=(u:any)=>u.nickname||u.name.split(' ').slice(-1)[0];
export default function Battlefield({battle:s,onChange,onFinish,onRetreat,conversation,onTalk,onMap,quests,onMissionFinish,mission}:Props){
  const motion=useUnitMotion(s);
  const [keyHelp,setKeyHelp]=useState(false);
  const [talking,setTalking]=useState<any>(null);
  const [showSight,setShowSight]=useState(false);
  const [selected,setSelected]=useState(s.units.find((u:any)=>u.side==='player')?.id);
  const [poses,setPoses]=useState<Record<string,string>>({});const [directions,setDirections]=useState<Record<string,number>>({});const [zoom,setZoom]=useState(1.8);const [cameraOffset,setCameraOffset]=useState({x:0,y:0});const [cameraFollowsSelection,setCameraFollowsSelection]=useState(false);const cameraSelection=useRef(selected);const [details,setDetails]=useState(false);const [mode,setMode]=useState('move');const [aim,setAim]=useState(0);const [hover,setHover]=useState<any>(null);const [turnBusy,setBusy]=useState(false);const busy=turnBusy||motion.moving;
  const u=s.units.find((u:any)=>u.id===selected);const players=s.units.filter((u:any)=>u.side==='player');const enemies=visibleEnemies(s);const renderedUnits=s.units.filter((v:any)=>v.side==='player'||players.some((p:any)=>canSee(s,p,v)));const sight=new Set<string>(u?visibleTiles(s,u).map((t:any)=>`${t.x},${t.y}`):[]);
  const revealedBuildingRooms=useMemo(()=>new Set<string>([...(s.revealedRooms||[]),...visibleRooms(s)]),[s]);
  const hiredPlayers=players.filter((p:any)=>!p.militia&&!p.missionAlly),missionAllies=players.filter((p:any)=>p.missionAlly),localMilitia=players.filter((p:any)=>p.militia);
  const reachable=useMemo(()=>u?getReachable(s,u):[],[s,u]);
  const costs=u?actionCosts(s,u):null;const weapon=u?weaponFor(u):null;const firearm=u&&hasFirearm(u);const [cannonId,setCannonId]=useState('');const [shotType,setShotType]=useState('solid');const gun=s.artillery?.find((g:any)=>g.id===cannonId);const gunCosts=u&&gun?artilleryCosts(s,u,gun):null;
  const order=(a:any)=>{if(!u||busy)return;const next=actBattle(s,{unitId:selected,aim,...a});if(!next.lastError){const target=s.units.find((t:any)=>t.id===a.targetId)||a;if(Number.isFinite(target.x)&&Number.isFinite(target.y))setDirections(d=>({...d,[selected]:(Math.round(Math.atan2((target.x-u.x)-(target.y-u.y),-((target.x-u.x)+(target.y-u.y)))/(Math.PI/4))+8)%8}));const pose=a.type==='fire'?'fire':['reload','reprime','repair'].includes(a.type)?'reload':['melee','charge'].includes(a.type)?'strike':'idle';setPoses(p=>({...p,[selected]:pose}));setTimeout(()=>setPoses(p=>({...p,[selected]:'idle'})),1000);}onChange(next);};
  function nextTurn(){if(busy||s.status!=='active')return;setBusy(true);setTimeout(()=>{onChange(endTurn(s));setBusy(false);},450);}
  useEffect(()=>{if(!u||!isAlive(u))setSelected(players.find(isAlive)?.id);},[s]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{
    const editing=Boolean((e.target as HTMLElement)?.closest('input,select,textarea,[contenteditable]:not([contenteditable="false"]),[role="textbox"]'));
    if(talking&&e.key==='Escape'&&!e.ctrlKey&&!e.metaKey&&!e.repeat){e.preventDefault();setTalking(null);return;}
    if(keyHelp&&e.key==='Escape'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();setKeyHelp(false);return;}
    const nativeControl=Boolean((e.target as HTMLElement)?.closest('button,a,summary,[role="button"]'));
    const shortcut=tacticalShortcut(e,{editing,nativeControl,dialog:talking!==null||Boolean(document.querySelector('[role="dialog"],dialog[open]'))});
    if(!shortcut)return;e.preventDefault();
    if(shortcut==='help'){setKeyHelp(v=>!v);return;}if(keyHelp)return;
    if(shortcut==='cancel'){setMode('move');return;}
    if(shortcut==='sight'){setShowSight(v=>!v);return;}
    if(shortcut==='zoom-in'||shortcut==='zoom-out'){setZoom(v=>Math.max(1,Math.min(3,v+(shortcut==='zoom-in'?.25:-.25))));return;}
    if(busy||s.status!=='active')return;
    if(shortcut==='next'){const ready=players.filter(isAlive);if(ready.length)setSelected(ready[(ready.findIndex((p:any)=>p.id===selected)+1)%ready.length].id);return;}
    if(shortcut.startsWith('select:')){const p=hiredPlayers[Number(shortcut.split(':')[1])];if(p&&isAlive(p))setSelected(p.id);return;}
    if(shortcut==='turn'){nextTurn();return;}if(shortcut==='map'){onMap?.();return;}
    if(!u||!isAlive(u))return;
    if(['move','fire','melee','loot','heal'].includes(shortcut)){if(shortcut!=='fire'||firearm)setMode(shortcut);return;}
    if(['run','walk','crouch','prone'].includes(shortcut)){order({type:'movement',movement:shortcut});return;}
    if(shortcut==='sneak'){order({type:'movement',movement:u.movementMode==='crouch'?'walk':'crouch'});return;}
    if(shortcut.startsWith('stance-')){const levels=['walk','crouch','prone'],current=u.stance==='prone'?2:u.movementMode==='crouch'?1:0;order({type:'movement',movement:levels[Math.max(0,Math.min(2,current+(shortcut==='stance-up'?-1:1)))]});return;}
    if(shortcut==='reload'&&firearm)order({type:u.jammed?'reprime':'reload'});
    else if(shortcut==='weapon')order({type:'weapon',slot:u.activeSlot==='blade'?'primary':'blade'});
    else if(shortcut==='brace'&&bladeFor(u).id===1811)order({type:'brace'});
    else if(shortcut==='overwatch'&&firearm)order({type:'overwatch'});
    else if(shortcut==='mount'&&u.horse)order({type:'mount'});
    else if(shortcut==='aim-up'||shortcut==='aim-down')setAim(v=>Math.max(0,Math.min(4,v+(shortcut==='aim-up'?1:-1))));
  };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});

  const hw=26,hh=14,origin=s.height*hw+28,project=(x:number,y:number)=>({x:origin+(x-y)*hw,y:65+(x+y)*hh});
  const vw=(s.width+s.height)*hw+60,vh=(s.width+s.height)*hh+155;
  const followed=cameraFollowsSelection&&u?project(motion.positions[u.id]?.x??u.x,motion.positions[u.id]?.y??u.y):{x:vw/2,y:vh/2};
  const cameraX=Math.max(0,Math.min(vw-vw/zoom,followed.x+cameraOffset.x-vw/zoom/2)),cameraY=Math.max(0,Math.min(vh-vh/zoom,followed.y+cameraOffset.y-vh/zoom/2));
  const panCamera=(dx:number,dy:number)=>setCameraOffset({x:Math.max(0,Math.min(vw-vw/zoom,cameraX+dx))+vw/zoom/2-followed.x,y:Math.max(0,Math.min(vh-vh/zoom,cameraY+dy))+vh/zoom/2-followed.y});
  useEffect(()=>{if(cameraSelection.current!==selected){cameraSelection.current=selected;setCameraFollowsSelection(true);setCameraOffset({x:0,y:0});}},[selected]);
  const diamond=(x:number,y:number)=>`${x},${y-hh} ${x+hw},${y} ${x},${y+hh} ${x-hw},${y}`;
  const tileClick=(t:any)=>{const occupant=renderedUnits.find((p:any)=>p.x===t.x&&p.y===t.y&&!p.fled);if(mode==='torch'){order({type:'throwTorch',x:t.x,y:t.y});return;}if(mode==='loot'){if(occupant)order({type:'loot',targetId:occupant.id});else{const dropIndex=(s.droppedWeapons||[]).findIndex((d:any)=>d.x===t.x&&d.y===t.y&&!d.taken);const ground=(s.groundItems||[]).find((d:any)=>d.x===t.x&&d.y===t.y&&d.count>0);order({type:'loot',...(dropIndex>=0?{dropIndex}:{groundId:ground?.id})});}return;}if(t.type==='door'&&mode==='move'){order({type:'door',doorId:t.doorId});return;}if(mode==='bolas'&&occupant){order({type:'boleadoras',targetId:occupant.id});return;}if(mode.startsWith('artillery')){order({type:mode,artilleryId:cannonId,x:t.x,y:t.y,targetId:occupant?.id,mode:shotType});return;}if(occupant){if(occupant.side==='player'){if(mode==='heal')order({type:'heal',targetId:occupant.id});else setSelected(occupant.id);}else if(mode==='artillery')order({type:'artillery',artilleryId:cannonId,targetId:occupant.id,mode:shotType});else order({type:mode==='charge'?'charge':mode==='melee'||!firearm?'melee':'fire',targetId:occupant.id});}else if(mode==='move')order({type:'move',x:t.x,y:t.y});else if(mode==='artillery')order({type:'artillery',artilleryId:cannonId,x:t.x,y:t.y,mode:shotType});};
  return <section className={`battle-layout ${s.night?'night-field':''}`}>
    <header className="battle-header"><div><p className="eyebrow">OPERACIÓN TERRESTRE · {s.night?'NOCHE':'DÍA'} · {s.weather.rain?'LLUVIA':'CIELO DESPEJADO'}</p><h1>{s.sectorName}</h1></div><div className="battle-status"><span className="turn-dot"/>{busy?'Procesando órdenes':s.mode==='exploration'?'Exploración libre':`Turno ${s.turn} · Ejército patriota`}<span className="enemy-count">{enemies.length} avistados</span><button className="mobile-details line-button" aria-expanded={details} aria-controls="tactical-inspector" onClick={()=>setDetails(!details)}>{details?'Cerrar equipo':'Equipo y órdenes'}</button></div></header>
    {mission&&<details className="hud-mission" aria-label="Objetivos de la misión"><summary>{mission.name} · Objetivos</summary><ul>{(mission.objectives||[]).map((objective:any,index:number)=><li key={index}>{typeof objective==='string'?objective:`${objective.done?'✓ ':''}${objective.text||objective.label||objective.name}`}</li>)}</ul>{s.sceneId==='yatasto'&&onMissionFinish&&<button className="line-button" disabled={busy||!(mission.objectives||[]).every((o:any)=>o.done)} onClick={onMissionFinish}>Concluir el encuentro</button>}</details>}
    <div className="tactical-help-toggle"><button className="line-button" aria-expanded={keyHelp} aria-controls="tactical-key-reference" onClick={()=>setKeyHelp(v=>!v)}>Atajos de teclado · H</button>{keyHelp&&<section id="tactical-key-reference" aria-label="Atajos de teclado" style={{padding:'1rem',background:'#20332c',color:'#f1e5c7'}}><h2>Órdenes de teclado</h2><p>Los cursores requieren seleccionar una casilla o un objetivo. Las órdenes respetan los puntos de acción y el equipo disponible.</p><dl style={{display:'grid',gridTemplateColumns:'minmax(120px, 1fr) 3fr',gap:'.35rem 1rem'}}>{TACTICAL_KEYS.map(([keys,label])=><div key={keys} style={{display:'contents'}}><dt><kbd>{keys}</kbd></dt><dd style={{margin:0}}>{label}</dd></div>)}</dl><p>Mientras escribís o conversás, los atajos se suspenden. Ctrl y ⌘ quedan reservados al navegador.</p><button className="line-button" onClick={()=>setKeyHelp(false)}>Cerrar ayuda · Esc</button></section>}</div>
    <div className="battle-middle"><div className="field-wrap"><div className="map-caption"><span>↑ NORTE</span><span>{mode==='move'?'Seleccioná una casilla para avanzar':mode==='heal'?'Seleccioná un compañero herido':mode==='artilleryMove'?'Seleccioná una casilla contigua al cañón':mode==='artilleryPivot'?'Seleccioná hacia dónde apuntar':'Seleccioná un enemigo'}{hover&&` · ${String.fromCharCode(65+hover.y)}${hover.x+1}`}</span><span className="map-zoom"><button aria-label="Desplazar cámara a la izquierda" onClick={()=>panCamera(-90,0)}>←</button><button aria-label="Desplazar cámara hacia arriba" onClick={()=>panCamera(0,-65)}>↑</button><button aria-label="Centrar cámara en el combatiente seleccionado" onClick={()=>{setCameraFollowsSelection(true);setCameraOffset({x:0,y:0});}}>◎</button><button aria-label="Desplazar cámara hacia abajo" onClick={()=>panCamera(0,65)}>↓</button><button aria-label="Desplazar cámara a la derecha" onClick={()=>panCamera(90,0)}>→</button><button aria-label="Alejar campo" disabled={zoom<=1} onClick={()=>setZoom(Math.max(1,zoom-.25))}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="Acercar campo" disabled={zoom>=3} onClick={()=>setZoom(Math.min(3,zoom+.25))}>+</button></span></div>
      <svg className="tactical-field" viewBox={`${cameraX} ${cameraY} ${vw/zoom} ${vh/zoom}`} role="group" aria-label="Campo táctico. Seleccioná un soldado y una casilla.">
        <TacticalScene state={s} selected={selected} unit={u} players={players} units={renderedUnits} positions={motion.positions} poses={poses} directions={directions} hover={hover} mode={mode} aim={aim} reachable={reachable} showSight={showSight} sight={sight} revealed={revealedBuildingRooms} project={project} onTile={tileClick} onHover={setHover} onTalk={setTalking} onCannon={(id)=>{setCannonId(id);setMode('artillery')}} cannonId={cannonId}/>
      </svg>
      {s.lastError&&<p className="battle-error" role="alert">{s.lastError}</p>}{s.status!=='active'&&<div className="battle-result"><p className="eyebrow">PARTE DE GUERRA</p><h2>{s.status==='victory'?'¡Victoria patriota!':'La escuadra ha caído'}</h2><p>{s.status==='victory'?'El enemigo abandona el campo. La patria avanza.':'Reorganizá las tropas y prepará una nueva ofensiva.'}</p><>{s.status==='victory'&&<button className="line-button" onClick={()=>onChange(actBattle(s,{type:'explore'}))}>Explorar el sector y recoger equipo</button>}<button className="gold-button" onClick={onFinish}>Volver a la campaña <ChevronRight size={16}/></button></></div>}
    </div><aside id="tactical-inspector" aria-label="Equipo y órdenes del combatiente" className={`battle-inspector ${details?'inspector-open':''}`}><button className="inspector-close line-button" onClick={()=>setDetails(false)}>Cerrar equipo ×</button><p className="eyebrow">OFICIAL AL MANDO</p>{u&&<><div className="soldier-heading"><div className="portrait">{portraitFor(u.portraitId??u.id)?<img src={portraitFor(u.portraitId??u.id)!} alt={u.name}/>:<span>{short(u).slice(0,2).toUpperCase()}</span>}</div><div><h2>{short(u)}</h2><span>{u.mounted?'Granadero a caballo':'Ejército patriota'}</span></div></div><div className="stat-pair"><span>Salud</span><b>{Math.ceil(u.hp)} / {u.maxHp}</b></div><div className="meter"><i style={{width:`${100*u.hp/u.maxHp}%`}}/></div><div className="stat-pair"><span>{s.mode==='exploration'?'Movimiento sin coste de PA':'Puntos de acción'}</span><b>{u.ap} / {u.maxAP||100}</b></div><div className="meter ap"><i style={{width:`${100*u.ap/(u.maxAP||100)}%`}}/></div><div className="stat-pair"><span>Energía</span><b>{Math.round(u.energy??100)} / 100</b></div><div className="meter energy"><i style={{width:`${u.energy??100}%`}}/></div><div className="stat-pair"><span>Carga / capacidad</span><b>{carriedWeight(u).toFixed(1)} / {carryCapacity(u).toFixed(1)} kg</b></div><div className="weapon-detail"><span className="eyebrow">ARMAMENTO</span><h3>{weapon.name}</h3>{weapon.id>=1800&&weapon.id<=1813&&<img className="weapon-icon" src={`/art/weapon-${weapon.id}.png`} alt={weapon.name}/>}<p>{!firearm?'Arma blanca':u.jammed?'Cazoleta sin cebar':u.loaded?`${u.loaded} carga preparada`:'Arma descargada'}{firearm&&` · ${u.ammo} cartuchos`}</p><div className="stat-pair"><span>Moral</span><b>{Math.round(u.morale)}%</b></div><div className="stat-pair"><span>Estado del mecanismo</span><b>{u.condition}%</b></div>{firearm&&<div className="stat-pair"><span>Riesgo de chispa fallida</span><b>{Math.round(ignitionRisk(s,u))}%</b></div>}{u.knockedDown&&<p className="danger-text">Derribado: ponerse de pie cuesta 12 PA.</p>}{u.braced&&<p>Bayoneta calada: espera una carga.</p>}{u.bleeding>0&&<p className="danger-text">Hemorragia: −{u.bleeding} salud / turno</p>}</div>{firearm&&<div className="aim-control"><span>Puntería adicional</span><div>{[0,1,2,3,4].map(n=><button key={n} className={aim===n?'active':''} onClick={()=>setAim(n)} aria-label={`${n} niveles de puntería`}>{n}</button>)}</div><small>Disparo: {costs!.fire+aim*costs!.aim} PA</small></div>}</>}
    {u&&<div className="movement-orders"><p className="eyebrow">DESPLAZAMIENTO Y VISIBILIDAD</p><select aria-label="Forma de desplazarse" value={u.movementMode||'walk'} onChange={e=>order({type:'movement',movement:e.target.value})}>{[['walk','Caminar'],['run','Correr'],['crouch','Agachado y sigiloso'],['prone','Cuerpo a tierra']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button className="line-button" onClick={()=>setShowSight(!showSight)}>{showSight?'Ocultar':'Mostrar'} campo de visión</button><button className="line-button" onClick={()=>setMode('loot')}>Recoger equipo del suelo o un cuerpo</button><button className="line-button" disabled={(u.torches??2)<1} onClick={()=>setMode('torch')}>Arrojar antorcha · {u.torches??2} disponibles</button><button className="line-button" disabled={(u.boleadoras??0)<1} onClick={()=>setMode('bolas')}>Lanzar boleadoras · {u.boleadoras??0}</button>{u.entangled&&<button className="line-button" onClick={()=>order({type:'free'})}>Liberarse de las boleadoras</button>}</div>}
    {u&&<div className="field-supplies"><p className="eyebrow">EQUIPO DE CAMPAÑA</p>{bladeFor(u).id===1811&&<button className="line-button" disabled={busy||u.ap<16||s.status!=='active'} onClick={()=>order({type:'brace'})}>Calar bayoneta · reservar 16 PA</button>}<p>{u.priming??50} cargas de cebado · {u.flints??4} sílex · {u.rations??2} raciones</p><button className="line-button" disabled={busy||!firearm||(u.flints??4)<1||s.status!=='active'} onClick={()=>order({type:'repair'})}>Cambiar sílex · {costs!.repair} PA</button><button className="line-button" disabled={busy||(u.rations??2)<1||s.status!=='active'} onClick={()=>order({type:'ration'})}>Tasajo y vendas · 10 PA</button><small>La ración recupera fuerzas y detiene la hemorragia.</small></div>}
    {(s.artillery||[]).length>0&&<div className="artillery-control"><p className="eyebrow">ARTILLERÍA DE CAMPAÑA</p><select aria-label="Seleccionar pieza de artillería" value={cannonId} onChange={e=>{setCannonId(e.target.value);setMode('artillery')}}><option value="">Elegir cañón</option>{s.artillery.map((a:any)=><option key={a.id} value={a.id}>{(ARTILLERY as any)[a.type].name} · {a.loaded?'cargado':'descargado'}</option>)}</select><select aria-label="Munición de artillería" value={shotType} onChange={e=>setShotType(e.target.value)}><option value="solid">Bala rasa</option><option value="canister">Metralla</option></select><div className="artillery-orders"><button className="line-button" disabled={!cannonId} onClick={()=>setMode('artillery')}>Disparar · {gunCosts?.fire??'—'} PA</button><button className="line-button" disabled={!cannonId} onClick={()=>setMode('artilleryMove')}>Desplazar · {gunCosts?.move??'—'} PA</button><button className="line-button" disabled={!cannonId} onClick={()=>setMode('artilleryPivot')}>Girar · {gunCosts?.pivot??'—'} PA</button></div><button className="line-button" disabled={!cannonId} onClick={()=>order({type:'artilleryReload',artilleryId:cannonId})}>Recargar pieza · {gunCosts?.reload??'—'} PA</button><small>La pieza debe apuntar al objetivo. Cada artillero paga el coste de la orden.</small><small>Dotación: 2 artilleros para 4 lb, 3 para 8 lb, 1 para pedrero. La metralla también alcanza aliados.</small></div>}{u&&<TrainingProgress unit={u}/>}{u&&<RecoveredInventory unit={u} disabled={busy||s.status!=='active'||!isAlive(u)||(s.mode!=='exploration'&&u.ap<6)} onEquip={(inventoryKey,slot)=>order({type:'equipLoot',inventoryKey,slot})}/>}<div className="field-log"><p className="eyebrow">DIARIO DE COMBATE</p><div aria-live="polite">{s.log.slice(-5).reverse().map((l:string,i:number)=><p className={i===0?'latest':''} key={s.log.length-i}>{l}</p>)}</div></div><button className="retreat-button" onClick={onRetreat}>{s.mode==='exploration'?'Volver a la carta de operaciones':'Ordenar retirada'}</button></aside></div>
    {talking&&<section className="notice" aria-label="Conversación"><div><h3>{talking.name} · {String.fromCharCode(65+talking.y)}{talking.x+1}</h3>{u&&Math.abs(u.x-talking.x)+Math.abs(u.y-talking.y)>1&&<button className="line-button" disabled={busy} onClick={()=>{const target=reachable.filter((r:any)=>Math.abs(r.x-talking.x)+Math.abs(r.y-talking.y)===1).sort((a:any,b:any)=>(a.cost??0)-(b.cost??0))[0];if(target)order({type:'move',x:target.x,y:target.y});}}>Acercarse para conversar</button>}<p>{conversation?.npcId===talking.id?conversation.text:'Acercá al combatiente seleccionado a una casilla contigua para conversar.'}</p>{[...(talking.mission?[['mission','Conversar sobre la misión']]:[['friendly','Saludar'],['direct','Preguntar por sus condiciones']]),...(quests?.[talking.id]&&quests[talking.id].status!=='completed'?[['quest',quests[talking.id].status==='offered'?'Entregar pertrechos':'Consultar encargo']]:[]),...(talking.operativeId!==undefined?[['recruit','Proponer incorporación']]:[])].map(([approach,label])=><button className="line-button" key={approach} disabled={busy||!onTalk||!u||Math.abs(u.x-talking.x)+Math.abs(u.y-talking.y)>1} onClick={()=>onTalk?.(talking.id,approach,selected)}>{label}</button>)}<button className="line-button" onClick={()=>setTalking(null)}>Cerrar conversación</button></div></section>}

    <div className="command-bar"><div className="commands">{[{id:'move',label:'Mover',Icon:Footprints},{id:'fire',label:'Disparar',Icon:Crosshair},{id:'melee',label:'Atacar',Icon:Swords},{id:'charge',label:'Cargar',Icon:Flag},{id:'heal',label:'Curar',Icon:Heart}].map(({id,label,Icon})=><button key={id} className={mode===id?'selected':''} onClick={()=>setMode(id)} disabled={busy||s.status!=='active'||id==='fire'&&!firearm}><Icon size={19}/><span>{label}</span></button>)}<button onClick={()=>order({type:u?.jammed?'reprime':'reload'})} disabled={busy||!u||!firearm||s.status!=='active'}><RotateCcw size={19}/><span>{u?.jammed?`Cebar · ${costs?.reprime}`:`Recargar · ${u?reloadCost(u,s):0}`}</span></button><button onClick={()=>order({type:'weapon',slot:u?.activeSlot==='blade'?'primary':'blade'})} disabled={busy||!u||s.status!=='active'}><Swords size={19}/><span>Cambiar arma · 4</span></button><button onClick={()=>order({type:'stance',stance:u?.stance==='prone'?'standing':'prone'})} disabled={busy||!u||s.status!=='active'}><Shield size={19}/><span>{u?.stance==='prone'?'De pie':'Cuerpo a tierra'}</span></button><button onClick={()=>order({type:'overwatch'})} disabled={busy||!firearm||s.status!=='active'}><Eye size={19}/><span>Cubrir</span></button>{u?.horse&&<button disabled={busy||s.status!=='active'} onClick={()=>order({type:'mount'})}><CircleArrowUp size={19}/><span>{u.mounted?'Desmontar':'Montar'} · {costs?.mount}</span></button>}</div><button className="end-turn" onClick={nextTurn} disabled={busy||s.status!=='active'}>{busy?'Procesando…':s.mode==='exploration'?'Descansar':'Fin del turno'}<ChevronRight size={20}/></button></div>
    {missionAllies.length>0&&<details className="local-garrison" aria-label="Aliados de la misión"><summary>Oficiales aliados · {missionAllies.length} temporales</summary><div className="squad-strip">{missionAllies.map((p:any)=><button key={p.id} className={`squad-card ${p.id===selected?'active':''} ${!isAlive(p)?'fallen':''}`} onClick={()=>setSelected(p.id)} disabled={!isAlive(p)} aria-label={`Seleccionar aliado ${p.name}`}><div><strong>{p.name}</strong><span>{isAlive(p)?`${Math.ceil(p.hp)} SALUD · ${p.ap} PA`:'Fuera de combate'}</span></div></button>)}</div><small>Estos aliados participan en esta misión; no ocupan un contrato ni una plaza permanente en tu escuadra.</small></details>}
    {localMilitia.length>0&&<details className="local-garrison"><summary>Guarnición local · {localMilitia.length} milicianos</summary><div className="squad-strip">{localMilitia.map((p:any,index:number)=><button aria-label={`Seleccionar miliciano ${index+1}: ${p.name}`} key={p.id} className={`squad-card ${p.id===selected?'active':''} ${!isAlive(p)?'fallen':''}`} onClick={()=>setSelected(p.id)} disabled={!isAlive(p)}><div><strong>{index+1}. {p.name}</strong><span>{p.unconscious?'Inconsciente':!isAlive(p)?'Fuera de combate':`${Math.ceil(p.hp)} SALUD · ${p.ap} PA`}</span></div></button>)}</div></details>}
    <div className="squad-strip tactical-roster" aria-label="Escuadra táctica">{hiredPlayers.map((p:any,i:number)=>{const portrait=p.portrait||portraitFor(p.portraitId??p.id);return <button key={p.id} className={`squad-card portrait-card ${p.id===selected?'active':''} ${!isAlive(p)?'fallen':''}`} onClick={()=>setSelected(p.id)} onDoubleClick={()=>{setSelected(p.id);setDetails(true)}} disabled={!isAlive(p)} aria-label={`${i+1}. ${p.name}. Salud ${Math.ceil(p.hp)}, ${p.ap} puntos de acción, energía ${Math.round(p.energy??100)}`}><span className="portrait-name"><b>{i+1}</b> {short(p)}</span><div className="portrait-vitals">{portrait?<img src={portrait} alt=""/>:<span className="portrait-fallback">{short(p).slice(0,2)}</span>}<div className="hud-vitals"><span title="Salud"><i className="health" style={{height:`${Math.max(0,Math.min(100,p.hp/p.maxHp*100))}%`}}/></span><span title="Puntos de acción"><i className="action" style={{height:`${Math.max(0,Math.min(100,p.ap/(p.maxAP||100)*100))}%`}}/></span><span title="Energía"><i className="energy" style={{height:`${Math.max(0,Math.min(100,p.energy??100))}%`}}/></span></div></div><span className="portrait-numbers">{Math.ceil(p.hp)} SAL · {p.ap} PA · {Math.round(p.energy??100)} EN</span></button>})}{Array.from({length:Math.max(0,6-hiredPlayers.length)},(_,i)=><div className="empty-portrait-slot" key={`empty-${i}`} aria-hidden="true"><span>—</span></div>)}<div className="hud-selection"><strong>{u?short(u):'Sin selección'}</strong><span>{mode==='move'?'Desplazamiento':mode==='fire'?'Disparo':mode==='heal'?'Curación':mode==='loot'?'Recoger equipo':'Orden táctica'}</span><button className="line-button" disabled={!u} onClick={()=>setDetails(v=>!v)}>Equipo / órdenes</button></div></div>

  </section>;
}
