'use client';
import { useEffect, useMemo, useState } from 'react';
import { Crosshair, Footprints, Swords, RotateCcw, Heart, ChevronRight, Flag, Shield, Target, Eye, CircleArrowUp } from 'lucide-react';
import { actBattle, endTurn, getReachable, shotChance, weaponFor, reloadCost, hasFirearm, bladeFor } from '../../game/tactical.js';

type Props = {battle:any; onChange:(s:any)=>void; onFinish:()=>void; onRetreat:()=>void};
const isAlive=(u:any)=>u.hp>0&&!u.routed;
const short=(u:any)=>u.nickname||u.name.split(' ').slice(-1)[0];
export default function Battlefield({battle:s,onChange,onFinish,onRetreat}:Props){
  const [selected,setSelected]=useState(s.units.find((u:any)=>u.side==='player')?.id);
  const [mode,setMode]=useState('move');const [aim,setAim]=useState(0);const [hover,setHover]=useState<any>(null);const [busy,setBusy]=useState(false);
  const u=s.units.find((u:any)=>u.id===selected);const players=s.units.filter((u:any)=>u.side==='player');const enemies=s.units.filter((u:any)=>u.side==='enemy'&&isAlive(u));
  const reachable=useMemo(()=>u?getReachable(s,u):[],[s,u]);
  const weapon=u?weaponFor(u):null;const firearm=u&&hasFirearm(u);const [cannonId,setCannonId]=useState('');const [shotType,setShotType]=useState('solid');
  const order=(a:any)=>{if(!u||busy)return;onChange(actBattle(s,{unitId:selected,aim,...a}));};
  function nextTurn(){if(busy||s.status!=='active')return;setBusy(true);setTimeout(()=>{onChange(endTurn(s));setBusy(false);},450);}
  useEffect(()=>{if(!u||!isAlive(u))setSelected(players.find(isAlive)?.id);},[s]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('button,input,select,[role="dialog"]'))return;if(e.code==='Space'){e.preventDefault();nextTurn();}if(e.key.toLowerCase()==='r')order({type:u?.jammed?'reprime':'reload'});if(e.key.toLowerCase()==='m')setMode('move');if(e.key.toLowerCase()==='f')setMode('fire');if(/^[1-6]$/.test(e.key)){const p=players[Number(e.key)-1];if(p&&isAlive(p))setSelected(p.id);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  const hw=26,hh=14,origin=s.height*hw+28,project=(x:number,y:number)=>({x:origin+(x-y)*hw,y:65+(x+y)*hh});
  const vw=(s.width+s.height)*hw+60,vh=(s.width+s.height)*hh+155;
  const diamond=(x:number,y:number)=>`${x},${y-hh} ${x+hw},${y} ${x},${y+hh} ${x-hw},${y}`;
  const tileClick=(t:any)=>{const occupant=s.units.find((p:any)=>p.x===t.x&&p.y===t.y&&isAlive(p));if(occupant){if(occupant.side==='player'){if(mode==='heal')order({type:'heal',targetId:occupant.id});else setSelected(occupant.id);}else if(mode==='artillery')order({type:'artillery',artilleryId:cannonId,targetId:occupant.id,mode:shotType});else order({type:mode==='charge'?'charge':mode==='melee'||!firearm?'melee':'fire',targetId:occupant.id});}else if(mode==='move')order({type:'move',x:t.x,y:t.y});else if(mode==='artillery')order({type:'artillery',artilleryId:cannonId,x:t.x,y:t.y,mode:shotType});};
  return <section className="battle-layout">
    <header className="battle-header"><div><p className="eyebrow">OPERACIÓN TERRESTRE · {s.weather.rain?'LLUVIA':'CIELO DESPEJADO'}</p><h1>{s.sectorName}</h1></div><div className="battle-status"><span className="turn-dot"/>{busy?'Turno realista':`Turno ${s.turn} · Ejército patriota`}<span className="enemy-count">{enemies.length} realistas</span></div></header>
    <div className="battle-middle"><div className="field-wrap"><div className="map-caption"><span>↑ NORTE</span><span>{mode==='move'?'Seleccioná una casilla para avanzar':mode==='heal'?'Seleccioná un compañero herido':'Seleccioná un enemigo'}{hover&&` · ${String.fromCharCode(65+hover.y)}${hover.x+1}`}</span><span>100 PA / TURNO</span></div>
      <svg className="tactical-field" viewBox={`0 0 ${vw} ${vh}`} role="group" aria-label="Campo táctico. Seleccioná un soldado y una casilla.">
        <defs><filter id="groundshadow"><feDropShadow dx="0" dy="8" stdDeviation="8" floodOpacity=".35"/></filter><radialGradient id="smokefill"><stop offset="0" stopColor="#e5e1d3" stopOpacity=".72"/><stop offset="1" stopColor="#dfdfce" stopOpacity="0"/></radialGradient></defs>
        <g filter="url(#groundshadow)">{[...s.tiles].sort((a:any,b:any)=>(a.x+a.y)-(b.x+b.y)).map((t:any)=>{const p=project(t.x,t.y),can=reachable.some((r:any)=>r.x===t.x&&r.y===t.y),isHover=hover?.x===t.x&&hover?.y===t.y,occupant=s.units.find((v:any)=>v.x===t.x&&v.y===t.y&&isAlive(v));const shade=(t.x*17+t.y*11)%4;return <g key={`${t.x}-${t.y}`} onMouseEnter={()=>setHover(t)} onMouseLeave={()=>setHover(null)} onClick={()=>tileClick(t)} role="button" tabIndex={0} aria-label={`${String.fromCharCode(65+t.y)}${t.x+1}${occupant?`, ${occupant.name}`:t.blocked?', obstáculo':can?', accesible':''}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tileClick(t)}}}>
          <polygon points={diamond(p.x,p.y)} fill={t.type==='water'?'#476a70':t.type==='mud'?'#756442':t.type==='road'?'#ad9670':['#68724d','#727b51','#69714e','#7d8056'][shade]} stroke="#39463b" strokeWidth=".7"/>
          {can&&mode==='move'&&!t.blocked&&<polygon points={diamond(p.x,p.y)} fill="#91d6d3" opacity={isHover?.4:.10} stroke={isHover?'#d8efdd':'transparent'} strokeWidth="2"/>}
          {t.blocked&&t.type!=='water'&&<g><path d={`M${p.x-hw},${p.y}v-23l${hw},-${hh} ${hw},${hh}v23l-${hw},${hh}Z`} fill="#9c8764" stroke="#655a45"/><path d={`M${p.x-hw},${p.y-23}l${hw},${hh} ${hw},-${hh}M${p.x},${p.y-hh+23}v-23`} fill="none" stroke="#c4ac82"/></g>}
          {!t.blocked&&t.cover>0&&<polygon points={diamond(p.x,p.y-3)} fill="#3c5740" opacity=".7"/>}
          {isHover&&<polygon points={diamond(p.x,p.y)} fill="transparent" stroke="#eadcaa" strokeWidth="2"/>}
          {occupant&&<g><ellipse cx={p.x} cy={p.y} rx="17" ry="7" fill={occupant.side==='player'?'#8ed2d0':'#db7360'} opacity=".6"/>{occupant.id===selected&&<ellipse cx={p.x} cy={p.y} rx="22" ry="10" fill="none" stroke="#f5e4ad" strokeWidth="2"/>}<image href={occupant.mounted?'/art/mounted-granadero.png':occupant.side==='player'?'/art/granadero.png':'/art/royalist.png'} x={p.x-37} y={p.y-71} width="74" height="74" style={{pointerEvents:'none'}}/><rect x={p.x-18} y={p.y-74} width="36" height="3" fill="#152020"/><rect x={p.x-18} y={p.y-74} width={36*occupant.hp/occupant.maxHp} height="3" fill={occupant.side==='player'?'#9bceac':'#e18269'}/>{occupant.id===selected&&<text x={p.x} y={p.y+23} textAnchor="middle" fill="#f5e4ad" fontSize="12" fontWeight="bold">{short(occupant)}</text>}{isHover&&occupant.side==='enemy'&&u&&<text x={p.x} y={p.y-82} textAnchor="middle" fill="#ffedbd" fontWeight="bold" fontSize="14">{shotChance(s,u,occupant,aim)}%</text>}</g>}
        </g>})}</g>
        {(s.artillery||[]).map((a:any)=>{const p=project(a.x,a.y);return <g key={a.id} role="button" tabIndex={0} onClick={()=>{setCannonId(a.id);setMode('artillery')}} aria-label={`Seleccionar cañón ${a.id}`}><circle cx={p.x} cy={p.y} r="17" fill={a.id===cannonId?'#d8bf7e':'#647d68'} stroke="#e1d1a1"/><text x={p.x} y={p.y+5} fontSize="17" textAnchor="middle" fill="#162d24">✚</text></g>})}{s.smoke.map((v:any,i:number)=>{const p=project(v.x,v.y);return <ellipse key={i} cx={p.x} cy={p.y-26} rx={38*v.radius} ry={28*v.radius} fill="url(#smokefill)" pointerEvents="none"/>})}
      </svg>
      {s.status!=='active'&&<div className="battle-result"><p className="eyebrow">PARTE DE GUERRA</p><h2>{s.status==='victory'?'¡Victoria patriota!':'La escuadra ha caído'}</h2><p>{s.status==='victory'?'El enemigo abandona el campo. La patria avanza.':'Reorganizá las tropas y prepará una nueva ofensiva.'}</p><button className="gold-button" onClick={onFinish}>Volver a la campaña <ChevronRight size={16}/></button></div>}
    </div><aside className="battle-inspector"><p className="eyebrow">OFICIAL AL MANDO</p>{u&&<><div className="soldier-heading"><div className="portrait">{true?<img src={`/art/portrait-${u.id}.webp`} alt={u.name}/>:<span>{short(u).slice(0,2).toUpperCase()}</span>}</div><div><h2>{short(u)}</h2><span>{u.mounted?'Granadero a caballo':'Ejército patriota'}</span></div></div><div className="stat-pair"><span>Salud</span><b>{Math.ceil(u.hp)} / {u.maxHp}</b></div><div className="meter"><i style={{width:`${100*u.hp/u.maxHp}%`}}/></div><div className="stat-pair"><span>Puntos de acción</span><b>{u.ap} / {u.maxAP||100}</b></div><div className="meter ap"><i style={{width:`${100*u.ap/(u.maxAP||100)}%`}}/></div><div className="weapon-detail"><span className="eyebrow">ARMAMENTO</span><h3>{weapon.name}</h3><p>{!firearm?'Arma blanca':u.jammed?'Cazoleta sin cebar':u.loaded?`${u.loaded} carga preparada`:'Arma descargada'} · {u.ammo} cartuchos</p><div className="stat-pair"><span>Moral</span><b>{Math.round(u.morale)}%</b></div>{u.bleeding>0&&<p className="danger-text">Hemorragia: −{u.bleeding} salud / turno</p>}</div>{firearm&&<div className="aim-control"><span>Puntería adicional</span><div>{[0,1,2,3,4].map(n=><button key={n} className={aim===n?'active':''} onClick={()=>setAim(n)} aria-label={`${n} niveles de puntería`}>{n}</button>)}</div><small>Disparo: {weapon.fireAP+aim*weapon.aimAP} PA</small></div>}</>}
    {(s.artillery||[]).length>0&&<div className="artillery-control"><p className="eyebrow">ARTILLERÍA DE CAMPAÑA</p><select aria-label="Seleccionar pieza de artillería" value={cannonId} onChange={e=>{setCannonId(e.target.value);setMode('artillery')}}><option value="">Elegir cañón</option>{s.artillery.map((a:any)=><option key={a.id} value={a.id}>{a.id} · {a.loaded?'cargado':'descargado'}</option>)}</select><select aria-label="Munición de artillería" value={shotType} onChange={e=>setShotType(e.target.value)}><option value="solid">Bala rasa</option><option value="canister">Metralla</option></select><button className="line-button" disabled={!cannonId} onClick={()=>order({type:'artilleryReload',artilleryId:cannonId})}>Recargar pieza</button><small>Dos artilleros junto al cañón. La metralla también alcanza aliados.</small></div>}<div className="field-log"><p className="eyebrow">DIARIO DE COMBATE</p><div aria-live="polite">{s.log.slice(-5).reverse().map((l:string,i:number)=><p className={i===0?'latest':''} key={s.log.length-i}>{l}</p>)}</div></div><button className="retreat-button" onClick={onRetreat}>Ordenar retirada</button></aside></div>
    <div className="command-bar"><div className="commands">{[{id:'move',label:'Mover',Icon:Footprints},{id:'fire',label:'Disparar',Icon:Crosshair},{id:'melee',label:'Atacar',Icon:Swords},{id:'charge',label:'Cargar',Icon:Flag},{id:'heal',label:'Curar',Icon:Heart}].map(({id,label,Icon})=><button key={id} className={mode===id?'selected':''} onClick={()=>setMode(id)} disabled={busy||s.status!=='active'||id==='fire'&&!firearm}><Icon size={19}/><span>{label}</span></button>)}<button onClick={()=>order({type:u?.jammed?'reprime':'reload'})} disabled={busy||!u||!firearm||s.status!=='active'}><RotateCcw size={19}/><span>{u?.jammed?'Cebar · 15':`Recargar · ${u?reloadCost(u,s):0}`}</span></button><button onClick={()=>order({type:'weapon',slot:u?.activeSlot==='blade'?'primary':'blade'})} disabled={busy||!u||s.status!=='active'}><Swords size={19}/><span>Cambiar arma · 4</span></button><button onClick={()=>order({type:'stance',stance:u?.stance==='prone'?'standing':'prone'})} disabled={busy||!u||s.status!=='active'}><Shield size={19}/><span>{u?.stance==='prone'?'De pie':'Cuerpo a tierra'}</span></button><button onClick={()=>order({type:'overwatch'})} disabled={busy||!firearm||s.status!=='active'}><Eye size={19}/><span>Cubrir</span></button>{u?.horse&&<button onClick={()=>order({type:'mount'})}><CircleArrowUp size={19}/><span>{u.mounted?'Desmontar':'Montar'}</span></button>}</div><button className="end-turn" onClick={nextTurn} disabled={busy||s.status!=='active'}>{busy?'Realistas…':'Fin del turno'}<ChevronRight size={20}/></button></div>
    <div className="squad-strip">{players.map((p:any,i:number)=><button key={p.id} className={`squad-card ${p.id===selected?'active':''} ${!isAlive(p)?'fallen':''}`} onClick={()=>setSelected(p.id)} disabled={!isAlive(p)}><span className="unit-index">0{i+1}</span><div><strong>{short(p)}</strong><span>{!isAlive(p)?'Fuera de combate':`${Math.ceil(p.hp)} SALUD · ${p.ap} PA`}</span></div><div className="tiny-bars"><i style={{height:`${p.hp/p.maxHp*100}%`}}/><i style={{height:`${p.ap}%`}}/></div></button>)}<span className="keyboard-help">1–6 · Seleccionar<br/>M · Mover &nbsp; F · Disparar<br/>R · Recargar &nbsp; Espacio · Turno</span></div>
  </section>;
}
