'use client';
import StrategicMap from './StrategicMap';
import {incomeSources,incomeSummary} from '../../game/economy.js';
import {missionStatus} from '../../game/missions.js';
import MissionBriefing from './MissionBriefing';
import {useState} from 'react';
import {CAMPAIGN_SECTORS,deploymentCost,rosterFor,operativeLocation,isSupplied,militiaCourse,militiaAssignment} from '../../game/campaign.js';
import {cityForSector,getCityStatus} from '../../game/cities.js';
import {militiaEligibility} from '../../game/militia.js';
import {contractStatus} from '../../game/contracts.js';
import {portraitFor} from '../lib/portraits';
import CharacterDossier from './CharacterDossier';
import Squads from './Squads';
import './strategy.css';
const place=(id:string)=>CAMPAIGN_SECTORS.find(s=>s.id===id);
const cell=(d:any)=>({x:32+(Number(d.grid.slice(1))-1)*30,y:32+(d.grid.charCodeAt(0)-65)*30});
export default function Campaign({state:s,dispatch,onBattle,onOpenDesk}:{state:any;dispatch:(a:any)=>void;onBattle:()=>void;onOpenDesk:()=>void}){
 const [selected,setSelected]=useState(s.location),[dossier,setDossier]=useState<number|null>(null),[manage,setManage]=useState(false),[trainerId,setTrainerId]=useState(''),[hours,setHours]=useState(1);
 const roster=rosterFor(s),hired=s.recruited.map((id:number)=>roster.find(o=>o.id===id)).filter(Boolean),def=place(selected)!,sector=s.sectors[selected],city=getCityStatus(s,selected),eligibility=militiaEligibility(s,selected),training=s.militiaTraining?.find((t:any)=>t.sector===selected);
 const trainers=hired.filter((o:any)=>s.operativeState[o.id]?.alive&&operativeLocation(s,o.id)===selected&&o.leadership>=30&&!militiaAssignment(s,o.id)).sort((a:any,b:any)=>militiaCourse(a,0).hours-militiaCourse(b,0).hours);const trainer=trainers.find((o:any)=>String(o.id)===trainerId)??trainers[0];
 const rank=sector.militia[0]>=3?1:sector.militia[1]>=3?2:0;const course=trainer?militiaCourse(trainer,rank):null;
 return <section className="strategy-screen"><header className="strategy-top"><div><p className="eyebrow">CARTA DE OPERACIONES</p><h1>Provincias Unidas</h1></div><div className="strategy-time"><span>Día {Math.floor(s.hour/24)+1} · {String(s.hour%24).padStart(2,'0')}:00</span><select aria-label="Tiempo a avanzar" value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={1}>1 hora</option><option value={6}>6 horas</option><option value={24}>1 día</option></select><button className="line-button" disabled={Boolean(s.pendingBattle)||s.defeated} onClick={()=>dispatch({type:'wait',hours})}>Avanzar</button></div><button className="gold-button" onClick={onOpenDesk}>Escritorio →</button></header>
 {s.lastError&&<p className="notice error" role="alert">{s.lastError}</p>}{s.defeated&&<p className="notice error">La campaña terminó. Conservá tu partida o comenzá otra desde el menú.</p>}{s.completed&&<p className="notice">Las provincias están libres. Podés continuar administrando tus fuerzas.</p>}
 <div className="strategy-layout"><aside className="strategy-personnel"><div className="personnel-title"><h2>Granaderos</h2><span>{hired.length}</span></div>{!hired.length?<div className="empty-personnel"><p>Todavía no hay nadie en tus filas.</p><button className="line-button" onClick={onOpenDesk}>Crear o contratar en el escritorio</button></div>:<ul>{hired.map((o:any)=>{const record=s.operativeState[o.id],contract=contractStatus(s,o.id);return <li key={o.id}><button className="personnel-row" onClick={()=>{setDossier(o.id);setSelected(operativeLocation(s,o.id));}}>{portraitFor((o as any).portraitId??o.id)?<img src={portraitFor((o as any).portraitId??o.id)!} alt=""/>:<span className="personnel-initials">{o.nickname.slice(0,2)}</span>}<span><strong>{o.nickname}</strong><small>{place(operativeLocation(s,o.id))?.grid} · {record.alive?`${Math.round(record.hp)} salud`:'Caído'}</small><small>{militiaAssignment(s,o.id)?'Instruyendo milicias':contract?.remaining===null?'Servicio permanente':`${contract?.remaining??0} h de contrato`}</small></span></button></li>;})}</ul>}<label>Escuadra<select aria-label="Escuadra activa" value={s.activeSquadId} onChange={e=>dispatch({type:'selectSquad',id:e.target.value})}>{s.squads.map((q:any)=><option key={q.id} value={q.id}>{q.name} · {q.members.length}/6</option>)}</select></label><button className="dossier-link" onClick={()=>setManage(!manage)}>{manage?'Cerrar organización':'Organizar escuadras'}</button><p className="strategy-treasury">{s.resources.treasury.toLocaleString('es-AR')} pesos<br/><small>+{incomeSummary(s).daily} por día · cobro en {incomeSummary(s).hoursUntilPayment} h</small></p></aside>
 <StrategicMap state={s} selected={selected} onSelect={setSelected} dispatch={dispatch}/>
 <aside className="strategy-orders"><p className="eyebrow">SECTOR {def.grid}</p><h2>{def.name.split(' · ')[0]}</h2><p>{sector.owner==='patriot'?'Bajo control patriota':'Ocupación realista'}</p><p>{incomeSources(s).find(site=>site.id===selected)?.income} pesos por día · {incomeSources(s).find(site=>site.id===selected)?.status}</p>{city?<p className="city-summary">{city.name}<br/><strong>{city.sectors.length-city.uncontrolled.length}/{city.sectors.length} sectores · {city.loyalty}% lealtad</strong></p>:<p>Zona rural</p>}
 {s.pendingBattle?<button className="gold-button" onClick={onBattle}>Volver al sector táctico</button>:selected===s.location&&sector.owner==='patriot'?<button className="gold-button" disabled={!s.squad.length} onClick={()=>dispatch({type:'visitSector',sector:selected})}>Entrar al sector · {deploymentCost(s)} pesos</button>:<button className="gold-button" disabled={!s.squad.length} onClick={()=>dispatch({type:sector.owner==='patriot'?'travel':'attack',sector:selected,mode:'march'})}>{sector.owner==='patriot'?'Mover escuadra aquí':`Combatir · ${deploymentCost(s)} pesos`}</button>}
 {selected==='tucuman'&&s.phase>=2&&!missionStatus(s,'yatasto').completed&&<MissionBriefing mission={missionStatus(s,'yatasto')} canEnter={s.location==='tucuman'&&sector.owner==='patriot'&&s.squad.length>0} blocked={Boolean(s.pendingBattle)} onEnter={()=>dispatch({type:'visitMission',mission:'yatasto'})}/>}
 <button className="line-button" disabled={sector.owner!=='patriot'||sector.fort>=3||s.resources.treasury<150||Boolean(s.pendingBattle)} onClick={()=>dispatch({type:'fortify',sector:selected})}>Fortificar · 150 pesos ({sector.fort}/3)</button><section className="simple-militia"><h3>Milicias</h3><p>{sector.militia.reduce((a:number,b:number)=>a+b,0)} defensores</p>{training?<><p>{training.count} en instrucción · {training.remaining} h</p>{(!eligibility.eligible||!isSupplied(s,selected))&&<small>Instrucción detenida: {!eligibility.eligible?eligibility.reason:'falta abastecimiento.'}</small>}<button className="line-button" onClick={()=>dispatch({type:'cancelMilitia',sector:selected})}>Suspender instrucción</button></>:!eligibility.eligible?<p className="muted">{eligibility.reason}</p>:<><label>Instructor<select aria-label="Instructor de milicias" value={trainer?.id??''} onChange={e=>setTrainerId(e.target.value)}>{!trainers.length&&<option value="">Necesitás un granadero presente</option>}{trainers.map((o:any)=><option key={o.id} value={o.id}>{o.nickname}</option>)}</select></label><button className="line-button" disabled={!trainer||!isSupplied(s,selected)||Boolean(s.pendingBattle)} onClick={()=>dispatch({type:'militia',sector:selected,rank,trainerId:trainer?.id})}>Entrenar milicias{course?` · ${course.cost.treasury} pesos`:''}</button>{course&&<small>{course.hours} horas · {rank===0?'Tres nuevos defensores':'Promover tres defensores'}</small>}</>}</section></aside></div>
 {manage&&<div className="strategy-management"><Squads state={s} dispatch={dispatch}/></div>}<CharacterDossier operative={hired.find((o:any)=>o.id===dossier)} record={s.operativeState[dossier??-1]} onClose={()=>setDossier(null)}/></section>;
}
