'use client';
import { useState } from 'react';
import Recruitment from './Recruitment';
import Logistics from './Logistics';
import Armory from './Armory';
import Squads from './Squads';
import { Map, Users, Hammer, ScrollText, Flag, ChevronRight, Coins, Shield, Anchor, ArrowRight, LockKeyhole, Check } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { CAMPAIGN_SECTORS, OPERATIVES, PHASES, FACTIONS, RECIPES, RESOURCE_NAMES, recruitmentStatus, isSupplied, royalistIntel, mentorDispatch } from '../../game/campaign.js';
const labels:any={treasury:'Plata',horses:'Caballos',powder:'Pólvora',muskets:'Mosquetes',cartridges:'Cartuchos',infantry:'Infantes'};
const briefName=(s:any)=>(s.id==='retiro'?'Retiro':s.name.split(' · ')[0]).replace('San Miguel de Tucumán','Tucumán').replace('San Salvador de Jujuy','Jujuy').replace('Córdoba y talleres de Caroya','Córdoba').replace('Santa Fe de la Vera Cruz','Santa Fe').replace('San Nicolás de los Arroyos','San Nicolás').replace('Ensenada de Barragán','Ensenada').replace('Quebrada de Humahuaca','Humahuaca');
export default function Campaign({state:s,dispatch,onBattle}:{state:any;dispatch:(a:any)=>void;onBattle:()=>void}){
  const [selected,setSelected]=useState('san_nicolas');const [tab,setTab]=useState('map');const [transport,setTransport]=useState('march');const def=CAMPAIGN_SECTORS.find(x=>x.id===selected)!;const sector=s.sectors[selected];
  const intelligence=royalistIntel(s);const mentor=mentorDispatch(s);
  const current=CAMPAIGN_SECTORS.find(x=>x.id===s.location);const phase=PHASES[s.phase];
  return <div className="campaign"><header className="campaign-heading"><div><p className="eyebrow">CUARTEL GENERAL · {current?.name}</p><h1>La campaña de independencia</h1></div><div className="campaign-clock"><span>DÍA {1+Math.floor(s.hour/24)}</span><b>{String(s.hour%24).padStart(2,'0')}:00</b><button className="line-button" disabled={s.completed||s.defeated} onClick={()=>dispatch({type:'wait',hours:24})}>Avanzar un día <ChevronRight size={14}/></button></div></header>
    {(s.completed||s.defeated)&&<section className="campaign-outcome" role="status"><p className="eyebrow">PARTE FINAL DE CAMPAÑA</p><h2>{s.completed?'¡Las provincias están libres!':'La campaña ha terminado'}</h2><p>{s.completed?'Las comunicaciones están aseguradas y el Ejército de los Andes se encuentra preparado. Tu campaña queda conservada en el archivo.':'La pérdida de la capital o del último destacamento impide continuar. Podés conservar este archivo y comenzar otra campaña desde el menú.'}</p></section>}
    <div className="resources">{Object.keys(labels).map(k=><div key={k}><span>{labels[k]}</span><b>{(s.resources[k]||0).toLocaleString('es-AR')}</b></div>)}<div className="control-count"><span>Sectores liberados</span><b>{Object.values(s.sectors).filter((x:any)=>x.owner==='patriot').length} <small>/ 13</small></b></div></div>
    <div className="phase-banner"><div className="phase-symbol">{String(s.phase+1).padStart(2,'0')}</div><div><p className="eyebrow">{s.completed?'INDEPENDENCIA ASEGURADA':'OBJETIVO DE CAMPAÑA'}</p><h2>{phase.name}</h2><p>{phase.objective}</p></div>{!s.flags.academy?<button className="gold-button" onClick={()=>dispatch({type:'academy'})}>Fundar el regimiento <ArrowRight size={16}/></button>:s.phase===1&&s.sectors.san_nicolas.owner==='patriot'?<button className="gold-button" onClick={()=>dispatch({type:'attack',sector:'san_lorenzo'})}>Marchar a San Lorenzo <ArrowRight size={16}/></button>:<span className="phase-checks">{PHASES.map((p,i)=><i key={p.id} className={i<=s.phase?'done':''}/>)}</span>}</div>
    {s.lastError&&<div className="notice error" role="alert">{s.lastError}</div>}{s.blockade&&<div className="notice">La flotilla realista bloquea el litoral. Liberá un sector costero para reabrir las aduanas.</div>}
    {s.pendingBattle&&<button className="gold-button" onClick={onBattle}>Continuar la batalla pendiente</button>}
    <Tabs value={tab} onValueChange={setTab} className="campaign-tabs"><TabsList className="campaign-tab-list">{[{id:'map',name:'Carta de operaciones',Icon:Map},{id:'roster',name:'Logia Lautaro',Icon:Users},{id:'workshop',name:'Maestranza',Icon:Hammer},{id:'diplomacy',name:'Cabildo',Icon:Flag},{id:'journal',name:'Cuaderno',Icon:ScrollText}].map(({id,name,Icon})=><TabsTrigger key={id} value={id} className="campaign-tab"><Icon size={16}/>{name}</TabsTrigger>)}</TabsList>
    <TabsContent value="map"><Squads state={s} dispatch={dispatch}/><div className="strategic-layout"><aside className="theater-list"><p className="eyebrow">TEATROS DE OPERACIONES</p>{[{id:'north',name:'Frente del Norte'},{id:'interior',name:'Camino Real'},{id:'cuyo',name:'Cuyo y los Andes'},{id:'coast',name:'Buenos Aires y Litoral'}].map(t=><div className="theater" key={t.id}><h3>{t.name}</h3>{CAMPAIGN_SECTORS.filter(x=>x.theater===t.id).map(x=><button key={x.id} className={selected===x.id?'active':''} onClick={()=>setSelected(x.id)}><span className={s.sectors[x.id].owner==='patriot'?'patriot-dot':'royalist-dot'}/>{briefName(x)}<small>{x.grid}</small></button>)}</div>)}</aside>
      <div className="strategic-map"><div className="map-topline"><span>PROVINCIAS UNIDAS</span><span>1812</span></div><svg viewBox="0 0 640 555" role="group" aria-label="Mapa estratégico de los trece sectores de campaña">
        <defs><pattern id="chart-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#819e9a" strokeWidth=".4" opacity=".16"/></pattern></defs><rect width="640" height="555" fill="url(#chart-grid)"/>
        <path d="M145 0L129 53 138 103 117 157 106 216 92 258 79 317 57 370 55 430 43 485 35 555" fill="none" stroke="#637d74" strokeWidth="30" opacity=".18"/><text x="80" y="275" fill="#879b89" fontSize="13" transform="rotate(-77 80 275)" letterSpacing="5">CORDILLERA DE LOS ANDES</text>
        <path d="M548 0C530 90 553 141 488 207S460 322 508 386 597 443 640 465" fill="none" stroke="#6ba0a4" opacity=".3" strokeWidth="9"/><text x="522" y="243" fill="#8ba7a4" fontFamily="Georgia" fontSize="16" transform="rotate(63 522 243)">Río Paraná</text>
        <path d="M558 401Q599 403 640 416V555H580Q601 480 558 401" fill="#497079" opacity=".25"/><text x="474" y="516" fill="#799597" fontFamily="Georgia" fontSize="17" letterSpacing="3">RÍO DE LA PLATA</text>
        {CAMPAIGN_SECTORS.flatMap(x=>x.neighbors.filter(n=>x.id<n).map(n=>{const b=CAMPAIGN_SECTORS.find(y=>y.id===n)!;const safe=s.sectors[x.id].owner==='patriot'&&s.sectors[n].owner==='patriot';return <line key={x.id+n} x1={x.x*5.9+20} y1={x.y*5+28} x2={b.x*5.9+20} y2={b.y*5+28} stroke={safe?'#8eb9a9':'#8b8d74'} strokeWidth={safe?'2':'1'} strokeDasharray="4 5" opacity=".6"/>}))}
        {CAMPAIGN_SECTORS.map(x=>{const px=x.x*5.9+20,py=x.y*5+28,ours=s.sectors[x.id].owner==='patriot';return <g className="sector-node" key={x.id} role="button" tabIndex={0} onClick={()=>setSelected(x.id)} onKeyDown={e=>{if(e.key==='Enter')setSelected(x.id)}} aria-label={`${x.name}, ${ours?'patriota':'realista'}`}><circle cx={px} cy={py} r="20" fill="transparent"/>{selected===x.id&&<circle cx={px} cy={py} r="17" fill="none" stroke="#d9c38b" strokeWidth="1"/>}<circle cx={px} cy={py} r="7" fill={ours?'#86b9b6':'#bc7560'} stroke="#1a2d31" strokeWidth="2"/>{s.location===x.id&&<path d={`M${px} ${py-13}v-16l13 5-13 5`} fill="#e4cea0" stroke="#e4cea0"/>}<text x={px+(x.x>85?-15:15)} y={py+5} textAnchor={x.x>85?'end':'start'} fill={selected===x.id?'#f0dfb5':'#bac7ba'} fontSize="13" fontFamily="Georgia">{briefName(x)}</text></g>})}
      </svg><div className="map-legend"><span><i className="patriot-dot"/>Patriotas</span><span><i className="royalist-dot"/>Realistas</span><span>— Red de abastecimiento</span></div></div>
      <aside className="sector-detail"><p className="eyebrow">SECTOR {def.grid} · {sector.owner==='patriot'?'PATRIOTA':'REALISTA'}</p><h2>{def.name}</h2><p className="sector-asset">{def.asset}</p><div className="sector-stat"><span>Ingresos diarios</span><b>{def.income} pesos</b></div><div className="sector-stat"><span>Lealtad local</span><b>{sector.loyalty}%</b></div><div className="sector-stat"><span>Abastecimiento</span><b>{isSupplied(s,def.id)?'Conectado':'Interrumpido'}</b></div><div className="sector-stat"><span>Guarnición</span><b>{sector.militia.reduce((a:number,b:number)=>a+b,0)} hombres</b></div><div className="sector-stat"><span>Fortificaciones</span><b>{sector.fort} / 3</b></div>
      {sector.owner==='royalist'||s.blockade&&def.theater==='coast'?<button className="gold-button deploy-button" onClick={()=>dispatch({type:'attack',sector:def.id})}><SwordsIcon/>Desplegar escuadra</button>:<><label className="transport-label">Medio de transporte<select value={transport} onChange={e=>setTransport(e.target.value)}><option value="march">Marcha a pie</option><option value="posta">Red de postas</option><option value="flotilla">Flotilla fluvial</option><option value="carts">Carretas de Cuyo</option></select></label><button className="gold-button deploy-button" disabled={s.location===def.id} onClick={()=>dispatch({type:'travel',sector:def.id,mode:transport})}>{s.location===def.id?'Campamento actual':'Trasladar destacamento'}</button><button className="line-button" onClick={()=>dispatch({type:'fortify',sector:def.id})}>Fortificar · 150 pesos, 5 sables</button><p className="eyebrow militia-label">INSTRUCCIÓN DE MILICIAS</p>{['Cívicos','Montoneras','Granaderos y línea'].map((r,i)=><button key={r} className="militia-button" onClick={()=>dispatch({type:'militia',sector:def.id,rank:i})}><span>{r}</span><b>{sector.militia[i]}</b><span>+</span></button>)}</>}
      <div className="squad-note"><Users size={18}/><span>{s.squad.length} combatientes en la escuadra<br/><small>Hasta 6 oficiales por destacamento</small></span></div></aside>
    </div></TabsContent>
    <TabsContent value="roster"><Recruitment state={s} dispatch={dispatch}/></TabsContent>
    <TabsContent value="workshop"><section className="workshop"><div className="section-intro"><h2>Maestranzas y abastecimiento</h2><p>La independencia se prepara en las fraguas. Los encargos se completan al avanzar el tiempo.</p></div><div className="inventory-band">{Object.entries(s.resources).map(([k,v]:any)=><span key={k}>{(RESOURCE_NAMES as any)[k]} <b>{v}</b></span>)}</div><img className="foundry-illustration" src="/art/foundry.png" alt="Maestranza colonial con fragua y piezas de artillería"/><div className="workshop-grid"><div><h3>Sala de armas</h3>{Object.entries(RECIPES).map(([id,r]:any)=><article className="recipe" key={id}><div><h3>{r.name}</h3><p>{Object.entries(r.cost).map(([k,v])=>`${v} ${(RESOURCE_NAMES as any)[k].toLowerCase()}`).join(' · ')}</p><small>{r.hours} horas de producción</small></div><button className="line-button" onClick={()=>dispatch({type:'produce',recipe:id,sector:['cannon','infantry'].includes(id)?'mendoza':['retiro','cordoba','mendoza'].includes(s.location)?s.location:'retiro'})}>Encargar +</button></article>)}<button className="gold-button" disabled={s.flags.foundry} onClick={()=>dispatch({type:'foundry'})}>{s.flags.foundry?'Fundición de Beltrán en marcha':'Activar El Plumerillo · 500 pesos, 20 cobre'}</button></div><div><h3>Contrabando del Río de la Plata</h3><p className="muted">Arribo en 72 a 120 horas. Los bloqueos demoran los cargamentos.</p>{[{id:'arms',name:'50 mosquetes y 100 cartuchos',cost:250},{id:'supplies',name:'Pólvora, textiles y cobre',cost:180},{id:'mounts',name:'15 caballos de remonta',cost:150},{id:'winter',name:'6 ponchos de lana',cost:100}].map(x=><article className="offer" key={x.id}><span>{x.name}</span><button className="line-button" onClick={()=>dispatch({type:'contraband',offer:x.id})}>{x.cost} pesos</button></article>)}<h3 className="spaced-heading">Redes de transporte</h3>{[{id:'posta',name:'Postas de chasques',cost:'150 pesos · 10 caballos'},{id:'flotilla',name:'Flotilla fluvial',cost:'400 pesos · 1 cañón'},{id:'carts',name:'Carretas de Cuyo',cost:'180 pesos · 4 caballos'}].map(x=><article className="offer" key={x.id}><div>{x.name}<small>{x.cost}</small></div><button className="line-button" disabled={s.routes[x.id]} onClick={()=>dispatch({type:'transport',mode:x.id})}>{s.routes[x.id]?'Activa':'Organizar'}</button></article>)}</div></div><Armory state={s} dispatch={dispatch}/><Logistics state={s} dispatch={dispatch}/><div className="production-queue"><h3>Encargos y cargamentos en curso</h3>{!s.production.length&&!s.shipments.length?<p className="muted">No hay encargos pendientes.</p>:<>{s.production.map((p:any)=><p key={p.id}>{p.name} · {Math.max(0,p.due-s.hour)} horas restantes</p>)}{s.shipments.map((p:any,i:number)=><p key={i}>Cargamento británico · {Math.max(0,p.due-s.hour)} horas restantes{s.blockade?' · Demorado por el bloqueo':''}</p>)}</>}</div></section></TabsContent>
    <TabsContent value="diplomacy"><section className="diplomacy"><div className="section-intro"><h2>Una revolución, muchas voluntades</h2><p>Los acuerdos abren rutas y suman combatientes. Cada decisión afecta la confianza en el ejército.</p></div><div className="faction-grid">{FACTIONS.map(f=><article className="faction" key={f.id}><h3>{f.name}</h3><p>{f.description}</p><div className="stat-pair"><span>{f.id==='royalists'?'Enemigo permanente':s.reputation[f.id]>=40?'Aliados':s.reputation[f.id]<0?'Hostiles':'En diálogo'}</span><b>{s.reputation[f.id]}</b></div><div className="reputation-meter"><i style={{width:`${(s.reputation[f.id]+100)/2}%`}}/></div></article>)}</div><div className="accord-grid">{[{id:'northPact',name:'Pactar con Güemes',desc:'20 mosquetes · 10 caballos · 10 pólvora'},{id:'partisanSupply',name:'Abastecer a las partidas',desc:'50 mosquetes para la resistencia'},{id:'parliament',name:'Parlamento pehuenche',desc:'200 pesos · 60 textiles · 10 sables'},{id:'emancipation',name:'Proclamar la emancipación',desc:'150 pesos para proteger a las familias'},{id:'commission',name:'Comisionar oficiales pardos',desc:'100 pesos para nuevas comisiones'},{id:'gift',name:'Enviar presentes a la frontera',desc:'80 pesos · 20 textiles'},{id:'autonomy',name:'Respetar la autonomía provincial',desc:'80 pesos para las autoridades locales'},{id:'requisition',name:'Requisar ganado',desc:'+200 pesos · +5 caballos; reduce la lealtad'}].map(x=><button key={x.id} className="accord" disabled={Boolean(s.flags[x.id])} onClick={()=>dispatch({type:'diplomacy',kind:x.id})}><span>{x.name}{s.flags[x.id]?' ✓':' →'}</span><small>{x.desc}</small></button>)}</div></section></TabsContent>
    <TabsContent value="journal"><section className="journal"><h2>Cuaderno de campaña</h2><article className="mentor-dispatch"><img src="/art/portrait-57.webp" alt="José de San Martín"/><div><p className="eyebrow">{mentor.role} · Despacho dramatizado</p><h3>{mentor.name}</h3><p>{mentor.text}</p></div></article><div className="command-intelligence">{intelligence.map((c:any)=><article key={c.id}><p className="eyebrow">{c.active?'MANDO REALISTA ACTIVO':'MANDO CONTENIDO'}</p><h3>{c.name}</h3><p><strong>{c.commander}</strong>{c.deputy&&` · ${c.deputy}`}</p><p>{c.objective}</p><small>{c.doctrine}</small>{c.target&&<p>Objetivo: {CAMPAIGN_SECTORS.find(x=>x.id===c.target)?.name||c.target}</p>}</article>)}</div><div className="journal-columns"><div><p className="eyebrow">EL CAMINO A LA INDEPENDENCIA</p>{PHASES.map((p,i)=><article className={`chapter ${i===s.phase?'active':''}`} key={p.id}><h3>{p.name}{i<s.phase?' ✓':''}</h3><p>{p.objective}</p></article>)}</div><div><p className="eyebrow">DESPACHOS RECIBIDOS</p>{s.log.map((p:any,i:number)=><article className="dispatch-entry" key={i}><span>DÍA {1+Math.floor(p.hour/24)} · {p.hour%24}:00</span><p>{p.text}</p></article>)}</div></div></section></TabsContent>
    </Tabs>
    <footer className="campaign-footer"><span>«Seamos libres, que lo demás no importa nada.»</span><span>JOSÉ DE SAN MARTÍN</span></footer>
  </div>;
}
function SwordsIcon(){return <Flag size={16}/>;}
