'use client';
import {sitePath} from '../lib/site-path.js';
import {weaponSpecification} from '../../game/weapon-definition.js';
import TrainingProgress from './TrainingProgress';
import {portraitFor} from '../lib/portraits';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ATTRIBUTE_LABELS,characterProfile} from '../../game/characters.js';
import {contractQuote} from '../../game/contracts.js';
import {serviceRelationships} from '../../game/service-relationships.js';
import {OFFICER_TRAITS,CHARACTER_CLASSES} from '../../game/recruitment.js';
import {WEAPONS,BLADES} from '../../game/tactical.js';
export default function CharacterDossier({operative:o,record,state,onClose}:{operative:any;record:any;state?:any;onClose:()=>void}){
 const profile=o?characterProfile(o):null;const quote=o?contractQuote(state??{hour:0,contracts:{},operativeState:{[o.id]:record}},o,'day'):null;
 const relationships=o?serviceRelationships(state,o):[];
 return <Dialog open={Boolean(o)} onOpenChange={open=>!open&&onClose()}><DialogContent className="dossier-modal" showCloseButton={false}>{o&&profile&&<><p className="eyebrow">{profile.registry}</p><div className="dossier-heading">{portraitFor(o.portraitId??o.id)?<img src={sitePath(portraitFor(o.portraitId??o.id)!)} alt={o.name}/>:<div className="dossier-initials">{o.nickname.slice(0,2).toUpperCase()}</div>}<div><DialogTitle>{o.name}</DialogTitle><DialogDescription>{o.role}</DialogDescription><p>{quote?.permanent?'Servicio permanente':`${quote?.daily??quote?.price} pesos por día`}</p>{o.classId&&<p>Clase: {CHARACTER_CLASSES.find(c=>c.id===o.classId)?.name}</p>}<p>Grado {o.level||1} · {o.xp||0} experiencia</p></div></div><div className="dossier-stats">{Object.entries(ATTRIBUTE_LABELS).map(([key,label])=><div key={key}><span>{label}</span><strong>{key==='maxHp'?`${Math.round(record?.hp??o.maxHp)} / ${o.maxHp}`:o[key]}</strong><meter min="0" max="100" value={key==='maxHp'?record?.hp??o.maxHp:o[key]} aria-label={label}/></div>)}</div><p className="dossier-stat-note">Pólvora y artillería: manejo de municiones y servicio de las piezas de campaña.</p><TrainingProgress unit={{...o,skillPractice:record?.skillPractice,trainedStats:record?.trainedStats}}/><h3>Especialidades</h3><div className="dossier-skills">{profile.skills.map((skill:string)=><span key={skill}>{OFFICER_TRAITS.find(t=>t.id===skill)?.name||skill}</span>)}</div><h3>Equipo personal</h3><div className="dossier-equipment">{[weaponSpecification(o),weaponSpecification(o,'blade')].filter(Boolean).map((w:any,i:number)=><div key={`${w.id}-${i}`}><img src={sitePath(w.art)} alt={w.name}/><span>{w.name}</span></div>)}</div><h3>Hoja de servicio</h3><p>{o.biography}</p><h3>Carácter</h3><p>{profile.personality}</p>{relationships.length>0&&<><h3>Condiciones de servicio</h3><ul>{relationships.map((relationship:any)=><li key={relationship.character}>No acepta contratarse ni renovar mientras {relationship.rivalName} siga en servicio. {relationship.reason}</li>)}</ul><p>El rechazo no acorta los contratos ya pagados.</p></>}<blockquote>«{profile.speech.hired}»</blockquote><small>Personalidad y diálogo dramatizados para el juego.</small><button className="gold-button" onClick={onClose}>Cerrar hoja de servicio</button></>}</DialogContent></Dialog>;
}
