'use client';
import {portraitFor} from '../lib/portraits';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ATTRIBUTE_LABELS,characterProfile} from '../../game/characters.js';
import {contractQuote} from '../../game/contracts.js';
import {OFFICER_TRAITS,CHARACTER_CLASSES} from '../../game/recruitment.js';
import {WEAPONS,BLADES} from '../../game/tactical.js';
export default function CharacterDossier({operative:o,record,onClose}:{operative:any;record:any;onClose:()=>void}){
 const profile=o?characterProfile(o):null;const quote=o?contractQuote({operativeState:{[o.id]:record}},o):null;
 return <Dialog open={Boolean(o)} onOpenChange={open=>!open&&onClose()}><DialogContent className="dossier-modal" showCloseButton={false}>{o&&profile&&<><p className="eyebrow">{profile.registry}</p><div className="dossier-heading">{portraitFor(o.portraitId??o.id)?<img src={portraitFor(o.portraitId??o.id)!} alt={o.name}/>:<div className="dossier-initials">{o.nickname.slice(0,2).toUpperCase()}</div>}<div><DialogTitle>{o.name}</DialogTitle><DialogDescription>{o.role}</DialogDescription><p>{quote?.permanent?'Servicio permanente':`${quote?.price} pesos por día${quote?.topTier?' · Solo contratos diarios':''}`}</p>{o.classId&&<p>Clase: {CHARACTER_CLASSES.find(c=>c.id===o.classId)?.name}</p>}<p>Grado {o.level||1} · {o.xp||0} experiencia</p></div></div><div className="dossier-stats">{Object.entries(ATTRIBUTE_LABELS).map(([key,label])=><div key={key}><span>{label}</span><strong>{key==='maxHp'?`${Math.round(record?.hp??o.maxHp)} / ${o.maxHp}`:o[key]}</strong><meter min="0" max="100" value={key==='maxHp'?record?.hp??o.maxHp:o[key]} aria-label={label}/></div>)}</div><p className="dossier-stat-note">Pólvora y artillería: manejo de municiones y servicio de las piezas de campaña.</p><h3>Especialidades</h3><div className="dossier-skills">{profile.skills.map((skill:string)=><span key={skill}>{OFFICER_TRAITS.find(t=>t.id===skill)?.name||skill}</span>)}</div><h3>Equipo personal</h3><div className="dossier-equipment">{[o.weapon,o.blade].filter(Boolean).map((id:number,i:number)=><div key={`${id}-${i}`}><img src={`/art/weapon-${id}.png`} alt={(WEAPONS as any)[id]?.name||(BLADES as any)[id]?.name}/><span>{(WEAPONS as any)[id]?.name||(BLADES as any)[id]?.name}</span></div>)}</div><h3>Hoja de servicio</h3><p>{o.biography}</p><h3>Carácter</h3><p>{profile.personality}</p><blockquote>«{profile.speech.hired}»</blockquote><small>Personalidad y diálogo dramatizados para el juego.</small><button className="gold-button" onClick={onClose}>Cerrar hoja de servicio</button></>}</DialogContent></Dialog>;
}
