'use client';
import {useState} from 'react';
import {merchantExchangeOffers,merchantExchangePreview} from '../../game/merchant-exchange.js';
import {isSupplied} from '../../game/campaign.js';
type Line={key:string;receipt:string;quantity:number;label:string;price:number;sell:boolean};
function Picker({offers,sell,add}:{offers:any[];sell:boolean;add:(offer:any,quantity:number)=>void}){
 const [selected,setSelected]=useState(''),[quantity,setQuantity]=useState(1);
 const offer=offers.find(o=>o.key===selected)??offers[0],name=sell?'Equipo que entregás':'Equipo que recibís';
 return <fieldset><legend>{sell?'Entregás':'Recibís'}</legend><label>{name}<select value={offer?.key??''} disabled={!offers.length} onChange={e=>{setSelected(e.target.value);setQuantity(1);}}><option value="" disabled>Sin ofertas</option>{offers.map((o,index)=><option key={o.key} value={o.key}>{o.label}{o.instance||o.gun?` · ejemplar ${index+1}`:''}{o.instance?` · estado ${o.instance.condition}%`:o.gun?` · ${o.gun.ammo} reservas${o.gun.reloadProgress?` · recarga ${Math.floor(o.gun.reloadProgress*100)}%`:''}`:''} · {o.price} pesos · {o.available} disponibles</option>)}</select></label>{offer&&<p>{offer.price} pesos por unidad{offer.instance?` · estado ${offer.instance.condition}%${offer.instance.jammed?' · fallo de chispa':''}`:''}{offer.instance?.fittings?.bayonet?` · bayoneta fijada, estado ${offer.instance.fittings.bayonet.condition}%`:''}{offer.gun?` · ${offer.gun.loaded?'cargada':offer.gun.reloadProgress?`recarga ${Math.floor(offer.gun.reloadProgress*100)}%`:'descargada'} · ${offer.gun.ammo} municiones de reserva`:''}</p>}<label>Cantidad {sell?'a entregar':'a recibir'}<input type="number" min="1" max={Math.min(100,offer?.available??1)} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><button type="button" className="line-button" disabled={!offer||Boolean(offer.reason)||!Number.isInteger(quantity)||quantity<1||quantity>Math.min(100,offer.available)} onClick={()=>add(offer,quantity)}>{sell?'Agregar entrega':'Agregar compra'}</button>{offer?.reason&&<p>{offer.reason}</p>}</fieldset>;
}
export default function MerchantExchange({state,dispatch}:{state:any;dispatch:(action:any)=>void}){
 const [lines,setLines]=useState<Line[]>([]),offers=merchantExchangeOffers(state,isSupplied);
 const action={type:'exchangeEquipment',sector:state.location,lines:lines.map(({key,receipt,quantity})=>({key,receipt,quantity}))},plan=merchantExchangePreview(state,action,isSupplied);
 const add=(offer:any,quantity:number)=>setLines(current=>{const old=current.find(line=>line.key===offer.key);return old?current.map(line=>line.key===offer.key?{...line,quantity:line.quantity+quantity}:line):[...current,{key:offer.key,receipt:offer.receipt,quantity,label:offer.label,price:offer.price,sell:offer.sell}];});
 return <details className="merchant-exchange"><summary>Intercambiar equipo</summary><p>Entregá armas o cañones y elegí equipo del comercio. Solo se paga o cobra la diferencia. Nada cambia hasta confirmar. Los pedidos de importación se tramitan por separado.</p><div className="exchange-pickers"><Picker offers={offers.filter(o=>o.sell)} sell={true} add={add}/><Picker offers={offers.filter(o=>!o.sell)} sell={false} add={add}/></div>
  <ul aria-label="Equipo propuesto para intercambio">{lines.map(line=><li key={line.key}><span>{line.sell?'Entregás':'Recibís'} {line.quantity} × {line.label} · {line.price*line.quantity} pesos</span><button type="button" className="line-button" aria-label={`Retirar ${line.label} del intercambio`} onClick={()=>setLines(current=>current.filter(other=>other.key!==line.key))}>Retirar</button></li>)}</ul>
  <p role="status">Entrega: {plan.sales} pesos · Compra: {plan.purchases} pesos · {plan.net>0?`Pagás ${plan.net}`:plan.net<0?`Cobrás ${-plan.net}`:'Diferencia: 0'} pesos</p>{lines.length>0&&plan.reason&&<p role="alert">{plan.reason}</p>}
  <button type="button" className="gold-button" disabled={!plan.valid} onClick={()=>{dispatch(action);setLines([]);}}>Confirmar intercambio</button><button type="button" className="line-button" disabled={!lines.length} onClick={()=>setLines([])}>Cancelar propuesta</button>
 </details>;
}
