'use client';
import {useState} from 'react';
import {rosterFor,contractQuote,contractStatus} from '../../game/campaign.js';
import {CIVIC_RECRUITS} from '../../game/recruitment.js';
import {characterProfile} from '../../game/characters.js';
import {portraitFor} from '../lib/portraits';
import CharacterDossier from './CharacterDossier';
import './recruitment.css';
type Props={state:any;dispatch:(a:any)=>void};
const terms=[['day','Un día'],['week','Una semana'],['month','Un mes']];
export default function Recruitment({state:s,dispatch}:Props){
 const [selected,setSelected]=useState<number|null>(null),[periods,setPeriods]=useState<Record<number,string>>({});
 const roster=rosterFor(s).filter(o=>CIVIC_RECRUITS.some(c=>c.id===o.id));
 return <section className="roster-section"><p>Voluntarios por estipendio. Cada contrato se paga por adelantado; el precio aumenta con la experiencia del combatiente.</p><div className="recruit-catalogue">{roster.map(o=>{const hired=s.recruited.includes(o.id),term=periods[o.id]||'day',quote=contractQuote(s,o,term),contract=contractStatus(s,o.id),profile=characterProfile(o),record=s.operativeState[o.id];return <article key={o.id} className="contract-card"><button className="candidate-face" onClick={()=>setSelected(o.id)} aria-label={`Ver hoja de servicio de ${o.name}`}>{portraitFor((o as any).portraitId??o.id)?<img src={portraitFor((o as any).portraitId??o.id)!} alt={o.name}/>:<span>{o.nickname.slice(0,2).toUpperCase()}</span>}<span>{o.name}</span></button><p className="eyebrow">{o.role}</p><p className="candidate-specialties">{profile.skills.join(' · ')}</p><div className="candidate-stats"><span>Puntería <b>{o.marksmanship}</b></span><span>Liderazgo <b>{o.leadership}</b></span><span>Grado <b>{o.level}</b></span></div><button className="dossier-link" onClick={()=>setSelected(o.id)}>Atributos, carácter y equipo →</button>{quote.topTier&&<small className="elite-contract">Especialista de élite · Solo un día por contrato</small>}{hired&&<p className="contract-remaining">{contract?.remaining===null?'Servicio permanente':`${contract?.remaining??0} horas de contrato restantes`}</p>}{quote.reason&&<small>{quote.reason}</small>}{hired&&quote.renewalNote&&<small>{quote.renewalNote}</small>}<label>Duración<select aria-label={`Duración del contrato de ${o.name}`} value={term} onChange={e=>setPeriods({...periods,[o.id]:e.target.value})}>{terms.map(([id,name])=><option key={id} value={id} disabled={quote.topTier&&id!=='day'}>{name}</option>)}</select></label><button className="gold-button" disabled={!quote.available||s.resources.treasury<quote.price||record?.alive===false||Boolean(s.pendingBattle)} onClick={()=>dispatch(hired?{type:'renewContract',id:o.id,term}:{type:'recruitCivic',id:o.id,term})}>{record?.alive===false?'Caído en combate':`${hired?'Renovar':'Contratar'} · ${quote.price} pesos`}</button>{hired&&<button className="dossier-link" disabled={Boolean(s.pendingBattle)} onClick={()=>dispatch({type:'dismiss',id:o.id})}>Finalizar servicio</button>}<small>Personaje ficticio · {profile.personality.split('.')[0]}.</small></article>;})}</div><CharacterDossier operative={roster.find(o=>o.id===selected)} record={s.operativeState[selected??-1]} onClose={()=>setSelected(null)}/></section>;
}
