'use client';
import {useState} from 'react';
import {rosterFor,contractQuote,contractStatus} from '../../game/campaign.js';
import {filterMercenaries} from '../../game/mercenary-catalogue.js';
import {CIVIC_RECRUITS} from '../../game/recruitment.js';
import {characterProfile} from '../../game/characters.js';
import {portraitFor} from '../lib/portraits';
import CharacterDossier from './CharacterDossier';
import './recruitment.css';
type Props={state:any;dispatch:(a:any)=>void};
const terms=[['day','Un día'],['week','Una semana'],['month','Un mes']];
export default function Recruitment({state:s,dispatch}:Props){
 const [selected,setSelected]=useState<number|null>(null),[periods,setPeriods]=useState<Record<number,string>>({});
 const [query,setQuery]=useState(''),[specialty,setSpecialty]=useState('all'),[availability,setAvailability]=useState('all'),[sort,setSort]=useState('name');
 const roster=rosterFor(s).filter(o=>CIVIC_RECRUITS.some(c=>c.id===o.id));
 const serving=roster.filter(o=>{const r=s.operativeState[o.id];return s.recruited.includes(o.id)&&r?.alive&&r.hp>0&&!r.captured;}).length;
 const visible:typeof roster=filterMercenaries(roster,s,{query,specialty,availability,sort});
 return <section className="roster-section"><p>Voluntarios por estipendio. Cada contrato se paga por adelantado; el precio aumenta con la experiencia del combatiente.</p><div className="catalogue-tools">
  <label>Buscar mercenario<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, apodo u oficio"/></label>
  <label>Especialidad<select value={specialty} onChange={e=>setSpecialty(e.target.value)}>{[['all','Todas'],['marksman','Tiro · 70+'],['medic','Medicina · 70+'],['mechanic','Mecánica · 70+'],['artillery','Artillería · 70+'],['leader','Liderazgo · 70+'],['scout','Exploración'],['rider','Caballería']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
  <label>Estado<select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="all">Todos</option><option value="available">Sin contratar · Con vida</option><option value="hired">En tus filas</option><option value="fallen">Caídos</option></select></label>
  <label>Ordenar<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Nombre</option><option value="price">Menor paga diaria</option><option value="marksmanship">Mayor puntería</option><option value="medical">Mayor medicina</option></select></label>
 </div><p className="catalogue-count" role="status">{visible.length} de {roster.length} mercenarios · {serving} en tus filas</p>{!visible.length&&<p className="catalogue-empty">No hay mercenarios con estos filtros. <button className="dossier-link" onClick={()=>{setQuery('');setSpecialty('all');setAvailability('all');}}>Mostrar todos</button></p>}<div className="recruit-catalogue">{visible.map(o=>{const hired=s.recruited.includes(o.id),term=periods[o.id]||'day',quote=contractQuote(s,o,term),contract=contractStatus(s,o.id),profile=characterProfile(o),record=s.operativeState[o.id];return <article key={o.id} className="contract-card"><button className="candidate-face" onClick={()=>setSelected(o.id)} aria-label={`Ver hoja de servicio de ${o.name}`}>{portraitFor((o as any).portraitId??o.id)?<img src={portraitFor((o as any).portraitId??o.id)!} alt={o.name} loading="lazy"/>:<span>{o.nickname.slice(0,2).toUpperCase()}</span>}<span>{o.name}</span></button><p className="eyebrow">{o.role}</p><p className="candidate-specialties">{profile.skills.join(' · ')}</p><div className="candidate-stats"><span>Puntería <b>{o.marksmanship}</b></span><span>Liderazgo <b>{o.leadership}</b></span><span>Grado <b>{o.level}</b></span></div><button className="dossier-link" onClick={()=>setSelected(o.id)}>Atributos, carácter y equipo →</button>{quote.topTier&&<small className="elite-contract">Especialista de élite</small>}{hired&&<p className="contract-remaining">{contract?.remaining===null?'Servicio permanente':`${contract?.remaining??0} horas de contrato restantes`}</p>}{quote.reason&&<small>{quote.reason}</small>}<label>Duración<select aria-label={`Duración del contrato de ${o.name}`} value={term} onChange={e=>setPeriods({...periods,[o.id]:e.target.value})}>{terms.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button className="gold-button" disabled={!quote.available||s.resources.treasury<quote.price||record?.alive===false||Boolean(s.pendingBattle)} onClick={()=>dispatch(hired?{type:'renewContract',id:o.id,term}:{type:'recruitCivic',id:o.id,term})}>{record?.alive===false?'Caído en combate':`${hired?'Renovar':'Contratar'} · ${quote.price} pesos`}</button>{hired&&<button className="dossier-link" disabled={Boolean(s.pendingBattle)} onClick={()=>dispatch({type:'dismiss',id:o.id})}>Finalizar servicio</button>}<small>Personaje ficticio · {profile.personality.split('.')[0]}.</small></article>;})}</div><CharacterDossier operative={roster.find(o=>o.id===selected)} record={s.operativeState[selected??-1]} onClose={()=>setSelected(null)}/></section>;
}
