'use client';
import {maximumEnergy} from '../../game/fatigue.js';
import {marchFatigueRate} from '../../game/march-fatigue.js';
import {mountForOperative} from '../../game/horses.js';
import {activeSquad,operativeInTransit,canReassignOperative,canCreateSquad} from '../../game/squads.js';
import {useState} from 'react';
import {CAMPAIGN_SECTORS} from '../../game/data.js';
import {rosterFor,operativeLocation} from '../../game/campaign.js';
import {campaignPlace,worldCell,worldOwner} from '../../game/world-cells.js';
import './squads.css';
type Props={state:any;dispatch:(action:any)=>void};
export default function Squads({state:s,dispatch}:Props){
 const [name,setName]=useState(''),[formationSector,setFormationSector]=useState(''),[members,setMembers]=useState<number[]>([]),[destination,setDestination]=useState('buenos_aires'),[mode,setMode]=useState('march'),[waypoints,setWaypoints]=useState<string[]>([]);
 const roster=rosterFor(s),squads=s.squads??[{id:'squad-1',name:'Primera escuadra',members:s.squad,location:s.location}],hired=roster.filter(o=>s.recruited.includes(o.id));
 const sectorName=(id:string)=>campaignPlace(id)?.name??id;
 const blocked=Boolean(s.pendingBattle||s.pendingEncounter)||s.defeated;
 const rural=!worldCell(s.location)?.anchor;
 const moving=Boolean(activeSquad(s).journey),hostile=s.sectors[destination]?.owner!=='patriot'||s.enemyGroups?.some((g:any)=>g.target===destination&&g.status==='stationed');
 const available=hired.filter(o=>canReassignOperative(s,o.id));
 const sites=Array.from(new Set(available.map(o=>operativeLocation(s,o.id)))).map(id=>({id,name:campaignPlace(id)?.name??id}));
 const at=sites.some(d=>d.id===formationSector)?formationSector:sites.some(d=>d.id===s.location)?s.location:sites[0]?.id??s.location;
 const local=available.filter(o=>operativeLocation(s,o.id)===at);
 const rates=s.squad.map((id:number)=>marchFatigueRate({...roster.find(o=>o.id===id),...s.operativeState[id],...(mountForOperative(s.horseState,id)??{})},{mode}));
 const chosen=members.filter(id=>local.some(o=>o.id===id));
 return <section className="squads-panel" aria-labelledby="squads-title"><div className="section-intro"><p className="eyebrow">ORDEN DE BATALLA</p><h2 id="squads-title">Escuadras en campaña</h2><p>Cada escuadra conserva su ubicación. Los combatientes deben reunirse en un mismo sector para cambiar de unidad.</p></div>
  <div className="squads-cards">{squads.map((q:any)=><article key={q.id} className={q.id===s.activeSquadId?'squad-card selected':'squad-card'}><div className="squad-card-title"><h3>{q.name}</h3><span>{q.members.length}/6</span></div><p>{['moving','ready'].includes(q.journey?.status)?'En camino desde ':''}{sectorName(q.location)}</p><ol>{Array.from({length:6},(_,i)=>{const op=roster.find(o=>o.id===q.members[i]);return <li key={i} className={op?'':'vacant'}>{op?op.name:'Plaza libre'}</li>;})}</ol><button className={q.id===s.activeSquadId?'gold-button':'line-button'} disabled={q.id===s.activeSquadId||Boolean(s.pendingBattle)||s.defeated} onClick={()=>dispatch({type:'selectSquad',id:q.id})}>{q.id===s.activeSquadId?'✓ Escuadra activa':'Tomar el mando'}</button></article>)}</div>
  <div className="squads-controls"><form onSubmit={e=>{e.preventDefault();if(chosen.length&&name.trim().length>=2){dispatch({type:'createSquad',name,ids:chosen,sector:at});setMembers([]);setName('');}}}><h3>Formar otra escuadra</h3><label htmlFor="squad-formation-sector">Localidad de formación<select id="squad-formation-sector" value={at} disabled={!sites.length} onChange={e=>{setFormationSector(e.target.value);setMembers([]);}}>{sites.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{!sites.length&&<p role="status">No hay combatientes disponibles para formar una escuadra. Esperá la llegada o cancelá su ruta.</p>}<label htmlFor="squad-name">Nombre de la unidad<input id="squad-name" value={name} onChange={e=>setName(e.target.value)} maxLength={30} minLength={2} placeholder="Escuadra del Litoral" required/></label><fieldset><legend>Combatientes reunidos en {sectorName(at)}</legend>{local.map(o=><label key={o.id} className="squad-choice"><input type="checkbox" checked={chosen.includes(o.id)} disabled={!chosen.includes(o.id)&&chosen.length>=6} onChange={e=>setMembers(e.target.checked?[...chosen,o.id]:chosen.filter(id=>id!==o.id))}/><span>{o.name}</span></label>)}</fieldset><button type="submit" className="gold-button" disabled={blocked||!chosen.length||name.trim().length<2||!canCreateSquad(s)}>Formar escuadra · {chosen.length}/6</button></form>
  <div className="squad-march"><h3>Órdenes para la escuadra activa</h3><p>{moving?'Último sector alcanzado':'Posición actual'}: <strong>{sectorName(s.location)}</strong></p>{rural?<p>Trazá la marcha desde esta celda en la carta de operaciones.</p>:<><label htmlFor="squad-destination">Destino<select id="squad-destination" value={destination} onChange={e=>{setDestination(e.target.value);if(s.sectors[e.target.value].owner!=='patriot')setWaypoints([]);}}>{CAMPAIGN_SECTORS.filter(d=>s.sectors[d.id].owner==='patriot'||d.neighbors.includes(s.location)).map(d=><option key={d.id} value={d.id}>{d.name}{s.sectors[d.id].owner!=='patriot'?' · realista':''}</option>)}</select></label><label htmlFor="squad-mode">Modo de marcha<select id="squad-mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="march">Marcha a pie</option><option value="posta" disabled={!s.routes.posta}>Postas de chasques</option><option value="flotilla" disabled={!s.routes.flotilla}>Flotilla del Plata</option><option value="carts" disabled={!s.routes.carts}>Carretas de Cuyo</option></select></label><div><button className="line-button" disabled={blocked||moving||hostile||waypoints.length>=8} onClick={()=>setWaypoints([...waypoints,destination])}>Añadir escala</button>{waypoints.length>0&&<><p>Escalas: {waypoints.map(sectorName).join(" → ")}</p><button className="line-button" onClick={()=>setWaypoints(waypoints.slice(0,-1))}>Quitar última escala</button><button className="line-button" onClick={()=>setWaypoints([])}>Borrar escalas</button></>}</div><button className="line-button" disabled={blocked||moving||(!waypoints.length&&destination===s.location)||!s.squad.length} onClick={()=>dispatch({type:hostile?'attack':'travel',sector:destination,mode,waypoints:hostile?[]:waypoints,queue:true})}>{hostile?'Preparar el ataque':'Ordenar la marcha'}</button></>}<button className="gold-button" disabled={blocked||moving||!s.squad.length||!worldCell(s.location)?.land||worldOwner(s,s.location)==='royalist'} onClick={()=>dispatch({type:'visitSector',sector:s.location})}>Entrar al sector y explorar</button><small>{rates.length?`Terreno llano: ${Math.min(...rates)}–${Math.max(...rates)} de fatiga por hora. La montaña aumenta el esfuerzo. `:''}El peso extra acelera el agotamiento a pie. La escuadra se detiene al final de una etapa si necesita descansar. La orden prepara la ruta. Avanzá el reloj para viajar mientras otras escuadras trabajan. Una incursión puede interrumpir la ruta antes de la llegada.</small></div></div>
  <div className="squads-personnel"><h3>Estado de fuerzas</h3><div className="squads-table-scroll"><table><thead><tr><th>Combatiente</th><th>Ubicación</th><th>Salud</th><th>Energía</th><th>Puntería</th><th>Agilidad</th><th>Medicina</th><th>Estado</th></tr></thead><tbody>{hired.map(o=><tr key={o.id}><th>{o.name}</th><td>{operativeInTransit(s,o.id)?'En camino desde ':''}{sectorName(operativeLocation(s,o.id))}</td><td>{Math.round(s.operativeState[o.id].hp)}/{o.maxHp}</td><td>{Math.round(s.operativeState[o.id].energy??100)}/{maximumEnergy(s.operativeState[o.id])} · Fatiga {s.operativeState[o.id].fatigue}</td><td>{o.marksmanship}</td><td>{o.agility}</td><td>{o.medical}</td><td>{!s.operativeState[o.id].alive?'Caído':squads.find((q:any)=>q.members.includes(o.id))?.name??'En reserva'}</td></tr>)}</tbody></table></div></div>
 </section>;
}
