'use client';
import {useState} from 'react';
import {CAMPAIGN_SECTORS} from '../../game/data.js';
import {rosterFor,operativeLocation} from '../../game/campaign.js';
import './squads.css';
type Props={state:any;dispatch:(action:any)=>void};
export default function Squads({state:s,dispatch}:Props){
 const [name,setName]=useState(''),[members,setMembers]=useState<number[]>([]),[destination,setDestination]=useState('buenos_aires'),[mode,setMode]=useState('march');
 const roster=rosterFor(s),squads=s.squads??[{id:'squad-1',name:'Primera escuadra',members:s.squad,location:s.location}],hired=roster.filter(o=>s.recruited.includes(o.id));
 const sectorName=(id:string)=>CAMPAIGN_SECTORS.find(d=>d.id===id)?.name??id;
 const local=hired.filter(o=>s.operativeState[o.id].alive&&operativeLocation(s,o.id)===s.location);
 const chosen=members.filter(id=>local.some(o=>o.id===id));
 return <section className="squads-panel" aria-labelledby="squads-title"><div className="section-intro"><p className="eyebrow">ORDEN DE BATALLA</p><h2 id="squads-title">Escuadras en campaña</h2><p>Cada escuadra conserva su ubicación. Los combatientes deben reunirse en un mismo sector para cambiar de unidad.</p></div>
  <div className="squads-cards">{squads.map((q:any)=><article key={q.id} className={q.id===s.activeSquadId?'squad-card selected':'squad-card'}><div className="squad-card-title"><h3>{q.name}</h3><span>{q.members.length}/6</span></div><p>{sectorName(q.location)}</p><ol>{Array.from({length:6},(_,i)=>{const op=roster.find(o=>o.id===q.members[i]);return <li key={i} className={op?'':'vacant'}>{op?op.name:'Plaza libre'}</li>;})}</ol><button className={q.id===s.activeSquadId?'gold-button':'line-button'} disabled={q.id===s.activeSquadId} onClick={()=>dispatch({type:'selectSquad',id:q.id})}>{q.id===s.activeSquadId?'✓ Escuadra activa':'Tomar el mando'}</button></article>)}</div>
  <div className="squads-controls"><form onSubmit={e=>{e.preventDefault();if(chosen.length&&name.trim().length>=2){dispatch({type:'createSquad',name,ids:chosen});setMembers([]);setName('');}}}><h3>Formar otra escuadra</h3><label htmlFor="squad-name">Nombre de la unidad<input id="squad-name" value={name} onChange={e=>setName(e.target.value)} maxLength={30} minLength={2} placeholder="Escuadra del Litoral" required/></label><fieldset><legend>Combatientes reunidos en {sectorName(s.location)}</legend>{local.map(o=><label key={o.id} className="squad-choice"><input type="checkbox" checked={chosen.includes(o.id)} disabled={!chosen.includes(o.id)&&chosen.length>=6} onChange={e=>setMembers(e.target.checked?[...chosen,o.id]:chosen.filter(id=>id!==o.id))}/><span>{o.name}</span></label>)}</fieldset><button type="submit" className="gold-button" disabled={!chosen.length||name.trim().length<2||squads.length>=8}>Formar escuadra · {chosen.length}/6</button></form>
  <div className="squad-march"><h3>Órdenes para la escuadra activa</h3><p>Posición actual: <strong>{sectorName(s.location)}</strong></p><label htmlFor="squad-destination">Destino<select id="squad-destination" value={destination} onChange={e=>setDestination(e.target.value)}>{CAMPAIGN_SECTORS.filter(d=>s.sectors[d.id].owner==='patriot').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label htmlFor="squad-mode">Modo de marcha<select id="squad-mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="march">Marcha a pie</option><option value="posta" disabled={!s.routes.posta}>Postas de chasques</option><option value="flotilla" disabled={!s.routes.flotilla}>Flotilla del Plata</option><option value="carts" disabled={!s.routes.carts}>Carretas de Cuyo</option></select></label><button className="line-button" disabled={destination===s.location||!s.squad.length} onClick={()=>dispatch({type:'travel',sector:destination,mode})}>Ordenar la marcha</button><button className="gold-button" disabled={!s.squad.length||s.sectors[s.location]?.owner!=='patriot'} onClick={()=>dispatch({type:'visitSector',sector:s.location})}>Entrar al sector y explorar</button><small>El viaje consume tiempo. Una incursión puede interrumpir la ruta antes de la llegada.</small></div></div>
  <div className="squads-personnel"><h3>Estado de fuerzas</h3><div className="squads-table-scroll"><table><thead><tr><th>Combatiente</th><th>Ubicación</th><th>Salud</th><th>Puntería</th><th>Agilidad</th><th>Medicina</th><th>Estado</th></tr></thead><tbody>{hired.map(o=><tr key={o.id}><th>{o.name}</th><td>{sectorName(operativeLocation(s,o.id))}</td><td>{Math.round(s.operativeState[o.id].hp)}/{o.maxHp}</td><td>{o.marksmanship}</td><td>{o.agility}</td><td>{o.medical}</td><td>{!s.operativeState[o.id].alive?'Caído':squads.find((q:any)=>q.members.includes(o.id))?.name??'En reserva'}</td></tr>)}</tbody></table></div></div>
 </section>;
}
