'use client';
import {campaignPlace} from '../../game/world-cells.js';
import {squadTravelStatus,assaultGroups} from '../../game/squad-travel.js';
import './travel-status.css';
import {travelTime} from '../lib/travel-time';
const place=(id:string)=>campaignPlace(id)?.name??id;
export default function TravelStatus({state:s,dispatch}:{state:any;dispatch:(a:any)=>void}){
 const assaults=assaultGroups(s);
 const squads=s.squads.filter((q:any)=>q.journey),blocked=Boolean(s.pendingBattle||s.pendingEncounter||s.defeated);
 if(!squads.length&&!s.travelNotice)return null;
 return <section className="travel-status" aria-label="Rutas de las escuadras"><h2>Marchas y llegadas</h2>{s.travelNotice&&<div role="status" aria-live="polite"><p>Día {Math.floor(s.travelNotice.hour/24)+1} · {String(s.travelNotice.hour%24).padStart(2,'0')}:{String(Math.floor((s.travelNotice.secondOfHour??0)/60)).padStart(2,'0')}</p><ul>{s.travelNotice.events.map((e:any,i:number)=><li key={i}><strong>{e.name}</strong>: {e.text}</li>)}</ul></div>}<p>Avanzá el reloj para mover todas las escuadras. El reloj se detiene al llegar al destino o si hay novedades.</p><div>{assaults.filter(group=>group.ready.length).map(group=><article key={group.sector} aria-label={`Asalto a ${place(group.sector)}`}><h3>Asalto a {place(group.sector)}</h3><p>Listas: {group.ready.map((q:any)=>q.name).join(", ")} · {group.ready.reduce((sum:number,q:any)=>sum+q.members.length,0)} combatientes</p>{group.incoming.length>0?<><p>En camino: {group.incoming.map((q:any)=>`${q.name} (${travelTime(q.remaining)}${q.status==='paused'?', detenida':''})`).join(", ")}</p><p>Avanzá el reloj para esperar a las demás, o atacá ahora con las escuadras listas.</p></>:<p>Todas las escuadras con esta orden han llegado.</p>}<button className="gold-button" disabled={blocked} onClick={()=>dispatch({type:'beginAssault',sector:group.sector})}>Atacar con las escuadras listas</button></article>)}{squads.map((q:any)=>{const j=squadTravelStatus(q)!;return <article key={q.id} aria-label={`Ruta de ${q.name}`}><h3>{q.name}</h3><p>{j.status==='paused'?'Detenida en':j.status==='ready'?'En el límite de':j.returning?'Regresa a':'En camino hacia'} <strong>{place(j.status==='paused'?q.location:j.to)}</strong></p><p>{['paused','ready'].includes(j.status)?j.reason:`${travelTime(j.legRemaining)} hasta ${place(j.to)}`}</p><small>{j.path.map(place).join(' → ')}{!j.returning&&` · ${travelTime(j.remaining)} de viaje restante, sin contar descansos`}</small><div className="travel-actions">{j.status==='paused'&&<button className="gold-button" disabled={blocked} onClick={()=>dispatch({type:'resumeTravel',squadId:q.id})}>Retomar marcha</button>}{j.intent!=='attack'&&<button className="line-button" disabled={blocked||j.returning} onClick={()=>dispatch({type:'cancelTravel',squadId:q.id,choice:'stop'})}>{j.elapsed===0?'Cancelar ruta':'Detenerse en el próximo sector'}</button>}{j.intent==='attack'&&j.elapsed===0&&<button className="line-button" disabled={blocked} onClick={()=>dispatch({type:'cancelTravel',squadId:q.id})}>Cancelar ataque</button>}{j.elapsed>0&&!j.returning&&<button className="line-button" disabled={blocked} onClick={()=>dispatch({type:'cancelTravel',squadId:q.id,choice:'return'})}>Regresar · {travelTime(j.elapsed)}</button>}</div></article>;})}</div></section>;
}
