'use client';
import {ownedArtilleryCount} from '../../game/campaign-artillery.js';
import {foundryFor,foundryLocationName} from '../../game/campaign-foundry.js';
import {campaignRole,foundryReason} from '../../game/campaign-roles.js';
import {incomeSources,incomeSummary} from '../../game/economy.js';
import Armory from './Armory';
import './treasury.css';
export default function Treasury({state:s,dispatch}:{state:any;dispatch:(action:any)=>void}){
 const summary=incomeSummary(s),sources=incomeSources(s),engineer=campaignRole(s,'foundryEngineer'),reason=foundryReason(s),foundry=foundryFor(s);
 return <section className="treasury"><p className="desk-lead">Dinero para la campaña</p><div className="cash-summary"><div><span>Disponible</span><strong>{s.resources.treasury.toLocaleString('es-AR')} pesos</strong></div><div><span>Ingreso diario</span><strong>+{summary.daily.toLocaleString('es-AR')} pesos</strong></div><div><span>Próximo cobro</span><strong>En {summary.hoursUntilPayment} h</strong></div></div><p>Las localidades bajo tu control pagan cada día. Los bloqueos y los daños reducen el ingreso. También podés cobrar encargos y encontrar dinero al explorar.</p><details className="income-details"><summary>Ver ingresos por localidad</summary><div className="income-table"><table><thead><tr><th>Localidad</th><th>Fuente</th><th>Estado</th><th>Pesos / día</th></tr></thead><tbody>{sources.map(site=><tr key={site.id}><td>{site.name}</td><td>{site.source}</td><td>{site.status}</td><td>{site.income}{site.income!==site.base&&<small> / {site.base}</small>}</td></tr>)}</tbody></table></div></details>{(engineer||s.flags.foundry)&&<section className="campaign-funding"><h3>Preparar el {foundry.armyName}</h3><p>{engineer?`Organizá ${foundry.name} con ${engineer.name}`:`La preparación de ${foundry.name} está completa`}, financiá la tropa y comprá tres cañones. Los pasos se fortifican desde la carta.</p><p>Fundición: {foundryLocationName(s)}.</p><div>{!s.flags.foundry&&reason&&<p>{reason}</p>}<button className="line-button" disabled={s.flags.foundry||s.resources.treasury<foundry.setupCost||Boolean(reason)||Boolean(s.pendingBattle)} onClick={()=>dispatch({type:'foundry'})}>{s.flags.foundry?`${foundry.name} organizado`:`Organizar ${foundry.name} · ${foundry.setupCost} pesos`}</button><button className="line-button" disabled={!s.flags.foundry||s.flags.armyFunded||s.resources.treasury<foundry.fundingCost||Boolean(s.pendingBattle)} onClick={()=>dispatch({type:'fundArmy'})}>{s.flags.armyFunded?'Ejército financiado':`Financiar el ejército · ${foundry.fundingCost} pesos`}</button></div><p>{Math.min(3,ownedArtilleryCount(s))}/3 cañones propios</p></section>}<details className="income-details"><summary>Comprar armas y revisar equipo</summary><Armory state={s} dispatch={dispatch}/></details></section>;
}
