import {AnimationClip,Vector3} from 'three';
import {NativeMeleeContactFit} from './melee-contact-fit';
import {restoreActor,restoreCalibration,type ActorSnapshot,type Calibration} from './melee-worker-snapshot';
import type {ActorCue} from './presentation';
import type {ClipSpec} from './actor-assets';
import {lowerCacheFor} from './melee-lower-path-cache';
import {nativePoseCacheFor,settledPoseCacheFor} from './melee-native-pose-cache';

export type FitJob={id:number;own:ActorSnapshot;target:ActorSnapshot;calibration:Calibration;footwear:string;clip:any;gait?:{clip:any;speed:number};cue:ActorCue;spec:ClipSpec;time:number;lowerCache?:boolean;existingGait?:{step:number;foot:number;sole:number;boot:number}};
export function runFitJob(job:FitJob){
 const started=performance.now(),own=restoreActor(job.own),other=restoreActor(job.target),clip=AnimationClip.parse(job.clip),gait=job.gait?{clip:AnimationClip.parse(job.gait.clip),speed:job.gait.speed}:undefined,fit=new NativeMeleeContactFit(own.model,own.root,job.footwear,false,gait);
 restoreCalibration(fit,job.calibration);const source=fit as any;if(job.existingGait&&Object.values(job.existingGait).every(value=>Number.isFinite(value)&&value>0))Object.assign(source,{walkingStep:job.existingGait.step,walkingFootSpeed:job.existingGait.foot,walkingSoleSpeed:job.existingGait.sole,walkingBootSpeed:job.existingGait.boot});const plans:any[]=[],pairs:number[][]=[],path=source.pathAllowed;if(job.lowerCache)source.pathAllowed=function(plan:any,...args:any[]){plans.push({...plan,body:plan.body.clone(),hand:plan.hand.clone(),step:plan.step.clone(),rearStep:plan.rearStep.clone()});const accepted=path.call(this,plan,...args);if(source.rifleSpeedPair&&!pairs.some(pair=>pair[0]===source.rifleSpeedPair[0]&&pair[1]===source.rifleSpeedPair[1]))pairs.push([...source.rifleSpeedPair]);return accepted;};fit.apply(job.cue,clip,job.spec,own.weapon,job.time,()=>({model:other.model,root:other.root}));
 source.pathAllowed=path;const p=source.plan,plan=p?{key:p.key,cueId:p.cueId,hand:p.hand.toArray(),body:p.body.toArray(),step:p.step.toArray(),rearStep:p.rearStep.toArray(),contact:p.contact,duration:p.duration,pistol:p.pistol,sabre:p.sabre,twoHands:p.twoHands,handRecovery:p.handRecovery,yaw:p.yaw,turn:p.turn}:null;
 const pf=source.previewFit,cache=job.lowerCache&&pf?{core:pf.core.map((bound:any)=>({name:bound.bone.name,low:bound.low.toArray(),high:bound.high.toArray()})),recipes:[],names:[],previewLegs:[],gait:{step:source.walkingStep,foot:source.walkingFootSpeed,sole:source.walkingSoleSpeed,boot:source.walkingBootSpeed}}:undefined;const native=job.lowerCache&&source.sample?nativePoseCacheFor(fit,clip,job.spec.markers!.contact!):undefined;const seed={body:new Vector3(),hand:new Vector3(),step:new Vector3(),rearStep:new Vector3(),twoHands:true,contact:job.spec.markers!.contact!,duration:clip.duration,turn:job.cue.contactTurn?{...job.cue.contactTurn,until:clip.duration*.1,footDistance:0}:undefined};const settled=job.lowerCache&&source.sample?settledPoseCacheFor(fit,clip,seed):undefined;const result={id:job.id,plan,cache,native,settled,pairs,workerMs:performance.now()-started,gait:{step:source.walkingStep,foot:source.walkingFootSpeed,sole:source.walkingSoleSpeed,boot:source.walkingBootSpeed},rejectedFits:fit.rejectedFits};fit.dispose();return result;
}
if(typeof self!=='undefined')self.onmessage=(event:MessageEvent<FitJob>)=>{try{const result=runFitJob(event.data),transfer=[...(result.native?.rows.map(row=>row.values.buffer)??[]),...(result.settled?.rows.map(row=>row.values.buffer)??[])];(self as any).postMessage(result,{transfer});}catch(error){self.postMessage({id:event.data.id,error:error instanceof Error?error.message:String(error)});}};
