import fs from 'node:fs/promises';
import {SPRITE_DISPLAY_CALIBRATION as calibration} from '../../game/sprite-display-calibration.js';
import {ILLUSTRATED_SPRITE_ATLASES as atlases} from '../../game/illustrated-sprite-atlases.js';
import {SPRITE_APPEARANCES} from '../../game/sprite-appearances.js';
const active = JSON.parse(await fs.readFile('web/public/art/skin/manifest.json', 'utf8')).masks;
const runtimeAtlases = Object.fromEntries(Object.entries(atlases).filter(([name]) => Object.hasOwn(active, name)));
const html=`<!doctype html><meta charset="utf-8"><title>Idle style comparison</title><style>body{background:#1d2b20;color:#e8dfc5;font:16px system-ui;margin:24px}select,button{font:inherit;padding:8px}main{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:20px}.pair{background:#414c3b;padding:12px}.sprites{display:flex;gap:8px}.sprites>svg{background:#747966;width:50%;height:auto}small{display:block}h3{margin:0 0 8px}label{margin-right:12px}</style><h1>Idle style comparison</h1><p>Idle on the left. Animation on the right. Both use the same ground position and display scale.</p><label>Family <select id="family">${Object.keys(SPRITE_APPEARANCES).map(n=>`<option>${n}</option>`).join('')}</select></label><label>Action <select id="action"></select></label><button id="play">Pause</button><label>Frame <input id="frame" type="range" min="0" max="3" value="0" step="1"><output id="frameNumber">1</output></label><main></main><script>
const calibration=${JSON.stringify(calibration)},atlases=${JSON.stringify(runtimeAtlases)},dirs=['N','NE','E','SE','S','SW','W','NW'];let frame=0,playing=true;const family=document.querySelector('#family'),action=document.querySelector('#action');function options(){const v=action.value;action.innerHTML=Object.keys(atlases).filter(n=>n.startsWith(family.value+'-')).map(n=>'<option>'+n.slice(family.value.length+1)+'</option>').join('');if([...action.options].some(o=>o.value===v))action.value=v;frame=0;draw()}function sprite(n,d,f){const a=atlases[n],animated=a.framesPerDirection>1;const x=(animated?f%a.framesPerDirection:d)*a.cell,y=animated?d*a.cell:0,scale=a.logicalCell/a.cell,[sx,sy]=calibration[n]?.[d]??[1,1];return '<svg viewBox="15 35 80 75"><svg x="'+(55-a.anchor[0]*scale*sx)+'" y="'+(105-a.anchor[1]*scale*sy)+'" width="'+(a.logicalCell*sx)+'" height="'+(a.logicalCell*sy)+'" viewBox="'+[x,y,a.cell,a.cell].join(' ')+'" overflow="hidden"><image href="../../../web/public/art/illustrated/'+a.file+'" width="'+a.size[0]+'" height="'+a.size[1]+'" style="image-rendering:pixelated"/></svg></svg>'}function draw(){const total=atlases[family.value+'-'+action.value].framesPerDirection;document.querySelector('#frame').max=total-1;document.querySelector('#frame').value=frame;document.querySelector('#frameNumber').textContent=(frame+1)+' / '+total;document.querySelector('main').innerHTML=dirs.map((d,i)=>'<section class="pair"><h3>'+d+'</h3><div class="sprites">'+sprite(family.value+'-idle',i,0)+sprite(family.value+'-'+action.value,i,frame)+'</div><small>Idle · '+action.value+' · frame '+(frame+1)+'</small></section>').join('')}family.onchange=options;action.onchange=()=>{frame=0;draw()};document.querySelector('#play').onclick=e=>{playing=!playing;e.target.textContent=playing?'Pause':'Play'};document.querySelector('#frame').oninput=e=>{playing=false;document.querySelector('#play').textContent='Play';frame=Number(e.target.value);draw()};setInterval(()=>{if(playing){frame=(frame+1)%atlases[family.value+'-'+action.value].framesPerDirection;draw()}},200);options();</script>`;
await fs.writeFile('assets/previews/sprite-consistency/index.html',html);
