import {register} from 'node:module';register('./tactical-render-loader.mjs',import.meta.url);
import test,{after} from 'node:test';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
import {Group,Vector3,Quaternion,AnimationMixer,LoopOnce} from '../web/node_modules/three/build/three.module.js';
import {clone} from '../web/node_modules/three/examples/jsm/utils/SkeletonUtils.js';
import {BATTLE_PLAYBACK} from '../game/battle-playback.js';
import {publishedActor} from './published-actor-fixture.mjs';
const {ActorRuntime}=await import('../web/lib/three/actor-runtime.ts');
const {NativeGestureBlendSupport}=await import('../web/lib/three/gesture-blend-support.ts');
const metrics=[];after(()=>{if(process.env.GESTURE_SUPPORT_METRICS)writeFileSync(process.env.GESTURE_SUPPORT_METRICS,JSON.stringify(metrics,null,2)+'\n');});
const guardNames=['stand.idle.unarmed','stand.idle.long-gun','stand.idle.short-gun','stand.idle.blade','stand.idle.knife','stand.idle.lance','stand.aim.long-gun','stand.aim.short-gun','stand.brace.long-gun'];
const held={unarmed:null,'long-gun':1800,'short-gun':1805,blade:1810,knife:1813,lance:1812};
const leg=/^(thigh|calf|foot|ball)_[lr]$/;
const pose=model=>{const rows=[];model.traverse(n=>{if(n.isBone)rows.push({n,p:n.position.toArray(),q:n.quaternion.toArray(),s:n.scale.toArray()});});return rows;};
const assertPose=(rows,legs=false)=>{for(const {n,p,q,s}of rows){assert.deepEqual(n.position.toArray(),p,n.name+' native position');assert.deepEqual(n.scale.toArray(),s,n.name+' native scale');if(!legs||!leg.test(n.name))assert.deepEqual(n.quaternion.toArray(),q,n.name+' native rotation');}};
const points=mesh=>{mesh.updateWorldMatrix(true,false);mesh.skeleton.update();return Array.from({length:mesh.geometry.attributes.position.count},(_,i)=>mesh.getVertexPosition(i,new Vector3()).applyMatrix4(mesh.matrixWorld));};
function nativeFixture(asset){const model=clone(asset.body.scene),root=new Group();root.add(model);const mesh=model.getObjectByName('Human_footwear_LOD'+asset.lod),mixer=new AnimationMixer(model),helper=new NativeGestureBlendSupport(model,root,mesh.name);return {asset,model,root,mesh,mixer,helper};}
function blend(f,guard,gesture,direction,phase){f.helper.restore();f.mixer.stopAllAction();const gc=f.asset.animation.animations.find(c=>c.name===guard),hc=f.asset.animation.animations.find(c=>c.name===gesture),g=f.mixer.clipAction(gc).reset().play(),h=f.mixer.clipAction(hc).reset().setLoop(LoopOnce,1).play();h.clampWhenFinished=true;const names=direction==='entry'?[guard,gesture]:[gesture,guard];f.helper.begin(...names.map(name=>f.asset.clips.find(c=>c.name===name)),0);return (t,u)=>{f.helper.restore();g.time=(gc.duration*phase+t)%gc.duration;h.time=direction==='entry'?t:hc.duration;g.setEffectiveWeight(direction==='entry'?1-u:u);h.setEffectiveWeight(direction==='entry'?u:1-u);f.mixer.update(0);f.root.updateMatrixWorld(true);};}

for(const anatomy of ['granadero','woman-scout'])for(const lod of [0,1,2])test(`${anatomy} LOD${lod}: all nine actual guards and three gestures retain complete boot support and native body`,async()=>{
 const f=nativeFixture(await publishedActor(anatomy,lod)),soleCutoff=Math.min(...Array.from({length:f.mesh.geometry.attributes.position.count},(_,i)=>f.mesh.geometry.attributes.position.getY(i)))+.003;assert.equal(new Set(Array.from({length:f.mesh.geometry.attributes.position.count},(_,i)=>i).filter(i=>f.mesh.geometry.attributes.position.getY(i)<soleCutoff).map(i=>[f.mesh.geometry.attributes.position.getX(i),f.mesh.geometry.attributes.position.getY(i),f.mesh.geometry.attributes.position.getZ(i)].join(','))).size,96,'Use all48unique native sole points per foot, including every UV seam vertex in support checks');let largestLift=0,rawLowest=Infinity,lowest=Infinity,maxSpeed=0,maxRawSpeed=0,maxSoleDrift=0,active=0;
 try{for(const guard of guardNames)for(const gesture of ['stand.gesture.heal','stand.gesture.pickup','stand.gesture.free'])for(const direction of ['entry','return'])for(const phase of [0,.25,.5,.75]){
  const evaluate=blend(f,guard,gesture,direction,phase);let previous,previousRaw;const frameCount=16;
  for(let frame=0;frame<=frameCount;frame++){
   const t=.12*frame/frameCount;evaluate(t,frame/frameCount);const body=pose(f.model),raw=points(f.mesh),footGoals=['l','r'].map(side=>({p:f.model.getObjectByName('foot_'+side).getWorldPosition(new Vector3()),q:f.model.getObjectByName('foot_'+side).getWorldQuaternion(new Quaternion())}));
   const lengthBefore=['l','r'].map(side=>{const a=f.model.getObjectByName('thigh_'+side).getWorldPosition(new Vector3()),b=f.model.getObjectByName('calf_'+side).getWorldPosition(new Vector3()),c=f.model.getObjectByName('foot_'+side).getWorldPosition(new Vector3());return[a.distanceTo(b),b.distanceTo(c)];});const time=f.mixer.time;f.helper.apply(t);assert.equal(f.mixer.time,time,'Mixer clock remains exact');assertPose(body,true);assert.equal(f.helper.rejectedFits,0,'Admitted native fit must succeed');const full=points(f.mesh);lowest=Math.min(lowest,...full.map(p=>p.y));rawLowest=Math.min(rawLowest,...raw.map(p=>p.y));largestLift=Math.max(largestLift,f.helper.maximumAdjustment);if(f.helper.maximumAdjustment)active++;
   for(let i=0;i<full.length;i++){if(previous){maxSpeed=Math.max(maxSpeed,full[i].distanceTo(previous[i])/(.12/frameCount));maxRawSpeed=Math.max(maxRawSpeed,raw[i].distanceTo(previousRaw[i])/(.12/frameCount));}if(f.mesh.geometry.attributes.position.getY(i)<soleCutoff)maxSoleDrift=Math.max(maxSoleDrift,Math.hypot(full[i].x-raw[i].x,full[i].z-raw[i].z));}
   for(let side=0;side<2;side++){const bone=f.model.getObjectByName('foot_'+['l','r'][side]),p=bone.getWorldPosition(new Vector3()),thigh=f.model.getObjectByName('thigh_'+['l','r'][side]).getWorldPosition(new Vector3()),calf=f.model.getObjectByName('calf_'+['l','r'][side]).getWorldPosition(new Vector3());assert.ok(Math.abs(thigh.distanceTo(calf)-lengthBefore[side][0])<1e-6&&Math.abs(calf.distanceTo(p)-lengthBefore[side][1])<1e-6,'Keep actual native leg lengths');assert.ok(Math.hypot(p.x-footGoals[side].p.x,p.z-footGoals[side].p.z)<1e-6,'Keep world footprint');assert.ok(1-Math.abs(bone.getWorldQuaternion(new Quaternion()).normalize().dot(footGoals[side].q.clone().normalize()))<1e-10,'Keep native world foot direction');}
   if(frame===0||frame===frameCount)assertPose(body,false);previous=full;previousRaw=raw;
  }
 }
 assert.ok(rawLowest<-.003,'Reproduce the weighted raw blend floor defect');assert.ok(lowest>.0009,'The whole boot stays above the floor '+lowest);assert.ok(largestLift<.007,'Only the measured blend needs a small fit '+largestLift);assert.ok(active>0);assert.ok(maxSoleDrift<.000001,'Native sole footprint stays fixed '+maxSoleDrift);assert.ok(maxSpeed<2.5,'Full boot speed includes shaft '+maxSpeed);assert.ok(maxSpeed<maxRawSpeed*1.4,'No high speed snap '+maxSpeed+' / '+maxRawSpeed);metrics.push({kind:'weighted-blend-grid',anatomy,lod,states:216,rawLowest,lowest,largestLift,maxSpeed,maxRawSpeed,maxSoleDrift});
 }finally{f.helper.dispose();f.mixer.stopAllAction();}
});

for(const anatomy of ['granadero','woman-scout'])for(const lod of [0,1,2])for(const guard of guardNames)test(`${anatomy} LOD${lod} ${guard}: actual actor clocks, bounded fallback and automatic return`,async()=>{
 const asset=await publishedActor(anatomy,lod),equipment=guard.split('.').at(-1),idleAction=guard.split('.')[1],visual={key:'unit:gesture',id:'gesture',kind:'unit',appearance:anatomy,skin:'light',side:'player',position:[6,.4,-4],yaw:Math.PI/2,tacticalLevel:0,posture:'standing',mounted:false,action:idleAction,idleAction,equipment:['knife','lance'].includes(equipment)?'blade':equipment,items:held[equipment]?[{id:String(held[equipment]),reference:'primary',socket:'handRight'}]:[],garments:{},selected:false,bodyHeights:{}};
 const actor=new ActorRuntime(asset,visual),mesh=actor.model.getObjectByName('Human_footwear_LOD'+lod),support=actor.gestureSupport,soleCutoff=Math.min(...Array.from({length:mesh.geometry.attributes.position.count},(_,i)=>mesh.geometry.attributes.position.getY(i)))+.003;let min=Infinity,rawMin=Infinity,rawPeak=0,maxAdjustment=0,maxHorizontalSoleSpeed=0,maxSpeed=0,adjustedFrames=0,endpointFits=0,previous,completed=0;actor.onCueComplete=()=>completed++;const expectsRejection=['unarmed','lance'].includes(equipment);let rejectedFrames=0;
 // The fallback preserves its 60 mm admission limit. These two current
 // guards need more during a paid blend, so actual production uses the
 // separately tested clip-aware contact plan. Verify exact rejection here.
 // This regression exercises the retained no-clip floor fallback only.
 const floorBegin=support.begin.bind(support);support.begin=(previous,next,time)=>floorBegin(previous,next,time);
 let rawCurrent;const original=support.apply.bind(support);support.apply=time=>{actor.root.updateMatrixWorld(true);rawCurrent=points(mesh);rawMin=Math.min(rawMin,...rawCurrent.map(p=>p.y-.4));const before=pose(actor.model),clock=actor.mixer.time,actions=actor.mixer._actions.map(a=>[a.time,a.timeScale,a.getEffectiveWeight()]);original(time);maxAdjustment=Math.max(maxAdjustment,support.maximumAdjustment);assert.deepEqual(actor.mixer._actions.map(a=>[a.time,a.timeScale,a.getEffectiveWeight()]),actions,'Retain every action clock and native blend weight');assertPose(before,true);assert.equal(actor.mixer.time,clock);if(support.rejectedFits){assert.ok(expectsRejection,'An in-range guard must not reject');assert.equal(support.rejectedFits,1);assertPose(before,false);assert.equal(support.adjusted,false);rejectedFrames++;}else assert.equal(support.rejectedFits,0);};
 try{
  for(let frame=0;frame<20;frame++)actor.tick(1/60,frame*1000/60);
  for(const [index,action]of ['heal','pickup','free'].entries()){
   const start=2000+index*2500,delay=index*1000/60,phaseMs=BATTLE_PLAYBACK.action,born=start-delay,cue={id:'gesture-'+index,action,phase:'prepare',startedAt:born,phaseStartedAt:born,phaseDurationMs:phaseMs,durationMs:phaseMs*2};actor.update({...visual,action,cue},start);previous=points(mesh);let previousRaw=previous,returned=false;
   for(let frame=0;frame<=50;frame++){
    const now=start+frame*1000/60;if(!returned&&now>=born+phaseMs){actor.update({...visual,action,cue:{...cue,phase:'result',phaseStartedAt:born+phaseMs}},now);returned=true;}actor.tick(frame===0?0:1/60,now);actor.root.updateMatrixWorld(true);const full=points(mesh);min=Math.min(min,...full.map(p=>p.y-.4));for(let i=0;i<full.length;i++)if(frame>0){maxSpeed=Math.max(maxSpeed,full[i].distanceTo(previous[i])*60);rawPeak=Math.max(rawPeak,rawCurrent[i].distanceTo(previousRaw[i])*60);if(mesh.geometry.attributes.position.getY(i)<soleCutoff)maxHorizontalSoleSpeed=Math.max(maxHorizontalSoleSpeed,Math.hypot(full[i].x-previous[i].x,full[i].z-previous[i].z)*60);}previous=full;previousRaw=rawCurrent;
    assert.deepEqual(actor.root.position.toArray(),visual.position,'Keep saved world cell');assert.equal(actor.root.rotation.y,visual.yaw,'Keep body facing');if(support.maximumAdjustment)adjustedFrames++;if(frame===0||frame===50)endpointFits+=Number(support.maximumAdjustment>1e-9);
   }
   assert.equal(actor.clipSpec.name,guard,'Return to the actual selected rest guard');assert.equal(support.processedVertices,0,'Ordinary rest performs no boot scan');
  }
  assert.equal(completed,3);if(expectsRejection)assert.ok(rejectedFrames>0,'The excessive no-clip request restores exact native transforms');else{assert.equal(rejectedFrames,0);assert.ok(min>.00085,'All admitted complete weighted boot points remain clear '+min);}assert.ok(maxSpeed<rawPeak*1.5,'Retained paid-clock whole boot speed '+maxSpeed+' / '+rawPeak);assert.ok(maxAdjustment<.06,'Measured paid blend remains bounded '+maxAdjustment);assert.equal(endpointFits,0,'Native endpoints keep their exact source pose');metrics.push({kind:'actor-playback',anatomy,lod,guard,min,rawMin,rawPeak,maxAdjustment,maxSpeed,maxHorizontalSoleSpeed,adjustedFrames,completed,endpointFits,rejectedFrames});
 }finally{actor.dispose();}
});

test('unsupported clips, missing source evidence and missing boot geometry remain exact native playback',async()=>{
 const asset=await publishedActor('granadero',1),f=nativeFixture(asset),idle=asset.clips.find(c=>c.name==='stand.idle.unarmed'),gesture=asset.clips.find(c=>c.name==='stand.gesture.heal');
 for(const [previous,next]of [[idle,{...gesture,nativeBootSupport:undefined}],[gesture,{name:'stand.walk.unarmed'}],[{name:'crouch.idle.unarmed'},gesture],[{name:'stand.bayonet.long-gun'},gesture]]){const before=pose(f.model);f.helper.begin(previous,next,0);f.helper.apply(.06);assertPose(before);assert.equal(f.helper.processedVertices,0);}
 const missing=new NativeGestureBlendSupport(f.model,f.root,'missing-footwear');missing.begin(idle,gesture,0);missing.apply(.06);assert.equal(missing.processedVertices,0);missing.dispose();f.helper.dispose();
});
test('finite unsupported scale and excessive support requests restore atomically without limb stretching',async()=>{
 const f=nativeFixture(await publishedActor('granadero',1)),evaluate=blend(f,'stand.idle.long-gun','stand.gesture.heal','return',0);evaluate(.06,.5);const before=pose(f.model);f.root.scale.setScalar(1.1);f.helper.apply(.06);assertPose(before);assert.equal(f.helper.rejectedFits,1);assert.equal(f.helper.processedVertices,0);f.root.scale.setScalar(1);
 const run=blend(f,'stand.idle.long-gun','stand.gesture.heal','return',0);run(.06,.5);f.model.getObjectByName('Root').position.y-=.3;const bad=pose(f.model);f.helper.apply(.06);assertPose(bad);assert.equal(f.helper.rejectedFits,1);assert.ok(pose(f.model).every(row=>[...row.p,...row.q,...row.s].every(Number.isFinite)));f.helper.dispose();
});
test('held blend phase is deterministic and an expired or nonfinite clock performs no work',async()=>{
 const f=nativeFixture(await publishedActor('granadero',0)),evaluate=blend(f,'stand.idle.blade','stand.gesture.heal','return',0);evaluate(.06,.5);f.helper.apply(.06);const first=pose(f.model).map(r=>r.q);
 for(let i=0;i<16;i++){evaluate(.06,.5);f.helper.apply(.06);assert.deepEqual(pose(f.model).map(r=>r.q),first);}
 for(const time of [-1,NaN,Infinity,.12,1]){f.helper.restore();const before=pose(f.model);f.helper.apply(time);assertPose(before);assert.equal(f.helper.processedVertices,0);}
 f.helper.dispose();
});

for(const anatomy of ['granadero','woman-scout'])for(const lod of [0,2])for(const fps of [30,120,240])test(`${anatomy} LOD${lod} at${fps}Hz: real fade frames, zero-delta handoff and reduced motion remain continuous`,async()=>{
 const asset=await publishedActor(anatomy,lod),visual={key:'unit:fine',id:'fine',kind:'unit',appearance:anatomy,skin:'light',side:'player',position:[0,0,0],yaw:0,tacticalLevel:0,posture:'standing',mounted:false,action:'idle',idleAction:'idle',equipment:'long-gun',items:[{id:'1800',reference:'primary',socket:'handRight'}],garments:{},selected:false,bodyHeights:{}},actor=new ActorRuntime(asset,visual),mesh=actor.model.getObjectByName('Human_footwear_LOD'+lod);let low=Infinity,peak=0,rawPeak=0,releaseSpeed=0,releaseCorrectionSpeed=0,previous,previousRaw,rawCurrent,priorActive=false;const apply=actor.gestureSupport.apply.bind(actor.gestureSupport);actor.gestureSupport.apply=(...args)=>{actor.root.updateMatrixWorld(true);rawCurrent=points(mesh);apply(...args);};
 // Exercise the real clip-aware production path at finite frame rates.
 // The separate weighted grid above retains direct no-clip fallback coverage.
 try{for(let i=0;i<Math.ceil(.5*fps);i++)actor.tick(1/fps,i*1000/fps,true);const start=1000,phaseMs=BATTLE_PLAYBACK.action,cue={id:'fine',action:'heal',phase:'prepare',startedAt:start,phaseStartedAt:start,phaseDurationMs:phaseMs,durationMs:phaseMs*2};actor.update({...visual,action:'heal',cue},start);let returned=false;
  for(let i=0;i<=Math.ceil(.85*fps);i++){const now=start+i*1000/fps;if(!returned&&now>=start+phaseMs){actor.update({...visual,action:'heal',cue:{...cue,phase:'result',phaseStartedAt:start+phaseMs}},now);returned=true;}actor.tick(i?1/fps:0,now,true);actor.root.updateMatrixWorld(true);const full=points(mesh),active=actor.gestureSupport.maximumAdjustment>0;low=Math.min(low,...full.map(p=>p.y));if(previous)for(let p=0;p<full.length;p++){const speed=full[p].distanceTo(previous[p])*fps;peak=Math.max(peak,speed);rawPeak=Math.max(rawPeak,rawCurrent[p].distanceTo(previousRaw[p])*fps);if(priorActive&&!active){releaseSpeed=Math.max(releaseSpeed,speed);const correction=full[p].clone().sub(rawCurrent[p]),oldCorrection=previous[p].clone().sub(previousRaw[p]);releaseCorrectionSpeed=Math.max(releaseCorrectionSpeed,correction.distanceTo(oldCorrection)*fps);}}assert.equal(actor.gestureSupport.rejectedFits,0);assert.deepEqual(actor.root.position.toArray(),visual.position);assert.equal(actor.root.rotation.y,0);previous=full;previousRaw=rawCurrent;priorActive=active;}
  assert.ok(low>.0009,'Complete boot floor '+low);assert.ok(peak<rawPeak*1.5,'Whole boot finite-frame speed '+peak+' / '+rawPeak);assert.ok(releaseCorrectionSpeed<rawPeak*.2,'Bound the actual added fit handoff speed '+releaseCorrectionSpeed);assert.equal(actor.clipSpec.name,'stand.idle.long-gun');assert.equal(actor.action.time,0,'Reduced motion retains its native idle clock');metrics.push({kind:'frame-continuity',anatomy,lod,fps,low,peak,rawPeak,releaseSpeed,releaseCorrectionSpeed});
 }finally{actor.dispose();}
});

test('a valid finite interrupted gesture cancels outside scope and restores native transforms',async()=>{
 const asset=await publishedActor('granadero',1),visual={key:'unit:interrupt',id:'interrupt',kind:'unit',appearance:'granadero',skin:'light',side:'player',position:[0,0,0],yaw:0,tacticalLevel:0,posture:'standing',mounted:false,action:'idle',idleAction:'idle',equipment:'blade',items:[{id:'1810',reference:'primary',socket:'handRight'}],garments:{},selected:false,bodyHeights:{}},actor=new ActorRuntime(asset,visual);
 try{actor.tick(.1,0);actor.update({...visual,action:'heal',cue:{id:'interrupt',action:'heal',startedAt:100,durationMs:1400}},100);actor.tick(.05,150);actor.update({...visual,action:'door',cue:{id:'next',action:'door',startedAt:150,durationMs:1000}},150);let checks=0;const apply=actor.gestureSupport.apply.bind(actor.gestureSupport);actor.gestureSupport.apply=time=>{const rows=pose(actor.model);apply(time);assertPose(rows);assert.equal(actor.gestureSupport.processedVertices,0);checks++;};for(let i=0;i<12;i++)actor.tick(1/60,150+i*1000/60);assert.equal(checks,12);assert.ok(pose(actor.model).every(row=>[...row.p,...row.q,...row.s].every(Number.isFinite)));assert.equal(actor.gestureSupport.adjusted,false);assert.equal(actor.gaitSupport.plan,undefined);
 }finally{actor.dispose();}
});

test('second-leg rejection restores an already adjusted first leg atomically',async()=>{
 const asset=await publishedActor('granadero',1),f=nativeFixture(asset);f.helper.dispose();f.mesh.geometry=f.mesh.geometry.clone();const p=f.mesh.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,p.getY(i)-(p.getX(i)>0?.001:.10));f.helper=new NativeGestureBlendSupport(f.model,f.root,f.mesh.name);const evaluate=blend(f,'stand.idle.blade','stand.gesture.heal','return',0);evaluate(.06,.5);const native=pose(f.model);f.helper.apply(.06);assert.ok(f.helper.maximumAdjustment>0,'First leg really received a correction');assert.equal(f.helper.rejectedFits,1,'Second deeper source shape exceeds the measured local limit');assertPose(native);assert.equal(f.helper.adjusted,false);f.helper.apply(.07);assert.equal(f.helper.processedVertices,0,'Cancelled malformed source no longer scans');f.helper.dispose();f.mesh.geometry.dispose();
});
test('malformed weighted boot attributes disable support without a partial rig or pose change',async()=>{
 const f=nativeFixture(await publishedActor('granadero',1));f.helper.dispose();f.mesh.geometry=f.mesh.geometry.clone();f.mesh.geometry.deleteAttribute('position');const native=pose(f.model),helper=new NativeGestureBlendSupport(f.model,f.root,f.mesh.name);helper.begin(f.asset.clips.find(c=>c.name==='stand.idle.unarmed'),f.asset.clips.find(c=>c.name==='stand.gesture.heal'),0);helper.apply(.06);assertPose(native);assert.equal(helper.processedVertices,0);helper.dispose();f.mesh.geometry.dispose();
});
