import fs from 'node:fs/promises';import {createHash} from 'node:crypto';import sharp from '../../web/node_modules/sharp/lib/index.js';
import {SPRITE_APPEARANCES} from '../../game/sprite-appearances.js';import {SPRITE_SEQUENCES} from '../../game/sprite-state.js';
const root='web/public/art/skin',base=JSON.parse(await fs.readFile('assets/previews/illustrated-sprites/packed/manifest.json'));
const sha=b=>createHash('sha256').update(b).digest('hex');
// Reuse precisely the mask of the held source frame. Death cannot switch colour.
for(const a of Object.keys(SPRITE_APPEARANCES))for(const [target,source,last] of [['aim-idle','fire',false],['crouch-aim-idle','crouch-fire',false],['prone-aim-idle','prone-armed-fire',false],['dead-idle','collapse',true]]){
 const e=base.atlases[`${a}-${source}`],layers=[];
 for(let d=0;d<8;d++)layers.push({input:await sharp(`${root}/${a}-${source}.png`).extract({left:(last?e.framesPerDirection-1:0)*e.cell,top:d*e.cell,width:e.cell,height:e.cell}).png().toBuffer(),left:d*e.cell,top:0});
 await sharp({create:{width:e.cell*8,height:e.cell,channels:4,background:'#00000000'}}).composite(layers).png().toFile(`${root}/${a}-${target}.png`);
}
const masks={};let bytes=0,pixels=0;
for(const a of Object.keys(SPRITE_APPEARANCES))for(const s of SPRITE_SEQUENCES){
 const name=`${a}-${s}`,e=base.atlases[name];let b=await fs.readFile(`${root}/${name}.png`);const {data,info}=await sharp(b).ensureAlpha().raw().toBuffer({resolveWithObject:true});
 for(let i=0;i<data.length;i+=4)if(!data[i+3])data[i]=data[i+1]=data[i+2]=0;
 b=await sharp(data,{raw:{width:info.width,height:info.height,channels:4}}).png().toBuffer();await fs.writeFile(`${root}/${name}.png`,b);
 if(info.width!==e.size[0]||info.height!==e.size[1])throw Error(`Mask dimensions ${name}`);
 const source=await sharp(`assets/previews/illustrated-sprites/packed/${e.file}`).ensureAlpha().raw().toBuffer();
 let count=0;for(let i=0;i<data.length;i+=4){if(data[i+3]>source[i+3])throw Error(`Mask outside silhouette ${name}`);if(data[i+3])count++;}
 masks[name]={file:name+'.png',sha256:sha(b),sourceSha256:e.sha256,size:e.size,pixels:count};bytes+=b.length;pixels+=count;
}
await fs.writeFile(`${root}/manifest.json`,JSON.stringify({version:1,model:'mattmdjaga/segformer_b2_clothes',revision:'584abc1e1d260e23c0fc627c5217a09b2b461046',masks},null,2)+'\n');
await fs.writeFile('game/sprite-skin-masks.js','// Generated by tools/skin-masks/finalize.mjs.\nexport const SPRITE_SKIN_MASKS='+JSON.stringify(Object.keys(masks),null,2)+';\n');
await fs.mkdir('assets/source/skin-masks',{recursive:true});for(const file of [...Object.keys(masks).map(n=>n+'.png'),'manifest.json'])await fs.copyFile(`${root}/${file}`,`assets/source/skin-masks/${file}`);
console.log({masks:Object.keys(masks).length,bytes,pixels});
